### ISSUE TITLE
Multiplayer (DS Wireless Play) not working and crashing on ROMs in TWL++

### ISSUE THREAD

**Issue by amosmoses2** [DS-Homebrew/nds-bootstrap#1000]
**Your console:** New 2DS XL
**Launch Method:** Luma3DS v10.2; TWL++ v16.1.0; nds-bootstrap v0.35.1
**Version used:** release
**Flashcart used:** none used
**Game tested/used/applicable:** Call of Duty: MW3 Defiance, Legend of Zelda: Phantom Hourglass, Super Mario 64 DS, any multiplayer game did not work.

**Expected Behavior:** working multiplayer
**Actual Behavior:** crashing and disconnecting

### Steps to reproduce

[nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/5120120/nds-bootstrap.zip)

1. Open TWL++
2. Boot up any game
3. Host multiplayer, have players join
4. Start game

### Logs

n/a

### Other notes

I recently homebrewed three New 2DS XLs. I got Twilight Menu++ on all of them and wanted to play some multiplayer DS games with my brother. This is where the issues start. We use ROMs of course to try to play multiplayer. The first we tried was Modern Warfare 3. We were able to connect all three consoles together in the lobby, but whenever the game loaded and everyone hit spawn, those who joined the host would crash before they spawned and the host would be able to join the game, but would be disconnected shortly after.

We tested other ROMs like Zelda with basically the same results. We used DS Download Play to connect to the host (who used a ROM) and it would crash. However, when the host used the actual Phantom Hourglass cartridge, we were able to connect and play fine.

From the information above, I think it can be narrowed down to an nds-bootstrap issue. Is there any way to fix this? Should I downgrade nds-bootstrap? And if so, how do I do that? Please find a fix soon, We just bought these 2DSs and its a huge bummer we can't even play the old DS Pokemon games together.

Thanks in advance.

**Comment by SleepyLark** [comment]
Call of Duty MW3 isn't compatible at the moment (afaik) so I wouldn't be surprised if that's also affect multiplayer mode.
Phantom Hourglass you need to turn heap shrink off (Press Y before launching the game in Twilight Menu and turn it off in the per-game settings) in order for it to not get a black screen.
Super Mario 64 DS uses cloneboot for Download Play which nds-bootstrap doesn't support yet (see #553), though not ever game uses cloneboot.
To see which games work for Download Play, please check the [compatibility list](https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0), there's a separate sheet dedicated to this area.

**Comment by amosmoses2** [comment]
cool thank you. do you know when these games will become compatible?

**Comment by Kaisaan** [comment]
There isn't any set dates for when a game will become compatible. You'll have to wait for cloneboot support, You also mentioned that Pokemon doesn't work, what exactly happens to those games?

**Comment by TheFlano23** [comment]
Cloneboot support has been released as of three days ago, meaning that those games should work now.
