### ISSUE TITLE
Speaker Issues in Animal Crossing Wild Wold

### ISSUE THREAD

**Issue by Knightsurfer** [DS-Homebrew/nds-bootstrap#1005]
**Your console:** New 3DS 
**Launch Method:** Forwarder from Forwarder3-DS 
**Version used:** Release 0.35.1 
**Game tested/used/applicable: Animal Crossing Wild World** 

**Expected Behavior:** Clear audio through the speakers at the title. 
**Actual Behavior:** Buzzy audio like what you would expect from the No$gba Emulator 

### Steps to reproduce
Start up the game through the forwarder, it seems to be fine when loading through Twilight.

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/Animal Crossing.nds
SAV_PATH = sd:/roms/nds/saves/Animal Crossing.sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
HOMEBREW_ARG =
AP_FIX_PATH =

**Comment by RocketRobz** [comment]
This has been fixed for a while.
