### ISSUE TITLE
pokemon white/bowser's inside story not booting.

### ISSUE THREAD

**Issue by pakodx** [DS-Homebrew/nds-bootstrap#1009]
**Your console:** o3ds
**Launch Method:** luma
**Version used:** release

**Game tested/used/applicable:** pokemon white ( fan translation ), mario & luigi 3( JP )

**Expected Behavior:** game should boot
**Actual Behavior:** 
mario & luigi 3 - white screen after mario and luigi yell "NINTENDO!"
pokemon white - won't boot.

### Steps to reproduce
put game on sd card, boot twlmenu++.
### Other notes

sent a copy of the pokemon fan translations ips files to retrogamefan on gbatemp a while ago

**Comment by RocketRobz** [comment]
Closing, since I don't know why those issues would happen.
