### ISSUE TITLE
Odd Behavior in Pokemon Wireless Distribution ROMs

### ISSUE THREAD

**Issue by SNBeast** [DS-Homebrew/nds-bootstrap#1010]
**Your console:** DSi XL
**Launch Method:** hiyaCFW 1.3.3, FIRM 1.4.5, launched from Twilight Menu 16.1.0, which was in turn launched from hiya's DSi Menu
**Version used:** Release 0.35.1
**Game tested/used/applicable:**
All carts used were distributed in the US.
2007 Manaphy (DP) - Title ID: Y44E - MD5: 8DD5FC0A95936DA820716BE76CA3ED9C
2008 Deoxys (DP) - Title ID: AARE - MD5: F2C7A5367DCE1256956E9A27ADC5924E
2009 Shaymin + Regigigas (DP) - Title ID: Y6OE - MD5: 3B592DB6A34536393574B482F631407A
2011 Ash's Pikachu (Gen IV) - Title ID: Y8SE - MD5: 3E56A353A27C71F881B7B15E07B40301
2011 Secret Eggs (BW) - Title ID: Y82E - MD5: FB0FC8337D44CA8F4CE1BAA612D59CBF
2013 Shiny Legendary Titans (Gen V) - Title ID: Y9OE - MD5: 566B80B9FEF542BE16179F6262293068
Probably applies to the others.

**Expected Behavior:** They don't soft reset or error out randomly. (Confirmed on Wood.)
**Actual Behavior:** The first one, Manaphy, works perfectly fine. The third one, Shaymin + Regigigas, will error out to "Distribution not available now." after a short random amount of time. The others will soft reset after a short random amount of time.

### Steps to reproduce

Nothing much is needed to reproduce besides launching the game and waiting. You'll need to have the date set within the range the Pokemon was distributed, excluding Manaphy which didn't yet have date checking.
Gen IV date ranges: https://bulbapedia.bulbagarden.net/wiki/List_of_local_English_event_Pok%C3%A9mon_distributions_in_Generation_IV
Gen V date ranges: https://bulbapedia.bulbagarden.net/wiki/List_of_local_English_event_Pok%C3%A9mon_distributions_in_Generation_V

[nds-bootstrap.ini.txt](https://github.com/ahezard/nds-bootstrap/files/5213205/nds-bootstrap.ini.txt)

### Logs

From Deoxys: [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/5213227/NDSBTSRP.LOG)
From Shaymin + Regigigas: [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/5213254/NDSBTSRP.LOG)
From Shiny Legendary Titans: [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/5213264/NDSBTSRP.LOG)

Note that the log gets overwritten upon the soft reset.

### Other notes
This is distinguishable from when the date is wrong, where you'll be flatly and immediately told that the distribution is unavailable.
The Manaphy is notable because it works perfectly, and is the only one that has no date verification. The Shaymin + Regigigas is interesting for being the only one that doesn't soft reset, particularly when Deoxys, an earlier one, does.

Were I to guess, it's an anti-piracy issue, since none of these Title IDs have corresponding APFixes.

**Comment by RocketRobz** [comment]
Closing, due to various improvements having been made since then, and no issues occurring on my side.
