### ISSUE TITLE
Pokemon platinum mt Coronet freeze

### ISSUE THREAD

**Issue by Blueskiyer** [DS-Homebrew/nds-bootstrap#1011]
So I'm using my dsi XL with the latest version of tw++ with relaunch. I'm having a problem with Pokemon platinum. So after I faught Mars and juniper, the moment the lake guardians go to the top of mtCoronet at spear pillar, the game freezes and the music keeps playing and I'm stu. What do I do?

**Comment by RocketRobz** [comment]
Try updating TWLMenu++, and see if the bug is still there.

**Comment by RocketRobz** [comment]
Closing, due to no response, and various improvements (ex. RTC fix) having been made since then.
