### ISSUE TITLE
.gba roms not playing in Twilightmenu++ error 1

### ISSUE THREAD

**Issue by matsukix** [DS-Homebrew/nds-bootstrap#1015]
**Your console:** 2ds xl
**Launch Method:** Twilightmenu++
**Version used:** I do not know how to check version. Downloaded latest as of a month ago.
**Game tested/used/applicable:** 

**Expected Behavior:** Twilightmenu++ runs .gb, .gbc, .nds just fine when a rom is selected.
**Actual Behavior:** When I open Twilightmenu++ and select a gba rom to play it gives the error message to place gba bios in the root as bios.bin. I did that but now I get the error: Start failed. Error 1 nds-bootstrap (release) not found. 

### Logs

I don't know how to pull logs.

### Other notes
I followed rocketrobz advice on GitHub: 
"The nds-bootstrap .nds files have to be outside the nds-bootstrap folder, and should be in the same folder as nds-bootstrap.ini."
https://github.com/DS-Homebrew/nds-bootstrap/issues/641

My file structure was already that way by default but I still get the error.

**Comment by NightYoshi370** [comment]
You need to copy the homebrew nds-bootstrap as well.
For general support like this, please use our Discord Server instead
