### ISSUE TITLE
Sloane to MacHale no Nazo no Story 2 (Japan) game resets every time begin new game is selected

### ISSUE THREAD

**Issue by Mariobario** [DS-Homebrew/nds-bootstrap#1016]
**Your console:** new 3ds xl
**Launch Method:** Twilight menu
**Version used:** 0.35.1 

**Game tested/used/applicable:** 4151 - Sloane to MacHale no Nazo no Story 2 (Japan)

**Expected Behavior:** Game begins by going to name input screen, works on a flash cart
**Actual Behavior:** Game immediately resets to opening screen as if reset button was pushed, does not freeze or crash

### Steps to reproduce 
Launch game. 
Select first option はじめから（from the beginning) 

### Other notes
Worked on a flash cart using ysmenu but froze on black screen during first opening story. Quit and cart was no longer visible. Shut down, reinserted cart, restarted and now seems to work perfectly on cart.

**Comment by RocketRobz** [comment]
Soft-resetting has been improved since. If it still occurs, then it's possibly an AP issue.
Closing.
