### ISSUE TITLE
Mario & Luigi RPG 3!!! (Japan) Freeze after the logo screen.

### ISSUE THREAD

**Issue by Atomwho** [DS-Homebrew/nds-bootstrap#1017]
**Your console: NDSI**
**Launch Method: TWLMenu++ v16.3.0**
**Version used:** 
**Game tested/used/applicable: Mario & Luigi RPG 3!!! (Japan)(MD5:f9b21070b76aa08f9750bb790992161b)** 

**Actual Behavior: Freeze after the logo screen.**

### Other notes
Whether the ROM is patched or not.

**Comment by RocketRobz** [comment]
Does this error persist in the stealth nds-bootstrap build included in TWLMenu++ v17.0.0?

**Comment by RocketRobz** [comment]
Closing due to no response, and the AP fix is updated.
