### ISSUE TITLE
Pokemon soft reset start failed. error 1

### ISSUE THREAD

**Issue by JSFLinkirby** [DS-Homebrew/nds-bootstrap#1018]
**Your console:** 3DS OLD
**Launch Method:** Luma3DS
**Version used:** release last version 
**Flashcart used:** SD Card 16GB
**Game tested/used/applicable:** All Pokemon DS games

**Expected Behavior:** 
Soft reset with L+R+Select+Start
**Actual Behavior:** 
When I try to soft reset in Pokemon Blaze Black 2 (Pokemon Black 2) with L+R+Select+Start the game try to soft reset but a black screen jump with an error "Start failed. Error 1". I try with Pokemon Black and Soul Silver and its the same.

### Steps to reproduce

Just start any Pokemon DS game and do soft reset pressing L+R+Select+Start

### Logs

I dont know T-T

### Other notes

Before something similar happened to me but it happened that I still had installed dsimenu++ and Pokemon Blaze Black 2 doesnt work and the game started in dsimenu++.

**Comment by RocketRobz** [comment]
If `nds-bootstrap-release.nds` (or `nds-bootstrap-nightly.nds`, if using Nightly) is in `sd:/_nds/`, try manually installing the latest TWiLight Menu++ CIAs.

**Comment by JSFLinkirby** [comment]
It worked very good, thanks a lot!
