### ISSUE TITLE
Super Mario 64 DS sleep mode malfunctioning

### ISSUE THREAD

**Issue by FulguroBoy** [DS-Homebrew/nds-bootstrap#1020]
**Your console:** O3DS
**Launch Method:** CFW: Luma3DS, v10.2. Launching nds-bootstrap with TWiLightMenu++ v16.3.0
**Version used:** 0.35.1
**Game tested/used/applicable:** Super Mario 64 DS (Europe) (ID: NTR-ASMP-EUR; MD5: 867B3D17AD268E10357C9754A77147E5) 

**Expected Behavior:** When you close the console to enter sleep mode, a coin sound is heard and Mario says "Bye bye!". When you open it again, a coin sound is heard and Mario says "It's-a me, Mario!" and you can continue the game normally
**Actual Behavior:** When I close the console, it keeps playing the sounds heard when closing and opening the console, indefinitely and alternatively. And when you reopen the console, both screens are black but the game still runs normally.

### Steps to reproduce

1: Launch the game
2: Close the console to enter sleep mode
3: Reopen it
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/5314944/nds-bootstrap.zip)

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/5314903/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
That's caused by certain Slot-1 carts.
Leaving the slot empty, or enabling `Force sleep patch` fixes this.
