### ISSUE TITLE
TwilightMenu++ "an exception occurred" 

### ISSUE THREAD

**Issue by ZepAfter** [DS-Homebrew/nds-bootstrap#1021]
Hello guys. I need help. I install the TwilightMenu Updater and want to release but when the release ended I got an error "An exception occurred" 
Current process : fs(00000000000000)

![Screenshot_20201014_062408_com huawei himovie overseas](https://user-images.githubusercontent.com/72848241/95943385-ed02fd00-0de5-11eb-89c0-72a6af2d8514.jpg)

**Comment by RocketRobz** [comment]
TWiLight Menu++ Updater has it's own repo.
Please report the issue there instead.
