### ISSUE TITLE
Sonic Rush credits freeze

### ISSUE THREAD

**Issue by Rib15** [DS-Homebrew/nds-bootstrap#1022]
New 3ds xl
Luma 3ds 10.2 and twighlight menu
Hacktober 2
**Game tested/used/applicable:** Sonic Rush, more specifically Sonic's campaign

They will eventually fade and the player goes back to title screen
 The credits of Sonic's campaign freeze about 1 minute in 

### Steps to reproduce
Beat the final zone called "unknown" at the end of Sonic's campaign

### Other notes

Not sure if this happens at the end of Blaze's or the final campaign but I would not be surprised

**Comment by Kaisaan** [comment]
According to the [compatibility list](https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit?usp=sharing), changing the Cache Block Size setting to 32KB. You can change this setting within the Games & Apps page of the TWiLightMenu++ settings, so try changing that and see if it works. Also update your TWiLightMenu++ and see if this issue and fix still happens on the latest version of nds-bootstrap (which should be 0.35.s5 afaik).

**Comment by RocketRobz** [comment]
Card read improvements have been made since then, so it's safe to assume this is fixed.
