### ISSUE TITLE
Nintendogs Freezing

### ISSUE THREAD

**Issue by blueingsh** [DS-Homebrew/nds-bootstrap#1024]
Game is Nintendogs: Chihuahuas and friends, it keeps freezing randomly. Don't know if this helps but I converted my DeSMUme save (dsv) to the .sav file

(System: Nintendo 2DS XL, BootStrap ver: v6e211072)

**Comment by blueingsh** [comment]
o wait nevermind

**Comment by RocketRobz** [comment]
Judging by the comment, I'll assume this is fixed.
