### ISSUE TITLE
Monster Jam (2007) White Screen Bug

### ISSUE THREAD

**Issue by hnlcory** [DS-Homebrew/nds-bootstrap#1025]
Your console
Tell us which console you are using:
 Old 3DS XL
 
CFW and configuration
Tell us which CFW do you have:
 Luma3DS
 
nds-bootstrap version
Tell us which versions you are using:
 Release [v0.35.1]

Tell us which card you are using:
 SD Card
 
If this issue only affects a certain game, which game is it?
Monster Jam (2007)
[Gamestop Link](https://www.gamestop.com/video-games/more-platforms/nintendo-ds/games/products/monster-jam/10066857.html)

Expected behavior
Game goes black and is expected to boot. Shows developer/publisher logos and game start screen.

Actual behavior
(Done using TWiLightMenu++ Application, version details in issue.)
nds-bootstrap logo appears. Game is stuck at a white screen afterwards.

Steps to reproduce
Insert Monster Jam DS Cartridge into gameslot.
Copy .nds file from gameslot via Godmode9 into it's clipboard
Paste .nds file into (root)/roms/nds
Open TWiLightMenu++ and launch .nds file from it's targeted directory. (/roms/nds)

Other notes
I've tried ds and dsi mode but no difference. Launching from ds menu also makes no difference. Tried leaving it on white screen but no change after several minutes.

**Comment by RocketRobz** [comment]
Does turning off heap shrink fix this?

**Comment by hnlcory** [comment]
> Does turning off heap shrink fix this?

Holding L when starting to skip heat shrinking causes the screen to briefly turn black as if it's loading but instantly turns white again. I've tested the same rom file using DeSmuME which loaded properly

**Comment by RocketRobz** [comment]
You disable heap shrink by going into the per-game settings.
Holding L only works in forwarders.

**Comment by hnlcory** [comment]
> You disable heap shrink by going into the per-game settings.
> Holding L only works in forwarders.

My mistake, changing it there works perfectly. Thanks for the help!
