### ISSUE TITLE
Pokemon White 2 Loading Issue

### ISSUE THREAD

**Issue by BigWut** [DS-Homebrew/nds-bootstrap#1026]
**Your console:** 3ds
**Launch Method:** Luma 10.2,  Twilight menu Hacktober 2020 release #2
**Version used:** Nds bootrap V.0.35.1
**Game tested/used/applicable:** Pokemon White
**Expected Behavior:** Game should boot normally
**Actual Behavior:**  Bootstrap "Please wait..." screen displays for the appropriate amount of time, then displays a black screen on top and a white screen on bottom. The top screen later also turns white. after several minutes displays the game freak intro logo, but will take about 10 seconds to load.
    It will then start the game trailer portion, and will again freeze for about 10 seconds, and again with the last screen before file select of the legendary, will have the same effect. After about a minute, the file select screen will load. After selecting a save file and waiting a few more minutes, the new game intro with the professor starts, and I can get up to right before the name selection before it needs to wait a while again. after entering my name, it freezes for a while again, and after trying to play the game for a while, it seems that anytime the game loads a different screen, it needs to do this. Text and animation changes do not cause this issue.

**Comment by Epicpkmn11** [comment]
Make sure your SD card is formatted as FAT32 with 32KB clusters, smaller cluster sizes will cause really slow loading like this
http://dsi.cfw.guide/sd-card-setup

**Comment by BigWut** [comment]
I will try this and see if it works, thanks.

**Comment by BigWut** [comment]
What would be the correct allocation size for an 8gb sd card?

**Comment by Epicpkmn11** [comment]
32KB, anything larger than 1GB should use that (1GB will need 16KB as their too small for 32KB)
