### ISSUE TITLE
problem with ram dump?/error -2

### ISSUE THREAD

**Issue by bwoukwyd** [DS-Homebrew/nds-bootstrap#1027]
Your console:new 3ds xl <
Launch Method: luma10.2
Version used:TWiLight Menu++: v16.5.0 
Game tested/used/applicable: every ds game

Expected Behavior: game should launch normally
Actual Behavior: first time lauching the game, it stops at "creating ram dumb file" for a few seconds, after that, it says error -2. every time i launch the game after that, it simply show a black top screen and a white one, without showing the logo nds bootstrap.

**Comment by SleepyLark** [comment]
Try reinstalling, maybe a file is missing?  Also how much space is left on the SD card?

**Comment by bwoukwyd** [comment]
i already tried fixing with TWLFix-CFW.3dsx, restore the sysnand safe and also unstalled everything, got my 3ds back to stock, and reinstalling every thing.

**Comment by bwoukwyd** [comment]
and i have 1.4g left

**Comment by RocketRobz** [comment]
Error -2 means that it failed to get the sector of the .nds file on the SD card.
What's the size of the SD card?

**Comment by bwoukwyd** [comment]
4gb

**Comment by RocketRobz** [comment]
Try checking the SD card for errors.

**Comment by bwoukwyd** [comment]
i'm sorry but how?

**Comment by SleepyLark** [comment]
https://3ds.hacks.guide/h2testw-(windows).html

**Comment by bwoukwyd** [comment]
okay i found it i think, and no errors was found

**Comment by bwoukwyd** [comment]
so i did it and it says Warning: " Test finished without errors."

**Comment by RocketRobz** [comment]
I have no idea why this error happens, so I'll close this.
