### ISSUE TITLE
White screen when a load pokemon black

### ISSUE THREAD

**Issue by demonium21** [DS-Homebrew/nds-bootstrap#1028]
**Your consolle:** new 2ds xl 
**Launch Method:** luma 3ds and twilight menu ++ v16.4.0
**Version used:** release 
**Game tested/used/applicable:** pokemon black usa eur 5585 

**Expected Behavior:** the game have to boot 
**Actual Behavior:** i have a white when i launch the game

**Comment by demonium21** [comment]
Please help me

**Comment by RocketRobz** [comment]
Solved at one of the Discord servers.
