### ISSUE TITLE
Rune factory graphics problems

### ISSUE THREAD

**Issue by aznerol** [DS-Homebrew/nds-bootstrap#1030]
**Your console:** Nintendo 3DS
**Launch Method:** TLMenu++ v16.6.0
**Version used:** stable v0.35.1
**Game tested/used/applicable:** Rune Factory - A fantasy harvest moon [ID 3443]
**Expected Behavior:** Smooth gameplay during combat and game action
**Actual Behavior:** Problems viewing screens that have lagging and streaks across the display, rendering the game unusable

**Steps to reproduce**

- open game
- load a project or start a new one
- after the introduction take the watering can and try to use it
- the screen begins to flicker, showing broken lines and images

**Other notes**

Two problems occur during the game that make the game unusable.  Using the watering can, fishing rod or fighting bosses in the caves, the screen shakes and creates lags and lines on the screen

**Comment by Kaisaan** [comment]
With [TWiLightMenu/1842](https://github.com/DS-Homebrew/TWiLightMenu/pull/1842) being merged, this issue should be fixed already. Closing.
