### ISSUE TITLE
Call of Duty Modern Warfare 3 freez out

### ISSUE THREAD

**Issue by Leichtos** [DS-Homebrew/nds-bootstrap#1034]
**Your console:**  Nintendo New 3DS XL
**Launch Method:**  Luma3DS
**Version used:** 10.2
**Game tested/used/applicable:**  Call of Duty 3 Modern Warfare

**Expected Behavior:**  If i start the Call of Duty 3 Modern Warfare in 
TWiLightMenu every time freez out the first in cutscene. The all other ROm work in the TWiLightMenu. I tried other MW3 rom. The problem is same.
**Actual Behavior:**

**Comment by SofyUchiha** [comment]
Have you tried running the game in DS Mode? Press Y and choose the option

**Comment by urmum-69** [comment]
This is a known issue. It is mentioned on the compatibility list, the game is unsupported for now

**Comment by lifehackerhansol** [comment]
This was reported as working since 0.46.0. Is that still the case?

**Comment by Peter0x44** [comment]
This was indeed fixed last time I tried, though I haven't done so on the latest version
most likely it still works though.
