### ISSUE TITLE
PT-BR Translations for Ace Attorney 2 and 3 not working on Twilight Menu v17.0.0.

### ISSUE THREAD

**Issue by Halkem3ds** [DS-Homebrew/nds-bootstrap#1035]
**Your console:** Nintendo DSi.
**Launch Method:** TWiLight Menu++: v17.0.0
**Version used:** Release.
**Game tested/used/applicable:** I'll link the page where the xdelta patches are available. They're for the north american(USA) roms of Ace Attorney 1,2 and 3. https://jacutemsabao.bitbucket.io/download.html I'll also attach them here.

**Expected Behavior:** The game should get to the title screen as normal.
**Actual Behavior:** After showing the first disclaimer from the translation team the games goes into a black screen. Phoenix Wright: Ace Attorney works as intended.

### Steps to reproduce
Patch the north american rom of Ace Attorney 2 and 3. Place the resulting .nds files in the SD card and try to run them through Twilight Menu ++ 17.0.0.

### Other notes

[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/5536149/nds-bootstrap.zip)
[xdeltapatches ace attorney trilogy pt-bt.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/5536155/xdeltapatches.ace.attorney.trilogy.pt-bt.zip)

**Comment by RocketRobz** [comment]
Try turning off heap shrink

**Comment by RocketRobz** [comment]
Closing this, since heap shrink is removed, and is assumingly fixed, as a result.
