### ISSUE TITLE
The English translation patch for jump super star doesn't work

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/nds-bootstrap#1036]
**Your console:** 
**Launch Method:** 
**Version used:** 
**Flashcart used:** 
**Game tested/used/applicable:** 

**Expected Behavior:** 
**Actual Behavior:**

**Comment by SleepyLark** [comment]
Did you mean Jump Ultimate Star?  Because I can't find an English patch for Jump Super Star.
You also failed to give any other information such as the version of nds-bootstrap you're running and what device you're using.

**Comment by Syko7956** [comment]
It's just Jump Ultimate Star AFAIK. For added context, I actually used to relate to this problem a year ago. So maybe he's outdated? Using the latest version of nds-bootstrap and TwilightMenu++, I can confirm it works fine now.
