### ISSUE TITLE
Pokémon Mystery Dungeon Sky - Long Load times

### ISSUE THREAD

**Issue by everydaycent** [DS-Homebrew/nds-bootstrap#1037]
**Your console:** Nintendo DSI
**Launch Method:** Twilight Menu 
**Version used:** v.0.35.1
**Game tested/used/applicable:** Pokémon Mystery Dungeon Sky

**Expected Behavior:** Load times should be 1 second
**Actual Behavior:** Load times take 3-4 Seconds with some menu taking upto 8-10 seconds

### Other notes
Not sure what’s causing it. I saw one post to replace the nightly version with an older version. But wouldn’t that mess up the compatibility with other games patched after the release of an older version?

**Comment by RocketRobz** [comment]
You can set the nightly build specifically for that game.

**Comment by everydaycent** [comment]
How do I use a separate version specifically for that game?

**Comment by RocketRobz** [comment]
Fixed in recent commits.
