### ISSUE TITLE
Bowser inside

### ISSUE THREAD

**Issue by Walter1529** [DS-Homebrew/nds-bootstrap#1038]
Bowser inside y final fantasy 4 heroes de la luz (parcheado al español) se me congelan aun con la versión 17 de twilight menú, alguna solución?

**Comment by Walter1529** [comment]
> please


Bowser inside and final fantasy 4 heroes de la luz (patched to Spanish) freeze me even with version 17 of twilight menu, any solution?

**Comment by RocketRobz** [comment]
You might need to AP-patch the ROMs.

**Comment by RocketRobz** [comment]
Closing due to no response.
