### ISSUE TITLE
Pokemon HeartGold - Infinite black screen when loading savegame

### ISSUE THREAD

**Issue by Shadark** [DS-Homebrew/nds-bootstrap#1039]
**Your console:** Old 3DS XL
**Launch Method:** Luma 10.2-bb07a73. Launching through TwilightMenu v17.0.0.
**Version used:** Release v.035.s2.
**Game tested/used/applicable:** Pokemon HeartGold [USA] - MD5 4fcded0e2713dc03929845de631d0932ea2b5a37

**Expected Behavior:** Game should work as usual.
**Actual Behavior:** After starting the game, I can save the game. If I try to load that save, I get an "infinite" black screen, not allowing me to play the game. **However, on a different Old 3DS XL the game works perfectly fine.** I'm going to refer to the problematic device as "bad 3DS" and the other one as the "good 3DS". They are almost identical, bought years ago with 1 month of difference.

### Steps to reproduce

nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/Games/Pokemon - HeartGold Version (USA).nds
SAV_PATH = sd:/Games/saves/Pokemon - HeartGold Version (USA).sav
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/IPKE-D061.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 0
FORCE_SLEEP_PATCH = 0

```

Also: I've disabled heap shrink option (both on and off), game is loading in DS mode. Haven't changed other options since the good 3DS is at default options for everything and seems to work just fine.

### Logs

```
findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027533
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200072A

cardIrqEnable location : 020D11D4

startOffset : 02000000

cardRead location : 020DD570

cardPullOut location : 020DDAD0

cardId location : 020DD660


patchCardSetDma
cardReadDma location : 020DD3E4

patchMpuSize: 00000000

reset location : 020D3B84

ERR_NONE


Arm7 (patch vAll)
forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238026C
Relocation dst: 037F8000

JumpTableFunc: 02388730
Eeprom read:	0238873C
Eeprom page write:	02388750
Eeprom page prog:	02388764
Eeprom verify:	02388778
Eeprom page erase:	02388788
swi12 location : 02388B70

swiGetPitchTable location : 02383FCC

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238ECF4

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: E0017FC2

```
### Other notes

I have a lotta notes.

- Game + save works fine on a PC emulator.
- Game + save works fine on the good 3DS.
- The game was working fine till a few days ago, then stopped working on the bad 3DS, can't recall why. Afterwards I tried everything mentioned here, creating a new savegame, got a backup of the older game for later.
- Reinstalling nds-bootstrap + TwilightMenu didn't work.
- Deleting ramdump and/or _nds folder didn't work.
- Downgrading to a older version of TwilightMenu and nds-bootstrap didn't work (the good 3DS is at TwilightMenu v16.6.0, nds-bootstrap at release v.035.1).
- Editing the save (+ verifying checksums) on emulator/savegame editor doesn't seem to fix anything, save is fine though (checksums are verified).
- Deleting the save + starting a new game doesn't allow to load afterwards, as I mentioned.
- Putting a new/different savegame also doesn't work.
- AP Patching the game manually also doesn't work (but works fine on the good 3DS).
- Swapping SD cards between consoles and trying to load the save doesn't work on the bad 3DS, works fine on the good 3DS.
- Other versions of the Pokemon HG ROM (don't have access to anything besides other untrusted dumps) behave similarly: they work fine on the good 3DS, they don't work on the bad 3DS (savegames seem compatible and they load just fine on the good 3DS).

Anything else I could try? I feel like I've run out of options and I don't know what else could I try, and it's apparently some issue related to the console/device and not to the installation, but since it doesn't seem to work at all... In any case, any help is appreciated and thanks for your time.

**Comment by RocketRobz** [comment]
Have you tried the latest nightly version of nds-bootstrap?

**Comment by Shadark** [comment]
Just tried now with latest nightly versions of both nds-bootstrap and TwilightMenu (I know it shouldn't matter, but just in case), still not working.

**Comment by RocketRobz** [comment]
Try launching the ROM with a DS game in Slot-1.

**Comment by Shadark** [comment]
Tried both with and without a cartridge in Slot-1, no changes (with nightly version(s), still).

**Comment by RocketRobz** [comment]
Does this still occur on the latest nightly?

**Comment by RocketRobz** [comment]
Closed due to no response, and for the reason stated in #1182

**Comment by shinynidorina** [comment]
this is the second thread I have seen RocketRobz be incredibly unhelpful on for this issue. thanks for once again closing the thread without actually helping. "due to no response" yet it took YOU four months to respond, what a waste of space.

**Comment by RocketRobz** [comment]
> this is the second thread I have seen RocketRobz be incredibly unhelpful on for this issue. thanks for once again closing the thread without actually helping. "due to no response" yet it took YOU four months to respond, what a waste of space.

And it took *you* nearly 4 years to notice this issue thread and respond to it.

The reason why we close such issues is because a majority of users cannot reproduce such issues on their side.
If you're getting the same issue, please make sure both TWLMenu++ and nds-bootstrap are up to date, because it's possible the issue has gotten fixed later on.
If it's still happening for you (or a few other users), then unfortunately, we can't really be of help for issues we don't know how to fix.
It'd still be nice to know if you're running either a clean or hacked ROM though.

If you are encountering freezing when running the game with nds-bootstrap on a flashcard though, please refer to issue #1661.

**Comment by NightScript370** [comment]
@shinynidorina Maybe don't join a development platform just to rant on one specific project because you couldn't spell out "hey, Robz, I still need help" on an issue which is most likely your fault at setting up.

For your type of support, you should instead go to the Discord server (that's why I'm sending this; just to correct Robz on that detail because it's most likely an issue with the way you set it up and not on our end). An invite link could be found in the repo's readme. Please don't pollute the GitHub issues with non-developmental support, or with your attitude. Thanks.
