### ISSUE TITLE
Bugs in some Games (DSi -nds-bootstrap 0.35.1)

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/nds-bootstrap#1040]
Hi, 
373/5000
When playing the game "Hotel Dusk: Room 215", it starts flashing.
How can I fix this error?
![WhatsApp Video 2020-11-19 at 21 14 39](https://user-images.githubusercontent.com/70182567/99749361-243b8c80-2abd-11eb-8bdf-1c45c360fb60.gif)

This same error occurs both games of "Etrian Odyssey" (but they are patched to Spanish)
![image](https://user-images.githubusercontent.com/70182567/99749722-ceb3af80-2abd-11eb-9203-0bb93642ae76.png)
![image](https://user-images.githubusercontent.com/70182567/99749780-e2f7ac80-2abd-11eb-80c7-45311db60a93.png)

Moreover, the game "Radiant Historia" does not work. Splash screens appear and then go black and not responding 😞 
![VID-20201119-WA0067](https://user-images.githubusercontent.com/70182567/99749387-3289a880-2abd-11eb-8946-365f6300c80a.gif)

I have TM v. 16.6.0 and ds-bootstrap 0.35.1
![image](https://user-images.githubusercontent.com/70182567/99749669-b93e8580-2abd-11eb-819f-f48a8b67edf4.png)

Help me, please 😞 
Thanks!

**Comment by RocketRobz** [comment]
Please update TWiLight Menu++.

**Comment by SofyUchiha** [comment]
> Please update TWiLight Menu++.

ok I'll try. Wait for me, so I tell you if the error continues 🙏

**Comment by SofyUchiha** [comment]
Ok, I have updated TM. "Hotel Dusk" starts up, but it is impossible to put it in Spanish (the specifications of the downloaded rom say that it contains the language. I am Argentine, English is not my strong suit)
The same goes for "etrian odessey" (only the 1)
But the games start!
