### ISSUE TITLE
Pokémon Black, White, Black 2 and White 2 Won't Load

### ISSUE THREAD

**Issue by EmperorOfTigers** [DS-Homebrew/nds-bootstrap#1041]
**Your console:** DSi XL 
**Launch Method:** Unlaunch with Twilight Menu 17.0.0
**Version used:** Release v0.35.s2
**Game tested/used/applicable:** Pokémon Black, White, Black 2 and White 2. All of which USA, Europe releases.

**Expected Behavior:** The game loads and is playable
**Actual Behavior:** "An error has occurred."

### Steps to reproduce
1. Load one of the 4 games from your SD Card.
2. Wait about 1 minute 
3.. Error message will show

**Comment by NightYoshi370** [comment]
Load it in DS Mode as opposed to DSi Mode.

**Comment by EmperorOfTigers** [comment]
Thank you for your reply.
That has made Black and White work now. Wonder why they don't in DSi Mode?
Black 2 and White 2 now pass that screen but the second they load, they freeze. The top screen is black and the bottom screen is white. After leaving it running for a few minutes the top screen also becomes white.

**Comment by RocketRobz** [comment]
You need to reformat in FAT32 with 32kb cluster size.

**Comment by EmperorOfTigers** [comment]
That's sorted it thank you so much!
Just means they don't work in DSi mode for whatever reason.
