### ISSUE TITLE
Games don't run in spanish

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/nds-bootstrap#1042]
**Your console:**  DSi XL
**Launch Method:**  Unlaunch 2.0 with TWilight Menu 17.0.0
**Version used:**  nds-bootstrap Release v0.35.s2
**Game tested/used/applicable:**  Hotel Dusk - Room 215 (EUR) and Etrian Odyssey (EUR)
**Expected Behavior:**  the games should run in Spanish, since they include that language officially (they are not patched)
**Actual Behavior:**  games run in English only, regardless of whether the language set in TM or nds-bootstrap is spanish.

It only happens with these two games. How can i fix it?
I'm from Argentina, I have a hard time speaking English. I'm sorry!

Thanks so much! ❤️

**Comment by Mnk3y** [comment]
Same issue: #654 

You can bypass the problem with the following Action Replay codes:

Hotel Dusk (EUR) `02100BBC 00000005`
Etrian Odyssey (EUR) `020DC5DC 00000005`

These codes will force the language to be Spanish.

**Comment by SofyUchiha** [comment]
> Same issue: #654
> 
> You can bypass the problem with the following Action Replay codes:
> 
> Hotel Dusk (EUR) `02100BBC 00000005`
> Etrian Odyssey (EUR) `020DC5DC 00000005`
> 
> These codes will force the language to be Spanish.

Ok, but how do I do that?  could you explain me? Please!

**Comment by RocketRobz** [comment]
> Ok, but how do I do that? could you explain me? Please!

It's best to wait for the fix to be implemented, so cheat usage isn't required.

**Comment by Mnk3y** [comment]
If you don't want to wait, look for r4cce (R4 Cheat Code Editor). Create a usrcheat.dat with the codes from above and copy it into `sd:/_nds/TWiLightMenu/extras`. After that you can activate the code via the game menu in TWiLight Menu++.
