### ISSUE TITLE
Can`t Play GTA Chinatown Wars

### ISSUE THREAD

**Issue by CyanTrigger** [DS-Homebrew/nds-bootstrap#1043]
**Your console:**  OLD 3ds Non-XL (USA)
**Launch Method:**  Boot9strap (Using Pichaxx on 11.14.0-26)
**Version used:**  Latest Release from Updater
**Game tested/used/applicable:**  Grand Theft Auto: Chinatown Wars (YGXP) w/ Chinese Translate Patch

**Expected Behavior:** 
Game Start
**Actual Behavior:** 
Just Flash Little bit, then Black Screen

### Steps to reproduce
Just Load up .nds file

### Logs
NDSBTSRP.log [https://gist.github.com/CyanTrigger/3c16dc32f45ad940e8455b3c9dabdaaa](url)
nds-bootstrap.ini [https://gist.github.com/CyanTrigger/d4a546f3ef4f2b92a6ae2808e251d12b](url)

**Comment by urmum-69** [comment]
Chinatown wars works fine on my end - I completed the game 100% actually

It could be this translate patch, have you tried in english instead?

**Comment by urmum-69** [comment]
I'll take it that it worked?
