### ISSUE TITLE
Phineas and Ferb DS crashes(?) on rollercoaster building screen

### ISSUE THREAD

**Issue by Cchartier2003** [DS-Homebrew/nds-bootstrap#1046]
**Your console:** New Nintendo 3DS XL
**Launch Method:** TWiLightMenu++ release v17.1.0 on Luma3DS v10.2
**Version used:** release v0.35.1
**Game tested/used/applicable:** Phineas and Ferb (Title ID: CFPE)

**Expected Behavior:** The game should get past the screen where you build the rollercoaster
**Actual Behavior:** The game locks up after getting to the rollercoaster building screen

### Steps to reproduce

Boot the game
Get all the prototype parts and head to "summer fun"
tap on the rollercoaster building area
The game will "freeze up" (music still plays, but buttons and stylus taps won't register)

[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/5610714/nds-bootstrap.zip)

**Comment by RocketRobz** [comment]
Update to [this](https://github.com/DS-Homebrew/nds-bootstrap/raw/master/nds-bootstrap-stealth.7z) nds-bootstrap version.

**Comment by xiongxioi** [comment]
> Update to [this](https://github.com/DS-Homebrew/nds-bootstrap/raw/master/nds-bootstrap-stealth.7z) nds-bootstrap version.

This update seems to have fixed my freeze issues with the pokemon games (walked around in the underground area in platinum for 10 minutes without a crash). I would recommand to send this update to the twilightmenu team. 

Great work, this finally makes twilightmenu usable to me.

**Comment by urmum-69** [comment]
the issue #737 is about just this
I suppose it's possible that got fixed also, but are you sure that's the cause?

**Comment by xiongxioi** [comment]
I would say so, after run around in those games for a while longer. I haven't encoutered any freezes. 
It appears that somehow this new bootstrap killed two birds with one stone.

**Comment by urmum-69** [comment]
well, I suggest you test with the version right before the commit to see if you can reproduce the crashes
hopefully it did fix that too though

**Comment by kaminariXXX** [comment]
> 
> 
> I would say so, after run around in those games for a while longer. I haven't encoutered any freezes.
> It appears that somehow this new bootstrap killed two birds with one stone.

Can you give me an update if the freezing in gen 4 games has totally stopped? I have an r4 but i still prefer to play my games using twlmenu. Thanks!
