### ISSUE TITLE
No experience gain by battling in Pokémon B2/W2

### ISSUE THREAD

**Issue by agBAZE** [DS-Homebrew/nds-bootstrap#1047]
**Your console:** DSi XL
**Launch Method:** TWiLight Menu++ v17.1.1
**Version used:** Release v0.35.s3
**Game tested/used/applicable:** [IRDS] Pokémon: Edición Blanca 2 (S)

**Expected Behavior:** When you initially battle your rival in Aspertia City, your starter Pokémon should gain experience at the end of the battle. Same with wild Pokémon of Route 19.
**Actual Behavior:** Your Pokémon doesn't gain experience fighting trainers/wild Pokémon.

### Steps to reproduce

1. Choose your starter Pokémon.
2. Battle your rival.
3. Your Pokémon should gain experience when you win the battle but it doesn't.
3.1. If you fight wild Pokémon, you won't gain experience either.

### Other notes

* My SD card is formatted in FAT32 with 32kb cluster size.
* I'm in DS mode.
* I tested the ROM on a PC emulator, it works fine.
* __EDIT__: I just updated to the latest version of TWiLight Menu.
* __EDIT2__: The problem doesn't happen in the US version of the game.

**Comment by imora7024** [comment]
Do you have the ap patch on it?

then if it dosent maybe thats why that happens

**Comment by agBAZE** [comment]
I think it is patched, but just in case, how can I check?

**Comment by urmum-69** [comment]
nds-bootstrap should apply ap patches on-the-fly to the game
16.3.0 is not the latest, but I doubt that's causing the problem
I suggest you update anyway

**Comment by takeshineale128** [comment]
mine gains exp on the uk version with the latest twilight menu

**Comment by agBAZE** [comment]
I just updated the TWL Menu to the latest version and still have the same problem. I will test with US version of the game for a reference

**Comment by agBAZE** [comment]
Here's the weird thing: I've tried the US Pokémon White 2 and the problem doesn't happen! It is only on Spanish version.
Well, I think I can understand English enough to play a Pokémon game in this language. So, I will do that.
Thanks you all for guiding me!

**Comment by takeshineale128** [comment]
https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/page-628#post-9279691
https://gbatemp.net/threads/nds-bootstrap-loader-run-commercial-nds-backups-from-an-sd-card.454323/
check out these thread to post your issue to see if the ap can be fixed on the spanish version

**Comment by agBAZE** [comment]
The problem seems not to be fixed. I'm closing this issue. Thank you guys.

**Comment by RocketRobz** [comment]
Usually, issues shouldn't be closed if they aren't fixed, but since this is not an nds-bootstrap issue, it's fine.

**Comment by MasterGamingYT** [comment]
That is an anti-piracy measure, please apply the AP Patch from the thread
