### ISSUE TITLE
SoftResetting crashes 3DS

### ISSUE THREAD

**Issue by Bloemenpot** [DS-Homebrew/nds-bootstrap#1048]
**Your console:** Old Nintendo 3DS
**Launch Method:** TWiLight Menu++ v17.1.1
**Version used:** 
**Flashcart used:** SD Card that came with my O3DS
**Game tested/used/applicable:** Pokemon Platinum

**Expected Behavior:** When pressing L + R + Start + Select the game should just restart.
**Actual Behavior:** The 3DS Crashes and i get the message "An error has occurred. Press and hold the POWER Button to turn the system off. Please refer to the Operations Manual for details. See image below in Other Notes."

### Steps to reproduce

 For reference i followed this tutorial https://www.youtube.com/watch?v=_VgGM9DwogA . Then just startup TWiLight Menu++. Start Pokemon Platinum. Do the key combination 'L + R + Start + Select'. then the game crashes 

### Logs

 I am quite new to modding etc so i dont know where to enable this.

### Other notes

![WhatsApp Image 2020-12-03 at 11 44 00](https://user-images.githubusercontent.com/71632717/101004736-efb9dd00-3560-11eb-96e8-4f8068197325.jpeg)

**Comment by RocketRobz** [comment]
You need to install the game booter CIA.
If you already did, then follow [this](https://3ds.hacks.guide/move-emunand) guide to move EmuNAND.

**Comment by Bloemenpot** [comment]
> 
> 
> You need to install the game booter CIA.
> If you already did, then follow [this](https://3ds.hacks.guide/move-emunand) guide to move EmuNAND.

Ah, it seems i forgot to actually install the CIA because i had it in the wrong folder and didn't see it in my cia's folder. 
thnx it works now
