### ISSUE TITLE
cheats not working with some games

### ISSUE THREAD

**Issue by eadmaster** [DS-Homebrew/nds-bootstrap#1049]
**Your console:** n3DS XL (11.6.0-39E)
**Launch Method:** SysNAND CFW + [Luma3DS v10.2.1 with Redshift and TwlBg switcher](https://gbatemp.net/download/luma-10-2-1-with-redshift-and-twlbg-switcher.35619/updates) + TWiLightMenu v16.6.0
**Version used:** v0.35.1
**Game tested/used/applicable:** Legendary Starfy, The (USA) (CRC32: 9999E966), Kirby - Mouse Attack (Europe) (En,Fr,De,Es,It).nds (CRC32: DF8258D2)
**Expected Behavior:** Infinite health and other cheats working
**Actual Behavior:** cheats not working

### Steps to reproduce

- download the latest usrcheat.dat via TM++ updater
- Start TM++
- select the ROM and enable the "Infinite health" cheat

my nds-bootstrap.ini:
````
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/_DPAD/Super Mario 64 DS (USA).nds
SAV_PATH = sd:/roms/nds/_DPAD/saves/Super Mario 64 DS (USA).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
AP_FIX_PATH =
GAME_SOFT_RESET = 1
````

**Comment by DeadSkullzJr** [comment]
You likely were trying to use codes that utilized a code type that nds-bootstrap has issues with. Codes utilizing said code type may work partially, not work at all, or in some cases, crash the game when used on TWiLightMenu. Defining which ones use it would be tough because so many cheats exist in the database that use them, so it's not something that can be altered easily. The cheats themselves actually work correctly when used on flash cartridges and or emulators (basically the cheats aren't the issue). You'll just have to use something else for the time being until that issue is fixed if you really want to use certain cheats.

**Comment by eadmaster** [comment]
indeed i suspected something like this so i switched back to my old R4 flashcart where they are working correctly.

Btw all the codes in the datfile i've tried for those games were not working, and i've also tried an old trainer made by cracker for Kirby Mouse Attack (statically patched) and it was not working either. So i guess this is related to ndsbootstrap in some other way... (or maybe those games have some kind of "protection" against cheats)

**Comment by DeadSkullzJr** [comment]
> 
> 
> indeed i suspected something like this so i switched back to my old R4 flashcart where they are working correctly.
> 
> Btw all the codes in the datfile i've tried for those games were not working, and i've also tried an old trainer made by cracker for Kirby Mouse Attack (statically patched) and it was not working either. So i guess this is related to ndsbootstrap in some other way... (or maybe those games have some kind of "protection" against cheats)

I tested the codes personally and they all seem to work on emulation and flash cartridges on my end. I haven't tested them on TWiLightMenu considering I don't really use it, but I would see if they would work on the latest version of TWiLightMenu if you haven't tried that already yet.

**Comment by eadmaster** [comment]
UPDATE: this seems fixed in the latest release of TWiLightMenu/nds-bootstrap.
