### ISSUE TITLE
Taiko no Tatsujin DS: Touch de Dokodon! screen flickers in a unusual way

### ISSUE THREAD

**Issue by Syko7956** [DS-Homebrew/nds-bootstrap#1051]
**NEW 3DS XL**
**Luma 3DS 10.2.1** 
**nds-bootstrap Ver. Release v0.35.1** 
**Taiko no Tatsujin DS: Touch de Dokodon!**  SDK ver: 3 TID: YKTJ

**Expected Behavior:** Display the game correctly
**Actual Behavior:** This has been a problem from the start (or at least since 2019 which is when I started using this) and it's my fault for never reporting this till now. Okay this is hard to describe in words but if you can experience the same problem, it's extremely noticeable. What happens is that a static frame of whatever is moving on the bottom screen will show up on the top screen and this happens the other way around. Then it flickers the previous menu containing the same issue. For example, at the file select menu, it will flicker the title screen. Both rendering improperly. This conveniently doesn't occur when you're playing an actual song. But it's really distracting seeing it literally everywhere else in the game. 

### Steps to reproduce

Trust me, you'll notice it instantly. The title screen shows the problem

NDSBTSRP.LOG:
`findModuleParamsOffset:
Module params offset restored: 02000B80
sdk_version: 03027532
This rom is compressed

Switched to NTR mode BIOS
old heap pointer: 020D0520

new heap pointer: 020D1D20

Heap Shrink Sucessfull

relocate_ce9
firstCardLocation 020D0520 : 02780000

armReadCardLocation 020D0614 : 02780000

thumbReadCardLocation 020D0630 : 02780000

armReadCardDmaLocation 020D0660 : 02780000

armReadSlot2Location 020D0684 : 02780000

armSetDmaCardLocation 020D06B8 : 02780000

thumbReadCardDmaLocation 020D06F0 : 02780000

thumbSetDmaCardLocation 020D0710 : 02780000

armReadNandLocation 020D073C : 02780000

thumbReadNandLocation 020D0768 : 02780000

armWriteNandLocation 020D0790 : 02780000

thumbWriteNandLocation 020D07B0 : 02780000

armIrqEnableLocation 020D07E0 : 02780000

thumbIrqEnableLocation 020D0800 : 02780000

pdashReadLocation 020D082C : 02780000

thumbReadSlot2Location 020D0850 : 02780000

ipcSyncHandlerLocation 020D0890 : 02780000

resetLocation 020D08BC : 02780000

globalCardLocation 020D1BEC : 02780000

 ce9->patches 020D0558

patchCardNds

swi12 location : 0200025C

cardIrqEnable location : 0206E0A4

startOffset : 02000000

cardRead location : 02077D6C

cardPullOut location : 020785AC

cardId location : 02077D04

patchCardSetDma
cardReadDma location : 02077E6C

patchMpuSize: 00000000

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

JumpTableFunc: 0238C200
Eeprom read:	0238C20C
Eeprom page write:	0238C224
Eeprom page prog:	0238C23C
Eeprom verify:	0238C254
Eeprom page erase:	0238C268
swi12 location : 0238C6F4

swiGetPitchTable location : 02387864

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02390440

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00001FC2`

**Comment by RocketRobz** [comment]
Make sure NTR clock speed is set.

Closing, since there have been some speed improvements.
