### ISSUE TITLE
Contact EUR gets stuck

### ISSUE THREAD

**Issue by EmperorOfTigers** [DS-Homebrew/nds-bootstrap#1052]
**Your console:** DSi XL
**Launch Method:** Unlaunch with Twilight Menu 17.2.1
**Version used:** Release v0.35.s4
**Game tested/used/applicable:** Contact - Europe release

**Expected Behavior:** Dialog starts showing in text area.
**Actual Behavior:** No dialog is shown so game is unable to continue

### Steps to reproduce

1. Load the game
2. Select new game
3. Select save slot 1
4. Game stops working at point mentioned

### Other notes
Picture included to show the issue.

![IMG_20201213_195630](https://user-images.githubusercontent.com/58532114/102022632-01c92600-3d80-11eb-8d17-fab816ea6949.jpg)

**Comment by RocketRobz** [comment]
Have you tried disabling heap shrink in the per-game settings?

**Comment by EmperorOfTigers** [comment]
> Have you tried disabling heap shrink in the per-game settings?

That worked great. Thank you
