### ISSUE TITLE
Pokemon Black 2 Summary Screen goes black when i enter it

### ISSUE THREAD

**Issue by HenryHeliolisk** [DS-Homebrew/nds-bootstrap#1053]
Console: 3ds XL
CFW: Luma 3ds and Godmode9/ TwilightMenu++
Version: Release
No Flashcart
Pokemon Black 2 (US)

:Should be able to go into summary menu, and go into battles normally.* <!--What actually happened?--Screen goes black, and music and screen freezes when i go into a battle, or view my pokemon's summary.

Download Pokemon Black 2 Rom (any rom, I have tested many)
Randomize it using Universal pokemon Randomizer (the new one on github)
Put it in the roms/nds folder on SD card with twilightmenu++ installed with the latest version.
Start Game
Get first Pokemon
View the Summary

This issue happened before with a vanilla version of the game, it got fixed when i downloaded twilightmenu++, but the glitch is happening again

**Comment by RocketRobz** [comment]
AP-patch the clean ROM first, using DS-Scene ROM Tool, then randomize the AP-patched ROM.

**Comment by Remadon** [comment]
> 
> 
> AP-patch the clean ROM first, using DS-Scene ROM Tool, then randomize the AP-patched ROM.

Can confirm that this fixed the same behavior occurring to me, same setup as far as 3ds/luma/twilightmenu/ndsbootstrap are concerned.

Thanks!
