### ISSUE TITLE
Club Penguin: Elite Penguin Force graphical glitches

### ISSUE THREAD

**Issue by RyanTheInkling** [DS-Homebrew/nds-bootstrap#1056]
**Your console:** Nintendo DSi XL
**Launch Method:** TWiLight Menu++ with Bootstrap
**Version used:** v0.35.s5
**Game tested/used/applicable:** Club Penguin: Elite Penguin Force

**Expected Behavior:** The game should load up with no graphical glitches what so ever.
**Actual Behavior:** The game loads up with graphical glitches, making the game impossible to play

### Steps to reproduce

1. Put the Club Penguin: EPF rom onto the SD card
2. Load up TWiLight Menu.
3. Launch Club Penguin: EPF.

### Other notes
The game used to work before, but now it doesn't work.

**Comment by RocketRobz** [comment]
What are the graphical glitches?
If the screens flicker between each one, switch the clock speed back to NTR.

**Comment by RyanTheInkling** [comment]
The sprites keep jumping between screens.

**Comment by RocketRobz** [comment]
Hmm, I don't recall having this issue.
If you're using TWL clock speed, then NTR clock speed should fix this.

**Comment by RyanTheInkling** [comment]
That fixed it.
