### ISSUE TITLE
Final fantasy tactics a2 music bug

### ISSUE THREAD

**Issue by PandRN** [DS-Homebrew/nds-bootstrap#1057]
**Your console:** Nintendo 2ds
**Launch Method:** Luma3DS ver. 10.2.1, TWLmenu++ ver. 18.1.0
**Version used:** 0.35.1 (lastest stable?)
**Game tested/used/applicable:** Final Fantasy Tactics A2 Grimorie of the Rift

**Expected Behavior:** When Main Character joins to clan, and obitained first profession, music must change to battle theme
**Actual Behavior:** battle music don't start playing, it's just silent

### Steps to reproduce

Nothing specific, it's a part of starting cutscene

**Comment by RocketRobz** [comment]
Assuming the latest commits have fixed this, I'll close this.
