### ISSUE TITLE
game:“hiren the Wanderer5: The Tower of Fortune and the Dice of Fate ”have a bug

### ISSUE THREAD

**Issue by ASHCHEN1993** [DS-Homebrew/nds-bootstrap#1058]
Console Configuration:default
TWiLight Menu++ Version:v18.2.1
TWiLight Menu++ Theme:ds
game:hiren the Wanderer5: The Tower of Fortune and the Dice of Fate（Chinese` version）

Expected behaviour:
Normal access to any room
Actual behaviour：
The game has a crash problem when you get out of the “Civet Cat Hotel”
Steps to reproduce：
go to the“Civet Cat Hotel” and get out。
ps.Chinese version modified to Japanese version

**Comment by RocketRobz** [comment]
Try turning off heap shrink in the per-game settings in TWLMenu++.

**Comment by RocketRobz** [comment]
Closing this due to no reply, and the latest version that removes heap shrink should fix this.
