### ISSUE TITLE
DSiWare games won't load 

### ISSUE THREAD

**Issue by EmperorOfTigers** [DS-Homebrew/nds-bootstrap#1059]
**Your console:** DSi XL.
**Launch Method:** Unlaunch 2.0 and TwiLight Menu 18.2.1
**Version used:** Release v0.35.s5
**Game tested/used/applicable:** Any DSiWare game I've tried (I tried Dragon Quest Wars, Legend Of Zelda Four Swords Anniversary Edition and Mario Vs Donkey Kong: Minis March Again).

**Expected Behavior:** Not sure of the exact steps but selecting the DSiWare game is meant to load through Unlaunch.
**Actual Behavior:** I get an error "fatInitDefault failed!".

### Steps to reproduce

Load any DSiWare game that I mentioned above through Twilight Menu.
Select target bootstrap file (I chose the release version mentioned).
Select target ROM (The DSiWare game) (When doing Dragon Quest Wars it was "4B445145.nds").
"NDS-BOOTSTRAP" screen appears then a second.
"fatInitDefault failed!" is displayed on bottom screen.

### Other notes
Loading directly through Unlaunch directly instead of through Twilight Menu leads to the same issue.
In Twilight Menu "DSiWare Booter" is set to Unlaunch.
ROMs were made as .nds with appgen.
I believe I am doing what I'm meant to but if I'm doing something wrong I apologise.

**Comment by RocketRobz** [comment]
Sounds like you're not actually launching a DSiWare game.
If you're sure it's a DSiWare game, idk how to fix this.
