### ISSUE TITLE
Poor LZSS Detection on Windows

### ISSUE THREAD

**Issue by SNBeast** [DS-Homebrew/nds-bootstrap#1060]
This is the definition of where the LZSS executable is in `retail/cardengine/arm7/Makefile` and other places:
```
ifeq ($(OS),Windows_NT)
LZSS                    ?=      ../../lzss.exe

else

LZSS                    ?=      lzss

endif
```
This means that on Windows the executable has to be in `retail` regardless of presence in directories on path (at least in MSYS). This is, if not unintended behavior, not documented in the README.

**Comment by Lieonkp** [comment]
Please try changed **ifeq** to **ifneq** may help.

**ifneq** ($(OS),Windows_NT)
LZSS                    ?=      ../../lzss.exe

else

LZSS                    ?=      lzss

endif

**Comment by Epicpkmn11** [comment]
Changing ifeq to ifneq would break anything besides windows, it'd be better to just change it to
```
LSZZ ?= lzss
```
on everything and require it to be in PATH, not sure why most of our Makefiles have that exception for Windows... I guess just cause Windows doesn't really have a proper place to just put executables and PATH is kinda weird to access?

**Comment by Lieonkp** [comment]
Me too.

> Changing ifeq to ifneq would break anything besides windows, it'd be better to just change it to
> 
> ```
> LSZZ ?= lzss
> ```
> 
> on everything and require it to be in PATH, not sure why most of our Makefiles have that exception for Windows... I guess just cause Windows doesn't really have a proper place to just put executables and PATH is kinda weird to edit?

Thank you.
