### ISSUE TITLE
Manual soft reset (L+R+SELECT+START) on nds game roms crashing on normal 3DS and very slow on 3DSXL

### ISSUE THREAD

**Issue by Animajosser** [DS-Homebrew/nds-bootstrap#1063]
**Your console:** Nintendo 3DS (not the new one as far as I know) and a Nintendo 3DS XL
**Launch Method:** on both: System software 11.14 + Luma3DS v10.2.1 + TwilightMenu v18.3.0 (installed on the 3DS and internal SD card); launching all games from the internal SD card (no flashcard and no physical games).
**Version used:** v0.35.s5 (included in TwilightMenu); also tried nightly (hash: 02979d9c)
**Game tested/used/applicable:** Pokemon Pearl, Pokemon SoulSilver, Pokemon  Black Version, Pokemon HeartGold, Pokemon Platinum, Pokemon Diamond, Pokemon White Version 2.

**Expected Behavior:** 
When pushing the button combination: L+R+SELECT+START a soft-reset of the game should occur.

**Actual Behavior:** 
On the normal 3DS, the screen goes black, after a few seconds the backlight turns on again, it takes a while and it returns to the system menu. When starting TwilightMenu again it immediately goes back into the game it tried to softreset.

On the 3DSXL, the screen goes black, it takes a while and it does actually eventually start the game, but it takes a long time.

### Steps to reproduce

Install TwilightMenu as described in "Launch Method" on a device as in "Your console". Add a game from "Game tested/used/applicable". Use standard settings and click on the game. Go into the game in a save file. Then hold L+R+SELECT+START.

Other tried settings:
Tried with default settings of TwilightMenu, but also tried setting some optimization settings, like setting to DSI mode, booting the CPU and VRAM and extending the Memory.

### Logs
Here the log for Pokemon White Version 2 and the nds-bootstrap.ini used for it on the normal 3DS

nds-bootstrap.ini:

    [NDS-BOOTSTRAP]
    DEBUG = 0
    LOGGING = 1
    CACHE_FAT_TABLE = 0
    ROMREAD_LED = 0
    DMA_ROMREAD_LED = -1
    CONSOLE_MODEL = 2
    CACHE_BLOCK_SIZE = 1
    PRECISE_VOLUME_CONTROL = 0
    SOUND_FREQ = 0
    NDS_PATH = sd:/roms/nds/Pokemon - White Version 2.nds
    SAV_PATH = sd:/roms/nds/saves/Pokemon - White Version 2.sav
    RAM_DRIVE_PATH = sd:/null.img
    LANGUAGE = -1
    DSI_MODE = 0
    BOOST_CPU = 0
    BOOST_VRAM = 0
    EXTENDED_MEMORY = 0
    DONOR_SDK_VER = 0
    PATCH_MPU_REGION = 0
    PATCH_MPU_SIZE = 0
    CARDENGINE_CACHED = 1
    FORCE_SLEEP_PATCH = 0
    AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/IRDO-D75C.ips

NDSBTSTRP.LOG:

    findModuleParamsOffset:
    Module params offset restored: 02004FCC
    sdk_version: 0503757C
    This rom is compressed
    
    Switched to NTR mode BIOS
    patchCardNds
    
    [SDK 5]
    
    swi12 location : 020044EA
    
    dsiModeCheck location : 02004EB4
    
    cardIrqEnable location : 02079E9C
    
    startOffset : 02004000
    
    cardRead location : 0206FAE0
    
    cardPullOut location : 0206FF28
    
    cardId location : 0206F9C0
    
    
    patchCardSetDma
    cardReadDma location : 0206FC94
    
    reset location : 0207C2C8
    
    ERR_NONE
    
    
    Arm7 (patch v5)
    Relocation src: 02380644
    JumpTableFunc: 0238FB14
    card read:	0238FAFC
    Eeprom read:	0238FB20
    Eeprom page write:	0238FB38
    Eeprom page prog:	0238FB50
    Eeprom verify:	0238FB68
    Eeprom page erase:	0238FB7C
    swi12 location : 02383BA4
    
    swiGetPitchTable location : 02383BB8
    
    ERR_NONE
    
    hookNdsRetailArm7
    hookLocation arm7: 02391918
    
    ERR_NONE
    hookLocation arm9: 02FE0020
    
    AP-fix found and applied
    chipID: C001FEC2

### Other notes

Might be related to #876

Already existed on Release v0.35.s4

**Comment by Animajosser** [comment]
Theory: After reading some of the release notes, it seems that the behavior on the normal 3ds looks like the behavior described for B4DS builds. However I'm using the 3DS builds, so that shouldn't happen.
While reading the manual page for nds-bootstrap, I saw there was a soft reset for all games using the same button combination (L+R+SELECT+START). If I understand correctly this will force it in games that don't support it normally. However, these Pokemon games support it also when playing the game from the official cartridges. Maybe there is some detection going wrong and does it force the reset here too? I'm not sure if that would cause it to crash or lag though (I understand there is some implementation on the side of nds-bootstrap required), but it might be related.

**Comment by Animajosser** [comment]
I just updated both devices to the latest version of TwilightMenu and with that the latest version of NDS-Bootstrap and it seems like soft-resetting on the normal 3DS doesn't crash to the homescreen anymore. It is still quite slow on both devices, but it seems like there is progress.

**Comment by Animajosser** [comment]
It seems to be resolved. I guess I'll close the issue to make it clear this is fixed for now.

**Comment by schm1dtHL** [comment]
I wouldn't actually close this yet, as only soft-resets that games themselves trigger are fixed on 3DS, due to them being able to use the new fast-soft-reset setup(in NSMB for example, prior to the update the Minigames menu would crash(O3DS)/take ages to load(N3DS), whilst now it loads correctly across the board and loads quickly). Manually soft-resetting or exiting to TWLMenu via the in-game-menu hasn't been affected though as they use the old soft-reset implementation, so on my O3DS those still crash to the homescreen, and I'd guess on N3DSes those are still slow.
