### ISSUE TITLE
Trouble launching Pokemon White 2

### ISSUE THREAD

**Issue by Lyzder** [DS-Homebrew/nds-bootstrap#1065]
**Your console:** old 3DS 
**Launch Method:** Firmware 11.14.0-46U. Luma v10.2.1. Fowarder3-DS v2.9.6
**Version used:** release 0.35.1 
**Game tested/used/applicable:** Pokemon White 2. TID TWL-IRDO-USA

**Expected Behavior:** The game should've launched without issue
**Actual Behavior:** at first nds-bootstrap printed "start failed. error -2", now the bottom screen turns white and the game doesn't launch.

### Steps to reproduce
Just try to launch the game. It's the only game I'm having this problem.

[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/5870306/nds-bootstrap.zip)

**Comment by RocketRobz** [comment]
Try reformatting the SD card to FAT32 with 32kb cluster size (even if already using FAT32).

**Comment by Lyzder** [comment]
Done, but it didn't help

**Comment by RocketRobz** [comment]
Does the ROM boot in an emulator?
If not, then your ROM is corrupted.

**Comment by Lyzder** [comment]
It does. Desmume opens the rom without issues

**Comment by RocketRobz** [comment]
Try launching the ROM through TWiLight Menu++ then.

**Comment by Lyzder** [comment]
It worked, but I don't know why tho

**Comment by RocketRobz** [comment]
Same here.
