### ISSUE TITLE
Frequent Freezing in HeartGold Randomizer

### ISSUE THREAD

**Issue by Washing-Tub** [DS-Homebrew/nds-bootstrap#1066]
**Your console:**  Nintendo DSi
**Launch Method:**  Twilight Menu ++ v18.3.0
**Version used:** Release v0.35.s5 AND Nightly
**Game tested/used/applicable:**  Pokemon HeartGold (USA) Randomizer made using the Universal Randomizer tool

**Expected Behavior:** Game should play as normal, no freezing. 
**Actual Behavior:** Game frequently freezes every 10-20 minutes, either a softlock or black screen, and has intensified to nearly every twenty seconds upon beating Whitney.

### Before Whitney: Simply wander around the overworld, usually occurs after entering or exiting a largenumber locations or maps during the current play session. Sometimes occurs when/after picking up an item or before/after a battle.
After Whitney: Run around for 20 seconds, or enter and exit any location/map, open a menu, open the PC, talk to NPCs, start a battle, switch Pokemon around, exist, have not tested with picking up items(haven't been able to move very far), sometimes happens right after booting up the game.

I'm sorry in advance, I do not know where to find the .ini file? 
As far as I've seen I do not require anything to make the freeze happen. There are two consistent types of freezes. One is in the overworld where the music keeps playing but you cannot move(this is the softlock many others reported having), the other is a simple black screen that occurs when I exit or enter buildings or battles, occasionally music will play during these.
 It became worse when I first visited Goldenrod City, and even worse when I beat Whitney.  I used the Univesral Randomizer tool and the tool used to randomize colors. 
I saw that others were having similar issues, but none to the degree I'm seeing. This rom was not AP patched before I started, and I do have a different HG randomizer with a similar seed that HAS been AP patched(randomized colors are also the same) and I'll test it soon, but considering I've already sunk about 9 hours into this save file I am NOT looking forward to restarting lol 
Maybe I'll test my other randomizers first.
Changing settings does not in any way change the outcome. Using Nightly or turning off WiFi however states there is a communication error when on the Title screen, before booting up normally.
### Logs

SCFG_ROM ARM9 1
SCFG_CLK ARM9 85
SCFG_CLK ARM7
SCFG_EXT ARM7
ARM7 data 187
ARM7 data FB06
debug: true
NdsPath:   "sd : /ROMs/Nintendo DS/Pokemon Rabdomizers/Heartgold Color + Randomizer1.nds "
savPath:    "sd : /ROMs/Nintendo DS/Pokemon Randomizers/saves/Heartgold Color + Randomizer1.sav "
gbaPath: " "
Press start. . .
donorE2Path: " "
donor2Path: " "
donor3Path: " "
donorPath: " "
donorTwlPath: " "
Press start. . .
saveSize: 80000
language:   FF
dsiMode: 0
donirsdkVer: 0
patchMpuRegion: 0
patchMpuSize:  0
ceCached:  true
cacheBlockSize:  8000
extendedMemory: false
consoleModel:   0
colorMode:  0
romRead_LED:  0
dmaRomRead_LED:   FFFFFFFF
boostCpu:  false
boostVram:  false
soundFreq:  false
forceSleepPatch:  false
logging:  false
initDisc:  false
gameOnFlashcard:  false
saveOnFlashcard:  fakse
backLightMode:  0
Press start. . .

### Other notes
I had another Randomizer that came with the SD card 
When I bought this DSi secondhand(the seller modded and set it up for the purpose of selling it) and that game froze frequently too. It is located in a different folder.
Edit: I was planning to post a video of the black screen freez happening in action, but the file was too big. I'll just state what happened, and clarify that it happened multiple times in my recording attempts.
In enter the gate from Goldenrod to Route 35. Exit to Route 35. Go back into the gate, and it freezes. This is about how frequently they occur. I spend less time in the game now than I do rebooting the game.

**Comment by xfix** [comment]
Seems like anti-piracy issue to me. You are using a ROM hack, so you need to patch anti-piracy patch manually, TWiLight Menu++ won't apply it for you as the ROM is different.

**Comment by RocketRobz** [comment]
Closing, as this is AP related.
