### ISSUE TITLE
Broke the DS side of my system can't play any NDS from cartidges

### ISSUE THREAD

**Issue by caydenpri44** [DS-Homebrew/nds-bootstrap#1071]
Twilight menu broke the DS side of my 3ds causing the system to not be able to play NDS games even cartridges. Twilight menu broke part of my 3DS. It tampered the DS part of my 3DS via the CTR NAND. It deleted NDS compatibility from the CTR NAND. I need the file to let 3DS play NDS games. Any DS game I play either crashes with a white and black screen this happened after updating. Or would appear with a Luma message saying please check your CTR NAND. Please fix this also what file is used to allow 3DS to be compatable with DS games I might be able to find the file online.

**Comment by Lillievela** [comment]
Im pretty sure Twilightmenu doesnt even touch the CTRNAND as its a TWLNAND only homebrew. Its possible that some other homebrew caused the CTRNAND issue, as far as the cart loading issue it could just be that the pins need cleaning or possibly something with something else.

**Comment by urmum-69** [comment]
Likely TWiLight Menu++ had absolutely nothing to do with it.

Follow this guide:
https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by caydenpri44** [comment]
why closed

**Comment by caydenpri44** [comment]
why closed. understand i don't.

**Comment by caydenpri44** [comment]
why closed. understand i don't. closed why?!?! whyyyyyyyy?!?! understand me don't. wat happen.

**Comment by caydenpri44** [comment]
> Likely TWiLight Menu++ had absolutely nothing to do with it.
> 
> Follow this guide:
> https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

thank you person.

**Comment by caydenpri44** [comment]
For one why need fix place first. just why?

**Comment by hansoljin** [comment]
> For one why need fix place first. just why?

For one, this isn't even TWiLight Menu++ related. 
Second, the hacking process for the 3DS isn't going to work perfectly for everyone. Other people had this issue too. It was fixed using that link.

**Comment by caydenpri44** [comment]
oh ok

**Comment by caydenpri44** [comment]
> > For one why need fix place first. just why?
> 
> For one, this isn't even TWiLight Menu++ related.
> Second, the hacking process for the 3DS isn't going to work perfectly for everyone. Other people had this issue too. It was fixed using that link.

wat why why bully felling hurt. much sad no bobux no robux. my eyes are bleeding from that comment. much depressed much sad. much hurt.

**Comment by caydenpri44** [comment]
im sad. "_'  :{ :[ ;( ;((
much double chin :)))))))))))

**Comment by NightYoshi370** [comment]
Please mature up or you will no longer be able to post issues or comments.
