### ISSUE TITLE
Golden Sun: Dark Dawn - Doesn't Boot , Black screen . PLS fix

### ISSUE THREAD

**Issue by Gusion-ux** [DS-Homebrew/nds-bootstrap#1072]
**Your console:** 
**Launch Method:** 
**Version used:** 
**Flashcart used:** 
**Game tested/used/applicable:** 

**Expected Behavior:** 
**Actual Behavior:**

**Comment by NightYoshi370** [comment]
Already a known issue. Closing due to duplicate
