### ISSUE TITLE
DSi: Unable to pass 'Touch to start' on Super Mario 64 DS

### ISSUE THREAD

**Issue by AmetusPayne** [DS-Homebrew/nds-bootstrap#1074]
Hi. How can I fix this? I found some ways for 3ds, but not for DSi. Touchscreen doest't work  in this game

**Comment by hansoljin** [comment]
Just tested it, I don't seem to be having this issue with a clean, untrimmed dump, on an Unlaunch'd DSi. Can't test it on the 3DS right now because I don't use nds-bootstrap on it.

Try another copy of the game and see if that does anything.

**Comment by AmetusPayne** [comment]
It's just needed an update of TWiLightMenu.
Thanks
