### ISSUE TITLE
Pokemon Ranger: Guardian Signs Crashing during transition

### ISSUE THREAD

**Issue by Ferbee** [DS-Homebrew/nds-bootstrap#1075]
**Your console:** Old 3DS XL
**Launch Method:** Luma3DS v10.2.1, I'm launching nds-bootstrap through TwilightMenu++ v18.5.0
**Version used:** Release v0.36.0
**Game tested/used/applicable:** MD5 Hash: E70F2A05F41FD00E01AD163E54A1407E 
TitleID: B3R3

**Expected Behavior:** It should've continued on to the next part of the cutscene with time travelling celebi
**Actual Behavior:** Black screen, with repeating music

### Steps to reproduce

[Pokemon Ranger - Guardian Signs Save.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/6004470/Pokemon.Ranger.-.Guardian.Signs.Save.zip)

1. Load up the save
2. Walk down out of the door twice
3. Go down to the right, and proceed out that door
4. Go out the door at the bottom
5. Celebi should come and put the character into a yellow ball thing, then transition to black
6. Freeze

### Logs

[Logs and debugging.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6004465/Logs.and.debugging.txt)

**Comment by RocketRobz** [comment]
In TWLMenu++ Settings, change the cache block size to 32KB.
