### ISSUE TITLE
Goldden Sun Dark Dawn (USA) not run

### ISSUE THREAD

**Issue by anonymous-88** [DS-Homebrew/nds-bootstrap#1076]
Hi,
thanks for the great work!

I run Goldden Sun Dark Dawn (USA) but it is not run and still stuck black screen after run
![IMG_1550](https://user-images.githubusercontent.com/79297359/108458226-ccbce080-72a6-11eb-8c22-8c471e171f94.JPG)
.
I Updated newest ver of nds-bootstrap 

Anyone can help me?

Thanks

**Comment by RocketRobz** [comment]
Nowhere in the changelog of the latest nds-bootstrap version says it's fixed.

**Comment by anonymous-88** [comment]
> Nowhere in the changelog of the latest nds-bootstrap version says it's fixed.

NO, Exactly problem in the list
https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/htmlview#gid=0
![image](https://user-images.githubusercontent.com/79297359/108480233-45cd2f80-72c9-11eb-8ffd-e09342bb5edf.png)
