### ISSUE TITLE
Apologies to chyyran unflag me, please help. My websites are gone. :(

### ISSUE THREAD

**Issue by caydenpri44altacc** [DS-Homebrew/nds-bootstrap#1086]
Please help. My hard work is gone. :( :(:( caydenpri44.github.io/Jacket_brew/ is not working cause i am flagged helpppppp!
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(
:(

**Comment by caydenpri44altacc** [comment]
help me please

**Comment by chyyran** [comment]
https://github.com/DS-Homebrew/nds-bootstrap/issues/1085

**Comment by chyyran** [comment]
Just as a note, if you have local copies of your git repositories, you can re-upload them to GitHub.
