### ISSUE TITLE
Consider adding bootstrap versioning and game ID CODE to the FAT and Patch caches

### ISSUE THREAD

**Issue by Squall-Leonhart** [DS-Homebrew/nds-bootstrap#1088]
**Is your feature request related to a problem?**
Yes, 

When a user updates TWMenu using the universal updater and new bootstrapper capabilities have been added, it has been seen (by myself) that the presence of a Patch table from a previous version results in things not working correctly.

For example, after the valentines update, I encountered the problem that the Auto setting for the heap size setting was not permitting Phantoms hourglass AZEP to boot, whilst Off and High did.  Deletion of the Patch cache for this game rectified this situation.

Secondly, if one has collected carts from multiple regions (such as myself for my past testing and contributions to desmume) if you have listed dumps per folder (per regions) without using the usual (Region) (Language X,Y,Z) that good dump sets typically organize by, the FAT and Patch cache will be invalid for say AZEE and fail to boot if AZEP has been booted previously.

**Describe the solution you'd like**
A good way, would be to embed the [title] information in the cached files and then logic which would result in invalidation of these files and forced updates if the bootstrap has updated or the game being booted differs from the one the game was created with.

as the bootstrap or TW Menu evolves, there is likely to be more and more changes that cause this cached data to just break game boots (and not all users are going to be savvy enough to dig through and realise these files are potentially a problem.)

**Describe alternatives you've considered**
~~The only alternative would pose a problem for romhacks, which would be creating the caches per the game ID instead of file name.~~

A workable alternative for the second issue would be to have the files be Filename[ID].extension so you wouldn't need to invalidate the caches because of booting the alternate regions rom, that still leaves the issue with strapper updates though.

**Comment by stevenptimms** [comment]
@Squall-Leonhart Squall I'm trying to contact you, please could you check your inbox on vba-m.com? Thanks

**Comment by RocketRobz** [comment]
The patch offset cache files already have versioning, and the filenames are already named the ROM's TID, along with the header CRC from the ROM.

Not sure as to why things wouldn't work properly, aside from those. Deleting the patch offset cache files is always an option.
