### ISSUE TITLE
Start failed. Error 1 whenever booting any of the generation 5 Pokemon games and their respective romhacks

### ISSUE THREAD

**Issue by pingas12345** [DS-Homebrew/nds-bootstrap#1089]
**Your console:** Original/Old 2DS
**Launch Method:** using Luma3DS on the latest version, using TwilightMenu latest, 11.14 FW 
**Version used:** Stable release

**Game tested/used/applicable:** Pokemon White, Pokemon White 2, Pokemon Black, Pokemon Black 2 and their respective romhacks Blaze Black/2 Volt White/2

**Expected Behavior:** normal boot with NDS-Bootstrap splash screen
**Actual Behavior:** White top screen and black bottom screen with text "Start failed. Error 1"

### Steps to reproduce

Boot the game?

Here's nds-bootstrap.ini as a .txt

[nds-bootstrap.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6061157/nds-bootstrap.txt)

### Other notes
I've been trying so many solutions suggested to me: deleting _nds, reinstalling TwilightMenu, changing settings, trying different roms but nothing seems to work.

**Comment by RocketRobz** [comment]
Are you sure this is only with those ROMs?
Do other ROMs have the same issue?

Also, did you follow [this](https://wiki.ds-homebrew.com/twilightmenu/installing-3ds) guide?

**Comment by pingas12345** [comment]
Yes, it seems only these games have this issue. I've tried another NDSi-enhanced game, Kung Fu Panda 2 and that boots up fine. As you can tell by the nds-bootstrap.ini I am in DS mode and not DSi.
And yes, I've followed the "Non-working Camera" part of the guide.
I have a feeling it's because of AP patching? But I really have no clue.

**Comment by RocketRobz** [comment]
Try holding A+B+X+Y after booting TWLMenu++, to reset the settings.

**Comment by RocketRobz** [comment]
Actually, I think there's something in the filename that's causing this.
Try changing the `e` in Pokemon to a regular `e`.

**Comment by pingas12345** [comment]
The "e" are all regular. I've resetted the settings using A+B+X+Y but still get the error

**Comment by RocketRobz** [comment]
Please check the SD card for errors.
If there's none found, then please try another SD card, or else, I'm out of ideas.

**Comment by pingas12345** [comment]
I've recently reformatted the SD to 32KB cluster because I got the prompt that it was under 32KB. Otherwise, I'll try changing SD cards.

**Comment by Squall-Leonhart** [comment]
> Try changing the `e` in Pokemon to a regular `e`.

accented e's work just fine with the bootstrap.
