### ISSUE TITLE
Pokemon Black 2 "an error has occurred" set it to DS Mode nothing works...

### ISSUE THREAD

**Issue by BrokenCreature** [DS-Homebrew/nds-bootstrap#1090]
Hello.. 

I have a Problem when booting up Pokemon Black and White 1+2. Everytime i try to start the Game, it always fade away to a Black error screen and i have to press the Power Button for a couple of seconds to turn the DS off. I have a New 3ds XL, the latest Twilightmenu++ Version, latest Luma3ds Version, i run it in DS Mode, i even had different Roms, AP Patches and non-AP Patches Roms.. but nothing seems to work.. is there any solution to fix the problem? :)

**Comment by RocketRobz** [comment]
Install the TWiLight Menu++ game booter CIA as well.
