### ISSUE TITLE
Yuuzai x Muzai(J) White screen with apfix

### ISSUE THREAD

**Issue by R-YaTian** [DS-Homebrew/nds-bootstrap#1091]
**Your console:** DSi
**Launch Method:** hiyaCFW/TWLMenu++18.5.0
**Version used:** Release V0.36.0
**Game tested/used/applicable:** Rom name: 3791 - Saibanin Suiri Game - Yuuzai x Muzai (Japan) [b].nds(CBEJ-E8D2)

**Expected Behavior:** Game works fine with apfix from TWLMenu++
**Actual Behavior:** White screen

### Steps to reproduce

Just launch the game

### Logs

findModuleParamsOffset:
Module params offset restored: 02000BB8
sdk_version: 04027536
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020005EC

cardIrqEnable location : 020210E4

startOffset : 02000000

cardRead location : 02029E38

cardPullOut location : 0202A394

cardId location : 02029F28

patchCardSetDma
cardReadDma location : 02029CAC

patchMpuSize: 00000000

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F74C

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80001FC2

### Other notes

If delete the apfix file CBEJ-E8D2.ips from TWLMenu, the game will works but looping game logo screen.

**Comment by RocketRobz** [comment]
Fixed by https://github.com/DS-Homebrew/TWiLightMenu/commit/e7b9f2ed4870220626183eeba494879d9341b461
