### ISSUE TITLE
Pokemon Black/SoulSilver black screen

### ISSUE THREAD

**Issue by msmc101** [DS-Homebrew/nds-bootstrap#1093]
**Your console:**  New 3dsXl
**Launch Method:** Luma 3ds, TWilightMenu++, Luma 2.1.1 NDSbootstrap v0.36.0
**Version used:**  

**Game tested/used/applicable:**  5585 Pokemon - Black Version

**Expected Behavior:**  Game should launch with NDS Bootstrap
**Actual Behavior:**  Game black screens, system tells me to please restart.

### Steps to reproduce

1. Open TWilightMenu++
2. Boot Rom
3. Black Screen
### Other notes
I have other DS Games working perfectly fine such as Pokemon Platinum, Mario Kart DS, Castlevania, Chrono trigger, etc. and I am on the DS mode.

**Comment by RocketRobz** [comment]
This is a bug on TWiLight Menu++'s side. It'll be fixed in the next version.

**Comment by msmc101** [comment]
Thanks
