### ISSUE TITLE
Mario & Sonic at the Olympic Winter Games doesn't boot

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/nds-bootstrap#1095]
**Your console:** Nintendo DSi LL
**Launch Method:** Unlaunch with TWLMenu++
**Version used:** Nightly (as of 449ed367)
**Game tested/used/applicable:** Mario & Sonic at the Olympic Winter Games (COLE)

**Expected Behavior:** Game shows logos at the start.
**Actual Behavior:** Game crashes on white screens after a single card read.

### Steps to reproduce

1. Update nds-bootstrap to latest nightly.
2. Set nds-bootstrap to `Nightly` in TWLMenu++ Settings or the per-game settings.

**Comment by hansoljin** [comment]
COLK exact same issue, if that's relevant at all
