### ISSUE TITLE
Crafting Mama doesn't save states 

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/nds-bootstrap#1100]
**Your console:** Nintendo DSi XL
**Launch Method:**  TWiLight Menu ++ 19.0.0 with Unlaunch 2.0. 
**Version used:** nds-bootstrap v0.37.0
**Game tested/used/applicable:** Crafting Mama (EUR) (BJ8P)
**Expected Behavior:** The game must save your progress. In this way, when you run it again, you can continue the game from where you left it last time. 
**Actual Behavior:**  The game does not save your progress. When exiting the game and reopening it, all progress made previously was lost. You must start from scratch again. 

### Steps to reproduce
1. Open Crafting Mama (EUR)
2. Play
3. Exit the game
4. The next time you open the game your progress will be there

**Comment by RocketRobz** [comment]
Seems to have been fixed, as it's working on my side, though I tested the USA version.
I don't see why it wouldn't work in the EUR version.
