### ISSUE TITLE
Pokémon Soulsilver Crash 21MAR2021

### ISSUE THREAD

**Issue by ExostFPS** [DS-Homebrew/nds-bootstrap#1102]
**Your console:** <New 3DS XL>
**Launch Method:** <Luma 3DS via TWL>
**Version used:** <Release v0.37.0 and Nightly Ver. 0619341a>
**Game tested/used/applicable:** <Pokémon Soulsilver, randomized (Lower case names and impossible EVO’s) and AP patched>

**Expected Behavior:** <Game should continue to function normally when leaving/entering a battle or building>
**Actual Behavior:** <The game will stay on a black screen upon entering/leaving a fight or building, even sometimes just freezing randomly in grass.  Music continues to play normally, though.>

### Steps to reproduce

<Walk in and out of doors multiple times in order to attempt a replication.>

**Comment by ExostFPS** [comment]
Also, I realize this is a duplicate issue, but I have spent hours on the GitHub and other places looking for answers and have found NOTHING.  Just unfinished conversations so I wanted to share that it's still happening on my end.  It's frustrating having to save every few minutes.

**Comment by hansoljin** [comment]
Gen 4 has known issues with freezing out of nowhere. Refer to #737
