### ISSUE TITLE
NDS Bootstrap White Screen Chrono Trigger

### ISSUE THREAD

**Issue by DnezzarSevi** [DS-Homebrew/nds-bootstrap#1103]
**Your console:** New 3ds XL
**Launch Method:** CFW: Luma3DSV10.2.1. Launching nds-bootstrap through TWiLight Menu++ v19.0.0
**Version used:** nds-bootastrap v0.37.0 release
**Game tested/used/applicable:** Tested with: Kirby: Canvas Curse (TID: ATKE), The Legend of Zelda: Spirit Tracks (TID: BKIE), Super Scribblenauts (TID: BH2P), CHRONO TRIGGER (TID:YQUE)

**Expected Behavior:** Launch TwlightMenu++, select nds rom, save game is created, nds_bootstrap starts, game starts. This is the behavior experienced with the Kirby, Zelda, and Scribblenauts games listed above.
**Actual Behavior:** When following the same steps with Chrono Trigger, the game white screens after the 'nds-bootstrap, please wait' screen. 

### Steps to reproduce: nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/3055 - Chrono Trigger (USA) (En,Fr).nds
SAV_PATH = sd:/roms/nds/saves/3055 - Chrono Trigger (USA) (En,Fr).sav
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/YQUE-C2DF.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

Other notes: 
Have tried changing per game settings to DS Mode 67MHz (NTR Clock Speed) VRAM Boost off. Doesn't change anything.

**Comment by urmum-69** [comment]
There are some known regressions in the current release that have already been fixed in the nightly. Try using that first.

**Comment by DnezzarSevi** [comment]
Nightly works! Thanks for the help!
