### ISSUE TITLE
Increase/Decrease RAM address jump values independently

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1104]
I'm not sure if there's a proper term for this, so I'll try to describe it:
So, when jumping to an address in the in-game menu RAM Viewer, let's say the current address is 020000*0F*
If F is increased, the current address becomes 020000*10*, as if it were a whole number.

I find this counterintuitive, because if the RAM jump function is being used, the user is likely trying to go to a **specific** address that is too far to just scroll there. This is problematic because this may cause other parts of the address to be unintentionally changed.

Solution: Allow the values to be changed **completely** independently of each other, meaning 020000*0F* becomes 020000*00* when increased by 1.

**Comment by Epicpkmn11** [comment]
I think I've got it working like this in DS-Homebrew/Godmode9i#84, I'll probably port that back over to this once I'm done with it
