### ISSUE TITLE
Chrono Trigger White Screen on Launch

### ISSUE THREAD

**Issue by Damokeles** [DS-Homebrew/nds-bootstrap#1105]
**Your console:**  New 2DS XL
**Launch Method:**  LUMA3DS v10.2.1, TWLMenu++ v19.0.0
**Version used:**  release nds-bootstrap v0.37.0
**Game tested/used/applicable:**  NTR-YQUE-USA Chrono Trigger (USA) (En,Fr).nds 
**Expected Behavior:** Game launches 
**Actual Behavior:** White Screen
Launch Chrono Trigger

nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DSI_MODE = 0
NDS_PATH = sd:/roms/nds/Chrono Trigger (USA) (En,Fr).nds
SAV_PATH = sd:/roms/nds/saves/Chrono Trigger (USA) (En,Fr).sav
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
LANGUAGE = -1
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/YQUE-C2DF.ips
RAM_DRIVE_PATH = sd:/null.img
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 0

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B84
sdk_version: 04027531
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020000BC

cardIrqEnable location : 02006ABC

startOffset : 02000000

cardRead location : 02011C6C

cardPullOut location : 020121C8

cardId location : 02011D5C

patchCardSetDma
cardReadDma location : 02011AE0

patchMpuSize: 00000000

Mpu2 init: 020086A8

reset location : 02009074

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F584

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80007FC2

debug: true
ndsPath: "sd:/roms/nds/Chrono Trigger (USA) (En,Fr).nds"
savPath: "sd:/roms/nds/saves/Chrono Trigger (USA) (En,Fr).sav"
gbaPath: ""
donorE2Path: ""
donor2Path: ""
donor3Path: ""
donorPath: ""
donorTwlPath: ""
saveSize: 80000
language: FF
dsiMode: 0
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
extendedMemory: false
consoleModel: 2
colorMode: 0
romRead_LED: 0
dmaRomRead_LED: FF
boostCpu: false
boostVram: false
soundFreq: false
forceSleepPatch: false
logging: true
initDisc: false
gameOnFlashcard: false
saveOnFlashcard: false
macroMode: false

**Comment by RocketRobz** [comment]
Already fixed in recent commits.
