### ISSUE TITLE
Trauma Center 1 white screen on boot

### ISSUE THREAD

**Issue by hansoljin** [DS-Homebrew/nds-bootstrap#1106]
**Your console:** O3DSXL
**Launch Method:** Luma3DS 10.2.1 Nanquitas build
**Version used:** 72c94ee
**Flashcart used:** R4 Ultra, accessed from console-side TWiLight Menu++
**Game tested/used/applicable:** 0122 Trauma Center 1 USA (hash valid with No-Intro)

**Expected Behavior:** Game should boot.
**Actual Behavior:** White screen on boot.

### Steps to reproduce

Load game. Game will freeze.

```
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 1
NDS_PATH = fat:/ROMs/NDS/0122 - Trauma Center - Under the Knife (USA).nds
SAV_PATH = fat:/ROMs/NDS/saves/0122 - Trauma Center - Under the Knife (USA).sav
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 1
EXTENDED_MEMORY = 1
CACHE_BLOCK_SIZE = 1
CACHE_FAT_TABLE = 0
MACRO_MODE = 0

```

### Logs

log returned empty (is this normal?)

**Comment by RocketRobz** [comment]
For me, on DSi, this is fixed by turning on `Expand ROM space in RAM`.

**Comment by hansoljin** [comment]
I got the log to show. (3DS, internal SD, https://github.com/DS-Homebrew/nds-bootstrap/commit/95909a63f9cb0cfbcc42e1eae3b23af7d788597a)

`findModuleParamsOffset:
Module params offset restored: 02128554
sdk_version: 02017532
arm9 is not compressed

Switched to NTR mode BIOS
relocate_ce9
firstCardLocation 023F0000 : 02780000

armReadCardLocation 023F00F0 : 02780000

thumbReadCardLocation 023F0110 : 02780000

armReadCardDmaLocation 023F0140 : 02780000

armReadSlot2Location 023F0164 : 02780000

armSetDmaCardLocation 023F0198 : 02780000

thumbReadCardDmaLocation 023F01D0 : 02780000

thumbSetDmaCardLocation 023F01F0 : 02780000

armReadNandLocation 023F0214 : 02780000

thumbReadNandLocation 023F0238 : 02780000

armWriteNandLocation 023F0250 : 02780000

thumbWriteNandLocation 023F0270 : 02780000

armIrqEnableLocation 023F02A0 : 02780000

thumbIrqEnableLocation 023F02C0 : 02780000

pdashReadLocation 023F02EC : 02780000

thumbReadSlot2Location 023F0310 : 02780000

ipcSyncHandlerLocation 023F0378 : 02780000

resetLocation 023F03A0 : 02780000

globalCardLocation 023F1308 : 02780000

 ce9->patches 023F0034

patchCardNds

swi12 location : 02000704

cardIrqEnable location : 02005298

startOffset : 02000000

cardRead location : 0200F024
023F0000

cardPullOut location : 0200F6DC


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0200F2EC


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0200F2B8

patchMpuSize: 00000000

patchMpuSize: 00000000

Mpu2 init: 0200F9C8

ERR_NONE

forwardedRelocStartAddr
02380158
vAddrOfRelocSrc
02380170
Relocation src: 02380170
Relocation dst: 037F8000

Arm7 (patch v1)
cardReadEndAddr: 0238B9B8
cardstructAddr: 03809460
readCacheEnd: 0238BAD8
JumpTableFunc: 0238BADC
Retry the search
JumpTableFunc: 0238BB74
specificWramAddr: 03802E58
someAddr_799C: 0238B530
Eeprom page erase:	0238BB84
Eeprom verify:	0238BBA0
Eeprom page write:	0238BBBC
Eeprom page prog:	0238BBD8
Eeprom read:	0238BBF4
Card read:	0238BC14
Card id:	0238BC20
Arm7 patched!
swiHalt location : 02380694

swi12 location : 0238BF60

swiGetPitchTable location : 02387028

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FABC

ERR_NONE
hookLocation arm9: 027C0004

ROM loaded into RAM

chipID: 00000FC2`
