### ISSUE TITLE
Final Fantasy III black screen after logo

### ISSUE THREAD

**Issue by lavtz** [DS-Homebrew/nds-bootstrap#1107]
**Your console:** DSI 
**Launch Method:** unlaunch
**Version used:** v19.1.0 and nds-bootstrap v0.38.0
**Game tested/used/applicable:** Final Fantasy III US

**Expected Behavior:** run the intro scene and then go to the main menu
**Actual Behavior:** black screen after the developer logo

### Steps to reproduce
1- fresh update for TWiLight menu++ and nds-bootstrap 
2- launch the game using the latest TWiLight menu++ and nds-bootstrap 

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B78
sdk_version: 03017531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020001BC

cardIrqEnable location : 02047080

startOffset : 02000000

cardRead location : 02036200

cardPullOut location : 02036A04

cardId location : 0203619C

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 02036550

NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 020364B0

patchMpuSize: 00000000

Mpu2 init: 02049AE0

ERR_NONE

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238C0F0
Eeprom read:	0238C0FC
Eeprom page write:	0238C114
Eeprom page prog:	0238C12C
Eeprom verify:	0238C144
Eeprom page erase:	0238C158
swiHalt location : 023806DC

swi12 location : 0238C5D4

swiGetPitchTable location : 02387764

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D8

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00007FC2

**Comment by pa-august** [comment]
I also have this.

**Comment by KururinX** [comment]
Bootstrap ver : 559b60cf
Twilight Menu Ver : a5cc19e6

I confirmed the normal playback of the opening movie.
It doesn't stop (freeze) in the middle, and it doesn't matter how many times you repeat the playback.

**Comment by Kyhze** [comment]
Looks like this issue is happening again. TWLM v20.3.0 & NDS-Bootstrap v0.41.0

**Comment by RocketRobz** [comment]
Turn off `Card read DMA` to fix the issue.

**Comment by Kyhze** [comment]
Awesome thanks! That worked. 
But how can I set this as a game-specific option? I'm pretty sure it's possible but I couldn't find it in the per-game settings menu. I had to disable it globally through TWLM settings, which isn't ideal. Can this be "forced" by editing the configuration file?

**Comment by RocketRobz** [comment]
Scroll down while in the per-game settings menu.

**Comment by Kyhze** [comment]
There are only 3 options available: "Main screen, clock frequency" and "VRAM Boost" :(

**Comment by Kyhze** [comment]
Also side note, I noticed a small typo in my language (French) in the per-game settings menu. In the main section of the menu. I'm guessing the English entry is something like "Dump RAM", in French it's "Enregistrer la RAM" but it is mispelled as "EnreNgistrer". The extra N should be removed.

**Comment by RocketRobz** [comment]
> There are only 3 options available: "Main screen, clock frequency" and "VRAM Boost" :(

I meant in TWLMenu++, not nds-bootstrap's in-game menu.
You open the per-game settings menu by pressing Y.

> Also side note, I noticed a small typo in my language (French) in the per-game settings menu. In the main section of the menu. I'm guessing the English entry is something like "Dump RAM", in French it's "Enregistrer la RAM" but it is mispelled as "EnreNgistrer". The extra N should be removed.
> 
> Should I open a separate issue for this?

That should be easily fixable in Crowdin.

**Comment by Kyhze** [comment]
Oh awesome! I didn't know about this per-game menu in TWLMenu++. It worked perfectly, thanks again!
