### ISSUE TITLE
Medal Rally menu not accesible in Pokémon Black 2

### ISSUE THREAD

**Issue by xmplay** [DS-Homebrew/nds-bootstrap#1108]
**Your console:** New 3DS
**Launch Method:** Luma3DS v10.2.1
**Version used:** release v0.38.0
**Game tested/used/applicable:** Pokémon Black Version 2 (europe)

**Expected Behavior:** The Medal Rally menu in the Trainer Card menu should have opened and displayed your medal count and favourite medal
**Actual Behavior:** The screen turns black, the music keeps playing but gets disorted

### Steps to reproduce

1. Select the Trainer Card menu in the pause menu (your name)
2. Press the circle in the bottom right corner of your trainer's portrait
3. The screen will go black

### Other notes

My nds-bootstrap.ini file:

NDS_PATH = sd:/roms/nds/black2.nds
SAV_PATH = sd:/roms/nds/saves/black2.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 0
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
CONSOLE_MODEL = 2
LANGUAGE = -1
AP_FIX_PATH =

**Comment by hansoljin** [comment]
I can reproduce this issue. It seems as though an AP patch cheat does not fix this.

**Comment by Squall-Leonhart** [comment]
turrn off dma

**Comment by xmplay** [comment]
> turrn off dma

how?

**Comment by NightYoshi370** [comment]
A new TWiLight Menu++ update contains this setting.

**Comment by hansoljin** [comment]
DMA off does not fix the issue.

**Comment by xmplay** [comment]
> A new TWiLight Menu++ update contains this setting.

i'm not using twilight menu, only nds-bootstrap

**Comment by urmum-69** [comment]
Well, you cannot use nds-bootstrap alone, it needs some sort of frontend to write the parameters to the ini file

**Comment by xmplay** [comment]
> Well, you cannot use nds-bootstrap alone, it needs some sort of frontend to write the parameters to the ini file

i'm using nds-bootstrap and a fowarder

**Comment by Squall-Leonhart** [comment]
Medal Rally working for me, though my save only has one medal presently, my dump is hard patched with ndstool though which might make the difference.

If it does not make a difference, then it could be either of the cache files responsible given the many changes in the new version.

**Comment by xmplay** [comment]
> Medal Rally working for me, though my save only has one medal presently, my dump is hard patched with ndstool though which might make the difference.
> 
> If it does not make a difference, then it could be either of the cache files responsible given the many changes in the new version.
> 
> Edit, hard ap patching doesn't make a difference.

Do you have the medal set as favourite in the medal box?

**Comment by Squall-Leonhart** [comment]
> > Medal Rally working for me, though my save only has one medal presently, my dump is hard patched with ndstool though which might make the difference.
> > If it does not make a difference, then it could be either of the cache files responsible given the many changes in the new version.
> > Edit, hard ap patching doesn't make a difference.
> 
> Do you have the medal set as favourite in the medal box?

Yes, 
it may be caused by stale cache data from previous versions of the bootstrapper and menu, erase the subfiles of _nds\nds-bootstrap

**Comment by hansoljin** [comment]
> > > Medal Rally working for me, though my save only has one medal presently, my dump is hard patched with ndstool though which might make the difference.
> > > If it does not make a difference, then it could be either of the cache files responsible given the many changes in the new version.
> > > Edit, hard ap patching doesn't make a difference.
> > 
> > 
> > Do you have the medal set as favourite in the medal box?
> 
> Yes,
> it may be caused by stale cache data from previous versions of the bootstrapper and menu, erase the subfiles of _nds\nds-bootstrap

Still doesn't work on mine. I had this folder wiped just last week, and I did it again for a sanity check.

I can't verify if this is a direct result of failed auto AP-patching, though. I'll check on that soon.

**Comment by xmplay** [comment]
> > > Medal Rally working for me, though my save only has one medal presently, my dump is hard patched with ndstool though which might make the difference.
> > > If it does not make a difference, then it could be either of the cache files responsible given the many changes in the new version.
> > > Edit, hard ap patching doesn't make a difference.
> > 
> > 
> > Do you have the medal set as favourite in the medal box?
> 
> Yes,
> it may be caused by stale cache data from previous versions of the bootstrapper and menu, erase the subfiles of _nds\nds-bootstrap

didn't fix anything

**Comment by Squall-Leonhart** [comment]
have you checked the dump against nds scene tool to be sure its a good valid dump?

you don't have dsi enabled or anything?

**Comment by xmplay** [comment]
> have you checked the dump against nds scene tool to be sure its a good valid dump?
> 
> you don't have dsi enabled or anything?

everything works properly in melodns, i don't have dsi enabled

**Comment by Squall-Leonhart** [comment]
> everything works properly in melonds

That doesn't mean a lot, emulators can have fixes that work around specific dump problems.

alot of the early black 2/white2's had the dsi region stripped.

**Comment by hansoljin** [comment]
> > everything works properly in melonds
> 
> That doesn't mean a lot, emulators can have fixes that work around specific dump problems.
> 
> alot of the early black 2/white2's had the dsi region stripped.

I can assure you my ROM matches the verified No-Intro hashes, and therefore retains all DSi binaries. I have never turned on DSi mode and don't plan on doing so until that gets fixed at all.

Still does not work.

**Comment by Squall-Leonhart** [comment]
Attach your battery file.

**Comment by xmplay** [comment]
i managed to get the menu working on twilight menu with the dsi clock speed

**Comment by hansoljin** [comment]
Did you change the settings from TWiLight Menu++ global settings, or did you change the game individually?

**Comment by xmplay** [comment]
> Did you change the settings from TWiLight Menu++ global settings, or did you change the game individually?

invidually

**Comment by hansoljin** [comment]
Try changing TWiLight global settings to use 133mhz, save by pressing B to exit settings, then re-try from the forwarder.

**Comment by xmplay** [comment]
> Try changing TWiLight global settings to use 133mhz, save by pressing B to exit settings, then re-try from the forwarder.

tried with ntr clock speed and twl clock speed, works on both after installing twilight menu

**Comment by hansoljin** [comment]
I wonder why it works _after_ TWiLight Menu++ install. (and I wonder why mine doesn't work. Possibly my save data being wonky, I'll have to look, but my issue is likely irrelevant.) 
Maybe it was an incomplete nds-bootstrap update then?
