### ISSUE TITLE
Tetris Party Deluxe doesn't save profile, softlocks after exiting game

### ISSUE THREAD

**Issue by SimPiko** [DS-Homebrew/nds-bootstrap#1109]
**Your console:** DSi XL, 1.4.5E
**Launch Method:** Twilight Menu 19.0.0
**Version used:** f31c641, but first noticed on v0.37.0
Last working version: v0.36.0  
**Game tested/used/applicable:** Tetris Party Deluxe (USA) (B4TE), MD5:7da7954fce54b106be48684241fd4bcf

**Expected Behavior:** After creating profile, game should retain all highscores, avatar info etc on next game boot, also exiting tutorial or any gamemode should return player to main menu.
**Actual Behavior:** Game asks for creating new profile every time it is booted, exiting tutorial/gameplay softlocks game at black screen, you can still press L+DOWN+SELECT to access nds-bootstrap's menu.

### Steps to reproduce
Run game, create profile, reload game.
for black screen: run tutorial or any mode, and try exiting game.

nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
ROMREAD_LED = 1
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 0
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/Tetris Party Deluxe (USA).nds
SAV_PATH = sd:/roms/nds/saves/Tetris Party Deluxe (USA).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 1
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/B4TE-8877.ips
HOMEBREW_ARG =
MACRO_MODE = 0
CARD_READ_DMA = 1
```

### Other notes
Video of the issue: https://www.youtube.com/watch?v=56Oic9N3TPQ
While you can still play the game, the profile creation popping every time game is loaded is kinda annoying.

**Comment by SimPiko** [comment]
One more thing, I've tried creating fresh clean .sav file and after loading and restarting multiple times, sav file was still blank, untouched.

**Comment by RocketRobz** [comment]
Please turn on logging, re-launch the game, and after it boots, post `NDSBTSRP.LOG` from `sd:/` here.

**Comment by SimPiko** [comment]
here's the log
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6214436/NDSBTSRP.LOG)

**Comment by SimPiko** [comment]
just tested with v0.40.0 and v0.40.1, seems like it is fixed. Closing.

**Comment by RocketRobz** [comment]
Commit 0d4552c7 has caused this issue again.
