### ISSUE TITLE
Pokemon Diamond/Pearl demo rom boots to white screen

### ISSUE THREAD

**Issue by Mewthree3** [DS-Homebrew/nds-bootstrap#1110]
**Your console:** New 2DS XL
Launch method: Luma3DS v10.2.1-d0a44fd2, TWiLight Menu++
**Version used:** Release (for both NDS bootstrap and TWL Menu)
**Game tested/used/applicable:** Pokemon Diamond/Pearl Demo Version. TID Y23E, SDK v-3

**Expected Behavior:** Game boots as normal
**Actual Behavior:** Game boots to white screen after the NDS-Bootsrap loading screen

### Steps to reproduce

1. Get demo rom (It's easy to find them online)
2. Boot up TWiLight Menu++ on a 3DS console of some sort.
3. Play it.

### Logs

(I can't figure out how to get the log, apologies)

### Other notes
I've used multiple different roms, to try and play this.
Here's the nds-bootstrap.ini file.
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/DS/Pokemon/Pokemon Diamond and Pearl Demo.nds
SAV_PATH = sd:/roms/DS/Pokemon/saves/Pokemon Diamond and Pearl Demo.sav
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_CPU = 1
BOOST_VRAM = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
CACHE_BLOCK_SIZE = 1
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
HOMEBREW_ARG =
MACRO_MODE = 0

**Comment by RocketRobz** [comment]
What version numbers are shown in TWLMenu++ Settings?

**Comment by Mewthree3** [comment]
> What version numbers are shown in TWLMenu++ Settings?

nds-bootstrap Ver. Release v0.36.0, and v18.5.0

**Comment by RocketRobz** [comment]
Update both TWLMenu++ and nds-bootstrap versions then.

**Comment by Mewthree3** [comment]
> Update both TWLMenu++ and nds-bootstrap versions then.

I'll do that. Weird thing is that there wasn't a green dot on the TWL Menu
updater for both the releases, and I know that I had the L-DOWN-SELECT menu
available.
Anyways, it just updated. It still says I'm in 18.5.0 and 0.36.0 despite me
re-updating just now. The issue still is persisting, even if I run it in DS
Mode instead of DSi Mode.

**Comment by RocketRobz** [comment]
Use Universal Updater to update, instead of TWLMenu++ Updater.

**Comment by Mewthree3** [comment]
I did that, thank you for telling me the correct way to update!
Yeah, it still doesn't want to work, however.

**Comment by Squall-Leonhart** [comment]
It might be due to the save support in ndsbootstrap not knowing how to handle nds carts that lack a save type, emulators create a 0KB file for this game where nds-bootstrap creates a 512kb file.

**Comment by Mewthree3** [comment]
> It might be due to the save support in ndsbootstrap not knowing how to handle nds carts that lack a save type, emulators create a 0KB file for this game where nds-bootstrap creates a 512kb file.
> 
> But its more likely the fact this rom stacks boot loaders and chain loads alternating between diamond and pearl each reset.
> [NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6217523/NDSBTSRP.LOG)
 co
So do you think that there's an easy fix for this, or should I give up on playing the demo? lol

**Comment by Squall-Leonhart** [comment]
i think we should wait and see what Robz latest changes bring.

**Comment by Mewthree3** [comment]
I looked in some forums, and downloaded what seemed to be the "kiosk save". I tried it out (it's a 512kb SAV like normal), and it still started into a white screen sadly.

**Comment by Mewthree3** [comment]
The demo works now. Thank you for your hard work!
