### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1111]
Your console: DSI
Version used: v19.1.1 and nds-bootstrap v0.38.0

GG Series Collection plus (JP) ...... In-game menus don't work properly
Kimokawa-E (JP) ...... don't work (White out)
Annie no Atelier (JP) ...... don't work (White out)
Lina no Atelier (JP) ...... don't work (White out)
etrian odyssey (EU) ...... don't work (White out)
devil survivor 1 (JP) ......  in-game menu will appear as only a black screen
FinalFantasy 3 (JP) ...... Unstable operation similar to ”Final Fantasy III black screen after logo (#1107) ”

For the time being, I will use "36.0.0" disguised as "Nightly"

**Comment by hansoljin** [comment]
Please turn on logging, re-launch the game, and after it boots, post `NDSBTSRP.LOG` from `sd:/` here. Do this for each game.

**Comment by KururinX** [comment]
GG Series Collection plus (JP)

findModuleParamsOffset:
Module params offset restored: 02000BA4
sdk_version: 05037535
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

swi12 location : 0200030A

cardIrqEnable location : 02050400

startOffset : 02000000

cardRead location : 02046E90

cardPullOut location : 02047438

cardId location : 02046CF0


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0204704C


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 020470DC

findMpuInitCacheOffset:
Mpu init cache not found

patchMpuSize: 00000000

Mpu init: 02052160

reset location : 02052F78

ERR_NONE

Relocation src: 023802E4

Arm7 (patch v5)
JumpTableFunc: 0238ECA8
card read:	0238EC90
Eeprom read:	0238ECB4
Eeprom page write:	0238ECCC
Eeprom page prog:	0238ECE4
Eeprom verify:	0238ECFC
Eeprom page erase:	0238ED10
swiHalt location : 02380664

swi12 location : 02383600

swiGetPitchTable location : 02383614

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FDBC

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80003FC2

**Comment by KururinX** [comment]
Kimokawa-E (JP)

findModuleParamsOffset:
Module params offset restored: 02000BB8
sdk_version: 04027531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200046C

cardIrqEnable location : 0200366C

startOffset : 02000000

cardRead location : 0200CC50

cardPullOut location : 0200D1AC

cardId location : 0200CD40


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0200C9A0


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0200CA3C

patchMpuSize: 00000000

Mpu2 init: 02004E70

ERR_NONE

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swiHalt location : 02380660

swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F584

ERR_NONE
hookLocation arm9: 027E0000

chipID: 8000FFC2

**Comment by KururinX** [comment]
Annie no Atelier (JP)

findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020006A8

cardIrqEnable location : 020062A0

startOffset : 02000000

cardRead location : 0200ED84

cardPullOut location : 0200F2E0

cardId location : 0200EE74


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0200EAD4


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0200EB70

patchMpuSize: 00000000

Mpu2 init: 02007B4C

reset location : 020084BC

ERR_NONE

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swiHalt location : 02380660

swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F584

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80007FC2

**Comment by KururinX** [comment]
Lina no Atelier (JP)

findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027539
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200073C

cardIrqEnable location : 0200495C

startOffset : 02000000

cardRead location : 0200E4C0

cardPullOut location : 0200EA1C

cardId location : 0200E5B0


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0200E210


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0200E2AC

patchMpuSize: 00000000

Mpu2 init: 02006250

reset location : 02006BC0

ERR_NONE

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5F0
Eeprom read:	0238B5FC
Eeprom page write:	0238B610
Eeprom page prog:	0238B624
Eeprom verify:	0238B638
Eeprom page erase:	0238B648
swiHalt location : 02380694

swi12 location : 0238BA30

swiGetPitchTable location : 02386FE8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F780

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80007FC2

**Comment by KururinX** [comment]
Etrian Odyssey (EU)

findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 02000404

cardIrqEnable location : 0200473C

startOffset : 02000000

cardRead location : 0200D2A4

cardPullOut location : 0200D800

cardId location : 0200D394


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0200CFF4


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0200D090

patchMpuSize: 00000000

Mpu2 init: 020061F0

reset location : 02006760

ERR_NONE

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swiHalt location : 02380660

swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F584

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80001FC2

**Comment by KururinX** [comment]
Devil Survivor 1 (JP)

findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200066E

cardIrqEnable location : 02003014

startOffset : 02000000

cardRead location : 0200CA4C

cardPullOut location : 0200CFA8

cardId location : 0200CB3C


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0200C79C


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0200C838

patchMpuSize: 00000000

Mpu2 init: 020049B4

reset location : 02004F64

ERR_NONE

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
swiHalt location : 02380660

swi12 location : 0238B9FC

swiGetPitchTable location : 02386FB4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F584

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80003FC2

**Comment by KururinX** [comment]
Final Fantasy 3 (JP)

findModuleParamsOffset:
Module params offset restored: 02000B78
sdk_version: 03017531
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 02000084

cardIrqEnable location : 02046E5C

startOffset : 02000000

cardRead location : 02035FDC

cardPullOut location : 020367E0

cardId location : 02035F78


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0203632C


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0203628C

patchMpuSize: 00000000

Mpu2 init: 020498BC

ERR_NONE

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238C0F0
Eeprom read:	0238C0FC
Eeprom page write:	0238C114
Eeprom page prog:	0238C12C
Eeprom verify:	0238C144
Eeprom page erase:	0238C158
swiHalt location : 023806DC

swi12 location : 0238C5D4

swiGetPitchTable location : 02387764

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D8

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00007FC2

**Comment by KururinX** [comment]
SaGa3 -Shadow or Light- (JP)

findModuleParamsOffset:
Module params offset restored: 02000BA4
sdk_version: 05057530
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

swi12 location : 02000718

cardIrqEnable location : 020128A4

startOffset : 02000000

cardRead location : 0201B7E4

cardPullOut location : 0201BC08

cardId location : 0201B6D0


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDmaOffset location : 0201B920


NDMA CARD READ METHOD ACTIVE
cardEndReadDmaOffset location : 0201B984

findMpuInitCacheOffset:
Mpu init cache not found

patchMpuSize: 00000000

Mpu init: 02013B90

reset location : 0201452C

ERR_NONE

Relocation src: 02380394

Arm7 (patch v5)
JumpTableFunc: 0238F6E8
card read:	0238F6D0
Eeprom read:	0238F6F4
Eeprom page write:	0238F70C
Eeprom page prog:	0238F724
Eeprom verify:	0238F73C
Eeprom page erase:	0238F750
swiHalt location : 02380714

swi12 location : 023836E0

swiGetPitchTable location : 023836F4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02391698

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80007FC2

**Comment by KururinX** [comment]
nightly build:272891c0

GG Series Collection plus (JP) ...... OK
Kimokawa-E (JP) ...... OK
Annie no Atelier (JP) ...... OK
Lina no Atelier (JP) ...... OK

**Comment by KururinX** [comment]
etrian odyssey (EU) ...... OK　(checked ver.122209bf)
 Set the language, it worked fine accordingly.
 This was my mistake.


FinalFantasy 3 (JP) ...... Opening movie does not play (blackout)

findModuleParamsOffset:
Module params offset restored: 02000B78
sdk_version: 03017531
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 02000084

cardIrqEnable location : 02046E5C

startOffset : 02000000

cardRead location : 02035FDC
023F0000

cardPullOut location : 020367E0

cardId location : 02035F78


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0203632C


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0203628C

patchMpuSize: 00000000

patchMpuSize: 00000000

Mpu2 init: 020498BC

ERR_NONE

cardIrqEnable location : 02383DFC

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238C0F0
Eeprom read:	0238C0FC
Eeprom page write:	0238C114
Eeprom page prog:	0238C12C
Eeprom verify:	0238C144
Eeprom page erase:	0238C158
swiHalt location : 023806DC

swi12 location : 0238C5D4

swiGetPitchTable location : 02387764

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D8

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00007FC2

**Comment by hansoljin** [comment]
Looks like FF3's other issue, #1107 is still open. I'd suggest your bug reports for that game continues there.

**Comment by RocketRobz** [comment]
Some of those issues should already be fixed by later nds-bootstrap versions, so I'll close this.
