### ISSUE TITLE
Mario vs. Donkey Kong: Mini-Land Mayhem! sprites invisible

### ISSUE THREAD

**Issue by songokuemumania** [DS-Homebrew/nds-bootstrap#1112]
**Your console: new 3DS XL** 
**Launch Method:luma 10.2.1** 
**Version used: bootstrap 0.38.0** 

**Game tested/used/applicable:Mario vs. Donkey Kong: Mini-Land Mayhem! USA rom** 

**Expected Behavior: mario should show up on scren** 
**Actual Behavior: mario is there but invisible**

**Comment by RocketRobz** [comment]
Duplicate of #467
