### ISSUE TITLE
MKDS (Korean region) black/white screen on boot

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/nds-bootstrap#1114]
**Your console:** O3DSXL
**Launch Method:** Luma3DS 10.2.1
**Version used:** f31c641
**Flashcart used:** R4 Ultra with SCFG access
**Game tested/used/applicable:** 0990 AMCK Mario Kart DS Korea. Verified dump on No-Intro.

**Expected Behavior:** Game loads.
**Actual Behavior:** black screen top, white screen bottom

### Steps to reproduce

[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 1
NDS_PATH = fat:/ROMs/NDS/0990 - Mario Kart DS (Korea).nds
SAV_PATH = fat:/ROMs/NDS/saves/0990 - Mario Kart DS (Korea).sav1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 1
EXTENDED_MEMORY = 1
CACHE_BLOCK_SIZE = 1
CACHE_FAT_TABLE = 0
MACRO_MODE = 0
CARD_READ_DMA = 0

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6220832/NDSBTSRP.LOG)

### Other notes

I tested EUR MKDS (also No-Intro verified dump), and this works.

**Comment by hansoljin** [comment]
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6220913/NDSBTSRP.LOG)

Booted it from console SD this time.
So it boots from console SD card, but it does not boot when loading from R4 Ultra (accessed from console-side TWiLight Menu++.) I've seen this sort of thing happen with other games, notably PMD EoS lags when loaded in Slot-1 SCFG, but I've never seen it straight up black screen like this game.

**Comment by lifehackerhansol** [comment]
Appears to be fixed as of v0.52.0.
