### ISSUE TITLE
Pokemon Black2 game freeze

### ISSUE THREAD

**Issue by kangsimin** [DS-Homebrew/nds-bootstrap#1115]
**Your console:** dsi
**Launch Method:** twilight menu ++ v18.5.0  
**Version used:**  nds-bootstrap release v0.38.0
**Game tested/used/applicable:** Pokemon black2 (korea) IREK
**Expected Behavior:**  Bianca catch pokemon sucessfully.
**Actual Behavior:**  game stopped when Bianca tried to catch pokemon.

### Steps to reproduce

[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
NDS_PATH = sd:/game/포켓몬스터 블랙2(K).nds
SAV_PATH = sd:/game/saves/포켓몬스터 블랙2(K).sav
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/IREK-8ED6.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
MACRO_MODE = 0

### Logs

findModuleParamsOffset:
Module params offset restored: 02004FCC
sdk_version: 0503757C
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

swi12 location : 02004626

dsiModeCheck location : 02004EB4

cardIrqEnable location : 0207A55C

startOffset : 02004000

cardRead location : 020701A0

cardPullOut location : 020705E8

cardId location : 02070080

cardReadDma location : 0207020C

patchMpuSize: 00000000

Mpu init: 0207BED8

reset location : 0207C988

ERR_NONE

Relocation src: 02380644

Arm7 (patch v5)
JumpTableFunc: 0238FB14
card read:	0238FAFC
Eeprom read:	0238FB20
Eeprom page write:	0238FB38
Eeprom page prog:	0238FB50
Eeprom verify:	0238FB68
Eeprom page erase:	0238FB7C
swiHalt location : 023807A4

swi12 location : 02383BA4

swiGetPitchTable location : 02383BB8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02391918

ERR_NONE
hookLocation arm9: 02FE0020

AP-fix found and applied
chipID: C001FEC2
                            
debug: true
ndsPath: "sd:/game/포켓몬스터 블랙2(K).nds"
savPath: "sd:/game/saves/포켓몬스터 블랙2(K).sav"
gbaPath: ""
donorE2Path: ""
donor2Path: ""
donor3Path: ""
donorPath: ""
donorTwlPath: ""
saveSize: 80000
language: FF
dsiMode: 0
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
extendedMemory: false
consoleModel: 0
colorMode: 0
romRead_LED: 0
dmaRomRead_LED: FF
cardReadDMA: false
boostCpu: false
boostVram: false
soundFreq: false
forceSleepPatch: false
logging: true
initDisc: false
gameOnFlashcard: false
saveOnFlashcard: false
macroMode: false

### Other notes
https://youtu.be/PeelJKs2Gws

**Comment by Squall-Leonhart** [comment]
this game requires DMA if im not mistaken.
