### ISSUE TITLE
Final Fantasy Tactics A2 - White screen on boot

### ISSUE THREAD

**Issue by Setador** [DS-Homebrew/nds-bootstrap#1116]
**Your console:** New 3DS XL
**Launch Method:** Luma3DS v10.2.1-d0a44fd2, TWiLight Menu++
**Version used:**  TWiLight Menu++ v19.1.0, NDS bootstrap v0.38.0
**Game tested/used/applicable:** Final Fantasy Tactics A2: Grimoire of the Rift, A6FE, SDK v-4

**Expected Behavior:** Game boots as normal
**Actual Behavior:** Game boots to white screen after the NDS-Bootsrap loading screen

### Steps to reproduce

   1.-  Get demo rom (It's easy to find them online)
    2.- Boot up TWiLight Menu++ on a 3DS console of some sort.
    3.- Play it.

### Logs

(I can't figure out how to get the log, apologies)

### Other notes

I've used multiple different roms, to try and play this.
Here's the nds-bootstrap.ini file.
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/Final Fantasy Tactics A2 - Grimoire of the Rift (USA) (En,Fr,Es).nds
SAV_PATH = sd:/roms/nds/saves/Final Fantasy Tactics A2 - Grimoire of the Rift (USA) (En,Fr,Es).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
AP_FIX_PATH =

**Comment by RocketRobz** [comment]
Turn on TWL clock speed for that game.

**Comment by Setador** [comment]
It works now, thank you :)

**Comment by Peter0x44** [comment]
I guess this issue should be closed now then?
