### ISSUE TITLE
At least 2 games not starting

### ISSUE THREAD

**Issue by beertmpb8** [DS-Homebrew/nds-bootstrap#1117]
**Your console:** DSi
**Launch Method:** Twilight Menu++
**Version used:** nds-bootstrap: 0.38.0; Twilight Menu++: 19.1.1
**Game tested/used/applicable:** Yoshi Touch and Go (ID: AYIP) and Spore Creatures (ID: YSPP)

**Expected Behavior:** Launch the game from Twilight Menu and game works.
**Actual Behavior:** Launch the game from Twilight Menu but Yoshi Touch and Go gets stuck in a white screen while Spore Creatures does the same but in a black one.

### Steps to reproduce
0. Launch the game

### Other notes
I tested replacing the nds-bootstrap 0.38.0 version with the previous one (0.37.0) and both games boot perfectly in that version.
No cheats activated in any of the games btw.

![Spore](https://user-images.githubusercontent.com/81693339/113151390-50b6a080-9235-11eb-8596-42f1cc64815f.jpg)
![Yoshi](https://user-images.githubusercontent.com/81693339/113151397-51e7cd80-9235-11eb-9cf3-6494db71622c.jpg)

Thanks a lot in advance for your great work <3

**Comment by hansoljin** [comment]
Yoshi Touch & Go is working on my end. I have no idea why it is not working for you. Both NTR and TWL speed is working.

**Comment by beertmpb8** [comment]
> Yoshi Touch & Go is working on my end. I have no idea why it is not working for you. Both NTR and TWL speed is working. Tried all sorts of settings and it still boots.

Sorry for taking this long to respond, my private life have been a mess since i created this thread.
I just checked again and Yoshi seems to works, I have no idea why it failed before. Spore still doesnt work.

Im gonna install the new release of nds-bootstrap and try again both games.

**Comment by beertmpb8** [comment]
Great, both games works now with nds-bootstrap v0.39.0 (D⁽ⁱ⁾rectors' Cut), Spore looks like it didnt like v0.38.0 of nds-bootstrap cause it worked perfectly with the 0.37.0 version and earlier ones. Anyway both are working now and I read the DSi mode is finally working, cant wait to try it out, thanks a lot to all of you who contribute to make this project better <3.
