### ISSUE TITLE
Glitched graphics in Drawn to Life

### ISSUE THREAD

**Issue by Zyanbob** [DS-Homebrew/nds-bootstrap#1119]
**new 3ds xl with boot9strap:**  
**TWiLight Menu++ Version:lastest 
**TWiLight Menu++ Theme:3ds 

### Expected behaviour

the game plays as normal

### Actual behaviour

screen goes dark for the collection and the everything is buggy expect the npcs for the 1st game.

### Steps to reproduce

1.put game rom in nds file.
2.start game in twilight menu.
3. the glitch happens.

**Comment by RocketRobz** [comment]
The latest nds-bootstrap has some bugs related to card read DMA.
Update nds-bootstrap to the latest nightly build, or turn off card read DMA for that game.

**Comment by Zyanbob** [comment]
![IMG_1316 1](https://user-images.githubusercontent.com/81934264/113524133-ff6d2f00-95ef-11eb-9752-35f793c43705.JPG)
i just download the last nightly build for nds-bootstrap (it didn't work).

**Comment by RocketRobz** [comment]
Did you switch `Bootstrap` to `Nightly` in the per-game settings?

**Comment by Zyanbob** [comment]
what setting?

**Comment by RocketRobz** [comment]
The one called `Bootstrap`.
In TWLMenu++ Settings, it's in the Games/Apps page. In the per-game settings, you just scroll down to the setting.

**Comment by Zyanbob** [comment]
the setting in the updater or are their secert settings in the menu itself?

**Comment by RocketRobz** [comment]
TWLMenu++ has a settings menu that you can open, by pressing SELECT, then touching the small DS icon.
To open the per-game settings menu, just press Y with the game highlighted.

**Comment by Zyanbob** [comment]
![IMG_1317 1](https://user-images.githubusercontent.com/81934264/113524669-95ef1f80-95f3-11eb-8d51-24064b922ea6.JPG)
its even worse now

**Comment by Zyanbob** [comment]
can't even see mari's face anymore

**Comment by RocketRobz** [comment]
Turn off the `card read DMA` setting then.

**Comment by Zyanbob** [comment]
same as before

**Comment by RocketRobz** [comment]
Then either try the Drawn to Life Collection instead, or wait for a fix.

**Comment by Zyanbob** [comment]
ok

**Comment by Zyanbob** [comment]
you should ask the creator of nds-bootstrap to fix this

**Comment by RocketRobz** [comment]
@ahezard hasn't been around for like a year, so it's going to be a long while.

**Comment by RocketRobz** [comment]
Just tried the game on my side in the Collection ROM, and looks fine for me.
Make sure you're using Universal Updater instead of TWLMenu++ Updater, as that's discontinued.

Closing, as the bug doesn't occur for me. If someone else has this issue, I'll re-open it.
