### ISSUE TITLE
Black screen on drawn to life collection

### ISSUE THREAD

**Issue by Zyanbob** [DS-Homebrew/nds-bootstrap#1120]
**Your console:**  new 3ds xl
**Launch Method:** lastest
**Version used:**  lastest nightly
**Game tested/used/applicable:** drawn to life  collection 
**Expected Behavior:**  menu start as normal

**Actual Behavior:** black screen
### Steps to reproduce
download rom from (link deleted)
put rom in rom file

### Other notes
![IMG_1322 1](https://user-images.githubusercontent.com/81934264/113526505-a7d5c000-95fd-11eb-9b15-5448d13a07cb.JPG)

**Comment by RocketRobz** [comment]
1. Please don't post links to ROM sites.
2. Try reinstalling both TWLMenu++ and nds-bootstrap. Install them again with either the manual method or by using Universal Updater.

Closing, as this cannot be reproduced.
For futher assistance, please join the Discord server [here](https://discord.gg/yD3spjv).

**Comment by Zyanbob** [comment]
the rom itself is fine, i can play other games on twilight menu but not drawn to life for some reason

**Comment by RocketRobz** [comment]
If you already reinstalled TWLMenu++, use Universal Updater to update to the latest nds-bootstrap nightly (which is bb82828c), and then re-set `Bootstrap` to `Nightly`.
If this doesn't fix your issue, let's move this over to the Discord server, please.
