### ISSUE TITLE
In-game menu options crash

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1122]
**Your console:** DSi
**Launch Method:** Unlaunch 1.8; TWiLight Menu++ 19.0.0
**Version used:** 0.38.0-ee792125
**Game tested/used/applicable:** Mario Kart DS (AMCE01_0), probably happens on any game

**Expected Behavior:** Either the screens would swap, or not.
**Actual Behavior:** System crashes immediately or shortly after.

### Steps to reproduce

Start the game, open the in-game menu, go to Options, and press left or right on the Main Screen option about 10-20 times. After about 9 times, the wrong text will begin to display and the game will probably crash eventually if you return to it after that. After about 18 times, the system will crash right in the in-game menu.
[NDS-BOOTSTRAP]
NDS_PATH = sd:/gm9i/out/MARIOKARTDS_AMCE01_0.nds
SAV_PATH = sd:/gm9i/out/saves/MARIOKARTDS_AMCE01_0.sav
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 3
BOOST_CPU = 0
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
LANGUAGE = -1
DSI_MODE = 0
BOOST_VRAM = 0
SOUND_FIX = 1
GAME_SOFT_RESET = 1
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
RAM_DRIVE_PATH = sd:/null.img
EXTENDED_MEMORY = 1
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 1
CARDENGINE_CACHED = 1

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B68
sdk_version: 030028A0
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020001B8

cardIrqEnable location : 0200CAE4

startOffset : 02000000

cardRead location : 021463A4

cardPullOut location : 02146B14

cardReadDma location : 021464A4

patchMpuSize: 00000000

Mpu2 init: 0200F364

ERR_NONE

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238028C
Relocation dst: 037F8000

Arm7 (patch v2)
cardReadEndAddr: 02388D68
cardstructAddr: 038090C0
readCacheEnd: 02388EA4
JumpTableFunc: 02388EA8
returned_A0_with_MKDS: 02388F48
addrOfSomething_85C0: 0238884C
anotherLocinA7WRAM: 038096E4
amal_8CBC: 02388F48
aFinalLocation: FE388F2C
Eeprom protect:	02388F88
Card id:	02388F90
Card read:	02388FB0
Eeprom read:	02388FC8
Eeprom page write:	02388FE0
Eeprom page prog:	02388FF8
Eeprom verify:	02389010
Eeprom page erase:	02389020
swiHalt location : 023807B4

swi12 location : 0238948C

swiGetPitchTable location : 02384448

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F7C0

ERR_NONE
hookLocation arm9: 027E0008

chipID: 00001FC2

[Huge empty space here]

debug: true
ndsPath: "sd:/gm9i/out/MARIOKARTDS_AMCE01_0.nds"
savPath: "sd:/gm9i/out/saves/MARIOKARTDS_AMCE01_0.sav"
gbaPath: ""
donorE2Path: ""
donor2Path: ""
donor3Path: ""
donorPath: ""
donorTwlPath: ""
saveSize: 40000
language: FF
dsiMode: 0
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
extendedMemory: true
consoleModel: 0
colorMode: 0
romRead_LED: 3
dmaRomRead_LED: FF
cardReadDMA: false
boostCpu: false
boostVram: false
soundFreq: true
forceSleepPatch: false
logging: true
initDisc: false
gameOnFlashcard: false
saveOnFlashcard: false
macroMode: false

### Other notes
Does not occur on 0.37.0

**Comment by spellboundtriangle** [comment]
Update: Still occurs with TWiLight Menu 1.9.1.1 and nds-bootstrap 272891c0 (latest as of writing this)

**Comment by Epicpkmn11** [comment]
Can you test on the latest? I believe this should be fixed, I think the problem was that it would go negative because this was checking the pointer, not the value, which has been fixed

https://github.com/DS-Homebrew/nds-bootstrap/blob/272891c0d84c580e0cea6a924ce79be59145e100/retail/cardenginei/arm9_igm/source/inGameMenu.c#L202

**Comment by spellboundtriangle** [comment]
Yep, seems to be fixed! Thank you! And, sorry about the wait.
