### ISSUE TITLE
Digimon Story - Lost Evolution (JP) Freeze

### ISSUE THREAD

**Issue by romnair** [DS-Homebrew/nds-bootstrap#1123]
**Your console:** Old 3ds
**Launch Method:** SD Card, with TWiLight Menu++: v19.1.1
nds-bootstrap: Release v0.38.0

RocketRobz, ahezard

**Version used:**  release v19.1.1 from TWiLightMenu-3DS.7z on this page https://github.com/DS-Homebrew/TWiLightMenu/releases my hash for the archive : 

MD5 :
- 5f 1b 30 0d 04 29 97 14 04 b5 a4 8c 78 20 b6 fb

SHA256 :
- e8 a8 9d 13 df 08 72 07 ea fa a6 00 05 8b d6 ce 
  34 17 1d 03 da 5d 41 df f2 e3 b1 bd f9 b0 3e 6c

**Game tested/used/applicable:** from DS-Scene Romtool : 
Game Title : BLEJ_DS3_BEC
Game Serial : NTR-BLEJ-JPN
Card/File size : 512Mb (67108864 bytes)
CRC32 : 83878137

From NDSHeader :
Internal name : BLEJ_DS3_BEC
Serial code : NTR-BLEJ-JPN
File CRC32 : 83878137
Card/File size : 512Mb (67108864 bytes)

MD5 :
- d9 94 ff 42 e8 08 27 fd 45 46 bb 64 ff d8 d2 ea

SHA256 :
- 6f 74 95 8b ce 94 f9 ac df fd 75 f0 ef a1 f8 5e
  7d 07 66 4d 8a c7 d6 c9 26 a5 56 b1 79 39 af 37

**Expected Behavior:** Not freezing xD, at least not 100% time
**Actual Behavior:** Freeze 100%

### Steps to reproduce

Start the game play until you get 3 other digimon(really early) from renamon, take all 3 in your party
go in a area with random encouter(folow the story) will freeze.

nds-bootstrap.ini :

`[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/5054 Digimon Story - Lost Evolution (JP).nds
SAV_PATH = sd:/roms/nds/saves/5054 Digimon Story - Lost Evolution (JP).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/BLEJ-D745.ips
CARD_READ_DMA = 1`

### Other notes 

The game freeze but not the music, my 3ds is unaffected(i mean i can get back to home) my 3ds is not freeze only the game.

### UPDATE

In order to make several test, i had made a save right before choosing my farm.
Now when i play from this save, the freeze seems to disapear(had not play enough to confirm it i will play more et bring the result in later day)
[Log when i had play from my save](https://github.com/DS-Homebrew/nds-bootstrap/files/6319887/NDSBTSRP.LOG)

I tried the game from a new game and... it didn't freeze, only 1 thing had change, log system, as soon as i put the log system on the game stopped freezzing, i don't understand, i will try to play more to see if it's occured again, crazy before i used the log system freeze encounter was 100% now vanish...
[Log when i had play from a new game](https://github.com/DS-Homebrew/nds-bootstrap/files/6320042/NDSBTSRP.LOG)

Had turn the log system off, i was able to play a better amount of time than before but the freeze comeback as soon as i let the game run some minute without input, had try with the log system on this time the game stay freezeless a much bigger time but it did freeze(i stay like 1hr and it did freeze).

**Comment by Kaisaan** [comment]
Does this still happen on the latest version of TWiLight Menu++ and nds-bootstrap?
