### ISSUE TITLE
Feel The Magic XY/XX

### ISSUE THREAD

**Issue by randysan18** [DS-Homebrew/nds-bootstrap#1124]
Hello,

I updated twilight menu on my dsi xl to v19.1.1 a few days ago.
It worked perfectly up to that point, I only updated for the sake of updating.

Everything seems fine other than the subject line rom (on sd card) no longer boots....it worked fine before the update.

Both screens go white immediately after opening rom, then i get the "please wait" message from nds bootstrap, and then the top screen goes dark, while the bottom remains white.

Any help is appreciated!

ps, i tried deleting the rom and re-installing to no avail

pss, i reverted back to version 19.0.0 and that game now works as it should, with the curious exception that the game now runs in Japanese!??  I set the game to English and it seems to run fine.

**Comment by RocketRobz** [comment]
See if the latest nds-bootstrap nightly fixes it. Download it [here](https://github.com/TWLBot/Builds/commit/56d39b25b8f93aea0c4735f531a7923ab45c1c85).
After doing so, press Y in TWLMenu++ to open the settings for that game, and change `Bootstrap` to `Nightly`.

**Comment by randysan18** [comment]
thank you, i made the changes as you suggested but the result was the same:
top screen frozen dark/bottom screen frozen white.

**Comment by RocketRobz** [comment]
Try turning off `Card read DMA` then.

**Comment by randysan18** [comment]
thank you, that did the trick!!

....unfortunately Yoshi's Touch & Go still does not boot....I get the double frozen white screens (tried both the nightly bootstrap update as well as turning off card read dma.

**Comment by RocketRobz** [comment]
Turn on the `Extend ROM space in RAM` setting for that game, which fixes it for me.
