### ISSUE TITLE
Can't load save file - FF: The 4 Heroes of Light

### ISSUE THREAD

**Issue by Drakyem** [DS-Homebrew/nds-bootstrap#1125]
**Your console:** New 3DS XL
**Launch Method:** SD Card
**Version used:** Release, 19.1.1
**Game tested/used/applicable:** Final Fantasy: The 4 Heroes of Light (EUR) CRC32: BBC02A91 ---> which changed to 46527C2C after applying a xdelta Spanish translation patch. (I didn't AP-Patched it beforehand)

**Expected Behavior:** The game should've run with no problems.
**Actual Behavior:** When you save your game and try to continue playing (after rebooting it), the game says something like "Save data could not be loaded. Please restart and try again."

### Steps to reproduce

1.- Start new game
2.- Get out of your home, then to the left and talk to the guy next to a fox to save the game
3.- Try to load and continue playing
4.- Get and error message

nds-bootstrap.ini screenshot:
![nds-bootstrap-ini-screenshot](https://user-images.githubusercontent.com/57108266/114944188-6fc54d00-9e47-11eb-818e-a484ab445f4f.png)

### Logs

(Sorry, I don't know how to enable this)

### Other notes
I tried applying first an AP-Patch, but the CRC32 changes and the translation patch doesn't work anymore. But then, if I try to apply the AP-Patch after applying the .xdelta one, the AP-Patcher doesn't recognise the ROM because its CRC32 has changed.

**Comment by RocketRobz** [comment]
To enable logging, open TWLMenu++ Settings, switch to the Games/Apps page, and scroll down to the `Logging` setting to enable it.
After doing so, re-launch the game 'til you encounter the issue again.
After encountering the issue, upload `NDSBTSRP.LOG` from the SD root.

Before doing all this though, please update both TWLMenu++ and nds-bootstrap.

**Comment by RocketRobz** [comment]
Closing, due to no response, and no recent reports of this issue.
