### ISSUE TITLE
Taiko no Tatsujin DS: Touch de Dokodon and Meccha! Taiko no Tatsujin DS have strange screen flashes on startup

### ISSUE THREAD

**Issue by takoyaki99** [DS-Homebrew/nds-bootstrap#1128]
**Your console:** N2DS XL
**Launch Method:** Via microSD card, 32GB Sandisk Ultra, TWiLight Menu++ v20.0.1
**Version used:** nds-bootstrap v.0.39.0
**Game tested/used/applicable:** Taiko no Tatsujin DS: Touch de Dokodon (NTSC-J-YKTJ) (CRC32: e21fd652 MD5: 1019506751710229da06d606d8b23b44 SHA-1: dcf0139a74848265ceaaee0eb6b7a1fc587426e7), Meccha! Taiko no Tatsujin DS: 7-tsu no Shima no Daibouken (NTSC-J-YWVJ) (CRC32: 40675442 MD5: 37b5a56721f5cfbc0caf6225b39c22be SHA-1: 991bf6042ec2dcdbb9436d179c454ff72c14a28e)

**Expected Behavior:** Games boot as normal without screen flashing or obstruction to screen
**Actual Behavior:** Screen seems to flash up/down, other strange obstructions, etc

### Steps to reproduce

1. Get Taiko no Tatsujin 1 and 2 DS roms (they're easy to find even though they're Japanese games)
2. Boot games.
3. Notice that the screen seems to be "flashing"
Here's the nds-bootstrap.ini file.
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/DS/Taiko no Tatsujin/Taiko no Tatsujin DS - Touch de Dokodon! (J)(Independent).nds
SAV_PATH = sd:/roms/DS/Taiko no Tatsujin/saves/Taiko no Tatsujin DS - Touch de Dokodon! (J)(Independent).sav
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 1
DSI_MODE = 1
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
CONSOLE_MODEL = 2
LANGUAGE = 1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
CARD_READ_DMA = 0
EXTENDED_MEMORY = 1
FORCE_SLEEP_PATCH = 0
REGION = -2
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 1

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B80
sdk_version: 03027532
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200025C

cardIrqEnable location : 0206DD50

startOffset : 02000000

cardRead location : 02077A18
023F0000

cardPullOut location : 02078258

cardId location : 020779B0

cardReadDma location : 02077B18

patchMpuSize: 00000000

patchMpuSize: 00000000

Mpu2 init: 0206F7B0

ERR_NONE

cardIrqEnable location : 02383EDC

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238C200
Eeprom read:	0238C20C
Eeprom page write:	0238C224
Eeprom page prog:	0238C23C
Eeprom verify:	0238C254
Eeprom page erase:	0238C268
swiHalt location : 023806DC

swi12 location : 0238C6F4

swiGetPitchTable location : 02387864

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02390440

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00001FC2

### Other notes
As for the Taiko no Tatsujin DS 3 - Dororon Yokai Daikessen rom, there's an anti-piracy cheat that showed up for it on the "Cheats" menu. I enabled it, and the game worked fine. However, I still suspect that this could be the bootstrap's doing because at times the L+DOWN+SELECT menu doesn't show up all the way.

**Comment by AbnormalPoof** [comment]
Try setting the clock speed to 67 NTR instead of 133 TWL

**Comment by Mewthree3** [comment]
Works perfectly now! I think that something in the new updates for ndsbstrap fixed it—or I somehow forgot to try this. Either way, I appreciate this fix!
Thank you!

**Comment by Mewthree3** [comment]
﻿
Works perfectly now! I think that something in the new updates for ndsbstrap fixed it—or I somehow forgot to try this. Either way, I appreciate this fix!
Thank you!
