### ISSUE TITLE
New Super Mario Bros. (JP) not start

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1129]
**Your console:** DSi LL
**Launch Method:** SD CARD
**Version used:** 0.39.0 , 0.39.0-4134d9ae
**Game tested/used/applicable:** New Super Mario Bros. (JP)

**Expected Behavior:** no freeze
**Actual Behavior:** white screen freeze after running from twilight menu

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B64
sdk_version: 03007532
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 0200064E

cardIrqEnable location : 02042C08

startOffset : 02000000

cardRead location : 02076978
023F0000

cardPullOut location : 02077178

cardId location : 02076914

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02076CB4

patchMpuSize: 00000000

patchMpuSize: 00000000

Mpu init: 0206DFEC

Mpu2 init: 0206DFF4

reset location : 0206E444

ERR_NONE

cardIrqEnable location : 02383DFC

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238BFC8
Eeprom read:	0238BFD4
Eeprom page write:	0238BFEC
Eeprom page prog:	0238C004
Eeprom verify:	0238C01C
Eeprom page erase:	00000008
swiHalt location : 023806DC

swi12 location : 0238C4A0

swiGetPitchTable location : 02387750

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D4

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00001FC2

**Comment by RocketRobz** [comment]
Have you tried other regions of the ROM?

**Comment by KururinX** [comment]
Setting
It didn't boot when I changed(VRAM, DMA) , but it booted when I changed bootstrap to a previous one (0.38.0 or 0.36.0)

**Comment by KururinX** [comment]
Unfortunately, we don't currently have an environment where you can try other regions.

**Comment by KururinX** [comment]
thanks a lot.
