### ISSUE TITLE
Syobon Action game problem

### ISSUE THREAD

**Issue by joelb-2011** [DS-Homebrew/nds-bootstrap#1130]
**Your console:** Nintendo DSi
**Launch Method:** TWiLight Menu++ 20.0.1 (SD Card)
**Version used:** Release 0.39.0
**Game tested/used/applicable:** Syobon Action

**Expected Behavior:** The game should run in nds-bootstrap and not in Unlaunch.
**Actual Behavior:** Before installing Unlaunch, I would play Syobon Action normally until the game no longer runs, and then when I install Unlaunch the game runs again but with Unlaunch. Which it shouldn't if it worked fine in nds-bootstrap.

### Steps to reproduce

1. Start the game.

2. The game brings me back to the Twilight Menu.

3. I install Unlaunch. 

4. The game runs but with Unlaunch, as if it were a DSiWare game.

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
ROMREAD_LED = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 0
CACHE_BLOCK_SIZE = 0
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
LANGUAGE = -1
DSI_MODE = 1
NDS_PATH = sd:/Juegos Homebrew/SyobonActionDS RC1.nds
HOMEBREW_ARG = sd:/Game Boy Advance/Mega Man Battle Network (2001).gba
BOOST_CPU = 1
BOOST_VRAM = 1
SAV_PATH = sd:/Juegos Homebrew/SyobonActionDS RC1.pub
RAM_DRIVE_PATH =
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
CARD_READ_DMA = 1
PRV_PATH = sd:/Juegos Homebrew/SyobonActionDS RC1.prv
REGION = -2
GAME_SOFT_RESET = 1

**Comment by RocketRobz** [comment]
DSiWare detection has been reworked in later TWLMenu++ versions, so closing.
