### ISSUE TITLE
Mega Man Zero Collection, ZX, and ZX Advent white screen on boot

### ISSUE THREAD

**Issue by QueenNiamh** [DS-Homebrew/nds-bootstrap#1131]
**Your console:** DSi (JPN, Original model)
**Launch Method:** Booted from SD card via TwilightMenu++ 20.0.1. Running on HiyaCFW 1.4.0 + Unlaunch 2.0
**Version used:** Release v0.39.0
**Game tested/used/applicable:** 
Mega Man Zero Collection (USA) - TID: B6ZE
Mega Man ZX (USA) - TID: ARZE
Mega Man ZX Advent (USA) - TID: YZXE

**Expected Behavior:** Game boots, functions correctly
**Actual Behavior:** Game locks up with two white screens upon attempting to boot (except for Zero Collection, which locks up with a black upper screen and a white lower screen).

### Steps to reproduce

1. Attempt to boot the games with Release v0.39.0
2. Games don't boot

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 1
NDS_PATH = sd:/roms/nds/Mega Man Zero Collection (U).nds
SAV_PATH = sd:/roms/nds/saves/Mega Man Zero Collection (U).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
REGION = -2
DSI_MODE = 0
BOOST_CPU = 1
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 1
PATCH_MPU_SIZE = 3145728
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
HOMEBREW_ARG =

### Other notes

All games booted without issue on Release v.0.38.0
Tried both NTR and TWL clock speeds, neither worked on v0.39.0

**Comment by RocketRobz** [comment]
Already fixed by https://github.com/DS-Homebrew/TWiLightMenu/commit/3dea15d3676a90cab72034ba36ce0f673811fe01, so this isn't an nds-bootstrap issue.
