### ISSUE TITLE
Some games do not open (White Screen)

### ISSUE THREAD

**Issue by 4ndreuw** [DS-Homebrew/nds-bootstrap#1134]
**Your console:** Nintendo Old 3ds
**Launch Method:**  The game should have opened
**Actual Behavior:**  When I open it from twilight, appears the logo "nds-bootstrap please wait" but when it loads, instead of opening the game, a white screen appears. In that moment, I can only hit home button and leave but the game never opens.

**Comment by RocketRobz** [comment]
Duplicate of #1131
