### ISSUE TITLE
GTA: Chinatown Wars crashes after last update

### ISSUE THREAD

**Issue by Zhounanitathai** [DS-Homebrew/nds-bootstrap#1143]
New 3DS LL-->
SD Card, v.0.39.1-->
Stable v.0.39.1-->
GTA: Chinatown Wars-->

Normally works before update-->
Now Crash -->

**Comment by RocketRobz** [comment]
Still works for me.
Have you tried changing the `Card read DMA` setting?

**Comment by Zhounanitathai** [comment]
Should I activate or deactivate it?

It's very strange, the game starts, but after playing for a few seconds it
suddenly freezes and I have to go back to console Home.
Before this latest update everything worked fine, without changing any
settings.

**Comment by RocketRobz** [comment]
Try turning it off.

**Comment by Zhounanitathai** [comment]
It works now!
Thank you very much!@
