### ISSUE TITLE
Button-enabled cheats don't work for DSi-Enhanced Games in DSi Mode.

### ISSUE THREAD

**Issue by Dimensional** [DS-Homebrew/nds-bootstrap#1144]
**Your console:**  n3DS
**Launch Method:**  Console SD Card. TWiLight Menu v20.1.0.
**Version used:**  Release, V0.39.1
**Game tested/used/applicable:** 
Pokemon Black, No-Intro verified, Decrypted
CRC-32: 4F6E5580
MD5: 37BFF1431EDA9B3A525737C7F59A432D
SHA-1: 26AD0B9967AA279C4A266EE69F52B9B2332399A5
SHA-256: B9979189D299A0231D01C8885C0D054B706976FFC75427CA59D84E0CE1493034

**Expected Behavior:**
Running game in DSi-Enhanced Mode, cheats enabled including cheats that require button pressing.
Expected button input to execute cheat code when activated

**Actual Behavior:** 
Button pressing doesn't execute cheats. Other cheats that don't require input still run however.

### Steps to reproduce

Select Cheats to run for DSi-Enhanced Game, including ones that require button input, such as the L and R buttons.
Set the game to run in DSi-Mode to enable DSi-Enhanced playthrough.
Start game, and when you come to a point to use a cheat, press buttons.
[nds-bootstrap.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6425117/nds-bootstrap.ini.txt)

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6425148/NDSBTSRP.LOG)

### Other notes
Discussed this in the the DSi Mode Hacking discord, and another user there tested this same issue with Pokemon white running in DSi Mode on their DSi. They ran into the same problem.

**Comment by Ben1701A** [comment]
Having a similar issue on my end with a ROM of Mario Kart DS.

``` 
223CE2E2 0000007F: OK - Unlocks all characters, cars, and classes
223CE2E1 0000007F: OK - Unlocks all Retro courses
223CE2E0 0000007F: OK - Unlocks all Nitro courses

4217BC4C 02000000
3217BC4C 02400000
B217BC4C 00000000
20000054 00000001
2000004C 00000001
D2000000 00000000: FAIL - Red shell does not appear in inventory.

923CDD40 0000000C
023CDD40 00000001
D2000000 00000000
94000130 FFFB0000
023CDD40 0000000C
D2000000 00000000: OK - Press SELECT while loading a course to play as Shy Guy.

4217BC4C 02000000
3217BC4C 02400000
B217BC4C 00000000
20000054 00000001
2000004C 00000001
D2000000 00000000: FAIL - Red shell does not appear in inventory when SELECT is pressed. 
```
From what I'm seeing, the cheats are applied at the start (only), and when a button is pressed.
But the button press only works for me when the game is loading, so maybe the game is preventing the cheats from being triggered?

**Comment by RocketRobz** [comment]
I think those cheats aren't working due to the difference in heap locations between DS & DSi mode.

**Comment by RocketRobz** [comment]
Closing, as this issue is on the cheat database side.
