### ISSUE TITLE
Castlevania Order of Ecclesia - Black Screens when loading Save files or change locations

### ISSUE THREAD

**Issue by XeideTH** [DS-Homebrew/nds-bootstrap#1146]
**Your console:** Old Nintendo 3DS
**Launch Method:** Luma 10.2.1 - TWiLight Menu++ v20.1.0 - SD Card
**Version used:** Release nds-bootstrap v0.39.1
**Game tested/used/applicable:** Castlevania Order of Ecclesia

**Expected Behavior:** The game not to black screen
**Actual Behavior:** When i try to play the game, Sometimes a black screen appears and it stay like this forever, Even if you managed to load the game, when you're playing it and change locations the black screen appears again.

### Steps to reproduce

Open the TWilight Menu++ and choose the game "Castlevania Order of Ecclesia, Then wait for the game starts, Choose the save file and wait for the game load, most of the time the game stay in a black screen and if you're luck the game loads and you can start playing. You can play the game for a while but when you change to another location, Black screen again

### Other notes

If my English is wrong, i'm sorry. The problem also happens with the other Castlevania series since i updated the Bootstrap and the TWilight Menu++

**Comment by Kaisaan** [comment]
This never happened to me. Tested all Castlevania games (Dawn of Sorrow, Portrait of Ruin, and Order of Ecclesia. Last tested on nds-bootstrap version 0.54.1 with TWiLight Menu++ version 24.1.0 so this seems to have been fixed in an update. Tested on a N3DS XL with Luma3DS 10.2.1 Closing.
