### ISSUE TITLE
Bowser's Inside story freezes

### ISSUE THREAD

**Issue by Superdude11235** [DS-Homebrew/nds-bootstrap#1148]
**Your console: New 3ds XL** 
**Launch Method: Twilight Menu v20.1.0 from microSD card** 
**Version: release v0.39.1** 
**Game tested/used/applicable: Mario & Luigi: Bowser's Inside Story** 

**Expected Behavior: Game should play normally** 
**Actual Behavior: The game sometimes freezes during loading screens** 

### Steps to reproduce

When I play Bowser's inside story, it seems to play normally. However, whenever there's some sort of loading screen (e.g. after a battle) the game will seemingly randomly crash and the screen will turn black. If there was music playing, it will turn glitchy for a second and then stop. The bootstrap menu won't show up and the only thing I can do is go to the home menu. Same results in both DS and DSi mode.

### Logs

SCFG_ROM ARM9 1
SCFG_CLK ARM9 85
SCFG_CLK ARM7
SCFG_EXT ARM 7
ARM7 data 187
ARM7 data FB06
CPU boosted
VRAM boosted
debug:true
ndsPath: "sd:/roms/nds/Mario & Luigi - Bowser's Inside Story.nds"
savPath: "sd:/roms/nds/saves/Mario & Luigi - Bowser's Inside Story.sav"
gbaPath: ""
Press start...

### Other notes

In previous versions of twilight menu and nds bootstrap the game worked fine. Is there a "quick fix" for my issue before it gets fixed in an update, or will I have to downgrade to a previous version in the meantime?

**Comment by ruhnarius** [comment]
I am having a similar issue in Zelda Phantom Hourglass. I am using a New 3DS XL with luma3ds v10.2.1, TWLmenu v20.1.0, and nds-bootstrap v0.39.1. The game occasionally freezes after loading (area transitions, opening menus, etc). 

from NDSBTSRP.LOG:
debug: true
ndsPath: "sd:/roms/nds/ZELDA_PH.nds"
savPath: "sd:/roms/nds/saves/ZELDA_PH.sav"
gbaPath: ""
donorE2Path: ""
donor2Path: ""
donor3Path: ""
donorPath: ""
donorTwlPath: ""
saveSize: 80000
language: FF
region: FE
dsiMode: 1
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
extendedMemory: false
consoleModel: 2
colorMode: 0
romRead_LED: 0
dmaRomRead_LED: FF
cardReadDMA: true
boostCpu: true
boostVram: true
soundFreq: false
forceSleepPatch: false
logging: true
initDisc: false
gameOnFlashcard: false
saveOnFlashcard: false
macroMode: false

**Comment by Superdude11235** [comment]
The new update didn't help, as I hoped. In fact, it made it worse! Now, it will always crash when I open my save file.

Also, I should mention that other games like Pokemon Platinum work fine, it's specifically Bowser's Inside Story that crashes.

**Comment by RocketRobz** [comment]
Commit 335f54b2 fixes the consistent (but still sometimes occurring) crash when opening the save file.
Try updating nds-bootstrap to latest nightly, and make sure `Bootstrap` setting is set to `Nightly` for that game.

**Comment by ruhnarius** [comment]
> 
> 
> Commit [335f54b](https://github.com/DS-Homebrew/nds-bootstrap/commit/335f54b2ece00416ec90837b7057885f430d3b6f) fixes the consistent (but still sometimes occurring) crash when opening the save file.
> Try updating nds-bootstrap to latest nightly, and make sure `Bootstrap` setting is set to `Nightly` for that game.

The nightly version (v0.40.1-dfa536a) appears to have fixed all the crashes in phantom hourglass, thank you very much

**Comment by RocketRobz** [comment]
> The nightly version (v0.40.1-dfa536a) fixed all the crashes in phantom hourglass, thank you very much

PH is actually fixed by v0.40.0. The nightly only contains the fix for Bowser's Inside Story.

**Comment by Superdude11235** [comment]
> Commit [335f54b](https://github.com/DS-Homebrew/nds-bootstrap/commit/335f54b2ece00416ec90837b7057885f430d3b6f) fixes the consistent (but still sometimes occurring) crash when opening the save file.
> Try updating nds-bootstrap to latest nightly, and make sure `Bootstrap` setting is set to `Nightly` for that game.

Thanks, this completely fixes the problem! I've played for about half and hour and no crashes! I also tested it by repeatedly going through loading screens and they work fine.

**Comment by RocketRobz** [comment]
You're welcome!
