### ISSUE TITLE
Castlevania Order of Ecclesia and Dawn of Sorrow problem

### ISSUE THREAD

**Issue by Agutom3112** [DS-Homebrew/nds-bootstrap#1149]
**Your console:** Nintendo DSi XL
**Launch Method:** Twilight Menu 20.1.0 SD card 
**Version used:** Released nds-bootsrap v0.39.1
**Game tested/used/applicable:** Castlevania Dawn of Sorrow / Castlevania Order of Ecclesia

**Expected Behavior:** Game should play normally
**Actual Behavior:** In Order of Ecclesia the game plays the intro cutscene normally but when I try to skip it the game crashes and when I'm able to skip the cutscene... the game crashes when I try to create a Save File. 
The same thing happen in Dawn of Sorrow but sometimes I'm able to play the game normally until the game decide to randomly crash.

### Steps to reproduce

The first time I play Order of Ecclesia I let the game to play the intro cutscene normally and when that cutscene finished, the screen turned black and then the game crash. The second time I try to play the game I try to skip the cutscene and then the game crash. I try a third time and  this time I´m able to reach the main menu, I try to create a Save file and the game crashed and the music turn glitchy.

With Dawn of Sorrow at first the game wouldn't load the title screen but after a few try the game load the title screen and I was able to play the game normally until out of nowhere the game randomly crashed and the graphics and the music turn glitchy.

### Logs

Sorry... I don´t know how to do this... I´m kinda new to this.

### Other notes
I used Twilight menu but an old version and that version ran the games perfectly. This is my first time I update Twilight Menu and I don't know if I have to downgrade to a previous version or if there is anyway to fix this.

**Comment by RocketRobz** [comment]
Both issues should be fixed by later nds-bootstrap versions.
The occasional crashes in Dawn of Sorrow may not be fixed though.
