### ISSUE TITLE
Ghost Trick: Phantom Detective Broken/Garbled Text

### ISSUE THREAD

**Issue by jonnehicles** [DS-Homebrew/nds-bootstrap#1151]
**Your console:** New 2DS LL (region changed to EU)
**Launch Method:** Twilight Menu v20.2.0, game launched via SD Card
**Version used:** Bootstrap v0.40.0 (release)
**Game tested/used/applicable:** Ghost Trick - Phantom Detective (EUR) [also tested US version with same issue]

**Expected Behavior:** Game continues as normal, text readable
**Actual Behavior:**  In Chapter 2, right after you Trick the control panel that flips the table, there is some slight screen tearing followed by the textboxes from that point onwards having garbled, unreadable text. Image is attached below
![PXL_20210517_163145407](https://user-images.githubusercontent.com/23199370/118543809-ad6e0c00-b74c-11eb-8ff8-0a015ce5ccc8.jpg)

### Steps to reproduce
1. Launch game in Twilight Menu
2. Start Chapter 2
3. Play normally until you use the Control Panel to flip the table
4.  Text boxes from here on out are garbled.

[NDS-BOOTSTRAP DEBUG INFO]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/5537_-_Ghost_Trick_Phantom_Detective_EUR_MULTi5_NDS-WetNWild_apfix.nds
SAV_PATH = sd:/roms/nds/saves/5537_-_Ghost_Trick_Phantom_Detective_EUR_MULTi5_NDS-WetNWild_apfix.sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284

### Logs
findModuleParamsOffset:
Module params offset restored: 02000BA4
sdk_version: 05047530
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

cardIrqEnable location : 020735A8

startOffset : 02000000

cardRead location : 0206AAD0
023F4000

swi12 location : 02000786

cardPullOut location : 0206B078

cardId location : 0206A930

sleep location : 02074288

cardReadDma location : 0206AD38

patchMpuSize: 00000000

findMpuInitCacheOffset:
Mpu init cache not found

patchMpuSize: 00000000

Mpu init: 02074FF4

reset location : 02075DA8

ERR_NONE

cardIrqEnable location : 02384060

Relocation src: 023802E4

Arm7 (patch v5)
JumpTableFunc: 0238ECB0
card read:	0238EC98
Eeprom read:	0238ECBC
Eeprom page write:	0238ECD4
Eeprom page prog:	0238ECEC
Eeprom verify:	0238ED04
Eeprom page erase:	0238ED18
swiHalt location : 02380664

swi12 location : 02383600

swiGetPitchTable location : 02383614

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FE78

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80007FC2

### Other notes
Applied anti-piracy removal patch using DS-Scene Rom Tool just incase there was an error with Twilight Menu and still doesn't work.
I have added the save file I've used below
https://drive.google.com/file/d/1ISYQy3a-K6jJbb70fZS7jVQmGSaZtOWk/view?usp=sharing

**Comment by clach04** [comment]
I recently (about two weeks ago) played through this successfully (US version) on a DSi. If its helpful I could dig out the version number of nds-bootstrap used. I do know the first version I tried did not work (AP issue with no text displayed at all, later version was fine).

**Comment by jonnehicles** [comment]
> I recently (about two weeks ago) played through this successfully (US version) on a DSi. If its helpful I could dig out the version number of nds-bootstrap used. I do know the first version I tried did not work (AP issue with no text displayed at all, later version was fine).

If you could, that would be greatly appreciated!

**Comment by clach04** [comment]
Failure with Ghost Trick (AP text issue, not the garbled one in the photo in this issue) with:

* https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v19.1.1
      * not sur eon nds-bootstrap version

Success with DSi (I don't have 2DS) using:

* https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v20.1.0
     * https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.39.1
* https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v20.2.1
     * https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.40.2
 
USA version, CRC32: 5CD93FE5

**Comment by bowsercastlepeach** [comment]
Not sure if related but I had some graphical glitches in ghost trick opening intro that were solved by switching vram boost to on but I did not play the game any further to see if text is normal. Give it a try tho, maybe it could solve your issue with text.

What I tested on
new 2ds xl
twilight menu v20.2.1
nds bootstrap v0.40.2

**Comment by RocketRobz** [comment]
iirc, this is caused by turning on `Asynch Card Read`, which doesn't work properly for some games.
