### ISSUE TITLE
Black screen when starting first case in Gyakuten Kenji 2

### ISSUE THREAD

**Issue by danny2004de** [DS-Homebrew/nds-bootstrap#1152]
**Your console:** 
Nintendo 2DS
**Launch Method:** 
 Launched via SD card on 2DS with Luma and latest versions of TwilightMenu and ndsbootstrap
**Version used:** 
Release v20.2.0
**Game tested/used/applicable:** 
Gyakuten Kenji 2, English Patched but not AP patched

**Expected Behavior:** 
Game should launch to title screen, then selecting the first should begin a cutscene.
**Actual Behavior:**
 Game launches to title screen and allows me to select the first case, but upon doing so the game fades to a black screen and doesn't continue. I can still exit back to TwilightMenu or the home screen.

### Steps to reproduce

Start TwilightMenu, start up Gyakuten Kenji 2, select New Game, then start Turnabout Target, after which watch a frozen black screen.

**Comment by csnow99** [comment]
I am having a very similar issue with a New 3DS, using the latest versions of everything. I don't believe it to be the AP measures, as I had the same issue using just the translation patched version and a version with both the translation and AP patch applied.

When I launch the first case, it goes up until the door to the plane opens partway, then freezes. Music continues, but even once it ends it stays frozen on that frame.

**Comment by gabman15** [comment]
I am also having a similar issue. I'm running the latest version of both Twilightmenu and nds-bootsrap. I have patched my rom such that the sha256 is
`SHA256 hash of Gyakuten Kenji 2 (Patch 2).nds:                                                                          ccfcd45cd4bbe9894d5364facc4858cea4b539e4cb2505d03f8da4e0df133525 `
When I load this rom via twilightmenu, it does the nds-bootstrap logo and then goes to a black screen indefinitely until I press home to quit. I have tested other ds games which all appear to work so far (Mario Kart DS) as well as the unpatched version of Gyakuten Kenji 2 which works as well. So something is weird is going on with the patch I assume.

**Comment by gabman15** [comment]
> I am also having a similar issue. I'm running the latest version of both Twilightmenu and nds-bootstrap on my new 3ds xl. I have patched my rom such that the sha256 is
> `SHA256 hash of Gyakuten Kenji 2 (Patch 2).nds: ccfcd45cd4bbe9894d5364facc4858cea4b539e4cb2505d03f8da4e0df133525 `
> When I load this rom via twilightmenu, it does the nds-bootstrap logo and then goes to a black screen indefinitely until I press home to quit. I have tested other ds games which all appear to work so far (Mario Kart DS) as well as the unpatched version of Gyakuten Kenji 2 which works as well. The patched rom does work in an emulator so I assume its on nds-bootstrap or twilightmenu's side. (or my system is screwed up somehow)

With update v0.42.0, This appears to have fixed it and I can load into the game!

**Comment by RocketRobz** [comment]
OP's issue should already be fixed then.
