### ISSUE TITLE
No sound in Professor Layton cutscenes after skipping them once

### ISSUE THREAD

**Issue by Kijaru** [DS-Homebrew/nds-bootstrap#1154]
**Your console:** New 2DS XL
**Launch Method:** Launched via SD card using Twilight Menu++, using Luma 10.2.1
**Version used:** 0.40.0
**Game tested/used/applicable:** Professor Layton and the Curious Village (EU), using French as system language

**Expected Behavior:** During animated cutscenes there should be FX sound and sometimes character voices, and in game movies should have sound
**Actual Behavior:** In game movies don't have sound at all, and animated cutscenes only have SFX sounds, no voice.
Also during the very first movie, there should be car SFX playing, but only the music is played.

### Steps to reproduce

Launch a game, and during the first animated cutscene skip one of the dialogs when a character is talking. It'll disable the character voices in all the animated cutscenes, as well as during the movies.

nds-bootstrap.ini content:
[NDS-BOOTSTRAP]
NDS_PATH = sd:/Games/xms-plve.nds
SAV_PATH = sd:/Games/saves/xms-plve.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 1
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
LOGGING = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = fr
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 0

### Logs

Debug logging wasn't enabled when the bug occured, I'd be more than happy to reproduce the issue with it enable, just tell me how.

### Other notes

Possible duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/585

**Comment by RocketRobz** [comment]
Try turning off card read DMA.

**Comment by RocketRobz** [comment]
Alright, just tried with both DMA on and off, and the cutscene audio (containing voices and SFX) played fine.
Make sure you've updated nds-bootstrap to v0.41.0.

**Comment by Kijaru** [comment]
Ok updating to the latest nds-bootstrap worked. However I have no idea why it stopped working all of sudden since twilightmenu++ was set to use the nightly version (the one which was fixed) and not the stable version of nds-bootstrap.

Sorry for the inconvenience, I must have done something wrong that made twilightmenu++ switch back to the stable version somehow.
