### ISSUE TITLE
Pokémon Black 2 and White 2 Crash when opening up Pokémon summary in-game 

### ISSUE THREAD

**Issue by StirkerPr** [DS-Homebrew/nds-bootstrap#1156]
**New 3Ds XL:** 
**SD:** 
**latest:** 
**Game tested/used/applicable:** 

**Open Up Pokémon Summary:** 
**game Crashes:**

**Comment by Epicpkmn11** [comment]
Make sure you're using a clean dump or have manually AP patched your ROM. This happens when the anti-piracy triggers.

You can get a clean dump from your cartridges has described here:
- DSi: https://dsi.cfw.guide/dumping-cartridges
- 3DS: https://3ds.hacks.guide/dumping-titles-and-game-cartridges
