### ISSUE TITLE
Gyakuten Kenji 2 English Patch Final V2 Crashing on Logic Mode, Scene switching (Ie Investigation Mode to Interactions), and in-between long animations

### ISSUE THREAD

**Issue by apowersak1** [DS-Homebrew/nds-bootstrap#1157]
**Your console:** Nintendo O2DS
**Launch Method:** Launched Via TwilightMenu++ 16GB Default SD
**Version used:** Release, boots through NDS BootStrap
**Game tested/used/applicable:** Gyakuten Kenji 2 (JPN) (Eng Patch Final V2)

**Expected Behavior:** It should usually just play the animations, if you load it right before the animations begin, it loads fine, an example is in case 1 when you're about to go into cross-examination against Knightly, and it all of a sudden freezes mid animation.
**Actual Behavior:** White screen when going into Logic Mode, Black Screen when changing screens, Frozen Screen when in-between animations

### Steps to reproduce

Step 1: Play Game
Step 2: Get to any Logic usage outside of tutorial (1st Time it occurs)
Step 3: Get Frozen White Screen

### Other notes
Ace Attorney Investigations 1 (USA) worked perfectly fine without any hitches if that means anything, but they seem to be built slightly different, so it might be a result of the coding

**Comment by TRAPMONETHIBBY** [comment]
Also find myself having trouble with this specifically. Additionally, sometimes I'll get graphical glitches with the character models or images where they get distorted.

**Comment by RocketRobz** [comment]
Does this issue persist in v0.63.1?

**Comment by spellboundtriangle** [comment]
The compatibility list seems to contradict this (with version 0.19.5, about two years older than this issue), so perhaps a regression check should be done, if it's still occurring on the latest release.

**Comment by RocketRobz** [comment]
Whatever change has been made some versions ago seems to have fixed it, because it's working fine for me.
