### ISSUE TITLE
Professor Layton and the last specter graphics issues

### ISSUE THREAD

**Issue by HDJDeadfur** [DS-Homebrew/nds-bootstrap#1159]
**Your console:** <Dsi>
**Launch Method:** <I'm used a 32gb sd card, i dont know what a scfg is, but the sd card worked perfectly on 15.4 twilight menu or something like that. Im using hiya cfw, with twilight menu 20.2.1>
**Version used:** <Ive tried both release and nightly (8b7f7b4c)>
**Game tested/used/applicable:** <Professor layton and the last specter>

**Expected Behavior:** <the images should look like what you find on the puzzle pages for the "incorrect" and "try again" screens. also how the title page should normally look>
**Actual Behavior:** <the images appear to be split up a bit, so the image doesn't "line up">

### Steps to reproduce

<I'm near the end of the game, in that odd area where the game doesnt save any further so you can do all the puzzles. I go to the left, past the kid and the guy with red hair, and to the kid with a red coat. he has a puzzle, so tap on him. looks fine and dandy, but i did the wrong answer. (SPOILER) don't do D (SPOILER). the screens then have the odd artifacts. It was working fine on bootstrap 15 something I believe. [nds-bootstrap.ini.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/6528534/nds-bootstrap.ini.zip)>

### Logs

<[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6528533/NDSBTSRP.LOG)>

### Other notes
I just upgraded from twilight menu from like, 2019 I believe. it was a fairly old one, everything had to be in DS mode. Also after enabling logging it seemed to work perfectly, but the title screen got weird. It's not exactly game breaking, but i figured I should bring it up.
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6528533/NDSBTSRP.LOG)

[nds-bootstrap.ini.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/6528534/nds-bootstrap.ini.zip)

![IMG_20210523_124803](https://user-images.githubusercontent.com/62817260/119269906-0bc14180-bbc8-11eb-8403-d7eba3639263.jpg)
![IMG_20210523_124806](https://user-images.githubusercontent.com/62817260/119269909-0d8b0500-bbc8-11eb-8f8f-52fdc7a7ad16.jpg)
![IMG_20210523_125838](https://user-images.githubusercontent.com/62817260/119269910-0ebc3200-bbc8-11eb-8be7-68657a436b64.jpg)

**Comment by HDJDeadfur** [comment]
Im using a dsi, it wont let me change it

**Comment by RocketRobz** [comment]
That's a known issue that should already be fixed in nightlies.
