### ISSUE TITLE
Bootstrap bug

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1160]
With the new nightly, the menus in bootstrap are messed up.
If you resume the game from there, the screen display may be distorted.

Bootstrap version where the phenomenon (bug) was confirmed
fb80aa91
d4cfb6f8
814e2123
47bc1859
6b76d0ce

**Comment by RocketRobz** [comment]
That's been a bug for a while.
The in-game menu doesn't display properly in some games.

**Comment by KururinX** [comment]
![E01](https://user-images.githubusercontent.com/81461991/119278837-cb62d180-bc62-11eb-92e3-eff9910cadaf.jpg)
![E02](https://user-images.githubusercontent.com/81461991/119278841-cf8eef00-bc62-11eb-8820-0ca1d2f234e4.jpg)
![IMG_20210524_071341](https://user-images.githubusercontent.com/81461991/119278846-d3227600-bc62-11eb-9e76-8265eebfbc17.jpg)

TWL : 346d0978  Bootstrap : 6b76d0ce  Use:DSi LL

Even in games that were not a problem before, the menu display is strange as shown in the first picture. (All the games I looked up are like that)
The second and subsequent sheets are examples when the menu is closed and restarted.

**Comment by RocketRobz** [comment]
> Final Fantasy III (JP) - BlackOut

Turn off card read DMA to fix the crash.

**Comment by RocketRobz** [comment]
2485ff27 should fix the bugged in-game-menu.

**Comment by KururinX** [comment]
In the case of FINAL FANTASY III, I couldn't think of turning off DMA. Confirmed startup. 
I'll try the new bootstrap soon.

**Comment by KururinX** [comment]
Bootstrap : 2485ff27
Report that the situation has improved.
