### ISSUE TITLE
Rest mode turns off console

### ISSUE THREAD

**Issue by sapfel93** [DS-Homebrew/nds-bootstrap#1161]
**Your console:** New 3DS
**Launch Method:** SD Card
**Version used:** 0.40.2
**Game tested/used/applicable:** Pokemon Heart Gold

**Expected Behavior:** Closing system puts game in sleep mode
**Actual Behavior:** On some occassions, the game goes to the power off screen

### Steps to reproduce

1) Turn on game
2) Put game in sleep mode

### Logs

Sometimes when the game is playing and I put it in sleep mode, the 3DS goes in the Power Off screen. It seems to happen at random.

**Comment by RocketRobz** [comment]
Are you sure you're using v0.40.2?
That bug should already be fixed in that version.
Also, what's inserted in the game card slot?

**Comment by sapfel93** [comment]
Positive. And Pokemon Black.

**Comment by RocketRobz** [comment]
Please check TWLMenu++ Settings to make sure that you're using v0.40.2.

**Comment by sapfel93** [comment]
I guarantee you i'm on release v0.40.2. I also experience the same issue consistently if I push the home button menu on a forwarder (not through TwilightMenu).

**Comment by RocketRobz** [comment]
Try updating nds-bootstrap to latest nightly then, and then switch `Bootstrap` to `Nightly` in TWLMenu++.

**Comment by sapfel93** [comment]
Do you know how to change the forwarder from release to nightly ndsbootstrap?

**Comment by RocketRobz** [comment]
Open `sd:/_nds/ntr-forwarder.ini`, and set `BOOTSTRAP_FILE` to `1`.

**Comment by sapfel93** [comment]
Sorry. See edited post above to see why nightly is bugged

**Comment by RocketRobz** [comment]
2485ff27 should fix the bugged in-game-menu.

**Comment by sapfel93** [comment]
Updated and in-game menu is fixed. Home menu button on forwarder still powers off. Game shuts off on sleep mode on nightly with forwarder; can't confirm if it does on twilightmenu.

**Comment by RocketRobz** [comment]
When did you make the forwarder?

**Comment by sapfel93** [comment]
A while ago. Should I try to create a new one? If so how do i do it without taking out the sd card?

**Comment by RocketRobz** [comment]
https://wiki.ds-homebrew.com/ds-index/3ds-forwarders

**Comment by sapfel93** [comment]
Okay. Deleting and reinstalling a new forwarder fixed the home button menu. Can't confirm if sleep mode powering off is fixed on nightly. Will probably need to play more to confirm.

**Comment by sapfel93** [comment]
Btw, instead of starting a new thread, can I ask if Pokemon Platinum has stopped randomly crashing on the dsi version? I'm sorry if this isn't the right way to ask.
