### ISSUE TITLE
AP Spirt Tracks

### ISSUE THREAD

**Issue by theapathyimp** [DS-Homebrew/nds-bootstrap#1162]
AP patch no longer working on most recent versions for The Legend of Zelda: Spirit Tracks. I am using the D-Pad patched ROM title ID: BKIE. 

The game was working fine and the train controls were functional until I updated Luma/gm9/TM++ last night. Now the AP block for the train controls is in place and I can no longer progress due to this. I changed my settings to run in DSi mode, but changed it back and made sure I had it running in DS Mode per DS-Homebrew/TWiLightMenu#1422 but the issues persisted.

Side note: no cheats are found when trying to apply them from the menu using the most recent usercheat.dat from universal-updater but I confirmed cheats do exist on code sites.

**Comment by RocketRobz** [comment]
There's a bug in nds-bootstrap that seems to cause this.
Try updating it to the latest nightly, switch `Bootstrap` to `Nightly` in TWLMenu++ Settings, and see if it fixes the AP issue.

**Comment by theapathyimp** [comment]
I just tested it with the nightly, no change.   From: RocketRobzSent: Monday, May 24, 2021 02:56To: DS-Homebrew/nds-bootstrapCc: theapathyimp; AuthorSubject: Re: [DS-Homebrew/nds-bootstrap] AP Spirt Tracks (#1162) There's a bug in nds-bootstrap that seems to cause this.Try updating it to the latest nightly, switch Bootstrap to Nightly in TWLMenu++ Settings, and see if it fixes the AP issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RocketRobz** [comment]
Get the latest version of the D-Pad patch from GBATemp. If that doesn't fix it either, try the clean ROM instead.

**Comment by RocketRobz** [comment]
This is happening again starting with v0.43.0.

**Comment by RocketRobz** [comment]
Should be fixed as of either nds-bootstrap v0.43.2 or TWLMenu++ v21.0.2.
