### ISSUE TITLE
Sound stutter during cinenatic intro in Nine Hours, Nine Persons, Nine Doors

### ISSUE THREAD

**Issue by ghost** [DS-Homebrew/nds-bootstrap#1163]
**Your console:** new 2ds xl
**Launch Method:** sd card
**Version used:** nds bootstrap v0.40.2 release, twilight menu v20.2.1 release
**Game tested/used/applicable:** Nine Hours, Nine Persons, Nine Doors (us version)

**Expected Behavior:** Cinematic intro plays without sound stutter in NTR mode
**Actual Behavior:** Sound stutters a bit in the second half of the cinematic intro in NTR mode but works normally in TWL mode.

### Steps to reproduce

Simply launch the rom in NTR mode and wait for the cinematic intro to start.

**Comment by retinasilver** [comment]
The problem still exists as of bootstrap v50.0 and twilight menu v23.0 but it lags somewhat less. What I also noticed is that the problem can be solved not only by using twl mode but also dsi mode itself removes the lag in the intro even when using it with ntr mode.

**Comment by lifehackerhansol** [comment]
@retinasilver please try toggling SWI Halt Hook.

**Comment by retinasilver** [comment]
I confirm that setting swi halt hook to off also works.

**Comment by lifehackerhansol** [comment]
SWI Halt is now defaulted to off.
