### ISSUE TITLE
Dragon Quest IX: Sentinels of the Starry Skies

### ISSUE THREAD

**Issue by Fireborn101** [DS-Homebrew/nds-bootstrap#1165]
**Your console:** new 2ds xl
**Launch Method:** SD card: NDS bootstrap v0.40.2 ; Twilight v20.2.1 
**Version used:** Release
**Game tested/used/applicable:** Dragon Quest IX: Sentinels of the Starry Skies (Nintendo DS)

**Expected Behavior:** After Leviathan boss battle, game proceeds to next area (Porth Llaffan, Mayor's Home when you awake). When you leave the Mayor's home in Porth Llaffan, the area should load in, progress able to continue.
**Actual Behavior:** When screen fades to black as you leave the Mayor's home ( to load next area) it remains black, music continues. Attempted boss battle/attempt to continue 4x, each time game freezes when leaving Mayor's home.

Extra Info: As an update, I ported the same save file and same rom file to the pc, and used DeSmueMe: On the 2ds xl, the house was empty, no npcs present. On DeSmueME, the npcs spawned properly, game didn't freeze.

**Comment by Fireborn101** [comment]
As an update, I ported the same save file and same rom file to the pc, and used DeSmueMe: On the 2ds xl, the house was empty, no npcs present. On DeSmueME, the npcs spawned properly, game didn't freeze. So bootstrap must have been loading things out of order, if that might help.

**Comment by RocketRobz** [comment]
I'm thinking `Asynch Card Read` has caused this. This game has been in TWLMenu++'s asynch card read blacklist for a while now.
