### ISSUE TITLE
Brain Age Express - Sudoku (USA) (Rev 2): Seeing "Download failed" error message

### ISSUE THREAD

**Issue by eisnerguy1** [DS-Homebrew/nds-bootstrap#1167]
**Your console:** N3DS

**Launch Method:** SD Card via TWiLight Menu++ v20.3.0

**Version used:** Release v0.41.0

**Game tested/used/applicable:** 
*Brain Age Express - Sudoku (USA) (Rev 2):
MD5:  114d157e31583c81f8a20757a25ee736

**Expected Behavior:** Game should allow you to select the profile.
**Actual Behavior:** Right after the title screen, a message will appear that says "Download failed. Please try again."

### Steps to reproduce

Launch Brain Age Express - Sudoku (USA) (Rev 2), wait a few seconds, and you'll see the error message about the download having failed.

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/NDS/DSiWare/Brain Age Express - Sudoku (USA) (Rev 2).nds
SAV_PATH = sd:/NDS/DSIWARE/BRAINA~2.PUB
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
GAME_SOFT_RESET = 1
CARDENGINE_CACHED = 1
AP_FIX_PATH =
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 1
REGION = -2
CARD_READ_DMA = 1
HOTKEY = 284
APP_PATH = sd:/NDS/DSIWARE/BRAINA~2.NDS
PRV_PATH = sd:/NDS/DSIWARE/DSiWare
GUI_LANGUAGE = en

### Logs
findModuleParamsOffset:
Module params offset found: 02004FCC
sdk_version: 05017537

hookNdsRetailArm7
hookLocation arm7: 02395088

ERR_NONE
Device list address: 037E3CD0

### Other notes
I generated the save file by downloading the DSiWare from the eShop, saving in game, exporting the public.sav file via Godmode 9, transferring it to my computer via FTPD, renaming the save file with the appropriate filename, changing the extension to .pub and then transferring the .pub file back to my N3DS.

I've verified that the DSiWare .nds file match the hashes of the DSiWare that I downloaded from the eShop.

**Comment by RocketRobz** [comment]
The Brain Age games use `banner.sav`, which isn't accounted for in the device list.

**Comment by fleefie** [comment]
Is `banner.sav` support planned in `nds-boostrap` ? If not, maybe there could be a way to fake `banner.sav` saving by redirecting it to a dummy file. For a more permanent solution though, it would have to be fully implemented. I'll check the code and see if i can help with it.

**Comment by RocketRobz** [comment]
I've tried redirecting the file by changing `nand:/<banner>` to `sdmc:/bnr.sav` in the arm9 binary, or what's considered as `nand:/<banner>` in the arm7i binary, but the error persists.

Apparently, unless someone else knows how to fix this, we're out of luck.

**Comment by AbnormalPoof** [comment]
Should we pin this?

**Comment by RocketRobz** [comment]
Fixed by 0c1a9f4c
