### ISSUE TITLE
Pokemon Soulsilver Golden Edition Black Screen

### ISSUE THREAD

**Issue by Pokemiah** [DS-Homebrew/nds-bootstrap#1168]
**Your console:** New 3DS XL
**Launch Method:** Twilight Menu ++ 20.3.0 on 3DS microSD Card System Firware: 11.14.0-46U
**Version used:** Release
**Game tested/used/applicable:** Pokemon Heartgold Golden Edition Patch Link: https://www.pokecommunity.com/showthread.php?t=347879
**Expected Behavior:** When changing screens such as entering or exiting an area, exiting a menu, etc. the game runs like normal.
**Actual Behavior:** Sometimes when changing screens, the game black screens with the audio still playing.

### Steps to reproduce

1. Either enter or exit an area or menu. (Seems to happen randomly).

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6565267/NDSBTSRP.LOG)

**Comment by Pokemiah** [comment]
nds-bootstap.ini code
`[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/PG43SSGE - (AP)Pokemon SoulSilver - Golden Edition (AP-PATCHED).nds
SAV_PATH = sd:/roms/nds/saves/PG43SSGE - (AP)Pokemon SoulSilver - Golden Edition (AP-PATCHED).sav1
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 1
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
FORCE_SLEEP_PATCH = 0
LOGGING = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
MACRO_MODE = 0
CARD_READ_DMA = 1`

**Comment by Squall-Leonhart** [comment]
AP patches must be manually applied to romhacks.
