### ISSUE TITLE
Issues in cinematic intro in Kingdom Hearts Re:Coded

### ISSUE THREAD

**Issue by bowsercastlepeach** [DS-Homebrew/nds-bootstrap#1169]
**Your console:** new 2ds xl
**Launch Method:** sd card
**Version used:** nds bootstrap v0.41 release, twilight menu v20.3 release
**Game tested/used/applicable:** Kingdom Hearts Re:Coded (eu version)

**Expected Behavior:** Cinematic intro plays without issues.
**Actual Behavior:** Cinematic intro freezes when DMA is set to off and has occasional framerate issues when cpu speed is set to NTR but works fine when set to TWL.

### Steps to reproduce

Launch the rom, click new game and watch the cinematic intro first with DMA set to off to see the freeze and then with CPU speed set to NTR to notice occasional framerate issues.

**Comment by RocketRobz** [comment]
I suggest turning card read DMA on in TWLMenu++ Settings, as the next TWLMenu++ version will have the setting revert to being turned on by default, due to unexpected issues.
