### ISSUE TITLE
Super Mario 64 can't enter doors

### ISSUE THREAD

**Issue by KH1501** [DS-Homebrew/nds-bootstrap#1171]
Your console: New 2DS XL
Launch Method: Twilight menu ++ 20.3.0  on 3DS microSD Card System Firware: 11.14.0-46E
Version used: release 0.41.0 
Game tested/used/applicable: Super mario 64 DS

**Expected Behavior:** when approaching the main door or the one down in the pit your carater should enter it 
**Actual Behavior:** you hug the door as if it was a wall and nothing hapens 

### Steps to reproduce
1. load up the game on either a new or an old save and try to enter a door

[NDS-BOOTSTRAP]
NDS_PATH = sd:/nds roms/S.MARIO64DS_ASMP01_00.trim.nds
SAV_PATH = sd:/nds roms/saves/S.MARIO64DS_ASMP01_00.trim.sav
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 0
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
LANGUAGE = -1
DSI_MODE = 1
BOOST_VRAM = 1
GAME_SOFT_RESET = 0
FORCE_SLEEP_PATCH = 0
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 1
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 1
AP_FIX_PATH =
DMA_ROMREAD_LED = -1
CACHE_FAT_TABLE = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 1
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = de
REGION = -2
CARD_READ_DMA = 1

### Logs

findModuleParamsOffset:
Module params offset restored: 02004AF4
sdk_version: 020029A7
arm9 is compressed

Switched to NTR mode BIOS
relocate_ce9
firstCardLocation 023F0000 : 02780000

armReadCardLocation 023F00F0 : 02780000

thumbReadCardLocation 023F0110 : 02780000

armReadCardDmaLocation 023F0140 : 02780000

armReadSlot2Location 023F0164 : 02780000

armSetDmaCardLocation 023F0194 : 02780000

thumbReadCardDmaLocation 023F01C0 : 02780000

thumbSetDmaCardLocation 023F01E0 : 02780000

armReadNandLocation 023F0204 : 02780000

thumbReadNandLocation 023F0228 : 02780000

armWriteNandLocation 023F0240 : 02780000

thumbWriteNandLocation 023F0260 : 02780000

armIrqEnableLocation 023F0290 : 02780000

thumbIrqEnableLocation 023F02B0 : 02780000

pdashReadLocation 023F02DC : 02780000

thumbReadSlot2Location 023F0300 : 02780000

ipcSyncHandlerLocation 023F0368 : 02780000

resetLocation 023F0390 : 02780000

globalCardLocation 023F1320 : 02780000

 ce9->patches 023F0034

patchCardNds

cardIrqEnable location : 02056DE0

startOffset : 02004000

cardRead location : 02060A64
023F0000

swi12 location : 02004656

cardPullOut location : 0206A634

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02060D1C

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 02060CE8

patchMpuSize: 00000000

reset location : 020A0D98

ERR_NONE

forwardedRelocStartAddr
02380154
vAddrOfRelocSrc
02380168
Relocation src: 02380168
Relocation dst: 037F8000

Arm7 (patch v1)
cardReadEndAddr: 02387EF8
cardstructAddr: 038087A0
readCacheEnd: 02388040
JumpTableFunc: 02388044
specificWramAddr: 037FF3A4
someAddr_799C: 02387AC4
Eeprom page erase:	02388054
Eeprom verify:	02388070
Eeprom page write:	0238808C
Eeprom page prog:	023880A8
Eeprom read:	023880C4
Card read:	023880E4
Card id:	023880F0
Identify backup:			02388114
Arm7 patched!
swiHalt location : 02380594

swi12 location : 02388190

swiGetPitchTable location : 02383A78

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238DF5C

ERR_NONE
hookLocation arm9: 02099FE4

ROM loaded into RAM

chipID: 00000FC2

**Comment by RocketRobz** [comment]
That sounds more like an issue with the ROM. This is the first I've heard of this.
Can you test this ROM using an emulator?

**Comment by KH1501** [comment]
Ok i have confirmed that the ROM was the culprit. It is strange cause I dumped it from my personal coppy but ok

**Comment by KH1501** [comment]
Ok i have confirmed that the ROM was the culprit. It is strange cause I dumped it from my personal coppy but ok
