### ISSUE TITLE
Some games (Clean Roms) not working correctly (v20.3.0)

### ISSUE THREAD

**Issue by MrRojano97** [DS-Homebrew/nds-bootstrap#1172]
**Console Configuration:** Nintendo DSi with hiyaCFW
**TWiLight Menu++ Version:** v20.3.0
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

The games should work correctly.

### Actual behaviour
(For the games I tested)
* White screen at launch on Mario vs Donkey Kong Mini Land Mayhem (DSi Mode) using Clean Rom.
* Mario & Luigi Bowser's Inside Story (Clean Rom): Black screen when load a savegame.

### Steps to reproduce

1. Make a clean installation of TWLightMenu++ 20.3.0
2. Launch the titles mentioned previously

**Comment by RocketRobz** [comment]
1. Mini-Land Mayhem on DSi needs to be either manually AP-patched, or run in DS mode, as the AP-fix isn't loaded due to lack of memory.
2. That issue happens sometimes. After launching the game and then waiting for it to boot, reboot the console with B held after launching TWLMenu++.
