### ISSUE TITLE
Multiplayer and sharing a content

### ISSUE THREAD

**Issue by arturo2711** [DS-Homebrew/nds-bootstrap#1173]
Add the option to play multiplayer with two DSi by games or DS Download Play Nintendo and the option to share content from a DSi to another DSi by wireless communications

**Comment by RocketRobz** [comment]
1. For DS Download Play to work, a fix for Cloneboot needs to be implemented to nds-bootstrap.
2. There is no way of sharing any content via homebrew apps.
