### ISSUE TITLE
Multiplayer of Mario kart ds

### ISSUE THREAD

**Issue by ferzen256** [DS-Homebrew/nds-bootstrap#1174]
**Console Configuration:**  Dsi XL Mario 25th anniversary edition, no unlaunch or hiya CFW
**TWiLight Menu++ Version:**  v20.3.0 (currently the lastest versión)
**TWiLight Menu++ Theme:**  Nintendo 3DS theme

### Expect behaviour

 Enter Mario kart DS (and MKDS romhacks) multiplayer, local and online

### Actual behaviour

 local multiplayer freezes everytime You enter and online softlocks in the loading screen with the connections bar always at 0 when You try to connect or test your connection

### Steps to reproduce

1. Enter Mario kart DS (or the rom hacks, both vanilla and mods suffer the same thing).
2. Enter multiplayer menu
3. (Online) Enter nintendo wifi connection menu.
4. Try to connect online (using wimmfi).
5. (Also online related) Enter the wifi settings and try to test your connection.

I research and i find out that You already discused and solve this problem, but here is the thing: if i go to an older version like v20.2.0, the Game runs romhacks and vanilla multiplayer perfectly without crashes, connecting to wimmfi or testing connection or making a local lobby. If You ask me how i found it, i simply try to see if multiplayer in CTGP worked, and it crashed. I tried other rom hacks and a vanilla mario kart rom and also crashed. Now, everything works fine with the 20.2.0 version, and i hope that for future releases this gets fixed.

**Comment by spellboundtriangle** [comment]
This still occurs for me launching from Memory Pit, nds-bootstrap version cdceae1

**Comment by RocketRobz** [comment]
It's fixed for me on my side. Are you sure you're using that nightly version?
idk why it would still happen. Might want to see if it works without Memory Pit as well, in that case.

**Comment by spellboundtriangle** [comment]
I'm sure, I checked using the in-game menu as well as TWiLight Menu++ settings.
And yeah, it's working fine with TWiLight Menu++ (fb87f7b) booted via Unlaunch.

**Comment by spellboundtriangle** [comment]
Still occurs with TWiLight Menu++ f26974f, nds-bootstrap cc367dc

**Comment by spellboundtriangle** [comment]
I can also reproduce this by opening TWiLight Menu++ from Unlaunch, starting the game, exiting to TWiLight Menu++ using the button combo or in-game menu, then starting the game again and entering multiplayer

**Comment by RocketRobz** [comment]
I see the issue now. It seems only the freezing issue in the WiFi menu is fixed.

**Comment by spellboundtriangle** [comment]
I'm still getting it in e215392

**Comment by RocketRobz** [comment]
> I'm still getting it in [e215392](https://github.com/DS-Homebrew/nds-bootstrap/commit/e21539260c2afe2fa1c24756cbe9d21db7960ed9)

Which options are you selecting in MKDS, exactly?

**Comment by RocketRobz** [comment]
The crash occurs if `WiFi` is turned off in TWLMenu++ Settings, so the crashing is unrelated to this issue now.

**Comment by ferzen256** [comment]
Right, i forget to mention it, i was using the "release" bootstrap in both versions (v20.2.0 and v20.3.0, You already know who worked and who didn't)

**Comment by ferzen256** [comment]
And it didn't matter if i had Wifi turned on or off
