### ISSUE TITLE
game freezing in gts

### ISSUE THREAD

**Issue by paf2014** [DS-Homebrew/nds-bootstrap#1175]
In last update, pokemon black2 game is freezing anytime I try to trade pokemon in a alternative gts server, is something like a bug while selecting the trade partner in screen or send the pkm to it like in the picture in attchment.please tray to fix this,thanks for something
![bug](https://user-images.githubusercontent.com/46760859/120878596-f5d25a00-c593-11eb-872a-fd78ed2c1873.png)

**Comment by RocketRobz** [comment]
Is the game running in DS mode or DSi mode?

**Comment by paf2014** [comment]
dsi mode

**Comment by RocketRobz** [comment]
Then it's probably something I can't fix then.

**Comment by paf2014** [comment]
But this bug has never been in twlightmenu++

Em sáb, 5 de jun de 2021 00:39, RocketRobz ***@***.***>
escreveu:

**Comment by RocketRobz** [comment]
So it works fine on cartridge then?

**Comment by paf2014** [comment]
I"ll test in my pokemon withe2 and tell you

Em sáb, 5 de jun de 2021 01:38, RocketRobz ***@***.***>
escreveu:

**Comment by paf2014** [comment]
Yes.It works fine in my white 2 cartridge.
bug confirmed.the game frizzes in gts in pokemon black and white 2.
after freezing when I reopen twlight menu ++ pokemon black icon appeared the way as in attachment, this can be a hint.
And in pokemon white 2 my boxes were the way as in attchment.this is what I can inform about this bug that is from the last update because twilght menu++ was worked fine with the games I play.
![20210605_141419](https://user-images.githubusercontent.com/46760859/120909610-114d6b80-c64d-11eb-96d5-0c04c31fb006.jpg)
![20210605_143056](https://user-images.githubusercontent.com/46760859/120909617-1b6f6a00-c64d-11eb-909e-3fa4428cbae7.jpg)

**Comment by RocketRobz** [comment]
The issue in photo 1 is a TWLMenu++ issue, not an nds-bootstrap issue.
As for photo 2, it seems to be related to card read DMA being turned off. Try turning it on in TWLMenu++ Settings.

**Comment by paf2014** [comment]
Ok, But the bug continues and is from last update.I cannot trade in gts in
black/white 2.the game freezes.

Em sáb, 5 de jun de 2021 22:36, RocketRobz ***@***.***>
escreveu:

**Comment by paf2014** [comment]
Frezes while send a pokemon to somedoby in gts or before when choosing the
pokemon that us going to be sent

Em dom, 6 de jun de 2021 15:36, Antonio Freitas ***@***.***>
escreveu:

**Comment by paf2014** [comment]
Bug is solved turning DMA  on in TWLMenu++ Settings.now I got this error.Where could I find the dsi binaries?where should I put them?or pkm black/white 2 just run on ds mode?thanks for all.
![erro](https://user-images.githubusercontent.com/46760859/121288715-2844c580-c8ba-11eb-9d98-8730fc690115.png)

**Comment by RocketRobz** [comment]
Get a clean dump of the ROM, as the message states.
You can do so by using GodMode9 to dump the ROM.
