### ISSUE TITLE
All LEGO games aren't working entirely or partially (flickering, black screen, touch broken)

### ISSUE THREAD

**Issue by Berny23** [DS-Homebrew/nds-bootstrap#1176]
**Your console:** DSi XL (memory pit with Unlaunch), 3DS & New 3DS XL (Seedminer with Luma3DS)
**Launch Method:** SD card, official retail flashcard via Twilight Menu++ v20.3.0
**Version used:** release, v0.41.0
**Game tested/used/applicable:**

- Official retail flashcard of Lego Batman 1
- Lego Batman 1 rom: 1F79CBFE29BC487279D6AA19107855F7
- Lego Harry Potter 1-4 rom: 0ACB799E11436683EA82BC41987759C1
- Lego Star Wars III rom: 01791EFD85C61F679CDC9865CFE0A843

**Expected Behavior:** Game should play the opening titles and cinematic on both screens simultaneously, touchscreen should work, selecting "exit game" in-game should get you back to the title screen/opening, games should be playable.
**Actual Behavior:** The content of the upper and lower screens are flickering constantly and randomly switching screens during the opening and in the title screen (creating messed up/wrong colors when logos overlap), upper screen is unresponsive (updating very slowly in certain Lego games), "exit game" option just produces a black screen with no sound. Some Lego games I've tested (like Lego Harry Potter 1-4 and Lego Star Wars III) don't even get to the title screen, but show a black screen instead. Sometimes, sound is completely missing (randomly AFAIK). I'm sure it has something to do with the engine every Lego game is using because the problems are the same.

### Steps to reproduce

1. Start any(?) Lego game from flashcard or sd card
2. You'll see it immediately in the opening titles or when trying to use the touch screen

### Logs

[nds-bootstrap.ini](https://github.com/DS-Homebrew/nds-bootstrap/files/6602575/nds-bootstrap.txt)

Log for Lego Batman 1 running from official cartridge:

```
findModuleParamsOffset:
Module params offset found: 02000BA4
sdk_version: 05057531
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 02146F00

startOffset : 02000000

findCardReadEndOffsetThumb5Type1:
ARM9 Card read end SDK 5 thumb (type 1) not found

findCardReadEndOffsetThumb5Type0:
ARM9 Card read end SDK 5 thumb alt 1 (type 0) not found

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:
ARM9 Card read end (type 0) short found: 02140F3C

findCardReadStartOffsetThumb5Type0:
ARM9 Card read start SDK 5 thumb (type 0) not found

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffset5:
ARM9 Card read start SDK 5 found

cardRead location : 02140E2C
023F4000

findSwi12Offset:
swi 0x12 call found

swi12 location : 020004BA

findCardPullOutOffset:
Card pull out handler SDK 5 not found
Card pull out handler SDK 5 alt found

cardPullOut location : 021413D4

findCardIdEndOffset:
Card ID end SDK 5 found: 02140D08

findCardIdStartOffset:
Card ID start SDK 5 not found
Card ID start SDK 5 alt 1 not found
Card ID start alt 1 found

cardId location : 02140C8C

findCardReadDmaEndOffset:
Card read DMA end found: 02141140

findCardReadDmaStartOffset:
Card read DMA start SDK 5 found

cardReadDma location : 02141094

findRandomPatchOffset:
Random patch not found

findRandomPatchOffset5Second:
Random patch SDK 5 second not found

findMpuStartOffset:
Mpu init found: 02000A9C

findMpuDataOffset:
Mpu data found: 02000B34

findMpuInitCacheOffset:
Mpu init cache not found

patchMpuSize: 00000000

Mpu init: 02148BF8

findResetOffset
Reset not found

ERR_NONE

findSleepPatchOffset:
Sleep patch found: 0238BB00

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 02384060

findCardCheckPullOutOffset:
Card check pull out not found

Relocation src: 023802E4

Arm7 (patch v5)
JumpTableFunc: 0238ECEC
card read:	0238ECD4
Eeprom read:	0238ECF8
Eeprom page write:	0238ED10
Eeprom page prog:	0238ED28
Eeprom verify:	0238ED40
Eeprom page erase:	0238ED54
findSwiHaltOffset:
swiHalt call found

swiHalt location : 02380664

findSwi12Offset:
swi 0x12 call found

findSwiGetPitchTableOffset:
swiGetPitchTable call SDK 5 found

swi12 location : 02383600

swiGetPitchTable location : 02383614

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FED0

ERR_NONE
handlerStartSig
0216D0E8
handlerEndSig
0216D128
tableAddr
027E0004
returnAddr
01FF81C0
hookLocation arm9: 027E0004

chipID: 80007FC2
```

### Other notes

Running Lego Batman 1 from official flashcard without Twilight Menu++ is working fine.

**Comment by spellboundtriangle** [comment]
Try setting ARM9 CPU Speed to 67mhz (NTR)

**Comment by Berny23** [comment]
I tried it but it didn't change anything.

**Comment by Berny23** [comment]
I made a video showcasing the issue: https://www.youtube.com/watch?v=yx0Hklp5agA

**Comment by AbnormalPoof** [comment]
Try turning off heap shrink

**Comment by RocketRobz** [comment]
> Try turning off heap shrink

That feature has been removed for a while.

Turning off asynch card read fixes the black screen crashes.
The flickering is a bug in the game itself.
