### ISSUE TITLE
FrodoDS boots on 3DS/DSi/NDS?

### ISSUE THREAD

**Issue by qamichele59** [DS-Homebrew/nds-bootstrap#1177]
**Your console:** Nintendo DSi
**Launch Method:** SD card
**Version used:** v0.41.0
**Game tested/used/applicable:** 

**Expected Behavior:** DLDI shows my ROMS folder??? hmmm well uns some C64 games at FPS.
**Actual Behavior:** Good C64 Emulator for DS

### Steps to reproduce

Port of Frodo for DS by GPF

### Logs

sd:/NDSBTSRP.LOG

### Other notes

Works

**Comment by RocketRobz** [comment]
Please post compatibility reports here: https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0
