### ISSUE TITLE
EU-release of Solatorobo crashes in DSi-mode after company logos

### ISSUE THREAD

**Issue by martravi** [DS-Homebrew/nds-bootstrap#1181]
**Your console:** European DSi 1.4.5E
**Launch Method:** From SD on a DSi with Hiya CFW and emuNAND
**Version used:** 0.42.0 stable
**Game tested/used/applicable:** Solatorobo EU-release, full dump, MD5: 3D2519DB4636E753517A2E6388ECE7FC

**Expected Behavior:** Title screen should appear (no or newly created save file) or opening movie should play (with save file) after company logos
**Actual Behavior:** After company logos, the game crashes to a white screen; console can only be turned off by holding power button for 5 seconds. This also happens on a fresh install of everything with default settings

### Steps to reproduce

- Prepare a freshly formatted SD card with emuNAND and CFW files (I tested: 2GB SD with FAT16, cluster size 32k, or 32GB SDHC with FAT32, cluster size 32k)
- Extract current (0.42.0) TWiLightMenu-DSi.7z to SD
- Put full ROM image of Solatorobo into SD:\roms\nds
- Try to launch it via TWiLight Menu++
- Settings (default besides logging enabled, but also tried several other settings like enabling CPU boost, with the same result):
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/Solatorobo E.nds
SAV_PATH = sd:/roms/nds/saves/Solatorobo E.sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP EU Version.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6622120/NDSBTSRP.EU.Version.LOG)
[NDSBTSRP US Version.LOG, see other notes below](https://github.com/DS-Homebrew/nds-bootstrap/files/6622121/NDSBTSRP.US.Version.LOG)

### Other notes

US version (MD5: C2E65ED81623DD9B46E1F06804352ED6) works fine with identical settings at first boot (and is fully playable until turning off), but crashes at any later try, randomly either during or after logo slideshow. Also attached is a log of the US version crashing at the second boot.

Both, EU and US version, work fine after setting DS-mode.

**Comment by RocketRobz** [comment]
It seems the AP-patching takes place in the overlays, rather than the arm9 binary itself.
You'll need to manually AP-patch your ROM to properly run the game DSi mode.

**Comment by martravi** [comment]
Manually patched using the DS-Scene Rom Tool, but with no success. Same symptoms, same logs.

Does the AP patch provided by the tool and/or by nds-bootstrap even affect DSi-Mode?

**Comment by RocketRobz** [comment]
I don't see why it wouldn't.
I've tried the game on my 3DS without patching the ROM, and worked fine for me.

**Comment by martravi** [comment]
Same ROM files (patched and unpatched) do indeed work on my 3DS with identical settings. Also, the US ROM boots fine even on second boot. The issues seem to affect DSi only.

I also noticed some defective strings in the US version booting on my DSi in DSi-Mode (at the first time with no save file): In the photo mode, the texts describing the button mapping for taking a photo are only made up of "rrrrrrrrrrrrrrrrrrrrrrrr" (going over the text boxes up to the end of the screen). This also does not happen on the 3DS with the identical ROM.
![rrrrrrrrrrrrr](https://user-images.githubusercontent.com/54960634/121472039-eb172b00-c9c0-11eb-9164-e232a48db710.jpg)
