### ISSUE TITLE
PokeyDS without errors/crashes on DSi?

### ISSUE THREAD

**Issue by qamichele59** [DS-Homebrew/nds-bootstrap#1183]
**Your console:** DSi
**Launch Method:** SD Card
**Version used:** 0.42.0
**Game tested/used/applicable:** Tested

**Expected Behavior:** Gold flawlessly games
**Actual Behavior:** used XEGS-DS/PokeyDS

### Steps to reproduce

Works good

### Logs

Tested by qamic59

### Other notes
An atari 800 emulator ported from atari800 for ds by alekmaul

**Comment by RocketRobz** [comment]
This is not the place for questions.
If you want to post your compatibility report, please do it here: https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0
