### ISSUE TITLE
Super Mario 256 Doesn't Save

### ISSUE THREAD

**Issue by ChainSwordCS** [DS-Homebrew/nds-bootstrap#1186]
**Your console:** New 3DS XL
**Launch Method:** SD Card, Luma3DS CFW
**Version used:** Nightly 6cac78f6
**Game tested/used/applicable:** Super Mario 256 v0.1.4 [http://kuribo64.net/board/thread.php?id=3119](http://kuribo64.net/board/thread.php?id=3119)

**Expected Behavior:** After saving the game, the file is saved properly and can be selected from the title screen.
**Actual Behavior:** The game appears to not save at all, even with Bookworm set to Donor ROM (this is an SDK5 game).

### Log

Note because this is kinda large: I booted the game, selected File 1, entered Course 1, collected Star 1, and chose "Save and Quit"

[NDSBTSRP.LOG.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6653539/NDSBTSRP.LOG.txt)

### Other Notes

Saving for this game may have worked before, but I am absolutely not sure. I only played it in the past few days, but I skimmed the entire forum thread where some people used TWiLightMenu to play it.

**Comment by RocketRobz** [comment]
Try turning off `Expand ROM space in RAM`.
If you never used TWiLight Menu++ though, then open `sd:/_nds/nds-bootstrap.ini`, and set `EXTENDED_MEMORY` to `0.

**Comment by ChainSwordCS** [comment]
Are there any other baseline settings I should try, or does it not matter a ton? For the sake of consistency I'm sticking with DS mode, 133mhz, VRAM Boost, and Card read DMA. (Some sounds like to break in DSi Mode, everything else makes no noticeable difference.)

And here's the second log:

[NDSBTSRP.LOG.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6660646/NDSBTSRP.LOG.txt)

**Comment by RocketRobz** [comment]
Try the default settings (e.g. 67mhz, no VRAM boost, etc.).
Also, do other games save?

**Comment by ChainSwordCS** [comment]
Other games do save. I use TWiLightMenu a lot.

Switching to default settings... Card Read DMA on or off?

**Comment by RocketRobz** [comment]
> Switching to default settings... Card Read DMA on or off?

On.

**Comment by ChainSwordCS** [comment]
Still no dice.

[NDSBTSRP.LOG.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/6660726/NDSBTSRP.LOG.txt)

**Comment by RocketRobz** [comment]
The log makes no difference, since the save functions are already patched.
Have you tried reformatting the SD card to FAT32 with 32kb cluster size?

**Comment by ChainSwordCS** [comment]
Is there a way to see the cluster size? I'm on Windows 10 by the way. I don't really have the available storage space to reformat at the moment

**Comment by RocketRobz** [comment]
Create a new .txt file on the SD card, and in the file, type in any text character, and then save.
Right-click on the file, and then click `Properties`, and check the `Size on disk`.

**Comment by ChainSwordCS** [comment]
Size on disk: 32,768 bytes

**Comment by RocketRobz** [comment]
Your cluster size is 32kb.

**Comment by ChainSwordCS** [comment]
Update. I have to check again, but I think the issue still exists in latest release.

But! What I overlooked was that the issue is with generating the save file. When I took a regular Super Mario 64 DS save file and copied it, Super Mario 256 is able to save.

**Comment by Kaisaan** [comment]
Issue still happens. Using my N3DS XL on Luma3DS 10.2.1 with TWiLight Menu++ version 24.1.0, and nds-bootstrap 0.54.1. No save file is being created, it seems. I think this is due to this ROM hack being edited with SDK tools, modifying it enough for nds-bootstrap to not recognize it as a Super Mario 64 DS ROM Hack. The SDK version has been upgraded to version 5.4, its TID has been changed to NTRJ and its region to JPN.
