### ISSUE TITLE
Feel the magic not working 

### ISSUE THREAD

**Issue by Iamallama1234** [DS-Homebrew/nds-bootstrap#1188]
**Your console:**  Nintendo Dsi XL
**Launch Method:**  launched via unlocked sd card using Memory Pit
**Version used:**  Release Version20.4.1
**Game tested/used/applicable:** Feel the Magic XY/XX

**Expected Behavior:**  after starting the game I should be taken to the title screen of game I am playing
**Actual Behavior:**  after starting the game the bootstrap logo appears, then a black screen flickers a few times then freezes

### Steps to reproduce

 start any version of feel the magic and this will happen

### Other notes
I have tried using multiple different files found online, none work

**Comment by RocketRobz** [comment]
Try changing the card read DMA setting in the per-game settings menu of TWLMenu++ (opened by pressing Y in the ROM menu).

**Comment by RocketRobz** [comment]
Yup, turning it off fixed it.
