### ISSUE TITLE
Megaman Battle Network 5 Double Team

### ISSUE THREAD

**Issue by deathwatch72** [DS-Homebrew/nds-bootstrap#1191]
**Your console:** <3DSXL>
**Launch Method:** <!SD>
**Version used:** <Release and Nightly>
**Game tested/used/applicable:** <Megaman Battle Network 5 Double Team>

**Expected Behavior:** <!Emotion window in battle does not flicker>
**Actual Behavior:** <!Emotion window in battle flickers now>

### Steps to reproduce

<Happens in both DS and DSi modes, VRAM doesnt effect it either>

### Other notes
Worked fine when I played a few days ago, issue just appeared.

**Comment by RocketRobz** [comment]
Have you tried changing the ARM9 CPU Speed option?

**Comment by deathwatch72** [comment]
Yes, both NTR and TWL produce identical results. 

My settings didn't change overnight( pretty sure) and everything was working perfect before with DS mode, 133 mhz, VRAM boost on. DSi mode used to produce some flickering during the intro splash but that no longer seems to happen.

**Comment by RocketRobz** [comment]
What version of nds-bootstrap are you using?
If you don't know, check TWLMenu++ Settings.

**Comment by deathwatch72** [comment]
.42.0

I tried reverting to a different version i had on my computer from the initial install but the same issue happens so maybe I was incorrect about it working before but I was fairy sure.

Everything began when I accidently installed NDS bootstrap again while already having TwiLight installed( big accident), maybe thats what broke something. If i could strip out all the TWL and NDS stuff and start from scratch Id consider that too

**Comment by deathwatch72** [comment]
It seems like the press start screen has a slight flickering that I never noticed too, could be related

**Comment by RocketRobz** [comment]
> It seems like the press start screen has a slight flickering that I never noticed too, could be related

That's the first time I've heard of this.
Never noticed it on my side.

Have you tried turning off card read DMA?

**Comment by deathwatch72** [comment]
Start menu flicker was unrelated, it was a power saving on lowest brightness being a problem, nothing on your end I was just being paranoid lmao.

card read DMA is off and so is the Asynch card read

**Comment by deathwatch72** [comment]
Its also just the emotion window of megaman, if another character is swapped to the flicker goes away until megaman is back. Inputs seem to also occassionly break and I can only move between corners while battling

**Comment by Stack3r** [comment]
Stupid question, but are you sure Megaman isn’t being affected by bugs from the NaviCust. The flashing emotion window and strange battle movement patterns sounds exactly like a bug from having too many parts installed

**Comment by deathwatch72** [comment]
Oh dear god, I'm just an actual idiot. This is what happens when I don't sleep I guess, and would also explain alot. Totally just wasted a ton of your time because I failed basic logic, thanks for being patient and awesome and making so many awesome tools and programs. I'm going to go pretend I didn't just embarrass myself and go hide somewhere dark
