### ISSUE TITLE
The Last Window, Black Screen At Launch

### ISSUE THREAD

**Issue by mattcm747** [DS-Homebrew/nds-bootstrap#1193]
**Your console:** Nintendo 3DS (O3DS)
**Launch Method:** TwilightMenu++, MicroSD card with Adapter, latest Luma version and I used Universal Updater to download TwilightMenu. The SD card (32GB) was formatted with guiformat with FAT32, 32k cluster size.
**Version used:** TwilightMenu++ stable release v20.4.1
**Game tested/used/applicable:** 5214 - The Last Windows: The Secret Of Cape West, TID:YLUP, European Version, SDK VER 4, if that's important.

**Expected Behavior:** The game should have launched showing the logo of the game, instead when launched it only shows a black screen.
**Actual Behavior:** The game starts with a black screen, and that's all.

### Steps to reproduce

To reproduce the steps you simply have to launch the game in the TwilightMenu++ bar, I tried different versions of the game on other consoles such as a DSi, and it launched, but with frequent black screens between transistions and loadings. 

### Logs

findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027539
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 0207058C

startOffset : 02000000

cardRead location : 0207A618
023F0000

swi12 location : 020000FC

cardPullOut location : 0207AB80

cardId location : 0207A708

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0207A368

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0207A404

patchMpuSize: 00000000

Mpu2 init: 02071C7C

reset location : 02072560

ERR_NONE

cardIrqEnable location : 02383B0C

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238B5F0
Eeprom read:	0238B5FC
Eeprom page write:	0238B610
Eeprom page prog:	0238B624
Eeprom verify:	0238B638
Eeprom page erase:	0238B648
swiHalt location : 02380694

swi12 location : 0238BA30

swiGetPitchTable location : 02386FE8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F780

ERR_NONE
hookLocation arm9: 027E0004

AP-fix found and applied
chipID: 80007FC2

**Comment by DMeisei** [comment]
I got the same issue but with my dsi and I am using nds-bootstrap v0.43.2 and twilight menu ++ v21.0.2, with identical steps to reproduce.

**Comment by RocketRobz** [comment]
Have you tried turning off card read DMA?

**Comment by DMeisei** [comment]
I just tried turning off and on only **Card Read DMA** with **Asynch Card Read** off. Also tried with **Card Read DMA** on/off with **Asynch Card Read** on.
**VRam boost** is always off and with **DS mode**.
I waited about 10 seconds each launch but the same black screen still appear it seem.

**Comment by mattcm747** [comment]
Tried everything, the game just won't launch at all, I tried switching to nightly, and I also tried to force the game in DSi-mode, still black screen. It used to launch on my DSi a while ago, but with random crashes and black screens.

**Comment by RocketRobz** [comment]
Which version did it last work on?

**Comment by mattcm747** [comment]
I will just leave the version.txt from my DSi:
TWiLight Menu++: v19.1.1
nds-bootstrap: Release v0.38.0

RocketRobz, ahezard

**Comment by RocketRobz** [comment]
Can you try on the latest nightly of nds-bootstrap? Card read DMA should be kept off, if using the nightly.
https://github.com/TWLBot/Builds/commit/f45167299635ee4b9917d2e4a5be14cb1eb50d16

**Comment by mattcm747** [comment]
Sure, give me a few minutes and I'll let you know.

**Comment by mattcm747** [comment]
Nope, last nightly doesn't work, still black screen with Card Read DMA off.

**Comment by RocketRobz** [comment]
Does turning off asynch card read give the same result as wel?

**Comment by mattcm747** [comment]
I pressed Y on the game and I turned off ansych card read, and I also turned on nightly release, black screen again

**Comment by olivil** [comment]
Having the same issue on v21.1.1 with nds-bootstrap v0.44.2 on a DSi XL.
Turning off Card Read DMA and/or Asynch Card Read doesn't fix it.

**Comment by JORGETECH** [comment]
I just tested this game using TwilightMenu++ v21.2.0 and nds-bootstrap v0.45.0 (DSi XL) and it does launch for me, but "Card Read DMA" needs to be disabled, I get a black screen when the video plays after starting a new game with DMA enabled.

The dump I'm using is already AP-patched though, that might make the difference.

**Comment by olivil** [comment]
Just tested with TwilightMenu++ v21.2.0/nds-bootstrap v0.45.0, same issue with my NoIntro rom. I then applied the SUXXORS crack to that ROM and it booted. It also prompted a TwilightMenu popup saying that the game contains anti-piracy and that I should make sure to have the latest Twilight version. This popup was not triggered by my NoIntro rom so maybe it simply does not apply the AP patch to the original clean rom?

**Comment by mattcm747** [comment]
I think the definitive fix is to patch the rom with the SUXXORS patch before launching it, I'm already at the PC so I'm gonna try and post results soon, if it works I'm gonna try to close the thread with a solved flag.

**Comment by mattcm747** [comment]
Tried the method with SUXXORS, the game boots but after the first video intro the game blackscreens, I'm gonna try a different rom dump.

**Comment by mattcm747** [comment]
Tried manually AP patching the game, not launching, if it boots, it stops at the first intro with a blackscreen sadly.

**Comment by mattcm747** [comment]
Problem solved, read the last comment.

**Comment by RocketRobz** [comment]
Can you please post a link to the patch? I can't find a working link anywhere.

**Comment by mattcm747** [comment]
you can find the crack at https://www.mediafire.com/file/7ow28816ro3qi9f/LWTSoCWECNS.rar/file, you have to patch it manually tho (you need a dump of the original game)
