### ISSUE TITLE
DScraft compability

### ISSUE THREAD

**Issue by GriShafir** [DS-Homebrew/nds-bootstrap#1194]
**Your console:**  Nintendo DS Lite
**Launch Method:**  R4 SDHC Gold Pro
**Version used:**  Release
**Game tested/used/applicable:**  [DScraft](https://dscraft.github.io/) (fat)

**Expected Behavior:**  Game starts without crashes
**Actual Behavior:**  "Guru Meditation Error: Data Abort!"

### Steps to reproduce
1. Download DScraft (fat) from [website](https://dscraft.github.io);
2. Start game;
3. Done!

**Comment by RocketRobz** [comment]
1. This is not an nds-bootstrap issue, as it does not run homebrew from flashcards.
2. I suggest trying the Nitro version instead of the FAT version. The Nitro version works on my side.
3. Make sure that in the per-game settings menu of TWLMenu++, `Direct Boot` is turned `On`.
