### ISSUE TITLE
Pokémon Platinum hangs while saving "A lot of data"

### ISSUE THREAD

**Issue by Radriant** [DS-Homebrew/nds-bootstrap#1198]
**Your console:** 2DSXL

**Launch Method:** SD card, SCFG off
 
**Version used:** 
working until commit 1fd65ca, starting commit 24d6008 the saving breaks.

**Game tested/used/applicable:** 
Pokémon Platinum version CPUE
MD5: C779CA1023D943D06F71975257626186

**Expected Behavior:** 
Be able to save without any problem.

**Actual Behavior:**
When saving as the game calls it "A lot of data" the game hangs, the sound is stuck on the last note played and the saving icon keeps rotating(tested up to 10 min).

### Steps to reproduce
Open the ["Saving a lot of data"](https://drive.google.com/file/d/1SNMFk9Jg1SZ11U2JRqfkmyupuMKSqcAX/view?usp=sharing) save file with a USA version of Pokémon platinum, load the game with commit 24d6008 or later and attempt to save.

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6730318/NDSBTSRP.LOG)

### Other notes
1.-Doing a normal save(i.e. saving again after a successful save) works as intended, only when the game is saving a lot of data the problem arise.
2.-Tested with all combinations of Asynch/DMA Card Read on the 0.43.0 release without any changes.
3.-Tried to replicate the problem with Pokémon Diamond and Pokémon SoulSilver and was not able to do it.
4.-Was not able to test commit 8d03d3a as the game boots in a white screen.

**Comment by RocketRobz** [comment]
This seems to be linked to #1197 
Apparently, saving is broken.
