### ISSUE TITLE
GTA Chinatown Wars not saving

### ISSUE THREAD

**Issue by Yashirow** [DS-Homebrew/nds-bootstrap#1199]
**Your console:** O3DS XL
**Launch Method:** SD CARD, Luma3DS
**Version used:** 0.43.1 release or beta (both don't work)
**Game tested/used/applicable:** GTA Chinatown Wars EU (TID : YGXE)

**Expected Behavior:** The game saves correctly.
**Actual Behavior:** Well, the game seems to save but after playing a bit the save is deleted. So if you save then exit the game, the save is totally deleted.

### Steps to reproduce

Just launch the game, save, play a bit, re-save then exit the game.
[nds-bootstrap.ini](https://github.com/DS-Homebrew/nds-bootstrap/files/6735144/nds-bootstrap.txt)

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6735192/NDSBTSRP.LOG)

### Other notes

It was working correctly until the 0.43.0 and 0.43.1 (I didn't used the 0.43.0 tho)

**Comment by RocketRobz** [comment]
I see no reason why v0.43.1 wouldn't fix this.
Try turning off asynch card read.

**Comment by RocketRobz** [comment]
Just tried saving on my side, and after restarting, it loaded fine for me.
