### ISSUE TITLE
Animal Crossing: Wild World is no longer working

### ISSUE THREAD

**Issue by daviiid99** [DS-Homebrew/nds-bootstrap#1201]
**Your console:**  Nintendo DSi XL
**Launch Method:** TwilightMenu++
**Version used:** TwilightMenu++ stable release v21.0.2
**Game tested/used/applicable:**  Animal Crossing: Wild World, PAL version, SDK3

**Expected Behavior:**  The game should start
**Actual Behavior:** After Launching the game from Twilightmenu++, the nds-bootstrap screen will appear and after that an infinite white screen

### Steps to reproduce

 Play Animal Crossing Wild World with the latest Twiligthmenu++ and nds-bootstrap version. The game is working in older versions so I think it's a regression

**Comment by RocketRobz** [comment]
Turn off `Asynch Card Read` to get the game to start.

**Comment by scruffy-cat** [comment]
can you get a rom or nds file for animal crossing wild world and install it if you don't have the cartridge?

**Comment by spellboundtriangle** [comment]
> can you get a rom or nds file for animal crossing wild world and install it if you don't have the cartridge? if so, how?

That would be illegal
