### ISSUE TITLE
sav file reset

### ISSUE THREAD

**Issue by nkwem** [DS-Homebrew/nds-bootstrap#1202]
for the new update that came out it seems to reset sav files when a game is booted. i think its a random bug but ive also heard the same things happening from friends so i think its the new update.

**Comment by nkwem** [comment]
I didnt back it up so lost the sav but luckily it was the only game i opened and since its a fighting game (mk3) with no story it doesn't really matter but if it was smt:ds probably would've cracked right there. I also downgraded to ver20.0.0

**Comment by spellboundtriangle** [comment]
Has this happened to anyone recently?

**Comment by Epicpkmn11** [comment]
I haven't heard of this happening recently so closing.
