### ISSUE TITLE
issues with snes and gen games

### ISSUE THREAD

**Issue by Alienthousiasm** [DS-Homebrew/nds-bootstrap#1203]
-->
Hello

im using DSi lite with v21.0.2 (hotfix) and nds-bootstrap v0.43.2
i have issues with snes game (axelay, secret of mana) and genesis game (musha aleste, street of rage, etc)
SNES games i changed the extension to .snes because the original .smc when launched told me to use unlaunched to work it
Genesis games works ok but without any sound :(

Could you help me?

thank you for the all the work here

**Comment by RocketRobz** [comment]
You need to install Unlaunch.
