### ISSUE TITLE
Soulsilver Crash during Cutscene (works fine on DesMume with same .sav)

### ISSUE THREAD

**Issue by PR3D4TOR91** [DS-Homebrew/nds-bootstrap#1205]
**Your console:**  new3dsm latest luma, latest nds-bootstrap, latest twilight menu
**Launch Method:**  release
**Game tested/used/applicable:**  Pokemon SoulSilver

**Expected Behavior:**  cutscene play
**Actual Behavior:**  crash with texture glitch

### Steps to reproduce

Just play to the point where you encounter lugia -> Crash, everytime after it is supposed to come out of the waterfall during the cutscene, music plays on.

### Logs

Any ideas? Does not matter if i run in NTR, TWL, VRAM boost on/off, cheats on/off
Rom is AP patched

Works fine on DesMume with .sav

**Comment by RocketRobz** [comment]
Try with a clean ROM, as the ROMs are automatically AP-patched.
If you get the same result with the clean ROM, try turning off asynch card read.

**Comment by PR3D4TOR91** [comment]
I already played past it with DesMume, no .sav available any longer, but i will play other pokemon .nds games the next days and try. 
Problem is aswell: This is Sacred Gold/Storm Silver, a rom hack by Drayano that has AP patch included in his .xdelta patch. 
Never had any issues with it though.

**Comment by Ryper-maximoft** [comment]
diferent issu whit the spanish version, blackscreen but i cant find a fix or ap patch, i just heard a guy named rudolph created an old patch for fix the blackscreen issue but all links are dead, you canso find the usa version whit that patch instead

**Comment by Kaisaan** [comment]
With the newer versions of nds-bootstrap fixing crashes/freezes with Soulsilver (and the other Gen 4 Pokemon games), this issue should be fixed now. Closing.
