### ISSUE TITLE
3d background objects in castlevania portrait of ruin being displayed completely white

### ISSUE THREAD

**Issue by clyde254** [DS-Homebrew/nds-bootstrap#1206]
**Your console:**  new 2ds xl 
**Launch Method:**  micro sd card, i think the scfg is unlocked, i'm using lumacfw version 10.1.3.
**Version used:** release
**Game tested/used/applicable:**  castlevania: portrait of ruin 

**Expected Behavior:**  3d background objects like buildings or pyramids should have color and textures
**Actual Behavior:** 3d background objects do not have color

### Steps to reproduce

 walk into a room with a 3d object in it 

### Logs

don't know how to make the log show up

**Comment by RocketRobz** [comment]
The SCFG setting doesn't matter, if not running from a flashcard.

Try updating both TWLMenu++ and nds-bootstrap.
If you get the same issue after updating try disabling either asynch or DMA card read.
