### ISSUE TITLE
Gen 4 Pokémon games communication error in 3DS

### ISSUE THREAD

**Issue by drasvidiu** [DS-Homebrew/nds-bootstrap#1212]
![IMG_20210720_122028](https://user-images.githubusercontent.com/87717468/126365096-2f726b2a-5924-4743-b36b-62ff7c4ab706.jpg)

I start any Pokémon gen 4 game (Diamond, Pearl, Platinim, HeartGold and SoulSilver). The game appears to work fine, then i save progress, and when i reopen the game and press A in the intro, a blue screen shows up this communication error text.
My 3ds WiFi is always turned on and working fine. Also, all of the NDS i play work and save perfectly, including gen 5 Pokémon games.
Is there a configuration settings or archive i missed or didn't install? Please, someone help me

**Comment by RocketRobz** [comment]
That error should not even occur on 3DS consoles.
Did you use TWPatch?

**Comment by RocketRobz** [comment]
Tried reproducing with WiFi turned off, and I'm still not getting this issue.
The only thing happening as a result, is that a WiFi connection couldn't be found.

Your console probably has either a bad or missing DS or DSi WiFi card.
Try starting Pokemon Gen 5, and see if turning on C-Gear causes a communication error.

**Comment by drasvidiu** [comment]
Thanks for awnsering. I am trying to solve this problem since two weeks, but i think it might be something with my console.
How can i change my DSi wifi card?
Also, i saw a lot of people solving it by turning wifi led on in some settings. But i can't find those wifi settings. Can you please tell me where to enable it?

**Comment by RocketRobz** [comment]
> Thanks for awnsering. I am trying to solve this problem since two weeks, but i think it might be something with my console.
How can i change my DSi wifi card?

You need to know how to hardmod first.
If you already know how, there should be replacement parts on eBay.

> Also, i saw a lot of people solving it by turning wifi led on in some settings. But i can't find those wifi settings. Can you please tell me where to enable it?

It's only visible on DSi consoles.

**Comment by drasvidiu** [comment]
Playing the games in DSi mode or DSi mode (forced) would help in using my existing WPA 3DS connection while the game is running instead of a directly NDS connection?

**Comment by RocketRobz** [comment]
Nope. This error is not related to WiFi access points.
Also, setting DSi WiFi mode (done on our side) causes this issue as well.

**Comment by drasvidiu** [comment]
I deleted my .sav file and restarted, this time with the wireless key turnes off. I saved the game and returned, but nothing changed.
I tried to connect to WFC in Pokémon Black Mystery Gift (since i didn't have time to obtain C-gear) and it only started searching for a connection point forever (maybe because i don't have ani DSi wfc)

**Comment by drasvidiu** [comment]
And why did you ask me if i TWPatched in the beggining of the thread? I don't know if i did it.
Is there any other problem that could envolve this error message instead of the WiFi Card?

**Comment by RocketRobz** [comment]
An earlier version of TWPatch patched code related to the WiFi card, afaik.

**Comment by drasvidiu** [comment]
HEYY, i am back here to tell de epilogue of this saga. Man... It has been a nightmare for a month trying to solve this problem, BUT I SOLVED!!!
The problem, of course, was the WiFi Card. I just opened my 3DS, removed the WiFi Card and inserted again haha. I felt so happy when it worked... 
Thanks for the help! And if someone have this problem, try solving by this method. If removing and inserting do not work, try buying a new WiFi Card.
