### ISSUE TITLE
Weird grinding noise when playing Cooking mama 2

### ISSUE THREAD

**Issue by Iamallama1234** [DS-Homebrew/nds-bootstrap#1213]
It's pretty self explanatory. I've downloaded from multiple sites, same issue. Some steps require good sound, so can anyone help?

**Comment by RocketRobz** [comment]
Which versions of both TWLMenu++ and nds-bootstrap are you using, and are you using a DSi or 3DS?

**Comment by Iamallama1234** [comment]
Just downloaded the newest version of both bootstrap and the twilight menu, same issurSent from my T-Mobile 4G LTE Device
-------- Original message --------From: RocketRobz ***@***.***> Date: 7/21/21  1:10 PM  (GMT-06:00) To: DS-Homebrew/nds-bootstrap ***@***.***> Cc: Iamallama1234 ***@***.***>, Author ***@***.***> Subject: Re: [DS-Homebrew/nds-bootstrap] Weird grinding noise when playing Cooking mama 2 (#1213) 
Which versions of both TWLMenu++ and nds-bootstrap are you using, and are you using a DSi or 3DS?

**Comment by RocketRobz** [comment]
Sound issues should be fixed in later versions.
