### ISSUE TITLE
Touchscreen doesnt work

### ISSUE THREAD

**Issue by TheEclypsilMage** [DS-Homebrew/nds-bootstrap#1215]
Touchscreen works fine on the menu but after launching a game the Touchscreen doesnt work.

**Comment by RocketRobz** [comment]
Which games did you try?

**Comment by TheEclypsilMage** [comment]
I tried both heart gold and soul silver as well as the two zelda ds games,
spirit tracks and phantom hourglass. As well as some other lesser known
titles. And yet nothing seems to work. When I launch the twilight menu on
my 3ds the touch screen works fine. It's only when a game Is launched. I
tried ds mode, dsi mode, all the modes and guides available for fixes
related to the touchscreen but it doesn't work I've even tried download
different versions of the same rom like say from a different region or
whatever nothing seems to work. The touchscreen functions as it should for
all other aspects of the 3ds system.

**Comment by RocketRobz** [comment]
Try re-running the touch calibration in System Settings.

**Comment by TheEclypsilMage** [comment]
I did that didn't work

**Comment by TheEclypsilMage** [comment]
Even tried Uninstalling and reinstalled but didn't work also tried
installing by cia and by fbi didn't work

**Comment by RocketRobz** [comment]
Does the touch issue also happen in DS Download Play, when launched from the 3DS Download Play menu?

**Comment by TheEclypsilMage** [comment]
No. It works fine I've only had to use it a couple times but when I did it
worked fine. Only seems to not work when I launch a game through twilight
menu I even checked the settings withing twilight and all setting choices
don't work

**Comment by TheEclypsilMage** [comment]
This is not good as games like platinum which I also tried cant be started
unless you touch the pokeball at the start of the game.

**Comment by TheEclypsilMage** [comment]
? I'm assuming this is unheard of

**Comment by RocketRobz** [comment]
It is unknown what causes this issue.

**Comment by RocketRobz** [comment]
Closing, since this is a user-specific issue.
