### ISSUE TITLE
Random crashing in Lufia Curse of the Sinistrals Undub

### ISSUE THREAD

**Issue by LittleTale** [DS-Homebrew/nds-bootstrap#1216]
**Your console:** New 3DS XL
**Launch Method:** launched from SD card, latest firmware version, latest Twilight menu version as of today.
**Version used:** twilight menu ++ 21.2.1(hotfix)
**Game tested/used/applicable:** GAME: Lufia curse of the sinistral (UNDUB) MOD CRC32: CF3D9F2F, game comes from [REDACTED]

**Expected Behavior:** the game was launching fine with the previous version of Twilight I had installed (I don't remember which version it was, one from around 3 weeks ago) although the game use to randomly crash to black screen when moving from a scene to another (going ot of a house, new room, etc), needed to return to 3DS menu.
**Actual Behavior:** White screen at launch now, game won't run or start.

### Steps to reproduce

[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Lufia Curse of the Sinistrals.nds
SAV_PATH = sd:/roms/nds/saves/Lufia Curse of the Sinistrals.sav
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 0
CACHE_FAT_TABLE = 0
AP_FIX_PATH =
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
LOGGING = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 0
ASYNC_CARD_READ = 1

### Logs

(first I launched Final Fantasy CC just to check if everything was working fine with other games)

findModuleParamsOffset:
Module params offset restored: 02000BA4
sdk_version: 05037535
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

cardIrqEnable location : 0210F050

startOffset : 02000000

cardRead location : 021056D0
023F4000

swi12 location : 0200048A

cardPullOut location : 02105C78

cardId location : 02105530

sleep location : 0210FCE4

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0210588C

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0210591C

findMpuInitCacheOffset:
Mpu init cache not found

patchMpuSize: 00000000

Mpu init: 02110D50

reset location : 02111BD4

ERR_NONE

cardIrqEnable location : 023812D0

Error in relocation checking
03802870 038027B4vAddrOfRelocSrc
023803A0Relocation src: 023803A0

Arm7 (patch v5)
JumpTableFunc: 0238D25C
card id:	0238D244
card read:	0238D254
Eeprom read:	0238D268
Eeprom page write:	0238D280
Eeprom page prog:	0238D298
Eeprom verify:	0238D2B0
Eeprom page erase:	0238D2C4
swiHalt location : 02380724

swi12 location : 02380870

swiGetPitchTable location : 02380884

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238E964

ERR_NONE
hookLocation arm9: 027E00A0

chipID: 80003FC2

### Other notes

Tried to apply the same AP patch as the original US game to this rom, but DS-SCENE won't allow it.
don't know what to do anymore, please help.

THANKS A LOT IN ADVANCE !

**Comment by RocketRobz** [comment]
Try turning off asynch card read and/or card read DMA.

**Comment by LittleTale** [comment]
> Try turning off asynch card read and/or card read DMA.

Wow I can't believe I got an answer from the man itselft !! Thanks so much. It's seems to do the trick, game now launch and start without issue by turning off asynch card read.
But game still crash randomly when loading a new area or a new image, like a game over or a new voiced conversation with a PNG. Never at the same place, tried to replicate the crash and it seems to be random . . .

**Comment by Kaisaan** [comment]
Judging by the Other Notes, I think this an AP issue. Try AP-patching your ROM first before applying the undub patch (and be sure to disable checksum verification in whatever patcher you are using to avoid patching errors. Closing this since I assume that this is the case.

If the issue still occurs, check to see if this happens on the latest version of TWiLight Menu++ and nds-bootstrap along with checking if this happens on an original (unpatched) ROM as well.
