### ISSUE TITLE
Professor Layton and the Unwound Future Stuck after first Cutscene

### ISSUE THREAD

**Issue by couselm** [DS-Homebrew/nds-bootstrap#1217]
**Your console:** New 3DS XL
**Launch Method:** Internal SD Card
**Version used:** Bootstrap v0.45.0 TWiLight Menu++, Widescreen Enabled
**Game tested/used/applicable:** Professor Layton and the Unwound Future

**Expected Behavior:** Playable opening scene. 
**Actual Behavior:** Freezes after first intro cutscene.  Stuck on black screen after. 

### Other notes
Tried with US and EU rom. Same issues.

**Comment by AbnormalPoof** [comment]
try disabling asynch card read

**Comment by RocketRobz** [comment]
Hmm, it should already be turned off by default for that game.
Card read DMA is probably causing this then, so try turning that off.

**Comment by AbnormalPoof** [comment]
They're using release, not nightly. Release hasn't been updated accordingly

**Comment by RocketRobz** [comment]
The latest TWLMenu++ release already has the game in the asynch card read blacklist.

**Comment by DReaper** [comment]
If I am using a forwarder, what is the code to add in the nds-bootstrap.ini? Is it still CARD_READ_DMA = 0?

**Comment by RocketRobz** [comment]
The forwarders set that and `ASYNCH_CARD_READ` without manual editing.

**Comment by RocketRobz** [comment]
Closing due to no response, and assuming the issue is already fixed.
