### ISSUE TITLE
Error in the first start of a Pokémon game

### ISSUE THREAD

**Issue by RuneinA** [DS-Homebrew/nds-bootstrap#1227]
Your console: New 3DS XL
Launch Method: Internal SD Card
Version used: Bootstrap v0.45.0

Every time I start a pokemon game for the first time, it crashes.
It only happens the first time (when the ram dumps), the next times I start the game it does not happen again.
![IMG_20210801_023533](https://user-images.githubusercontent.com/60844000/127755604-f6102225-16c0-4532-84bc-00e21cb5cdda.jpg)

**Comment by lifehackerhansol** [comment]
Doesn't seem to crash as of v0.53.0.

Admittedly this is a little late of a reply, but I think it's working fine. So will close.
