### ISSUE TITLE
Not compatible with other NDS emulator's .sav file

### ISSUE THREAD

**Issue by RoiArthurB** [DS-Homebrew/nds-bootstrap#1228]
nds-bootstrap isn't compatible with saves created with other NDS emulator

**Your console:** DSi
**Launch Method:** TWL++
**Version used:** release
**Game tested/used/applicable:** Final Fantasy Tactics A2
**Expected Behavior:** Should use `.sav` file generated by DeSmuME/MelonDS
**Actual Behavior:** Doesn't

### Steps to reproduce

- Create a new game save file with DeSmuME or MelonDS (I did it with the [Lemuroid](https://github.com/Swordfish90/Lemuroid) android emulator wrapper, but I'm pretty sure it'll do with computer version too).
- Import it on the SD card inside the `saves` folder
- Launch the game

**Comment by RocketRobz** [comment]
The nds-bootstrap saves are no different from save dumps from cartridges.
For DeSmuME, you need to trim the footer off from the end of the save file using a hex editor.
As for melonDS, I don't know.

**Comment by Peter0x44** [comment]
MelonDS saves work without issues, there's no need to remove a header/footer

**Comment by RoiArthurB** [comment]
>  For DeSmuME, you need to trim the footer off from the end of the save file using a hex editor.

@RocketRobz Any resources to try that solution?

@Peter0x44 Maybe the use of quick save is causing some problems? :/

**Comment by RocketRobz** [comment]
> @RocketRobz Any resources to try that solution?

Yes. There's an application called HxD.
Using HxD, open the .sav file, and scroll down to the end.

**Comment by RoiArthurB** [comment]
The real question was more "What should I remove" more than "how" 😅😅😅

Here's the end of my file, what should be removed ? 🤷🤷🤷

![image](https://user-images.githubusercontent.com/16764085/127811154-e80d6958-1535-4d01-ad55-7ccbd85c66c1.png)

**Comment by RocketRobz** [comment]
Delete everything starting with `|<--Snip`

**Comment by RoiArthurB** [comment]
Thanks for all your help, it all worked (seems that I was using only DeSmuME 'cause I only had dsv files) and I've been able to move all my games from my phone to my new DSi ! 🥰🥰🥰

Thanks for your help and for this whole project ! 🤗

**Comment by Squall-Leonhart** [comment]
> For DeSmuME, you need to trim the footer off from the end of the save file using a hex editor.

you can export to raw from within desmume whilst the game is running.
