### ISSUE TITLE
star wars episode 3 revenge of the sith black screen used to work on previous  releases

### ISSUE THREAD

**Issue by songokuemumania** [DS-Homebrew/nds-bootstrap#1229]
**Your console:**  new 3DS xl 
**Launch Method:** micro SD card
**Version used:** I am using the latest version of twilight and bootstrap at the moment , bootsrap v0.45.0 and twilight v21.2.1 (hotfix) version. I have tried using regular boostrap and nightly 
**Game tested/used/applicable:** star wars episode 3 revenge of the sith

**Expected Behavior:** after the boostrap logo it should have loaded and start
**Actual Behavior:**after boostrap logo it only shows 2 black screens

### Steps to reproduce

just launch the game in any settings either DSi mode or regular DS mode and it never shows anything but black screens . I do recall the game working a long time ago with earlier versions of twilight

### Logs

sorry no logs at the moment, cant connect my 3DS to my computer to edit the file

**Comment by RocketRobz** [comment]
Have you tried turning off asynch card read?

**Comment by RocketRobz** [comment]
Turning off card read DMA fixed the black screen crash.

**Comment by songokuemumania** [comment]
you are the best Robz , thank you so much for such fast response .
