### ISSUE TITLE
Transformers War for Cybertron Crashing

### ISSUE THREAD

**Issue by SquadGuy1** [DS-Homebrew/nds-bootstrap#1237]
**Your console:** <New 3ds xl>
**Launch Method:** SD Card
**Version used:** <0.41.0>
**Game tested/used/applicable:** Transformers War for Cybertron Decepticons USA md5 e60de878beaabb8319d7d952fc390a4b

**Expected Behavior:** <The game should have kept running>
**Actual Behavior:** <When the game has to load into a new area and fades to black, it stays on that black screen and I have to restart the game and it loads the next part of the level after I load my save. It also crashes at the boss battle at the end of the first level.>

### Steps to reproduce

<Play the game normally. 
[nds-bootstrapini.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/6944387/nds-bootstrapini.zip)>

### Logs

<findModuleParamsOffset:
Module params offset restored: 02000BB8
sdk_version: 04027539
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 02007954

startOffset : 02000000

cardRead location : 02001B28
023F0000

swi12 location : 020003F4

cardPullOut location : 02002084

cardId location : 02001C18

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02001878

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 02001914

patchMpuSize: 00000000

Mpu2 init: 020092B4

ERR_NONE

cardIrqEnable location : 02383B40

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238BCC8
Eeprom read:	0238BCD4
Eeprom page write:	0238BCE8
Eeprom page prog:	0238BCFC
Eeprom verify:	0238BD10
Eeprom page erase:	0238BD20
swiHalt location : 023806C8

swi12 location : 0238C11C

swiGetPitchTable location : 02387678

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02390A4C

ERR_NONE
hookLocation arm9: 02FE0000

chipID: 80003FC2->

### Other notes
The same happened on the latest build.

**Comment by AbnormalPoof** [comment]
disable asynch card read

**Comment by SquadGuy1** [comment]
> disable asynch card read

Async card read always turns its self back on and I don't know how to stop it.

**Comment by RocketRobz** [comment]
> Async card read always turns its self back on and I don't know how to stop it.

If you changed the setting in TWLMenu++ Settings menu, make sure you're saving by pressing B to exit the settings menu.

**Comment by SquadGuy1** [comment]
I edit from the bootstrap.ini and it turns itself back on. I’ve even used TWLmenu++ to turn it off but it doesn’t help.

**Comment by RocketRobz** [comment]
Looking at the nds-bootstrap version you're using, you're on an outdated version.
Please update both TWLMenu++ and nds-bootstrap. After doing so, launch TWLMenu++ and immediately hold A+B+X+Y until you're asked to reset the settings.
If you still get crashes, then wait for a fix.

**Comment by SquadGuy1** [comment]
The game still crashes so I’ll wait for a fix.

**Comment by RocketRobz** [comment]
Crashes seem to be fixed by the recent MPU commits.
