### ISSUE TITLE
The Urbz: Sims in the City touch doesn't load but making it 98% unplayable

### ISSUE THREAD

**Issue by michele559** [DS-Homebrew/nds-bootstrap#1239]
**Your console:** 3DS SD Card
**Game tested/used/applicable:** USA

**Expected Behavior:** 
**Actual Behavior:** 

### Other notes

Touch seems to be empty but unplayable due to change the "blue" to "red" here your spreadsheets nds-bootstrap compatibility list here? 3ds worked when i tried it on DeSmuME on my PC.

**Comment by RocketRobz** [comment]
This only happens on previous nds-bootstrap versions, so please update nds-bootstrap to fix this issue.

**Comment by RocketRobz** [comment]
Duplicate of #935

**Comment by michele559** [comment]
Changes the "Red - Game is unplayable" Status to be compatibility

**Comment by RocketRobz** [comment]
Which nds-bootstrap version are you using?
Tell me the exact version you see in TWLMenu++ Settings.

**Comment by michele559** [comment]
> This only happens on previous nds-bootstrap versions, so please update nds-bootstrap to fix this issue.

Changes blue to red at be unplayable

**Comment by michele559** [comment]
Known to be problematic corrupted game. Changes the blue to red

**Comment by RocketRobz** [comment]
Please answer my question.

> Which nds-bootstrap version are you using?
Tell me the exact version you see in TWLMenu++ Settings

If you need help with something, just ask. :P

**Comment by michele559** [comment]
Modification of nds-bootstrap changes the The Urbz: Sims in the City USA compatibilty blue to red

**Comment by qamichele5959** [comment]
The Urbz: Sims in the City USA edits compatibility status color blue to red at be rocket robz nds bootstrap?

**Comment by RocketRobz** [comment]
> The Urbz: Sims in the City USA edits compatibility status color blue to red at be rocket robz nds bootstrap?

Please stop posting the same thing. I've already told you to update nds-bootstrap.
I can assure you that updating will fix this issue.

**Comment by qamichele5959** [comment]
> This only happens on previous nds-bootstrap versions, so please update nds-bootstrap to fix this issue.

Works tried it on DeSmuME on my Computer.

**Comment by qamichele5959** [comment]
Touch screen doesn't work on nds bootstrap but Touch screen works tried it Desmume on my PC but when you will make it sad now :(

**Comment by Squall-Leonhart** [comment]
Works fine on the current bootstrap, try deleting the offset and fat caches, otherwise there could be some device specific issue at hand.

**Comment by qamichele5959** [comment]
The Urbz: Sims in the City USA changes following category compatibility rating color:

|Red: Game is unplayable.|
|---|

**Comment by Squall-Leonhart** [comment]
compatibility list should be changed to Green, Works.

Tested on N3DS and O3DS.
