### ISSUE TITLE
Lunar knights usa screen turns white or empty after booting

### ISSUE THREAD

**Issue by qamichele5959** [DS-Homebrew/nds-bootstrap#1240]
**Your console:** DSi
**Launch Method:** SD
**Version used:** v0.46.0
**Game tested/used/applicable:** N/A

**Expected Behavior:** 
**Actual Behavior:** 

### Other notes

Screen that shapes or turns white after loading for a few minutes. Worked when tried it DeSmuME on my Computee.

**Comment by RocketRobz** [comment]
It's evident that you're not on v0.46.0. This also got fixed some versions ago.
Again, please update nds-bootstrap.

Re-installing both TWLMenu++ and nds-bootstrap can also fix this.

**Comment by qamichele5959** [comment]
0.46.x Empty screen
0.40.0 White screen

**Comment by RocketRobz** [comment]
Changing the version to 0.46.x makes no difference, as 0.46.0 is currently the latest version.
Also, you're not making much sense. What do you mean by `Empty screen`? Is it white or black?

> 0.46.x Empty screen

This is not the result I'm getting, as the game works on my side.
I suggest reformatting your SD card to FAT32 with 32kb cluster size, though it depends on which SD size you're using, so please tell us, if you want us to help you.

Also:
1. Please refrain from adding reactions to your own posts.
2. Please post a screenshot of your TWLMenu++ Settings menu.
