### ISSUE TITLE
Uncharted Waters IV No reaction

### ISSUE THREAD

**Issue by 3l2333** [DS-Homebrew/nds-bootstrap#1241]
Hello，ask for help.The upper screen is white, and the lower screen is black

**Comment by RocketRobz** [comment]
Which version of TWLMenu++ and nds-bootstrap are you using?

**Comment by 3l2333** [comment]
v21.3.0

**Comment by 3l2333** [comment]
TWiLight Menu++: v21.3.0
nds-bootstrap: Release v0.46.0

**Comment by RocketRobz** [comment]
Is it a homebrew game?

**Comment by 3l2333** [comment]
No, this is not homemade, it uses a Japanese version of rom

**Comment by RocketRobz** [comment]
I recommend turning off asynch card read in TWLMenu++ Settings.
Otherwise, turn it off in the per-game settings.

**Comment by 3l2333** [comment]
Ok, the problem has been solved, thank you very much, and may the force be with you：）
