### ISSUE TITLE
Visual stuttering around edges of screen

### ISSUE THREAD

**Issue by AFriendlyIrin** [DS-Homebrew/nds-bootstrap#1245]
**Your console:** 3DS XL (USA)
**Launch Method:** SD card via TwilightMenu
**Version used:** Release. v21.4.0 for TwilightMenu, v0.46.2 for nds-bootstrap
**Game tested/used/applicable:** Any, including the TwilightMenu visual interface itself

**Expected Behavior:** Normal display output
**Actual Behavior:** The top and bottom edges of each screen seem to glitch and display a "stutter". Instead of what is supposed to display, they duplicate a small strip of the image directly above or below.

### Steps to reproduce

I cannot reproduce this glitch consistently. Restarting TwilightMenu sometimes fixes it.

**Comment by SombrAbsol** [comment]
Hi

This graphic bug is very common. You just have to put the console in sleep mode and take it out.

**Comment by lifehackerhansol** [comment]
Known TWL_FIRM bug, this also happens with real cartridges.
