### ISSUE TITLE
DS ROM audio bug

### ISSUE THREAD

**Issue by Adriatendo3ds** [DS-Homebrew/nds-bootstrap#1246]
**Console Configuration: Old Nintendo 3DS with Luma3DS, System Firmware Ver. 11.15.0-47U**  
**TWiLight Menu++ Version: v21.3.0, Release v0.46.0, Nightly 2ea69cd5** 
**TWiLight Menu++ Theme: Nintedo DSi + pink skin** 

### Expected behaviour
New Super Mario Bros/ Super Mario 64 DS (My cartridges in .nds files) or any other rom file should have full audio. (Full audio unaffected in cartridge form)

### Actual behaviour
The audio (in SM64DS for example) only plays the drums followed by static and after selecting Adventure, the audio seems to play a note and then stop, this repeats with the loop.

### Steps to reproduce

1. Earlier last night I checked out the menu's hotkeys, tested it mid-game (NSMB)
2. While in the menu I switched the main screen to the bottom and saved
3. The audio soon became static and it started glitching, only the drums can be heard (NSMB + SM64DS, this happened on both game dumps but it also happened on Mario Kart DS as I recently checked)

**Comment by Squall-Leonhart** [comment]
Tested with O3DS and N3DS, no issues with audio on 

NTR-A2DE-USA
NTR-ASMP-EUR

might be sd card related.

**Comment by RocketRobz** [comment]
No issues on my side either.
I think it's safe to assume this is fixed.
