### ISSUE TITLE
Please help me to solve Twilight Menu ++ Black screen error.

### ISSUE THREAD

**Issue by StegoTop** [DS-Homebrew/nds-bootstrap#1248]
https://www.reddit.com/r/3dshacks/comments/p46l4o/please_help_me_to_solve_twilight_menu_black/

I tried all I can to solve this problem, including reinstall twilight menu.cia, installing TWLFIX, update the N2DS system.... etc. But Still the black screen says, "An error occured. Please turn off the power and follow the manual's guide."

How can I solve this?

Real NDS Game card(Maplestory DS) is well working.

But when I try to DS DOWNLOAD PLAY or Twilight Menu, this screen appears and system is frozen.

**Comment by Squall-Leonhart** [comment]
Use the issue template.
