### ISSUE TITLE
inazuma eleven undub is crashing

### ISSUE THREAD

**Issue by vxiiw** [DS-Homebrew/nds-bootstrap#1258]
im using the new 3ds xl with bootstrap updated, the game runs fine but it crashes everytime (black screen). im playing the undub version and i tried with the normal ver. and it still crashes. hope that you can fix it

**Comment by vxiiw** [comment]
version is v0.46.2 and im launching the game from sd card

**Comment by lifehackerhansol** [comment]
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/1179.
