### ISSUE TITLE
Mario & Luigi: Bowser's Inside Story crashes upon starting a battle

### ISSUE THREAD

**Issue by VinMannie** [DS-Homebrew/nds-bootstrap#1263]
**Your console:** Nintendo DSi
**Launch Method:** SD Card
**Version used:** nds-bootstrap Release v0.46.1
**Game tested/used/applicable:** Mario & Luigi: Bowser's Inside Story 

**Expected Behavior:** Starting a battle with the brothers works just fine.
**Actual Behavior:** The game hangs upon encountering the enemy. If jumped on from the top, the game just freezes. If ran into from the side, the battle animation will begin playing and then freeze while Mario is saying "Let's a go."

### Steps to reproduce
Start a battle or load into a new room. The game will freeze. 
```[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = 0
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 1
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/Mario & Luigi - Bowser's Inside Story (USA) (En,Fr,Es).nds
SAV_PATH = sd:/saves/Mario & Luigi - Bowser's Inside Story (USA) (En,Fr,Es).sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFixCheat.bin
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
APP_PATH = sd:/CAVE_S~1.NDS
PRV_PATH = sd:/SAVES/
GAME_SOFT_RESET = 1
```

### Logs

nds-bootstrap locked up on the "Please wait..." screen whenever I started the game with logging enabled.

### Other notes
This may have something to do with the anti piracy measures, but I'm not fully sure.

**Comment by RocketRobz** [comment]
Try re-formatting your SD card to FAT32 with 32kb cluster size.

**Comment by RocketRobz** [comment]
Closing due to no response, and no crashes on my side.
