### ISSUE TITLE
Animal Crossing: Wild World is not Working in B4DS

### ISSUE THREAD

**Issue by JHONA64** [DS-Homebrew/nds-bootstrap#1268]
Your console: DS
Launch Method: TWLMenu++ v21.4.0
Version used: All Releases from v0.35.1 down to v0.29.3
Game tested/used/applicable: Animal Crossing - Wild World (E)(Legacy)
Device used: FlashCard

**Expected Behavior:** <The game should continuing running>
**Actual Behavior:** <The game just says "Nintendo!" while shows the logo in a very slow way. After it, the game just don't start.>

### Steps to reproduce

<Just starts the game>

Other notes
When I select the game, it appears the message "This game is known to not run. If there's an nds-bootstrap version that fixes this, please ignore this message."

**Comment by lifehackerhansol** [comment]
Ended up testing this myself, it is still broken.

**Comment by RocketRobz** [comment]
Fixed as of 8294aa6b48e6ecc03d560cd3834a752df8f9909e
