### ISSUE TITLE
Arkanoid DS screens switching constantly. Not very playable.

### ISSUE THREAD

**Issue by Aho-Shoujo** [DS-Homebrew/nds-bootstrap#1269]
Your console: N2DSXL
Launch Method: 3DS-Forwarder
Version used: v0.46.3
Game tested/used/applicable: Arkanoid DS
Device used: MicroSD card

Expected Behavior:
Actual Behavior: Game is constantly switching screens between top and bottom. (flashing between intermittently, strobing in cutscenes) It can't figure out what screen is the main one. Occurs in some stages as well.

Steps to reproduce
Other notes

Trying multiple times to use the bootstrap menu freezes the entire system (Non-responsive) seemingly randomly.

**Comment by spellboundtriangle** [comment]
Have you tried setting the clock speed to NTR?

**Comment by lifehackerhansol** [comment]
NTR clock speed fixes this.
