### ISSUE TITLE
[APRE]Feel the Magic boots in Japanese on first launch.

### ISSUE THREAD

**Issue by Squall-Leonhart** [DS-Homebrew/nds-bootstrap#1277]
**Your console:** N3DS and O3DS
**Launch Method:** SD card (via TWLMenu).

**Version used:** Nightly and Release
**Game tested/used/applicable:** Feel the Magic NTR-APRE-USA

**Expected Behavior:** Should have booted in the System detected or Configured language (it does on Flashcart and Emulator when no save present initially)
**Actual Behavior:** Main menu is Japanese (configurable to English in game if you know which option on the menu to press)

### Steps to reproduce

Start the game and tap the screen

[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
NDS_PATH = sd:/roms/nds/Feel the Magic - XY-XX.nds
LANGUAGE = 1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
SAV_PATH = sd:/roms/nds/saves/Feel the Magic - XY-XX.sav1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = -2
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0

### Logs

findModuleParamsOffset:
Module params offset found: 02000AF8
sdk_version: 02004E20
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 0202339C

startOffset : 02000000

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:
ARM9 Card read end SDK 2 alt not found
ARM9 Card read end (type 0) short found: 0202C33C

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffsetType0:
ARM9 Card read start (type 0) found

cardRead location : 0202C244
023F0000

findSwi12Offset:
swi 0x12 call found

swi12 location : 020005D2

findCardPullOutOffset:
Card pull out handler found

cardPullOut location : 0202C934

findCardIdEndOffset:
Card ID end not found

findCardReadDmaEndOffset:
Card read DMA end found: 0202C47C

findCardReadDmaStartOffset:
Card read DMA start not found
Card read DMA start SDK 2 alt not found
Card read DMA start alt 1 found

cardReadDma location : 0202C344

findMpuStartOffset:
Mpu init found: 02000A14

findMpuDataOffset:
Mpu data found: 02000AAC

findMpuInitCacheOffset:
Mpu init cache found: 02000A6C

patchMpuSize: 00000000

findResetOffset
Reset not found

ERR_NONE

findSleepPatchOffset:
Sleep patch found: 0238D818

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 02383E4C

findCardCheckPullOutOffset:
Card check pull out found: 0238BA88

forwardedRelocStartAddr
02380154
vAddrOfRelocSrc
02380168
Relocation src: 02380168
Relocation dst: 037F8000

Arm7 (patch v1)
cardReadEndAddr: 0238B75C
cardstructAddr: 0380C240
readCacheEnd: 0238B880
JumpTableFunc: 0238B884
Retry the search
JumpTableFunc: 0238B928
specificWramAddr: 03802B98
someAddr_799C: 0238B2B8
Eeprom page erase:	0238B938
Eeprom verify:	0238B954
Eeprom page write:	0238B970
Eeprom page prog:	0238B98C
Eeprom read:	0238B9A8
Card read:	0238B9C8
Card id:	0238B9D4
Identify backup:			0238B9F8
Arm7 patched!
findSwiHaltOffset:
swiHalt call not found

swiHalt location : 00000000

findSwi12Offset:
swi 0x12 call found

findSwiGetPitchTableOffset:
swiGetPitchTable SDK <= 2 call not found
swiGetPitchTable SDK <= 2 call alt 1 not found
swiGetPitchTable SDK <= 2 call alt 2 not found
swiGetPitchTable SDK <= 2 call alt 3 not found
swiGetPitchTable SDK <= 2 call alt 4 not found
swiGetPitchTable SDK <= 2 call alt 5 not found
swiGetPitchTable SDK <= 2 call alt 6 not found
swiGetPitchTable SDK <= 2 call alt 7 not found
swiGetPitchTable SDK <= 2 call alt 8 not found
swiGetPitchTable SDK <= 2 call alt 9 not found
swiGetPitchTable SDK <= 2 call alt 10 not found
swiGetPitchTable SDK 3 call not found
swiGetPitchTable SDK 3 call alt 1 not found
swiGetPitchTable SDK 3 call alt 2 not found
swiGetPitchTable SDK 3 call alt 3 not found
swiGetPitchTable SDK 3 call alt 4 not found
swiGetPitchTable SDK 3 call alt 5 not found
swiGetPitchTable SDK 3 call alt 6 not found
swiGetPitchTable SDK 3 call alt 7 not found
swiGetPitchTable SDK 3 call alt 8 not found
swiGetPitchTable SDK 3 call alt 9 not found
swiGetPitchTable SDK 3 call alt 10 not found
swiGetPitchTable SDK 3 call alt 11 not found
swiGetPitchTable SDK 4 call not found
swiGetPitchTable SDK 4 call alt 1 not found
swiGetPitchTable SDK 4 call alt 2 not found
swiGetPitchTable SDK 4 call alt 3 not found
swiGetPitchTable SDK 4 call alt 4 not found
swiGetPitchTable SDK 4 call alt 5 not found
swiGetPitchTable SDK 4 call alt 6 not found
swiGetPitchTable SDK 4 call alt 7 not found
swiGetPitchTable SDK 4 call alt 8 not found
swiGetPitchTable SDK 4 call alt 9 not found

swi12 location : 0238BD30

swiGetPitchTable location : 00000000

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02391A00

ERR_NONE
handlerStartSig
0206C420
handlerEndSig
0206C460
tableAddr
0206C0F0
returnAddr
01FF8058
hookLocation arm9: 0206C0F0

chipID: 00001FC2

**Comment by Squall-Leonhart** [comment]
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/1124 (Sorry, i didn't see it when searching for Feel the Magic)

**Comment by Squall-Leonhart** [comment]
My mistake, its not the same issue

**Comment by Squall-Leonhart** [comment]
This seems to be a more general issue of games not receiving the correct language, i just noticed Naruto vs Sasuke defaults to spanish despite being one of the titles that sets defaults based on the system language.

**Comment by RocketRobz** [comment]
Fixed by 3099e36f

**Comment by Squall-Leonhart** [comment]
confirmed fixed, thanks Rob.
