### ISSUE TITLE
Unable to boot into NDS games, error 'can only be used in DSi mode'

### ISSUE THREAD

**Issue by squishypixel** [DS-Homebrew/nds-bootstrap#1282]
**Your console:** DS Lite (USG-001)
**Launch Method:** R4i-SDHC Flashcart
**Version used:** 0.47
**Game tested/used/applicable:** Pokemon HeartGold, Super Mario 64 DS

**Expected Behavior:** Game should boot.
**Actual Behavior:** Game did not boot. Received error: `This edition of nds-bootstrap can only be used in DSi mode`

### Steps to reproduce

[nds-bootstrap.ini](https://github.com/DS-Homebrew/nds-bootstrap/files/7226720/nds-bootstrap.txt)

### Logs

Unable to get logging to work

**Comment by RocketRobz** [comment]
That message is only shown on past nds-bootstrap versions. It got removed later on.
