### ISSUE TITLE
report on Dragon Quest 5 (JP)

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1283]
About Dragon Quest 5 (JP)
I used "DSi mode" and "Countermeasure avoidance code".
Then, except for "Intro Loop" and "Tearing", it seemed to work normally.

The confirmed environment is DSiLL
TWL: v20210925-050615 (1d41264c)
Bootstrap: v20210925-062809 (d0ac446a) and v20210919-034318 (8e498762)
Was used.

It's been a long time since the last confirmation work, so I don't know when this situation started, but I will report it.

I haven't been able to confirm it carefully.
In "DS mode", it freezes (blackouts) in the intro movie.

**Comment by Squall-Leonhart** [comment]
disable async and or DMA

**Comment by KururinX** [comment]
In the DSiLL I tried, no matter how I set async, DMA, CPU speed, and VRAM Boost in DS mode, it didn't work.

**Comment by RocketRobz** [comment]
Doesn't seem to happen in the USA version on my side.
Have you tried the USA and/or EUR version?

**Comment by KururinX** [comment]
I'm sorry I'm not in an environment to try it.

Just in case, I will submit the log at that time.

- - - - - - - - - -
DSiLL (JP)
Dragon Quest 5(JP) CRC32:6EA9705 ,Trim at NDSTokyo Trim
TWL : v21.5.1-8e665473
Bootstrap : 53945620
DS mode-67Mhz
VRAM Boost ON
 ,DMA OFF ,async OFF
--- - - - -
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7230881/NDSBTSRP.LOG)
-

**Comment by Kamikaze1903** [comment]
@RocketRobz hi this error can only be fixed if i delete the nds-bootstrap folder temporarily, and will be back to causing black screens upon  reopening twilightmenu as the nds-bootstrap folder is restored. is there a way i can stop nds-bootstrap from restoring?

**Comment by RocketRobz** [comment]
Try turning off `FAT table cache` in TWLMenu++ Settings.

**Comment by Kamikaze1903** [comment]
> 

its already off by default

**Comment by Kamikaze1903** [comment]
> Try turning off `FAT table cache` in TWLMenu++ Settings.

its already off by default

**Comment by Kamikaze1903** [comment]
attempted with yes to save FAT table cache but no change.

**Comment by RocketRobz** [comment]
I can't get the intro to show at all, on my side.

It seems the AP-fix for the JP version is just broken. The USA versions works for me.

**Comment by Kamikaze1903** [comment]
i hope that a future update will let the JP version be playable
