### ISSUE TITLE
old homebrew doesn't work - NDS_TGM_20080815.nds

### ISSUE THREAD

**Issue by clach04** [DS-Homebrew/nds-bootstrap#1284]
**Your console:** DSi/LL (Japanese)
**Launch Method:** SD card
**Version used:**     nds-bootstrap: Release v0.47.0 (from TWiLightMenu v21.5.1)
**Launch Method:** SD card
**Game tested/used/applicable:** NDS_TGM_20080815.nd NDS_TGM_20080815.nds from https://www.gamebrew.org/wiki/Tetris:_The_Grand_Master_3_DS

**Expected Behavior:** NDS_TGM to play
**Actual Behavior:** NDS_TGM freezes

### Steps to reproduce

1. extract NDS_TGM_20080815.nds from https://www.gamebrew.org/wiki/Tetris:_The_Grand_Master_3_DS
2. load via TWiLightMenu 
3. See some loading with filenames scrolling quickly, so looks like dldi *might* be working
4. game freezes and won't start

issues #25 indicates this did once work?

Works fine with a flashcart so there is reasonable workaround. Logging as a compatability FYI.

### Logs

in progress...

### Notes

in-game menu L+Down+Select does not seem to work (screen changes but menu does not come up).

**Comment by RocketRobz** [comment]
You might need to create a RAM disk for that homebrew.

**Comment by clach04** [comment]
Gotcha' in-game menu not expected to work

I tried following https://github.com/DS-Homebrew/nds-bootstrap/issues/516#issuecomment-459553449 (created an empty 12Mb image with FAT16 format, with same name as the *.nds filename but nds replaced with img, I don't believe there is anything expected to be in the image) with no luck. Not sure if this means it doesn't work or I don't know how ramdisk/images work ;)

https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=1412086532 does mention it supported in the homebrew tab without ramdisk but I suspect the entry is from a while ago.

I'm happy to try other experiments/ideas if you have any.

**Comment by clach04** [comment]
I tried Set RAM disk set to 0 and also 1 in Twlight menu per game settings with no change.

**Comment by spellboundtriangle** [comment]
Unfortunately the homebrew is too large for a RAM disk, about 40 MB iirc. But, if you cut out a lot of files using EFE, it'll work.

**Comment by RocketRobz** [comment]
Fixed by ad180ab9

**Comment by bopchan** [comment]
> Fixed by [ad180ab](https://github.com/DS-Homebrew/nds-bootstrap/commit/ad180ab969e652d50bb46b25e4cdb6bea738385f)

I'm unable to get this game to work, I reach the main menu with the scores on the top screen and the title screen on the bottom screen but half of the bottom screen is cut off/black. This is on a DSi with everything on an SD card.

**Comment by RocketRobz** [comment]
> I'm unable to get this game to work, I reach the main menu with the scores on the top screen and the title screen on the bottom screen but half of the bottom screen is cut off/black. This is on a DSi with everything on an SD card.

Is Unlaunch installed?

**Comment by bopchan** [comment]
> > I'm unable to get this game to work, I reach the main menu with the scores on the top screen and the title screen on the bottom screen but half of the bottom screen is cut off/black. This is on a DSi with everything on an SD card.
> 
> Is Unlaunch installed?

Been a while since I set up the console, but it boots right into Twilight so I think so?

**Comment by RocketRobz** [comment]
> Been a while since I set up the console, but it boots right into Twilight so I think so?

It's probably a while since you updated then.
https://wiki.ds-homebrew.com/twilightmenu/updating-dsi

**Comment by bopchan** [comment]
> > Been a while since I set up the console, but it boots right into Twilight so I think so?
> 
> It's probably a while since you updated then. https://wiki.ds-homebrew.com/twilightmenu/updating-dsi

Updated and I'm still getting the same problem, are there specific launch options I need for the .nds in question?

**Comment by clach04** [comment]
@bopchan as you have this working, please could you document what versions it's working with? Thanks!

**Comment by bopchan** [comment]
> @bopchan as you have this working, please could you document what versions it's working with? Thanks!

DSi

TWiLight Menu++: v27.12.2
nds-bootstrap: Release v2.2.2

NDS_TGM_20080815.nds

RAM disk: None
Game Loader: nds-bootstrap
Run in: DS mode
ARM9 CPU Speed: Default
VRAM Mode: Default
Bootstrap: Default

Let me know if you need anything else!
