### ISSUE TITLE
Macro Mode Screen Swap Not Functioning

### ISSUE THREAD

**Issue by squishypixel** [DS-Homebrew/nds-bootstrap#1287]
**Your console:** NDS Lite (USG-001)
**Launch Method:** R4i-SDHC Flashcart
**Version used:** Release (0.48.0)
**Game tested/used/applicable:** Chrono Trigger

**Expected Behavior:** Top and Bottom screen should have swapped
**Actual Behavior:** Screens did not change.

### Steps to reproduce

```[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 1
CONSOLE_MODEL = -1
MACRO_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = fat:/roms/nds/Chrono Trigger (USA) (En,Fr).nds
SAV_PATH = fat:/roms/nds/saves/Chrono Trigger (USA) (En,Fr).sav
AP_FIX_PATH = fat:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs
```
findModuleParamsOffset:
Module params offset found: 02000B84
arm9 is compressed
Secure area already decrypted
ROM is loadable into RAM
patchCardNds

findCardIrqEnableOffset:
irq enable found: 02006ABC

cardIrqEnable location : 02006ABC

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:

findCardReadEndOffsetType1:
ARM9 Card read end alt (type 1) found: 02011D54

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffsetType1:
ARM9 Card read start alt 2 (type 1) found

cardRead location : 02011C6C
023DA000

findCardPullOutOffset:
Card pull out handler SDK 4 found

cardPullOut location : 020121C8

findCardIdEndOffset:
Card ID end found: 02011DB0

findCardIdStartOffset:
Card ID start not found
Card ID start alt 1 found

Found cardId

cardId location : 02011D5C

findCardReadDmaEndOffset:
Card read DMA end found: 02011C5C

findCardReadDmaStartOffset:
Card read DMA start found: 02011AE0

cardReadDma location : 02011AE0

findMpuStartOffset:
Mpu init found

findMpuDataOffset:
Mpu data found

Mpu data 2: 02000B3C

findMpuInitCacheOffset:
Mpu init cache found

Mpu init cache: 02000AF4

Mpu init 2: 020086A8

findHeapPointer2Offset:
02008164
old hi heap end pointer: 023E0000

new hi heap pointer: 023C0000

Hi Heap Shrink Sucessfull

findResetOffset
Reset found: 02009074
Reset constant found: 02009120
Reset found

reset location : 02009074

findRandomPatchOffset:
Random patch found: 0200F0EC

ERR_NONE

findSleepPatchOffset:
Sleep patch found: 0238D1F0

findCardIrqEnableOffset:
irq enable found: 02383AD8


Arm7 (patch v1)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000
[Error!] Card read addr not found

Arm7 (patch v2)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000
[Error!] Card read addr not found

Arm7 (patch vAll)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
ERR_NONE

hookLocation arm7: 0238F584

handlerStartSig
02065220
handlerEndSig
02065260
tableAddr
027E0000
returnAddr
01FF8058
hookLocation arm9: 027E0000

AP-fix found
AP-fix applied
chipID: 80007FC2
```

### Other notes
Tried using L+R+X+Up, L+R+X+Down, SEL+Up, SEL+Down, and held all combinations for 2 seconds.

**Comment by ZombieNW** [comment]
Can confirm this issue NDS Lite (USG-001) w/ R4SDHC Flashcart

**Comment by cybardev** [comment]
I updated from 0.72 or something (whatever cane with TwilightMenu++ 25.x to current latest TwilightMenu++ with 1.0.x but I still can't seem to swap screens in Macro Mode.

Any special steps I need to take to enable it?

**Comment by RocketRobz** [comment]
> I updated from 0.72 or something (whatever came with TwilightMenu++ 25.x) to current latest TwilightMenu++ with 1.0.x but I still can't seem to swap screens with hotkeys in Macro Mode. Screen swap only works through nds-bootstrap menu, by setting the main screen.
> 
> Any special steps I need to take to enable hotkeys?
> 
> Mine is DSi booting using Unlaunch on SD card.
> 
> Games tried: Tetris Party Deluxe, Pokemon Platinum

Because the screen swap setting now gets saved, the hotkey has been disabled in order to prevent continuous writes to the file containing the setting.

**Comment by cybardev** [comment]
Ah, I see. Thanks for the clarification.

Would it be possible to downgrade nds-bootstrap without downgrading TWLmenu? If so, any specific version you'd recommend for that?

On a side note, is it planned to bring hotkey screen swap back someday, or this is how it will be for the foreseeable future?

**Comment by RocketRobz** [comment]
> Ah, I see. Thanks for the clarification.
> 
> Would it be possible to downgrade nds-bootstrap without downgrading TWLmenu? If so, any specific version you'd recommend for that?

https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.72.1


> On a side note, is it planned to bring hotkey screen swap back someday, or this is how it will be for the foreseeable future?

It'll most likely be that way for the foreseeable future.
