### ISSUE TITLE
Magician's Quest: Mysterious Times - Crashes on TWL

### ISSUE THREAD

**Issue by Laxbby** [DS-Homebrew/nds-bootstrap#1290]
**Your console:** 3DS
**Launch Method:** new 3DS on 11.15 with SD Card
**Version used:** 0.48.0 nds-bootstrap, 22.0.0 of TwilightMenu, both release
**Game tested/used/applicable:** The US version of Magician's Quest: Mysterious Times. Game ID YNNE

**Expected Behavior:** Game runs normally
**Actual Behavior:** Game plays no sound, crashes after showing developer logos in the middle of the intro

### Steps to reproduce

Set mode to DSi and run the game.

### Logs

Attached 
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7274661/NDSBTSRP.LOG)

### Other notes
I was told in the DSi Mode Discord that this should be opened as an issue in Github so the game could be added to the TWL mode blacklist in the next update, so here it is. I've also already added the game to the compatibility list. I'll try to test it out on other versions of Twilight later. Thanks!

**Comment by spellboundtriangle** [comment]
To be clear, is this exclusively an issue with DSi mode, or does this also happen with DS mode at TWL clock speed (133mhz)?

**Comment by Laxbby** [comment]
If it’s set to DS mode with TWL clock speeds and DS VRAM mode, the game loads perfectly fine, but the screens will flicker every once in a while. It it’s set to TWL clock speeds and DSi VRAM mode, it works fine, but the screen flickering is noticeably worse. Still works perfectly fine, but NTR clock speeds is definitely better overall.

**Comment by Squall-Leonhart** [comment]
this game is a candidate for TWL clock blacklisting then.

**Comment by Laxbby** [comment]
Hello, I'm back on this. Sorry for taking a few months... It seems that sometime between this post and now, this has been mostly fixed. Booting in TWL mode works on both 3DS and DSi, but the screens will still flicker on occasion. DS mode/TWL clock speeds/DS VRAM seems to be more broken on 3DS than it was before, however: the flickering is way more frequent, and the bottom few lines on each screen has a "doubling" effect. These issues are only on 3DS, the DSi works the same as TWL mode. DS mode/TWL clock speeds/DSi VRAM works the same as TWL mode on both, and setting it to DS mode or DS clock speeds will remove the flickering entirely. Great to see that something got it working, even if the flickering is still present.
