### ISSUE TITLE
"Quit game" in B4DS in-game menu shuts down device instead of relaunching TWiLight Menu++

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/nds-bootstrap#1299]
**Your console:** DS Lite, O3DSXL 11.15.0 with Luma3DS 10.2.1
**Launch Method:** R4i Gold 3DS Plus with TWiLight Menu++ autoboot, launched through the official Slot-1 launching method
**Version used:** 0.49.1 release, will test nightly soon
**Game tested/used/applicable:** Jump Ultimate Stars (Japan) hash checked with No-Intro, however I've tested other random ROMs and they all happen

**Expected Behavior:** Relaunch TWiLight Menu++.
**Actual Behavior:** Shuts down. (On O3DSXL, reboots to the HOME menu)

### Steps to reproduce

1. Launch flashcart normally, with TWiLight Menu++ autoboot.
2. Launch literally any game. I didn't even mess with the config, just launched.
3. Open in-game menu and select "Quit ROM"

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7437656/NDSBTSRP.LOG)

**Comment by PrgmrAtHrt** [comment]
Still an issue as of v0.66.0.

**Comment by RocketRobz** [comment]
May not be fixed for a while, unfortunately.
