### ISSUE TITLE
Jump Ultimate Stars intro lag

### ISSUE THREAD

**Issue by ghost** [DS-Homebrew/nds-bootstrap#1300]
**Your console:** new 2ds xl
**Launch Method:** SD card
**Version used:** bootstrap release 50.0 / twilight menu release 23.0
**Game tested/used/applicable:** Jump Ultimate Stars (english patched)

**Expected Behavior:** Intro plays without lag (framerate issues) in either ds mode or ntr mode
**Actual Behavior:** Intro lags a bit, especially around the part where Jojo and Arale Norimaki appear in either ds mode or with ntr speed but works fine when using either dsi mode or twl speed

### Steps to reproduce

Launch the game in either ds mode or with ntr speed and watch the cinematic intro until the lag appears.

**Comment by spellboundtriangle** [comment]
Have you tried turning SWI Halt Hook off?

**Comment by retinasilver** [comment]
I just checked that as you suggested and yes, turning SWI Halt Hook off also removes the lag.

**Comment by lifehackerhansol** [comment]
SWI Halt Hook is now defaulted to off as of v0.53.0.
