### ISSUE TITLE
Mario&Luigi Partners in Time glitchy bottom screen when starting battles

### ISSUE THREAD

**Issue by Malick1160** [DS-Homebrew/nds-bootstrap#1303]
**Your console:** Standard DSi
**Launch Method:** The DSi is on firmware 1.4.5E, the game was launched from an 8gb sd card with TWiLightmenu version 23.0.1, launched with Unlaunch 2.0 and Nds-bootstrap is on version 0.50.1
**Version used:** Nds-bootstrap release 0,50,1
**Game tested/used/applicable:** The game is Mario&Luigi Partners in Time, the European release(Playing this in Italian as it's a Multilanguage game) the Crc32 is 3184FBC4

**Expected Behavior:** When starting the very first Bowser Junior fight, when you still control baby Mario and baby Luigi it should normally start the fight
**Actual Behavior:** When starting the fight the bottom screen flashes purple for 1 second and I can see glitchy stuff for a breaf moment

### Steps to reproduce 
Start the first Bowser JR. fight and the screen will flash purple

### Logs
findModuleParamsOffset:
Module params offset restored: 02004B18
sdk_version: 02017532
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 02038C8C

startOffset : 02004000

cardRead location : 0204345C
03700000

swi12 location : 020040FC

cardPullOut location : 02043B14

cardReadDma location : 0204355C

Mpu start: 02004A40

Mpu data: 02004AD4

Mpu init cache: 02004A90

Mpu init: 0203A4D0

Mpu data alt: 0203A37C

Mpu start 2: 02004A48

Mpu data 2: 02004AD8

Mpu init 2: 0203A4D8

reset location : 0203AE8C

ERR_NONE

cardIrqEnable location : 02383918

forwardedRelocStartAddr
02380158
vAddrOfRelocSrc
02380170
Relocation src: 02380170
Relocation dst: 037F8000

Arm7 (patch v1)
cardReadEndAddr: 0238B9B8
cardstructAddr: 03809460
readCacheEnd: 0238BAD8
JumpTableFunc: 0238BADC
Retry the search
JumpTableFunc: 0238BB74
specificWramAddr: 03802E58
someAddr_799C: 0238B530
Eeprom page erase:	0238BB84
Eeprom verify:	0238BBA0
Eeprom page write:	0238BBBC
Eeprom page prog:	0238BBD8
Eeprom read:	0238BBF4
Card read:	0238BC14
Card id:	0238BC20
Arm7 patched!
swiHalt location : 02380694

swi12 location : 0238BF60

swiGetPitchTable location : 02387028

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FABC

ERR_NONE
hookLocation arm9: 027E0004

chipID: 00003FC2

### Other notes

[nds-bootstrap.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7471299/nds-bootstrap.txt)
This issue happened both on my DSi and on my old 2DS, I can't give info about my old 2DS as it's broken.
Also the bootstrap config file is .txt and not .ini because GitHub said that .ini is not supported

**Comment by Malick1160** [comment]
Soo that issue also appears when starting other battles

**Comment by poudink** [comment]
oh yeah that happens for me too

**Comment by RocketRobz** [comment]
Still occurs as of v0.54.1.

**Comment by 9ary** [comment]
Set up twilightmenu++ (26.6.0) and nds-bootstrap (1.2.2) on my new 3ds xl yesterday and this doesn't repro for me. I've logged over 4h in-game time so far and haven't run into any issues, visual or otherwise.

```
$ md5sum Mario\ \&\ Luigi\ -\ Partners\ in\ Time\ \(Europe\)\ \(En,Fr,De,Es,It\).nds
f9e031c8d3aacea6306bbac41bf577f5  Mario & Luigi - Partners in Time (Europe) (En,Fr,De,Es,It).nds
```
