### ISSUE TITLE
Hotel Dusk: Room 215 + other

### ISSUE THREAD

**Issue by TheGaboefects** [DS-Homebrew/nds-bootstrap#1304]
I was playing this game a couple days ago, it had a couple visual glitches but it was playable.
However today i updated TWiLight Menu++ and now the game freezes as soon the ndsbootstrap logo leaves the screen.
pd: Trauma Center under the knife 2 before updating TWiLight Menu crashed at the end of the any briefing right before starting any operation, but after the update the game seems to be running perfectly fine!

**Your console:** Nintendo 3ds XL
**Launch Method:** SD card
**Version used:** v23.0.1
**Game tested/used/applicable:** 

**Expected Behavior:** Game Running Normally (maybe with a few graphical glitches)
**Actual Behavior:** Game freezes right after the NDSbootstrap logo fades

**Comment by RocketRobz** [comment]
Make sure asynch card read is turned off in TWLMenu++ Settings.
Otherwise, the ROM might've got corrupt somehow.

**Comment by TheGaboefects** [comment]
> Make sure asynch card read is turned off in TWLMenu++ Settings. Otherwise, the ROM might've got corrupt somehow.

I turn the asynch on and off but neither way worked.
I also try deleting both the save file and the room and put in a sd card the rom again but that also didn´t work.
However I deleted the European rom i was using and put the USA rom of hotel dusk and that does work perfectly!
I´m not sure why the usa version works while the european doesn´t, the strange thing is that before the update it did work (Albeit some of the graphics were gitch galore)

**Comment by RocketRobz** [comment]
Please downgrade nds-bootstrap to each previous version, and see which one the European version last booted on.
To downgrade, just follow the instructions on the version's release page.

**Comment by lifehackerhansol** [comment]
#1236 suggests it works when setting language to French in per-game options for some reason.
