### ISSUE TITLE
? icons and endless loading on nds bootstrap screen

### ISSUE THREAD

**Issue by pokemonfan6498** [DS-Homebrew/nds-bootstrap#1305]
**Your console:** New Nintendo 2ds XL
**Launch Method:** SD
**Version used:** Standard
**Game tested/used/applicable:** Pokemon heartgold

**Expected Behavior:** Launch normally
**Actual Behavior:** Displays ? icon and stuck on nds bootstrap loading screen

### Other notes
I was getting new version of twilight menu ++ but when i transferred all games i needed something strange happend half of my games were with ? icons the title was nds filename and when i attempted to play any game with ? icons the nds bootstrap loading screen appeared but it was been for too long

**Comment by RocketRobz** [comment]
This is not an nds-bootstrap (or TWiLight Menu++) issue.
It's possible your ROMs got corrupt somehow. This has never happened on my side.

**Comment by pokemonfan6498** [comment]
I have no idea how that happened because they worked well only my R4

пт, 5 нояб. 2021 г., 23:47 RocketRobz ***@***.***>:
