### ISSUE TITLE
Pokemon Pearl ( JAPAN ) has sound issue in both Nightly and Latest.

### ISSUE THREAD

**Issue by roabel8** [DS-Homebrew/nds-bootstrap#1306]
2DS ( OLD ) 
SD Card  
Latest release as of November 7, 2021 and Nightly 
Pokemon Pearl ( JAPAN ) 

Sound as intended 
Crackling sounds, innacurate sounds 

Play game like any other. <- Steps to reproduce

**Comment by RocketRobz** [comment]
Make sure SWI Halt Hook is turned on in either TWLMenu++ Settings or the per-game settings.

**Comment by roabel8** [comment]
Hey, it was already on.

But for some reason, after replaying again now it sounds perfectly fine again.

I'll keep you updated if anything. Thank you so much for this!

**Comment by roabel8** [comment]
It seems to be an graphical glitches when booting GBA (GBA Runner ) games and DS with the R4 Menu.

The bottom part of the top and bottom screens multiply into two. This error goes away when you exit and start the game with the Original DS/Lite-Like Menu. 

I don't know if this had to do with the audio as well. Who knows.

Thank you.

**Comment by lifehackerhansol** [comment]
Is audio still an issue?

**Comment by lifehackerhansol** [comment]
Closing due to no response from OP.
