### ISSUE TITLE
Pokemon Black 2 black screen when using clean dump with dsi binaries.

### ISSUE THREAD

**Issue by Rodokami** [DS-Homebrew/nds-bootstrap#1307]
**Your console:**  New Nintendo 2DS
**Launch Method:** SD card via NDS Forwarder Generator 1.2.0-beta
**Version used:** latest v0.50.1
**Game tested/used/applicable:** Pokémon Black 2

**Expected Behavior:** Game should start properly
**Actual Behavior:**  black screen after the character creation.

### Steps to reproduce

If I use a rom with the proper dsi binaries the game will crash after naming your character and rival, just before the games says "autumn" The game is ap patched. If I use a trimmed dump without the dsi binaries, the game plays in ds mode and works just fine.

### Other notes
Pokemon Black 1 works just fine with dsi features.

**Comment by RocketRobz** [comment]
You need to re-follow the AP part in the forwarder guide at GBATemp [here](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/), if you aren't using TWiLight Menu++.

**Comment by Squall-Leonhart** [comment]
TWL requires an unpatched rom in this case to apply its own AP patch, trimmed or not is irrelevant.

Some cheats also do not work in DSi mode, so it can be better to just run this in DS mode with DSi clocks.

**Comment by Rodokami** [comment]
I did what Robz suggested and it worked. There was a missing file I needed to copy into the forwarder folder.
