### ISSUE TITLE
Lufia / Estpolis not saving

### ISSUE THREAD

**Issue by Abzol** [DS-Homebrew/nds-bootstrap#1309]
Nintendo DSi TWL-001(EUR)

SD card
nds-bootstrap Ver. Release v0.50.1
TwlMenu++ v23.0.0.1

Lufia - Curse of the Sinistrals (U) [CAC43A4E]

**Expected Behavior:** Saved game should have loaded

**Actual Behavior:** Game seemingly unable to read save data

### Steps to reproduce
1. Boot Lufia 2
2. Press -start- to attempt to skip the intro cutscene.
(Expected: It should skip to the main menu)
3. If unskippable, watch intro cutscene, then press new game
4. Tap through a few lines of text
5. Once given control, save, then attempt to load the save back
6. If issue repros, you will see a "Save Data is corrupt. Data has been deleted" message show up.

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
SWI_HALT_HOOK = 1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/dsi/roms/Lufia - Curse of the Sinistrals (USA).nds
SAV_PATH = sd:/dsi/roms/saves/Lufia - Curse of the Sinistrals (USA).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips

### Other notes
Several other titles (picross 3d, final fantasy tactics a2, rune factory 3) can save and load succesfully.
Savefile is created on the SD card, with (roughly) correct file size of ~9kb.
Pushing a save file created from other emulator (desmume 0.9.12#10502f0f) exhibits same issue, although readable by emulator.
Emulator reads file created on console as empty savefile.
Estpolis DS (C8A8FA8B), the japanese version of the same game, exhibits the same issue.

**Comment by RocketRobz** [comment]
Try the latest nightly build [here](https://github.com/TWLBot/Builds/commit/6d4451ae47e9750786dae02fbf9ca7e48e8de3ea), and see if it fixes your issue.
To set the nightly build, set `Bootstrap` to `Nightly` in the per-game settings (opened by pressing Y in the ROM menu).

**Comment by lifehackerhansol** [comment]
Issue persistent in nds-bootstrap 0.52.0 release.

**Comment by RocketRobz** [comment]
Seems to be caused by this error here, from the log:
```
Error in relocation checking
0380286C 038027B4
vAddrOfRelocSrc: 0238039C
```
