### ISSUE TITLE
Mario Party DS - Power Washer minigame crash

### ISSUE THREAD

**Issue by SicklySilverMoon** [DS-Homebrew/nds-bootstrap#1315]
**Your console:** Nintendo 3DS XL (Old)
Region: Americas
Original firmware: 7.1.0-14U
Current firmware: 11.15.0-47U

**Launch Method:** SD Card, NDS Bootstrap 0.50.2, via TWiLight Menu++ 23.0.1

**Version used:** Release

**Game tested/used/applicable:** Mario Party DS Rev 2, (NTR-A8TE-USA), SHA-1: 6054049AC831720F1C7C63023CF18907352D45C

**Expected Behavior:** Loading Power Washer 1v3 from Story Mode, expected the minigame to start normally after pressing start.

**Actual Behavior:** Black screen crash/hang. Its likely it happens with loading from the minigame menu as well but I can't do so as I can't unlock the minigame without a crash.

### Steps to reproduce
If it doesn't crash from the minigame menu, play on story mode long enough to trigger a 1v3 with Power Washer as the minigame.

### nds-bootstrap.ini
[nds-bootstrap.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7558355/nds-bootstrap.ini.txt)
(Text because GitHub won't allow uploads of ini for... some reason)

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7558360/NDSBTSRP.LOG)

### Other notes
Appears to happen on other revisions as well but I can't confirm that as of now.

**Comment by RocketRobz** [comment]
Try turning off card read DMA in the per-game settings (opened by pressing Y in TWLMenu++).

**Comment by SicklySilverMoon** [comment]
> 
> 
> Try turning off card read DMA in the per-game settings (opened by pressing Y in TWLMenu++).

Unfortunately no dice  there, same result.
Here's my MPDS specific ini:
[Mario Party DS (USA) (Rev 2).nds.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7565575/Mario.Party.DS.USA.Rev.2.nds.ini.txt)

And here's the most recent log (renamed a little):
[NDSBTSRP.MPDSDMAOFF.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7565576/NDSBTSRP.MPDSDMAOFF.LOG)

Results are exactly the same as before, story mode, 1v3 happens, power washer is selected, it hangs on a black screen after pressing start.

**Comment by kwrotunni** [comment]
Seconded. It's really annoying having to reset every time I get a 1v3, and turning off card read DMA doesn't help.

**Comment by spellboundtriangle** [comment]
Is this still occurring for you guys?
https://user-images.githubusercontent.com/79382000/156433344-aa5a9fe7-b925-459d-a6b5-ec6bb14d1f07.mp4
This isn't a naturally occurring one per se, but it seems to be fine. I'm using the same version of the game, on nds-bootstrap v0.54.2

**Comment by SicklySilverMoon** [comment]
I can confirm its working correctly as of 0.53.2
