### ISSUE TITLE
Mario Kart DS Save Data working unusually

### ISSUE THREAD

**Issue by Squidsy** [DS-Homebrew/nds-bootstrap#1316]
**Your console:** New Nintendo 3DS XL

**Launch Method:**  MicroSD Card

**Version used:** Release v23.0.1, bootstrap v0.50.1, although it's happened on other version too

**Game tested/used/applicable:** Mario Kart DS and all hacks and variants, primarily the file obtained from [REDACTED], being "0168 - Mario Kart DS (U) (SCZ).nds"

**Expected Behavior:** Save Data remaining upon exit, Any unlocks to register

**Actual Behavior:** Save Data of custom emblem and player Name is saved from a good while ago when first installed, however name and emblem changes made do not remain once exiting the game, and any form of unlocks (Cups, Karts, probably characters but cant test since cant access needed cup) refuse to unlock on any speed difficulty. As such, characters and Mirror mode are completely inaccessible. Complete file replacement of the .sav was attempted using a 100% file from GBATemp, to the same results. No unlocks registered, only a name and emblem change.

### Steps to reproduce
1. Launch game
2. Try unlocking anything
3. Change name and emblem after initial registration, and close and re-open the game

### Other notes
I made this account just to report this problem, so sorry if this is a bit ameteur compared to usual. None of the other games I have have this problem, only MKDS and MKDS Mods.

**Comment by RocketRobz** [comment]
Try the latest nightly version of nds-bootstrap.

**Comment by lifehackerhansol** [comment]
This seems to work fine on a9cdb5086550486a8b9c6af39503940f56db3245.

**Comment by RocketRobz** [comment]
Haven't heard anyone else with this issue, so I'll close this.

**Comment by Chorwacjen** [comment]
funny, i got quite a similiar issue rn
