### ISSUE TITLE
(DSiWare) 'EJ Puzzles - Hooked' broken main menu, softlocks on selecting any option

### ISSUE THREAD

**Issue by SimPiko** [DS-Homebrew/nds-bootstrap#1317]
**Your console:** DSi XL, 1.4.5E

**Launch Method:** Twilight Menu 23.0.1

**Version used:** 0.50.2 (bundled with TWLMenu++ 23.0.1)

**Game tested/used/applicable:** EJ Puzzles - Hooked (USA) (KHWE), MD5: 35200ba4df7b36299434368ecc9c3fc3

**Expected Behavior:** Game's main menu should be populated with entries like "Select Level", "Pro Shop", "Profile", "Options" or "Help". Tapping them would activate in-game thing (level select, upgrades, options, help etc.)

**Actual Behavior:** Main menu shows empty grey buttons with missing text, tapping any of them softlocks console, the only way to exit it is to hold POWER button (not just tap, hold). This makes game unplayable.

### Steps to reproduce
1. Run game.
2. Either create new profile or select existing one.
3. Observe/interact.

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
ROMREAD_LED = 1
DMA_ROMREAD_LED = 2
LOADING_SCREEN = 1
CONSOLE_MODEL = 0
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/dsiware/EJ Puzzles - Hooked (USA).nds
SAV_PATH = sd:/ROMS/DSIWARE/SAVES/EJPUZZ~1.PUB
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/  
RAM_DRIVE_PATH = 
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 5
GAME_SOFT_RESET = 1
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 1
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
AP_FIX_PATH =
HOMEBREW_ARG = fat:/ROM.BIN
MACRO_MODE = 0
CARD_READ_DMA = 1
REGION = -2
GUI_LANGUAGE = en
HOTKEY = 284
APP_PATH = sd:/ROMS/DSIWARE/EJPUZZ~1.NDS
SDNAND = 0
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7566716/NDSBTSRP.LOG)

### Other notes
I remember this game running somewhat fine on my DSi XL, ~~but can't remember if it was using Unlaunch method or nds-bootstrap one.~~ just checked, game works fine when launching through Unlaunch.
At some point I've tried to bisect which version could introduce the bug but at some point even the versions that I've 'marked as working' stopped working, and I dunno why.
Seems like it could be somewhere between 0.47.0 and 0.48.0 but, as mentioned earlier, after using spare SD card i've tried to test on for some time, even 0.47.0 stopped working for me (menu displayed fine, but tapping any option caused softlock that _is_ 'exitable' by pressing or holding POWER button)

**Comment by RocketRobz** [comment]
On my side, the text is shown on the gray buttons, but tapping one of them still soft-locks the game, and can be exited by either pressing or holding POWER.

**Comment by SimPiko** [comment]
~~Okay, so I wasn't going insane.~~
Just tested on newest version (0.54.0), looks like game runs without any problems.
Issue can be closed.
