### ISSUE TITLE
(Sonic Colors) Zones become inaccessible after beating Tropical Resort

### ISSUE THREAD

**Issue by tinoposts** [DS-Homebrew/nds-bootstrap#1318]
**Your console: Nintendo DSi**

**Launch Method: SD Card**

**Version used: Release v0.50.1**

**Game tested/used/applicable: Sonic Colors (NTR-BXSE-USA)**

**Expected Behavior: Once you beat the boss of Tropical Resort, two other zones should be accessible, that being Sweet Carnival and Starlight Carnival.**

**Actual Behavior: Once the boss of Tropical Resort is beaten, every zone becomes inaccessible.**

### Steps to reproduce
1. Launch the game in either DSi mode or DS mode.
2. Beat the entirety of Tropical Resort
3. All zones should be greyed out on the map.

### nds-bootstrap.ini
(Cannot provide it at the moment, but I did provide some settings of Twilight Menu.)

### Logs
(Cannot provide it at the moment, but I will provide it later on from now.)

### Other notes

I am typing this on my iPad, and cannot upload my nds-bootstrap.ini, but I can provide my Twilight Menu's Games and Apps Settings. I'll upload the .ini file in 7 to 8 hours from now.

Run in: Auto
ARM9 CPU Speed: 133 MHz (TWL)
VRAM Mode: DSi Mode
Sound/Mic Frequency: 47.61 kHz
Card Read DMA: On
Asynch Card Read: Off
SWI Halt Hook: On
Expand ROM space in RAM: No
Save FAT table cache: No

**Comment by RocketRobz** [comment]
Please update nds-bootstrap. The latest version is v0.50.2.
