### ISSUE TITLE
Zelda Spirit Tracks hangs on white screen

### ISSUE THREAD

**Issue by jimmy117909** [DS-Homebrew/nds-bootstrap#1320]
**Your console: N3DSXL**

**Launch Method: SD Card, Twilight Menu v23.1.0**

**Version used: Release v0.51.0**

**Game tested/used/applicable: Zelda Spirit Tracks BKIE**

**Expected Behavior: normal cutscene/progression after Forest Temple**

**Actual Behavior: Game hangs on white screen after defeating 1st boss**

### Steps to reproduce
1. Progress through Forest Temple
2. Defeat Stagnox
3. Watch the screen fade to white and stay that way during the cutscene

### nds-bootstrap.ini
[nds-bootstrap.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7610154/nds-bootstrap.ini.txt)

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7610132/NDSBTSRP.LOG)

### Other notes
In game menu is still accessible

**Comment by Squall-Leonhart** [comment]
the fact you have cheats on could be involved.

**Comment by Squall-Leonhart** [comment]
No repro, stagox died and game continued on to the next cutscene without issue.

**Comment by jimmy117909** [comment]
Ah, I had tested the fake mic input cheat while reproducing the issue and forgot to turn it off. 
It fades to white when the big green chunk of triforce spins and never advances, even without any cheats on.

**Comment by Squall-Leonhart** [comment]
my ini as follows

`[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
NDS_PATH = sd:/roms/nds/The Legend of Zelda - Spirit Tracks.nds
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
SAV_PATH = sd:/roms/nds/saves/The Legend of Zelda - Spirit Tracks.sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
`

**Comment by Squall-Leonhart** [comment]
You should try a clean dump of the game, and formatting the SD card again with 32KB clusters.

**Comment by jimmy117909** [comment]
Reformatting did the trick, I used 65536 since i have a high capacity sd card, although that's exactly how it already was? Thanks for the help, anyway
