### ISSUE TITLE
Unable to build on Windows (cygwin)

### ISSUE THREAD

**Issue by kcinnaJlol** [DS-Homebrew/nds-bootstrap#1321]
**Your console:**
Windows with cygwin?

**Launch method:**
N/A

**Version used:**
Nightly, b57c6f27

**Game tested/used/applicable:**
None

**Expected Behavior:**
nds-bootstrap would have built.

**Actual Behavior:**
Make reports an error (see **Logs**)

### Steps to reproduce
1. Install cygwin and the other build requirements according to README.md
2. Clone this repository
3. Run `make package-nightly`

### nds-bootstrap.ini
Not applicable.

### Logs

Personal information removed.
Assume that `/` is the project root

```make[1]: Entering directory '/nds-bootstrap/retail'
make[2]: Entering directory '/nds-bootstrap/retail/cardengine/arm7'
make[3]: Entering directory '/nds-bootstrap/retail/cardengine/arm7/build'
make[3]: '/nds-bootstrap/retail/cardengine/arm7/../../nitrofiles/cardengine_arm7.bin' is up to date.
make[3]: Leaving directory '/nds-bootstrap/retail/cardengine/arm7/build'
make[2]: Leaving directory '/nds-bootstrap/retail/cardengine/arm7'
make[2]: Entering directory '/nds-bootstrap/retail/cardengine/arm9_igm'
make[3]: '/nds-bootstrap/retail/cardengine/arm9_igm/../../nitrofiles_dec/cardengine_arm9_igm.bin' is up to date.
make[2]: ../../lzss.exe: No such file or directory
make[2]: *** [Makefile:111: build] Error 127
make[2]: Leaving directory '/retail/cardengine/arm9_igm'
make[1]: *** [Makefile:178: cardengine_arm9_igm] Error 2
make[1]: Leaving directory '/nds-bootstrap/retail'
make: *** [Makefile:28: nightly] Error 2
```

### Other notes
Make tries to use `/retail/lzss.exe` instead of `/lzss.exe` (Yet again, assume that `/` is project root)

I already made a simple fix, but am unable to submit a pr for the fix.
The fix is located in kcinnajlol/nds-bootstrap@e589f619

**Comment by SNBeast** [comment]
Same issue as #1060.

**Comment by kcinnaJlol** [comment]
Ok, didnt search precise enough.
Closing issue due to it being a duplicate.
