### ISSUE TITLE
White screen when launching White 2 with patched EXP curve and no trade evolutions

### ISSUE THREAD

**Issue by Gamesbybram** [DS-Homebrew/nds-bootstrap#1323]
**Your console:**
 Old 3ds

**Launch Method:**
Its launched via SD card, I have the NDS forwarder generator

**Version used:**
I have no idea what release or nightly is and how i can check it sorry

**Game tested/used/applicable:**
Pokemon White 2 (Experience + Trade Evolution Patched) DS ROM

**Expected Behavior:**
The game launched normally like it was the case before

**Actual Behavior:**
While plaing the game, it froze so i close the software and rebooted my 3ds. When trying to launch it again, I just got a white screen for 10 minutes at least after the NDS bootstrap logo

### Steps to reproduce
1.  Download ROM 'Pokemon White 2 (Experience + Trade Evolution Patched) DS ROM'
2.  Play the game a bit and hack in some rare candy via PKSM because i dont like grinding
3. game freezes after second gym and wont launch again

### nds-bootstrap.ini
There is no file called nds-bootstrap.ini on my SD card?

### Other notes

I looked it up, and tried deleting fatTable and patchOffsetcache already with no result + I only have this issue with this specific game

**Comment by lifehackerhansol** [comment]
The file is in `/_nds/nds-bootstrap.ini`

You can also check the version used by pressing L+Down+SELECT while in-game.

**Comment by Gamesbybram** [comment]
For some reason, my 3ds just goes back to home menu when i do L + DOWN + SELECT and i think i found the file (srbackendId.bin) but Github says it doesnt support it...

**Comment by RocketRobz** [comment]
You need to download the latest forwarder pack using Universal Updater then.
If the button combo gives the same result, try updating nds-bootstrap as well, if updating the forwarder pack didn't fix it.

**Comment by Gamesbybram** [comment]
Okay, I will try that ty

**Comment by Gamesbybram** [comment]
Yes! Thank you, I just needed to update the nds bootstrap apparently lol ,ty so much!!!
