### ISSUE TITLE
GBARunner Dai-Mahjong freezes until hard-reboot?

### ISSUE THREAD

**Issue by newestdodain47** [DS-Homebrew/nds-bootstrap#1324]
**Your console:** Nintendo 2DS

**Launch Method:** Both

**Version used:** v?.??.?

**Game tested/used/applicable:** GBA DaiMahjong

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. Loads game
2. Starts game but doesnt get past bios screen
3. Then always i greeted me a white screen by pressing start so any to fix this

### Other notes
They all work on VisualBoy Advance-M Emulator.

**Comment by newestdodain47** [comment]
#1267

**Comment by lifehackerhansol** [comment]
This is not the place to report GBARunner2 issues.
