### ISSUE TITLE
Pokemon Black 2 doesn't load/ white screen/ rom already patched and ds mode on

### ISSUE THREAD

**Issue by SugarFreeHariboGummies** [DS-Homebrew/nds-bootstrap#1328]
**New 3ds XL:**

**:twilight menu, LATEST VERSION**

**release:**

**Game tested/used/applicable:**

**Pokemon Black 2 should have booted sucessfully*

**The game did not boot/ white screened**

### Steps to reproduce
1. 
2. 
3. 

### Other notes
Console: New 3ds XL

**Comment by lifehackerhansol** [comment]
Please properly fill out the issue template.

And for the record, game works just fine without any patching.
