### ISSUE TITLE
Emulate NDS Memory Expansion Pak for B4DS mode on DSi/3DS

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1329]
It would be nice if you could emulate the Memory Expansion Pak on DSi/3DS when using B4DS mode, similar to how you can already do this with the DS Web Browser. This would allow users to test B4DS with and without a MEP, without actually having to own a MEP and/or a DS Phat/Lite.

If I'm understanding correctly, this would require unlocked SCFG (Unlaunch w/ NTR Launcher/TWLM++) on the flashcard, so this would also be adding B4DS in general as a "Limited mode" of sorts.

**Comment by lifehackerhansol** [comment]
Limited mode was implemented as of https://github.com/DS-Homebrew/TWiLightMenu/commit/8dc1c1f124dcdff0985ffecb13e76db5c633d598, but I'm not sure about the MEP emulation.

**Comment by RocketRobz** [comment]
Yes, B4DS mode should be able to emulate the MEP on DSi/3DS, with the 8MB+ memory mode.
