### ISSUE TITLE
Digimon World DS freeze when viewing technique in digifarm

### ISSUE THREAD

**Issue by davg-qqq** [DS-Homebrew/nds-bootstrap#1333]
**Your console:** New 3DS XL

**Launch Method:** SD card

**Version used:** nds-bootstrap v0.50.0

**Game tested/used/applicable:** `Digimon World DS (USA).nds`
MD5 `aa68ac42848e257aa715f1d9937f6a2c`
SHA1 `225ffc25aaf1ab4006fcdce5896d411a8fee870f`

**Expected Behavior:** Not freeze

**Actual Behavior:** Game freezes, music continues to play, screen does not update anymore (background animation stops) and most buttons don't do anything.
nds-bootstrap menu is still accessible
Home button still works (shows message to close app).

### Steps to reproduce
1. Go to digimon farm (purple portal in central hub)
2. Select "Digimon List" from menu
3. Select any digimon, press A and select "View Stats"
4. Select "Techniques"

### nds-bootstrap.ini

[nds-bootstrap.ini.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7794549/nds-bootstrap.ini.txt)
(added `.txt` to filename to stop github complaining)

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7794550/NDSBTSRP.LOG)
I quit out of the game a few seconds after it froze using the home button.

### Other notes
Similar issue at #617, but at a different menu.
There is an almost identical menu you can access outside the digifarm by pressing start > digimon > [pick a digimon] > techniques but that menu seems to work without issue.
I can provide a save file if needed, you need to play through the tutorial for a while before you get access to the digifarm

**Comment by RocketRobz** [comment]
Please update nds-bootstrap (and TWiLight Menu++, if used as well), and see if the result changes.

**Comment by davg-qqq** [comment]
Checked again using nds-bootstrap v0.53.1 and it works now. There's is still a short freeze (~3 seconds) where only the music plays but then everything goes back to normal, so it's playable.
I updated TWiLight Menu++, but I launched through an nds forwarder if that's of any consequence.

Sorry, I should have checked with the latest version as well.
Out of curiosity do you know what changes resulted in it being fixed? I had a quick look at the commit messages but I didn't see anything specific to this game.

Thanks for the help, feel free to close the issue unless you want to track the short freeze.
