### ISSUE TITLE
Nintendogs randomly freezes

### ISSUE THREAD

**Issue by Yo-Yo-Kirby** [DS-Homebrew/nds-bootstrap#1334]
New Nintendo 3DS XL

**Launch Method:** SD Card, unlocked; Sys 11.15.0-47U; Luma 10.2.1-c058e3f

**Version used:** Release v0.53.0

**Game tested/used/applicable:** 0091 – Nintendogs – Dachshund & Friends (USA).nds

SDK ver: 2.1
NTR-ADGE-USA

**Expected Behavior:** Should not randomly freeze

**Actual Behavior:** Randomly freezes

### Steps to reproduce
1. Play the game. It just happens randomly.

### nds-bootstrap.ini
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/7796968/nds-bootstrap.zip)

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7796969/NDSBTSRP.LOG)

### Other notes
I set the ARM9 CPU speed to 133mhz because there was severe slowdown without it. It wasn't freezing before then though.

**Comment by RocketRobz** [comment]
Try updating nds-bootstrap, and then try enabling/disabling SWI Halt Hook.
I've heard about this issue before, though I have no idea what could cause it.

**Comment by Yo-Yo-Kirby** [comment]
I updated nds-bootstrap to v0.53.1 and tried playing the game with SWI Halt Hook disabled and then with it enabled. It still froze during both instances.

**Comment by RocketRobz** [comment]
Try reverting the clock speed then. The slowdown will be fixed with SWI Halt Hook turned off.

**Comment by Yo-Yo-Kirby** [comment]
Okay, I updated nds-bootstrap again, turned off SWI Halt Hook and changed everything to DSi mode (including the clock speed) and I haven't had any more freezing issues so far (knock on wood).
