### ISSUE TITLE
Picross DS shows black screen and beeps

### ISSUE THREAD

**Issue by winterbreezesrule** [DS-Homebrew/nds-bootstrap#1338]
**Your console:** Old 3DS XL

**Launch Method:** SD card

**Version used:** nightly (MD5 for nds-bootstrap-hb-nightly.nds is 27a366127cf2b401b15b521dd63a5f8a, MD5 for nds-bootstrap-nightly.nds is 952405ccce52d92d9bed8fcd4e9597f2)

**Game tested/used/applicable:** Picross DS, MD5 a980adb92b4bbda7784cdf960ada8826, retrieved from -snip-

**Expected Behavior:** The game properly starts after displaying the Jupiter and Nintendo logos.

**Actual Behavior:** After displaying the Jupiter and Nintendo logos, the screen goes black, and a beeping noise repeats.

### Steps to reproduce
No unique steps I'm aware of, just boot up the game like normal.

### nds-bootstrap.ini
Github is telling me it doesn't support .ini files, so I renamed this to .txt, but it's just the file renamed.
[nds-bootstrap.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/7872537/nds-bootstrap.txt)

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7872533/NDSBTSRP.LOG)

### Other notes
None I can think of.

**Comment by Epicpkmn11** [comment]
I'm not sure exactly which version of nds-bootstrap you're using from that MD5, however if it's not the latest maybe try updating. If you're using TWiLight Menu++ make sure it's up to date as well (updating TWiLight includes nds-bootstrap so can just do that)

https://wiki.ds-homebrew.com/twilightmenu/updating

The Japanese version of Picross DS works for me, but I don't have the USA version so can't test it.

**Comment by RocketRobz** [comment]
USA versions boots fine on my side.
So yeah, your nds-bootstrap version could be out of date.

**Comment by winterbreezesrule** [comment]
The thing is, that nightly build is the one I downloaded from the Universal Updater store on my 3DS, so I've got no clue what went wrong there.

I just installed the normal TWiLight Menu++ release off of Universal-DB (2022-01-02 release, v23.4.0, got rid of everything else), and still nothing. MD5s for what I got are: 0fa8ddc40f09488891e1eb97033b726a (for release) and 269edfd1be8ab596442fcf0c265c482b (for hb-release)

The bug still occurs. [Here's](https://www.youtube.com/watch?v=OE5VnwirZpk) a short video I took showing it off.

I realize now that every time I try to start the game, it says "save file created", and while I remember as I looked there was an issue with that, I know it was fixed in a later version of bootstrap? So I'm a little lost.

**Comment by RocketRobz** [comment]
Ah, I see what's wrong.
In `savPath`, there's a folder starting with `.`, and should be deleted from the SD card.

**Comment by winterbreezesrule** [comment]
Ohhhh my God, that explains it. I'd already deleted the folder from the SD card a while back, but I guess for some reason, it defaulted to writing the save there?

I changed the savPath directory, and it works fine now. Thank you so much!
