### ISSUE TITLE
LEGO batman 2: DC Super Heroes black screen 

### ISSUE THREAD

**Issue by MarceloCeS** [DS-Homebrew/nds-bootstrap#1340]
**Your console:** Nintendo DS Lite

**Launch Method:** Flashcard R4i Upgrade v1.4.1

**Version used:** Tested in both versions,same problem

**Game tested/used/applicable:** lego batman 2 DC super heroes sdk ver:5.5 NTR-B6FE-USA

**Actual Behavior:** the game not launch, black screen

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 1
CONSOLE_MODEL = -1
NDS_PATH = fat:/jogos/new/LEGO Batman 2 - DC Super Heroes.nds
SAV_PATH = fat:/jogos/new/saves/LEGO Batman 2 - DC Super Heroes.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = pt-BR
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
APP_PATH = fat:/JOGOS/JOGOSD~1/ARTSTY~5.NDS
PRV_PATH = fat:/JOGOS/JOGOSD~1/SAVES/  <oÿÿÿÿ
BOOST_CPU = 1
BOOST_VRAM = 1
GAME_SOFT_RESET = 1
DONORTWL_NDS_PATH = fat:/jogos/JOGOS DSIWare Part1/Art Style Series - BASE 10 (USA).nds
AP_FIX_PATH =
USE_ROM_REGION = 1

### Logs
findModuleParamsOffset:
Module params offset restored: 02000BA4
arm9 is not compressed
Secure area already decrypted
patchCardNds

[SDK 5]

cardIrqEnable location : 02168C1C

startOffset : 02000000

cardRead location : 02162B48
023D9000

cardPullOut location : 021630F0

cardId location : 021629A8

cardReadDma location : 02162DB0

old hi heap end pointer: 023E0000

new hi heap pointer: 023C0000

Hi Heap Shrink Sucessfull

reset location : 0216B620

ERR_NONE

cardIrqEnable location : 02384060

Relocation src: 023802E4

Arm7 (patch v5)
JumpTableFunc: 0238ECEC
card id:	0238ECD4
card read:	0238ECE4
Eeprom read:	0238ECF8
Eeprom page write:	0238ED10
Eeprom page prog:	0238ED28
Eeprom verify:	0238ED40
Eeprom page erase:	0238ED54
swi12 location : 02383600

swiGetPitchTable location : 02383614

ERR_NONE

hookLocation arm7: 0238FED0

hookLocation arm9: 027E0000

chipID: 80007FC2

**Comment by RocketRobz** [comment]
There's a low chance for non-booting games to boot in later versions.
It it suggested to use the flashcard kernel instead of nds-bootstrap.

**Comment by MarceloCeS** [comment]
what a pity, the kernel doesn't work either and I can't update it anywhere
:(
but thanks for the help, and much success in the project

Em dom, 16 de jan de 2022 8:18 PM, RocketRobz ***@***.***>
escreveu:
