### ISSUE TITLE
B4DS Dark Void Zero Doesn't Play because a bug in the microphone

### ISSUE THREAD

**Issue by Getze56901** [DS-Homebrew/nds-bootstrap#1341]
**Nintendo Ds lite:**

**Flashcard:**

**latest:**

**Game tested/used/applicable: Dark Void Zero
Title ID: KDVE-USA**

**the game requires the player to use the microphone to continue to the title screen of the game:**

**Actual Behavior:Even if I use the microphone perfectly, the game cannot access the main menu because it does not detect sound from the microphone.**

### Steps to reproduce
1. 
2. 
3.

**Comment by RocketRobz** [comment]
Your microphone is broken. The game works fine on my side.
