### ISSUE TITLE
In-game menu crashes in B4DS mode

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1344]
**Your console:** DSi

**Launch Method:** DSONE flashcard, with both locked and unlocked SCFG

**Version used:** Nightly build [bbb13592](https://github.com/TWLBot/Builds/releases/tag/v20220206-065925),comparing to release 0.53.2

**Game tested/used/applicable:** Mario Kart DS USA

**Expected Behavior:** The in-game menu would open.

**Actual Behavior:** A red screen would appear, with some white dots looking like it might've been an error screen.

### Steps to reproduce
1. Start a game (used MKDS here) using B4DS
2. Attempt to open the in-game menu

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 1
CONSOLE_MODEL = 0
MACRO_MODE = 0
SOUND_FREQ = 1
HOTKEY = 284
B4DS_MODE = 2
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
NDS_PATH = fat:/nds/MARIOKARTDS_AMCE01_0.nds
SAV_PATH = fat:/nds/saves/MARIOKARTDS_AMCE01_0.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
USE_ROM_REGION = 1
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8010305/NDSBTSRP.LOG)

### Other notes
The in-game menu still crashed the system after a few attempts of opening it on 0.53.2, but here it's not working at all.

**Comment by RocketRobz** [comment]
Does not happen on my side. Try deleting `pagefile.sys` in `fat:/_nds/`, and have nds-bootstrap re-generate the file.
