### ISSUE TITLE
Pokemon White (Randomized) Anti Piracy 

### ISSUE THREAD

**Issue by TotalWeakness** [DS-Homebrew/nds-bootstrap#1346]
**Your console:**
3DS xl

**Launch Method:**
SD Card - TWiLight Menu++ v23.4.0

**Version used:**
Release

**Game tested/used/applicable:**
Pokemon White (Vanilla) and (Randomized)

**Expected Behavior:**
Both Versions of the game should have launched as normal, with no Anti-Piracy measures.

**Actual Behavior:**
Vanilla Pokemon White Launched as expected,  Pokemon White Randomized launched with AP Measures in place.

### Steps to reproduce
1.  Load copy of Pokemon White rom into Universal Pokemon Randomizer
2.  Load randomized .nds file onto SD card
3.  Launch Pokemon White (Randomized) through TWiLight Menu++
4.  Game runs like normal, but pokemon can not earn Exp, and after so many battles the game will freeze.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/Pokemon - Black Version (USA, Europe) (NDSi Enhanced).nds
SAV_PATH = sd:/saves/Pokemon - Black Version (USA, Europe) (NDSi Enhanced).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 1
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips

### Other notes

[AP-patched games.txt](https://github.com/DS-Homebrew/nds-bootstrap/files/8020800/AP-patched.games.txt)

As noted in the above text file, Pokemon White AP-Patch should be available for both (Randomized) and (Vanilla) for both the US and Eur versions.

**Comment by RocketRobz** [comment]
The randomized ROM is made in a way that a single AP-fix .ips patch cannot be used, so one is not included in TWLMenu++, and you'll need to manually AP-patch the clean ROM first, before applying the randomized patch.

**Comment by TotalWeakness** [comment]
> The randomized ROM is made in a way that a single AP-fix .ips patch cannot be used, so one is not included in TWLMenu++, and you'll need to manually AP-patch the clean ROM first, before applying the randomized patch.

Where can I find a reliable patch, and what software do I need to use to patch it?

**Comment by RocketRobz** [comment]
A patch is included in a software called DS-Scene ROM Tool.

**Comment by TotalWeakness** [comment]
I tried downloading that, but it always says the patch database is unavailable.

**Comment by RocketRobz** [comment]
Make sure you have a clean unpatched ROM dump first.
If it's already clean, where are you downloading the tool from?

**Comment by TotalWeakness** [comment]
Pretty it's clean, i'll try a second just in case.

https://gbatemp.net/download/retrogamefan-nds-rom-tool-v1-0_b1215.35735/

Thats the link I downloaded from

**Comment by RocketRobz** [comment]
Hmm, that's the correct one. Make sure you aren't updating any databases either.

**Comment by TotalWeakness** [comment]
Ok, I just clean installed the Rom Tool, I'll try it again.

Good luck so far, it seem I may have had a pre patched rom, Looks like I may have a clean one now, but I'll post updates

**Comment by TotalWeakness** [comment]
I had an issue where it would fail to save the patched rom, but I quickly realized it was because I moved the source rom after I had already opened the rom. Exported Successfully, now only to test a randomizer to see if it will work.

**Comment by TotalWeakness** [comment]
Further Testing will likely be required, but it seems to be working so far. I only had time to test the first battle, and I was able to gain Exp, so it looks promising.
