### ISSUE TITLE
Alice in wonderland very unstable

### ISSUE THREAD

**Issue by F3arM3** [DS-Homebrew/nds-bootstrap#1351]
old 3ds twilight menu and nds lite with flash cart

Launched via flashcart on nds and slot 1 flashcart in twilight menu

release version

ALICENDS_VALE4Q_00

I expect the game to boot/ load

In 3ds twilight menu it white screens, on nds with flash cart it either has forever loading screens or randomly crashes

### Steps to reproduce
1. load the game
2. 
3. 

### nds-bootstrap.ini
*FlashCart*
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 282
CACHE_FAT_TABLE = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
SDNAND = 0
PRECISE_VOLUME_CONTROL = 0
NDS_PATH = fat:/roms/nds/ALICENDS_VALE4Q_00.nds
SAV_PATH = fat:/roms/nds/saves/ALICENDS_VALE4Q_00.sav
AP_FIX_PATH = fat:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

*3DS*
[NDS-BOOTSTRAP]
NDS_PATH = fat:/roms/nds/ALICENDS_VALE4Q_00.nds
SAV_PATH = fat:/roms/nds/saves/ALICENDS_VALE4Q_00.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 1
AP_FIX_PATH = fat:/_nds/nds-bootstrap/apFix.ips
USE_ROM_REGION = 1

**Comment by RocketRobz** [comment]
The ROM boots fine on my side, on DSi.
Try updating nds-bootstrap to latest nightly, using Universal-Updater, then in TWLMenu++, press Y to open the per-game settings menu, and set `Bootstrap` to `Nightly`.

**Comment by F3arM3** [comment]
How do I do per game settings, when I press a to confirm that I want nightly it acts like a right press

**Comment by RocketRobz** [comment]
Then you already opened the per-game settings, and set to `Nightly`. After setting it, press B.

**Comment by F3arM3** [comment]
When I press y again after exiting the settings everything still says default, is it supposed to do that? And I still get a white screen on my 3ds after the bootstrap logo goes away.

**Comment by RocketRobz** [comment]
Your TWiLight Menu++ version might be out of date then. Try updating it and nds-bootstrap to the latest (non-nightly) version, using Universal Updater.

**Comment by F3arM3** [comment]
I did, still no luck

**Comment by RocketRobz** [comment]
Are you able to switch `Run in` to `DS mode`?
If so, and the issue persists, then your ROM is corrupted.

**Comment by F3arM3** [comment]
I can get it to say that in the per game settings, but I have no idea if those settings stick because everytime I open that menu it lists everything as the default

**Comment by RocketRobz** [comment]
What version of TWLMenu++ is shown in TWLMenu++ Settings?

**Comment by F3arM3** [comment]
The weird thing is if I just boot if from the flashcart version of twilight menu it does load, albeit with most level transitions having infinite load screens, but nothing oads up the 3ds/dsi app

**Comment by F3arM3** [comment]
Version 1d78bbd0

**Comment by F3arM3** [comment]
There is a 0 at the end

**Comment by RocketRobz** [comment]
> Version [1d78bbd](https://github.com/DS-Homebrew/nds-bootstrap/commit/1d78bbd07751b809eed055f6934df245c924a12a)

I meant the TWiLight Menu++ version.
It's on the bottom of the top screen.

**Comment by F3arM3** [comment]
24.0.0

**Comment by RocketRobz** [comment]
Try deleting the `_nds` folder on the SD root, and re-install TWiLight Menu++.

**Comment by F3arM3** [comment]
ok, now it works, must've had some bad settings, but now I only have save slot options with this and the (L+R+down+B) ing doesn't work

**Comment by RocketRobz** [comment]
L+R+Down+B only works on the console's SD card.
Did you re-install TWiLight Menu++ on the flashcard, or the console's SD card?

**Comment by F3arM3** [comment]
I have it installed on both, but when I use my 3ds I run it off the sd card and load the games from the flash cart

**Comment by RocketRobz** [comment]
Ah, I see. Closing, since the game boots fine.
