### ISSUE TITLE
Dragon Quest V - Intro loop

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1354]
nds-bootstrap : v20220220-052734 (82210ff1)
TWiLightMenu :  v20220220-181831 (326924bc)

It has been confirmed that Dragon Quest 5 (JP) can be started even in DS mode, although it does an intro loop.
No workaround code required

**Comment by KururinX** [comment]
bootstrap: v20220221-184055 (9e9957d9) Twilight Menu: v24.1.0
We have confirmed that it works normally.
Thanks a lot.

**Comment by KururinX** [comment]
I examined it in a little more detail
When the boot mode is set to default or DS mode, intro loop is avoided if the speed is set to 133Mhz.

**Comment by KururinX** [comment]
We have confirmed that the intro works properly with Ver.759ad5e (20220808-004518).
Thank you.

**Comment by UncleStark** [comment]
bootstrap 0.72.1
intro loop still here
boot mode is set to DS mode, speed is set to 133Mhz
loop not avoided

**Comment by RocketRobz** [comment]
The loop after the first one will be fixed in the next version.

**Comment by amitkulk123** [comment]
Can confirm that using the latest nightly release seems to fix the issue. The intro loops once in the beginning but works fine after the first loop.

**Comment by RoninTurkey** [comment]
I'm using nightly latest version and still getting intro loop.

**Comment by RocketRobz** [comment]
> I'm using nightly latest version and still getting intro loop.

Each time, or just for the first time?
If it's each time, make sure you've set `Bootstrap` to `Nightly` in either TWLMenu++ Settings or the per-game settings menu.

**Comment by RoninTurkey** [comment]
It's workingnow with some screen artifacts. I only had TWiLight Menu++ nightly installed. I installed bootstrap nightly too and it started working after the first loop.

**Comment by luizefb** [comment]
Having the same problem here. I updated the twilight menu and worked, I played the game for a while, but I tried to play again and the intro loops again.

**Comment by lozovsky83** [comment]
I also have this problem. Tried different versions of the game, including clean roms. Nothing helps. Night version did not install.

**Comment by lozovsky83** [comment]
> > I also have this problem. Tried different versions of the game, including clean roms. Nothing helps. Night version did not install.
> 
> You need to make sure that you're running the nightly version. In the game, if you press L+R+Down+Select, it'll pull up a menu showing which version of nds-bootstrap your running. If you're running nightly, it'll show `nds-bootstrap-{commitID}`. So for me it shows `nds-bootstrap-a488476` since that's the version I downloaded but you can get the latest version by downloading from the 'Actions' tab on this github repo. After that put the nightly version on your SD card and select nightly from twilight menu.

I copied the 3 nightly build files into the bootstrap folder, but apparently the regular version is running. It looks like V 0.72.1.
How can I run the night build exactly?

**Comment by lozovsky83** [comment]
> > I copied the 3 nightly build files into the bootstrap folder, but apparently the regular version is running. It looks like V 0.72.1. How can I run the night build exactly?
> 
> In TWLMenu++, either open TWLMenu++ Settings or press Y to open per-game settings menu, then change the `Bootstrap` setting to `Nightly`.

I've done everything, but it doesn't help.

**Comment by RocketRobz** [comment]
> I've done everything, but it doesn't help.

If you're using a 3DS, have you tried using Universal-Updater to download the nds-bootstrap nightly?

**Comment by lozovsky83** [comment]
> > I've done everything, but it doesn't help.
> 
> If you're using a 3DS, have you tried using Universal-Updater to download the nds-bootstrap nightly?

I use a DSi XL

**Comment by RocketRobz** [comment]
> I use a DSi XL

Did you put the nds-bootstrap nightly .nds files in `sd:/_nds/` overwriting existing files?

**Comment by lozovsky83** [comment]
> > I use a DSi XL
> 
> Did you put the nds-bootstrap nightly .nds files in `sd:/_nds/` overwriting existing files?

They were just copied. Nothing was overwritten.

**Comment by RocketRobz** [comment]
> > > I use a DSi XL
> > 
> > 
> > Did you put the nds-bootstrap nightly .nds files in `sd:/_nds/` overwriting existing files?
> 
> They were just copied. Nothing was overwritten.

So you did change the `Bootstrap` setting to `Nightly` right?
If so, did you do it in TWLMenu++ Settings, or the per-game settings menu for DQV?

**Comment by lozovsky83** [comment]
> > > > I use a DSi XL
> > > 
> > > 
> > > Did you put the nds-bootstrap nightly .nds files in `sd:/_nds/` overwriting existing files?
> > 
> > 
> > They were just copied. Nothing was overwritten.
> 
> So you did change the `Bootstrap` setting to `Nightly` right? If so, did you do it in TWLMenu++ Settings, or the per-game settings menu for DQV?

I apologize. My mistake. 
I copied the nightly build not to the root of sd:/_nds/ but to sd:/_nds/nds-bootstrap/, so nothing was overwritten though it should have been.
It worked now, after the intro restarted once.
I'll try to play and see how it goes.
Thanks for your help!

**Comment by RocketRobz** [comment]
To the nightly users, in order for the full fix to take effect, make sure you have the latest nightly build, as well as having the latest `preLoadSettings` file for your console, which you can download from [here](https://github.com/DS-Homebrew/nds-bootstrap-extras/tree/main/preLoadSettings) to `sd:/_nds/nds-bootstrap/`.

**Comment by KururinX** [comment]
I just tried it and it works fine.

**Comment by ekirchman** [comment]
Still not working for me using a 3DS  with the latest patches w/nightly bootstrap as of today. Completely uninstalled as per the [guide](https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds) and installed with Universal Updater.

**Comment by RocketRobz** [comment]
> Still not working for me using a 3DS with the latest patches w/nightly bootstrap as of today. Completely uninstalled as per the [guide](https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds) and installed with Universal Updater.

Did you switch the `Bootstrap` setting to `Nightly`? If so, then what happens?

**Comment by ekirchman** [comment]
> > Still not working for me using a 3DS with the latest patches w/nightly bootstrap as of today. Completely uninstalled as per the [guide](https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds) and installed with Universal Updater.
> 
> Did you switch the `Bootstrap` setting to `Nightly`? If so, then what happens?

I downloaded the release version of TW++ and set `Bootstrap` to `nightly` using the per game menu (`y`). I was under the assumption that since I just downloaded TW++ that this nightly would be the latest. Checked the commit hash, and no, its not. So I downloaded the latest from nds-bootstrap `master` (1a281bc08b51a077b2503ba1be4f3b26e72d24a2) and now the game gets past the intro screen after the 1st or 2nd loop.

There's a noticeable black horizontal bar flicker in the intro title, but it doesn't seem to be effecting any gameplay so far.

**Comment by amitkulk123** [comment]
> > > Still not working for me using a 3DS with the latest patches w/nightly bootstrap as of today. Completely uninstalled as per the [guide](https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds) and installed with Universal Updater.
> > 
> > 
> > Did you switch the `Bootstrap` setting to `Nightly`? If so, then what happens?
> 
> I downloaded the release version of TW++ and set `Bootstrap` to `nightly` using the per game menu (`y`). I was under the assumption that since I just downloaded TW++ that this nightly would be the latest. Checked the commit hash, and no, its not. So I downloaded the latest from nds-bootstrap `master` ([1a281bc](https://github.com/DS-Homebrew/nds-bootstrap/commit/1a281bc08b51a077b2503ba1be4f3b26e72d24a2)) and now the game gets past the intro screen after the 1st or 2nd loop.
> 
> There's a noticeable black horizontal bar flicker in the intro title, but it doesn't seem to be effecting any gameplay so far.

It shouldn't loop if you copied `preLoadSettings???.pck` (which for you is [preLoadSettings3DS.pck](https://github.com/DS-Homebrew/nds-bootstrap-extras/blob/main/preLoadSettings/preLoadSettings3DS.pck) since you're on 3DS) to `sd:/_nds/nds-bootstrap/`. 

I'm on a New 3DS and copying and overwriting that file removes the loop and the other issues on both the latest stable (v0.72.1) and nightly releases.
