### ISSUE TITLE
yu-gi-oh world championship 2008 local  multiplayer wont work

### ISSUE THREAD

**Issue by riku4470** [DS-Homebrew/nds-bootstrap#1357]
new 3ds xl and a new 2ds xl

both sd card

release

yu-gi-oh world championship 2008 local  multiplayer wont work

the connection wont happen

### Steps to reproduce
1. created a looby in the game the other cant find the other
2. 
3. 

trying to connect two consoles to play yugioh.

**Comment by RocketRobz** [comment]
Try turning off card read DMA.

**Comment by riku4470** [comment]
were would that be located? Thank you!

**Comment by RocketRobz** [comment]
In the per-game settings menu of TWLMenu++, opened by pressing Y.
If you're using forwarders, hold Y before the game starts.

**Comment by riku4470** [comment]
okay so holding y starting the game didnt do anything for whatever reason(i am using forwarders). I then installed twilight menu++ i pressed y like you said i had a menu come up. the options i have are the following 

language 
save number 
run in
arm9 cpu speed 
vram boost
heap shrink 
bootstrap
screen aspect ratio 

i dont see anything that pertains to turning off card read DMA

**Comment by RocketRobz** [comment]
You need to update TWiLight Menu++ (and nds-bootstrap) then, as you installed an outdated version.

**Comment by riku4470** [comment]
So can confirm that i am fully updated with both applications. Are you suggesting i should be using the nightly build?

**Comment by RocketRobz** [comment]
No.

The presence of the `Heap Shrink` option makes it evident that your TWLMenu++ is not up to date.
Please use Universal-Updater to update, instead of the discontinued TWiLight Menu++ Updater.

**Comment by riku4470** [comment]
Oh jeez i am so sorry i am on this version TWiLight Menu++: v16.3.0 dont know how i missed that. i will update it now.

**Comment by riku4470** [comment]
ok i updated both apps. on both consoles. turned off that option. it still is not wanting to connect locally. 



![IMG_20220223_233159213](https://user-images.githubusercontent.com/12244255/155464647-9d42e555-a038-4091-95a5-cf3e7b66778e.jpg)
![IMG_20220223_233322350](https://user-images.githubusercontent.com/12244255/155464693-5533238b-c36a-4d13-bd4c-97695beab7a0.jpg)
![IMG_20220223_233316815](https://user-images.githubusercontent.com/12244255/155464667-4af7f9b7-84fc-41ed-93ba-2a2f06c8d8c2.jpg)

**Comment by RocketRobz** [comment]
Does wireless work in other DS games?

**Comment by riku4470** [comment]
okay so i just tried with mario kart ds. same story. i also tried it with card read on and off

**Comment by riku4470** [comment]
as an aside the wireless communication works for 3ds games we were trading Pokémon last night. and that was working.

**Comment by RocketRobz** [comment]
> okay so i just tried with mario kart ds. same story. i also tried it with card read on and off

Make sure the `WiFi` setting is turned on in TWLMenu++ Settings.

**Comment by riku4470** [comment]
where would that be located?

**Comment by RocketRobz** [comment]
In the `Misc settings` page.

**Comment by riku4470** [comment]
hell yes thank you it all works now. For whatever reason one was on and one was off. I dont even know how that would be possible. Issue solved!

**Comment by RocketRobz** [comment]
You're welcome!
