### ISSUE TITLE
Cant find other 3ds on local multiplayer

### ISSUE THREAD

**Issue by metehan5327** [DS-Homebrew/nds-bootstrap#1359]
hey,

I have the twlmenu++ and the wifi settings are on but somehow i cant find my friend on local multiplayer the signal is always red. Thanks for the help

**Comment by Barrettloganj13** [comment]
I have that same issue with it communicating with other ds systems including the dsi and the dsi can communicate fine with roms from the sd card but not the 3ds or 2DS

**Comment by RocketRobz** [comment]
You need to turn on the WiFi feature in TWLMenu++ Settings on the 3DS & 2DS.

**Comment by Barrettloganj13** [comment]
where is it located

**Comment by spellboundtriangle** [comment]
Misc. Settings

**Comment by Barrettloganj13** [comment]
did not see it there

**Comment by Barrettloganj13** [comment]
but have wireless turned on before opening the menu

**Comment by RocketRobz** [comment]
You need to update then: https://wiki.ds-homebrew.com/twilightmenu/updating-3ds

**Comment by Barrettloganj13** [comment]
that did work thanks a ton
