### ISSUE TITLE
Bloons TD 4 crashing upon boot (two time issue)

### ISSUE THREAD

**Issue by s-zenmode** [DS-Homebrew/nds-bootstrap#1361]
**Your console:** Nintendo DSi 

**Launch Method:** Launched via Twilight Menu++ on Memory Pit/OFW 1.4.5J

**Version used:** I believe it was 0.53.2 or 0.54 release

**Game tested/used/applicable:** Bloons TD 4 DSiWare (european rom and american rom both tried)

**Expected Behavior:** Upon tapping the game rom in twilight menu++, the game should have launched into the playable game.

**Actual Behavior:** 
1st boot: Says it creates a public save file and gets stuck on saying "Public save file created!" something along those lines. From here the only way out is to hard restart the console.
2nd boot: After the "public save file" was created, upon launching the game, the screen flashes white for about 3 seconds, and goes to black the very next second. The only way out is a hard reset.

### Steps to reproduce
1. Get the rom by any means
2. Put on SD card
3. Launch 1st time
4. Observe
5. Launch 2nd time
6. Observe

### Other notes

If it is important, my Twilight Menu++ theme is HBL.
if you need any more info leave a comment and i'll try to provide as best as possible.
I tried other DSiWare (Bloons TD and Bloons) and both of them seem to be working fine.

**Comment by RocketRobz** [comment]
That game may need Unlaunch installed for it to work.

**Comment by s-zenmode** [comment]
To be honest we'll have to see. I'll experiment with newer versions of nds-bootstrap and see if that does any help first. I'll try to dump logs too. And if updating doesn't work then I'll see about Unlaunch

**Comment by RocketRobz** [comment]
Logs will not help, in this case.

**Comment by Epicpkmn11** [comment]
It works for me on 1.4.5J without Unlaunch if I set a donor ROM, I used <ruby>どこでも Wiiのま<rp> (</rp><rt>dokodemo Wii no ma</rt><rp>) </rp></ruby> and it works fine. Without the donor ROM it works fine with Unlaunch but not without.

**Comment by RocketRobz** [comment]
> It works for me on 1.4.5J without Unlaunch if I set a donor ROM, I used どこでも Wiiのま (dokodemo Wii no ma) and it works fine. Without the donor ROM it works fine with Unlaunch but not without.

It does not use a donor ROM, regardless if one is set or not.
Also, make sure you used Memory Pit (not through TWLMenu++'s Limited Mode setting).

**Comment by Epicpkmn11** [comment]
Oh huh, well it didn't work the first time but did work the second after I set a donor ROM then I guess.

This was on a console that I don't have Unlaunch installed on and was using Memory Pit so it's just normal memory pit.

**Comment by s-zenmode** [comment]
> Oh huh, well it didn't work the first time but did work the second after I set a donor ROM then I guess.
> 
> This was on a console that I don't have Unlaunch installed on and was using Memory Pit so it's just normal memory pit.
I'll definitely try that and if it works ill close the issue

**Comment by s-zenmode** [comment]
> > Oh huh, well it didn't work the first time but did work the second after I set a donor ROM then I guess.
> 
> This was on a console that I don't have Unlaunch installed on and was using Memory Pit so it's just normal memory pit. 

I'll definitely try that and if it works ill close the issue

**Comment by s-zenmode** [comment]
> > Oh huh, well it didn't work the first time but did work the second after I set a donor ROM then I guess.
> > This was on a console that I don't have Unlaunch installed on and was using Memory Pit so it's just normal memory pit.
> 
> I'll definitely try that and if it works ill close the issue

Worked like a charm! :)
