### ISSUE TITLE
Castle Conqueror Against (DSiWare) Fails to Save (Perhaps Read Fail?)

### ISSUE THREAD

**Issue by SNBeast** [DS-Homebrew/nds-bootstrap#1364]
**Your console:** n3DS XL and DSi XL

**Launch Method:** Both from Twilight Menu++ and on SD, DSi mode, from Unlaunch 2.0 (DSi) / Luma 10.2,1 with 3GX loader on Sys 11.15.0 (3DS)

**Version used:** Release 0.54.2

**Game tested/used/applicable:**
Castle Conqueror Against (USA)
SHA-1: b3b8cfc0c01b87f98f4de16e3aca10e300f2e389
SHA-256: 5bd7d9cf460a5c6e7c1e8bb19a856a430a88cb7bae47a029fad164a6e3cb5e1a

**Expected Behavior:** Autosaving (the only saving) works and the save appears in the Main Menu.

**Actual Behavior:** Autosaving fails (it shows an error message where it would show that an autosave was made, how nice :D), and the failure is verifiable to 

### Steps to reproduce
1. Start a new game or load a game (if you can do the latter)
2. Beat the tutorial or a level, look at top-right corner
3. Notice it says autosave failed and go to the file select to see that the progress wasn't saved

### nds-bootstrap.ini
3DS. Lemme know if you want DSi.
```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/dsiware/cca.app
SAV_PATH = sd:/ROMS/DSIWARE/SAVES/CCA.PUB
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
LOGGING = 0
B4DS_MODE = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 2
HOTKEY = 284
APP_PATH = sd:/ROMS/DSIWARE/CCA.APP
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/  
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
USE_ROM_REGION = 1
DSI_MODE = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 5
GAME_SOFT_RESET = 1
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs
3DS. Lemme know if you want DSi.
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8174889/NDSBTSRP.LOG)

### Other notes
I saw that a copied pub save from NAND didn't read a save file that certainly was there.

**Comment by RocketRobz** [comment]
Not sure as to why the error would occur.
As some changes related to the device list have been made in later versions, can you please check if the issue still occurs?

**Comment by SNBeast** [comment]
Failing to reproduce. Seems fixed.
