### ISSUE TITLE
Pokemon white launch issue on dsi 

### ISSUE THREAD

**Issue by mergle365** [DS-Homebrew/nds-bootstrap#1368]
**Your console:**

**Launch Method:**

**Version used:**

**Game tested/used/applicable:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3. 

### Logs

I put Pokemon white same as Pokemon white 2 on DS mode but it just goes to a white screen after nds_bootstrap. Is it because I have a original dsi? ( the small one)

**Comment by lifehackerhansol** [comment]
Please fill the issue templates.
