### ISSUE TITLE
nds-bootstrap not found

### ISSUE THREAD

**Issue by Shin021** [DS-Homebrew/nds-bootstrap#1370]
Every time I try playing a game I get that message.

**Comment by Peter0x44** [comment]
Try installing TWiLight Menu++ again.
https://wiki.ds-homebrew.com/twilightmenu/installing

**Comment by Masamune3210** [comment]
This isn't a issue with nds-bootstrap, it's a issue with whatever launcher you are using, likely TWiLightMenu. Make sure you followed all instructions correctly and if the issue persists go make a issue over there instead
