### ISSUE TITLE
World of Sand DS has an invisible floor

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1372]
**Your console:** DSi w/ Unlaunch

**Launch Method:** SD card

**Version used:** 73fb31b

**Game tested/used/applicable:** [World of Sand DS](https://www.gamebrew.org/wiki/World_of_Sand_DS)

**Expected Behavior:** When the sand falls with nothing in the way, it will fall off the screen, never to be seen again.

**Actual Behavior:** About 2/5 of the way down the screen, the sand just stops and piles up (apparently falling off the edges), as if there's something solid blocking it.

### Steps to reproduce
1. Start World of Sand DS
2. Watch the sand fall, and hit the invisible floor

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
NDS_PATH = sd:/worldofsand-0.1.nds
SAV_PATH = sd:/saves/worldofsand-0.1.sav
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 3
BOOST_CPU = 0
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
LANGUAGE = -1
DSI_MODE = 0
BOOST_VRAM = 0
SOUND_FIX = 1
GAME_SOFT_RESET = 1
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 1
SOUND_FREQ = 1
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
APP_PATH = sd:/VANILL~1/NINTEN~1.NDS
PRV_PATH = sd:/VANILL~1/SAVES/NINTEN~1.PRV
SWI_HALT_HOOK = 0
HOMEBREW_ARG =
B4DS_MODE = 1
USE_ROM_REGION = 1
```

### Logs
[NDSBTSRPHB.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8214018/NDSBTSRPHB.LOG)

### Other notes
Normally I would leave compatibility issues to the list, but this issue is rather strange so I figured I would open an issue ticket.

**Comment by RocketRobz** [comment]
Cannot reproduce this on my side.
