### ISSUE TITLE
Tomodachi Collection crashes with some interiors when giving outfits

### ISSUE THREAD

**Issue by fn1y** [DS-Homebrew/nds-bootstrap#1381]
**Your console:**
Nintendo DSi

**Launch Method:**
SDHC Sandisk 32GB Card

**Version used:**
Release

**Game tested/used/applicable:**
Tomodachi Collection (English Patch by jjewel)

**Expected Behavior:**
Should be able to pick an outfit to gift to a Mii.

**Actual Behavior:**
Game and system crash. If in DS mode, the crash also produces a red upper screen with several white dots. This only works if the Mii has the "Barber" interior. Other interiors may be glitchy, but this is the only one I've encountered.

### Steps to reproduce
1. Enter a Mii's apartment (must have the "Barber" interior)
2. Open the gift menu
3. Head to "Outfit" and try to select an outfit.

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/5297 - Tomodachi Collection (Japan) (English APfix).nds
APP_PATH = sd:/FOTOFA~1.NDS
SAV_PATH = sd:/saves/5297 - Tomodachi Collection (Japan) (English APfix).sav
PRV_PATH = sd:/SAVES/
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 2
DSI_MODE = 2
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 1
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
RAM_DRIVE_PATH = sd:/null.img
CARD_READ_DMA = 1
ASYNC_CARD_READ = 1
EXTENDED_MEMORY = 0
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8268131/NDSBTSRP.LOG)

### Other notes
The game is modded, with an English Translation and AP fix.

**Comment by lifehackerhansol** [comment]
"Release"
Which version is "release"? You can check this in TWiLight Menu++ settings.

**Comment by fn1y** [comment]
@lifehackerhansol Ah, sorry. It's v24.1.1

**Comment by RocketRobz** [comment]
> @lifehackerhansol Ah, sorry. It's v24.1.1

That's the TWiLight Menu++ version. What's the nds-bootstrap version you're using?

**Comment by fn1y** [comment]
Sorry, was in a rush and just read the TwilightMenu Number. 

Release v0.54.2

**Comment by MisterSheeple** [comment]
Does anyone know if this issue is also present in the original Japanese version? For reference, the English patch is based on JP Rev 1.

**Comment by RocketRobz** [comment]
Does this issue persist in v0.63.1?

**Comment by RocketRobz** [comment]
Closing due to lack of response, as well as the possibility of the issue being fixed in later versions.

**Comment by Instandhaltung** [comment]
I think I've had the same problem. The game crashes if I want to give a Mii an outfit.
My Mii had the "Scandinavian" room interior. Bootstrap 2.16.0

<img width="3072" height="4096" alt="Image" src="https://github.com/user-attachments/assets/59174f49-1b96-4a1e-9756-e71da1b65ce6" />

**Comment by RocketRobz** [comment]
> I think I've had the same problem. The game crashes if I want to give a Mii an outfit. My Mii had the "Scandinavian" room interior. Bootstrap 2.16.0

Are you also using the English patch?
Also, are cheats enabled?

**Comment by Instandhaltung** [comment]
I am using a different English patch: https://gbatemp.net/threads/release-tomodachi-collection-english-translation-again.678776/
No cheats enabled.

**Comment by RocketRobz** [comment]
> I am using a different English patch: https://gbatemp.net/threads/release-tomodachi-collection-english-translation-again.678776/ No cheats enabled.

Try turning off `Card Read DMA` in the per-game settings menu of TWLMenu++ then.

**Comment by Instandhaltung** [comment]
Sadly, that didn't fix it. Still crashing.
