### ISSUE TITLE
Save Files Not Loading Anymore,

### ISSUE THREAD

**Issue by Noahbx** [DS-Homebrew/nds-bootstrap#1382]
All I did was open one game, and my save is gone, weird I thought, but I wasn't that far in the game so I just replayed it, then I open ace attorney investigations, and my save file which was on the 5th Final Case, Was Gone. I pull out my sd card and put it in my computer, and all my saves are still there, so I try opening the save in melonds, and it works, so theres nothing wrong with my save file, any idea why its not working?

**Comment by spellboundtriangle** [comment]
Can anyone reproduce this with this game?

**Comment by RocketRobz** [comment]
Does this issue persist in v0.63.1?

**Comment by Kaisaan** [comment]
Does this issue still happen on the latest versions of TWiLight Menu++ and nds-bootstrap? If so, can you upload the affected save file(s) here?

**Comment by lifehackerhansol** [comment]
Closing due to no response from author.
