### ISSUE TITLE
Some Cheats don't work after update

### ISSUE THREAD

**Issue by Spouik** [DS-Homebrew/nds-bootstrap#1386]
I've issue with a cheat code on TwilightMenu3DS after updating from a 2021 version to the first 2022 version if I remember correctly (I can't remember what version of 2021 sorry). The issue is still present in the last update (v24.3.0) : in Pokémon Black (French), the Always Shiny code doesn't work, and this is annoying because I can't know if the Removal Shiny Code still works or not. I'm on a Old 3DS Xl with Luma3DS. Other codes like Walktrough Walls works fine.

**Comment by RocketRobz** [comment]
The non-working cheats only work in DS mode, so in TWiLight Menu++, press Y to open the per-game settings, and change `Run in` to `DS mode`.

**Comment by Spouik** [comment]
Oh okay it works thank you !
