### ISSUE TITLE
Gen 4 Pokemon games freezing on white screen when supposed to return to title screen

### ISSUE THREAD

**Issue by dj2814** [DS-Homebrew/nds-bootstrap#1390]
**Your console:** DSi

**Launch Method:** SD Card, Twilight Menu++ v24.5.0, nds-bootstrap v0.55.4

**Version used:** release

**Game tested/used/applicable:** tested on:
- Pokemon - SoulSilver Version (USA).nds 
- Pokemon -HeartGold Version (Europe).nds
- Pokemon - Platinum Version (USA) (Rev1).nds
assuming the same problem applies for other Gen 4 Pokemon nds roms

**Expected Behavior:** 
- When entering the WiFi settings in the game and exiting it, the game should return back to the title screen. Also, each time after claiming Mystery Gifts, you should be returned back to the title screen.
- In SoulSilver, after beating E4 & Lance, registering into the hall of fame and going through the end credits, you should be returned back to the title screen.(tested in SS, but assuming the same for other gen 4 games)

**Actual Behavior:** In events where you should be returned back to the title screen (as listed above) the games just gets stuck on a white screen and will not go back to the title screen. The only way to exit is to use the power button or L+DOWN+SELECT -> Quit Game taking you out of the game and Twilight Menu++. This consistently happens when running the games on DS mode, however, having tried running SoulSilver on DSi mode, the game does return you back to the title screen in such events, however, it becomes prone to freezing in-game, whereas in DS mode there are no gameplay issues apart from returning back to the title screen, so I prefer to stay away from DSi mode unless required. On Gen V games like Pokemon Black/White, which run on DSi mode, all of this works perfectly fine.

I noticed a few years back that this issue was highlighted and was apparently fixed, so I tested out nds-bootstrap ver 0.30.1 (I think?), and although the game didn't hang on a white screen, it returned back to the camera, meaning I had to re-enter Twilight Menu and go back into the game rather than being returned to the title screen.

### Steps to reproduce
1. Launch Pokemon SoulSilver (or any other Gen 4 pokemon game)
2. On the menu scroll down and go to Nintendo Wi-Fi Connection Settings
3. Press B to exit, and the game will be stuck on a white screen until you use the power button to exit, or do L+DOWN+SELECT -> Quit Game which takes you out of the game and Twilight Menu++.
- Also happens after claiming Mystery Gift or beating Lance and going through end credits, but the one above is easiest to do.

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DONORTWLONLY0_NDS_PATH = sd:/roms/nds/Nintendo DSi Sound (USA) (Rev 2).nds
NDS_PATH = sd:/roms/nds/Pokemon - SoulSilver Version (USA).nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - SoulSilver Version (USA).sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8500595/NDSBTSRP.LOG)

### Other notes
I believe this issue is similar to the soft-reset issue #259 from what I've tried to find (my computing knowledge is quite basic though). 
Only discovered DS homebrew about a month or two ago and am a huge fan of the work put into this. Any help would be greatly appreciated. Thanks

**Comment by RocketRobz** [comment]
Sounds like soft-resetting isn't working for you in DS mode for some reason.
I have no idea why this issue would occur, especially since this issue doesn't occur on my side.
Try re-installing TWiLight Menu++ by deleting the `TWiLightMenu` folder in `sd:/_nds/`, then following the installation steps again.

**Comment by dj2814** [comment]
Thanks for the reply, will try. Also, should I have Unlaunch installed or should soft-resetting work regardless if I have it or not?

**Comment by RocketRobz** [comment]
Soft-reset will work regardless if you have Unlaunch installed or not.

**Comment by dj2814** [comment]
I've tried reinstalling the latest version of Twilight Menu++, which still results in the same issue. I've also just been trying out previous versions of Twilight Menu++. So far, the closest I've come to getting a proper soft-reset was with TWiLight Menu++ v23.0.0, nds-bootstrap Release v0.50.0, where there isn't a white screen freeze, but instead brings me back to the camera where I have to re-enter TWiLight Menu++, and when I do enter, I am brought back to the game rather than the menu itself. Ideally, I'd want to be brought straight back to the in-game title screen, but this is the closest so far. Not sure if this helps.

**Comment by RocketRobz** [comment]
Then your issue seems to be related to Memory Pit.
If you have Flipnote Studio installed, then use Flipnote Lenny instead of Memory Pit.
If Flipnote Studio isn't installed, then install Unlaunch, and have it autostart TWLMenu++.
