### ISSUE TITLE
Implement DSiWare soft-reset to frontend (not turning off the device) in DSi-Mode loaded roms

### ISSUE THREAD

**Issue by Dartz150** [DS-Homebrew/nds-bootstrap#1401]
**Your console:**
DSi/3DS

**Launch Method:**
SD Card

**Version used:**
Release

This would allow 3DS users to save time each time they want to return to the frontend, as rebooting the console takes a significant amount of time, specially with big SD cards, and somehow avoid the known issue where the old3DS reboots back to Home Menu. This feature is currently supported with DSiWare roms.

**Comment by RocketRobz** [comment]
Implemented in 696842d6
