### ISSUE TITLE
Dragon Quest VI YVIP - Savegame corrupted when forcing DSi Mode

### ISSUE THREAD

**Issue by Nemris** [DS-Homebrew/nds-bootstrap#1403]
**Your console:** New 3DS

**Launch Method:** SD Card

**Version used:** Release v0.57.0

**Game tested/used/applicable:** YVIP

**Expected Behavior:** Saving the game produces a good savegame.

**Actual Behavior:** Saving the game while forcing DSi Mode results in a corrupted savegame, which is detected and deleted the next time the game is launched.

### Steps to reproduce
1. Enable DSi Mode in the game's settings via TWLMenu;
2. Launch the game and go to a church to save;
3. Reboot the game and observe it deleting the corrupt savegame.

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Dragon Quest VI - Realms of Reverie (Trimmed) [YVIP].nds
SAV_PATH = sd:/roms/nds/saves/Dragon Quest VI - Realms of Reverie (Trimmed) [YVIP].sav
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 0
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
LOADING_DARK_THEME = 1
LOADING_SWAP_LCDS = 1
LOADING_SCREEN_FOLDER = /_nds/TWiLightMenu/dsimenu/loading/
LOADING_FRAMES = 0
LOADING_FPS = 0
LOADING_BAR_Y = 0
LANGUAGE = 1
DSI_MODE = 2
BOOST_VRAM = 0
GAME_SOFT_RESET = 0
FORCE_SLEEP_PATCH = 1
COLOR_MODE = 0
LOADING_BAR = 1
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
DMA_ROMREAD_LED = -1
CACHE_FAT_TABLE = 0
HOMEBREW_ARG =
EXTENDED_MEMORY = 1
CACHE_BLOCK_SIZE = 0
MACRO_MODE = 0
REGION = 2
CARD_READ_DMA = 1
GUI_LANGUAGE = en
HOTKEY = 284
SDNAND = 0
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
USE_ROM_REGION = 1
B4DS_MODE = 0
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8666916/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
If it works fine in DS mode, then you should only run that game in DS mode.
As this game is an NTR type, there is no point in running it in DSi mode.
