### ISSUE TITLE
Pokemon mystery dungeon rescue team blue not saving/not reading save file

### ISSUE THREAD

**Issue by GodlyBDS** [DS-Homebrew/nds-bootstrap#1406]
old 3ds

**Launch Method:**
default

release

0668 - Pokemon Mystery Dungeon - Blue Rescue Team (Europe) (En,Fr,De,Es,It).nds

Game saving

Game is not reading save file

### Steps to reproduce
1. play the game save 
2.restart save gone
3. 
4. 

### Other notes
the save file in rims nds saves is created but every time i start the game its just asking me to start a new game

**Comment by RocketRobz** [comment]
Does the same issue occur with other games?

**Comment by GodlyBDS** [comment]
> Does the same issue occur with other games?

nope i have like pokemon pearl platinum and heart gold and they save and read their save file without any issues i tried everything i could think of i used multiple different roms i even got a dumped version from a friend and it just wont read the save file it is created and it is as big as the other save files so no 0kb corrupted file or smth

**Comment by GodlyBDS** [comment]
[0668 - Pokemon Mystery Dungeon - Blue Rescue Team (Europe) (En,Fr,De,Es,It).zip](https://github.com/DS-Homebrew/nds-bootstrap/files/8754856/0668.-.Pokemon.Mystery.Dungeon.-.Blue.Rescue.Team.Europe.En.Fr.De.Es.It.zip)

here is the latest save file it created maybe it helps if you need anything else i will try to provide more info

**Comment by GodlyBDS** [comment]
I tried another game pokemon mystery dungeon rescue team sky and there it saves and reads save files normally so it is just this game causing trouble

**Comment by GodlyBDS** [comment]
sorry to ask but is this still being looked on still didnt figure out how to make it read the safe file

**Comment by RocketRobz** [comment]
It is unknown how to fix this issue. You're also the only one who has reported this.
Can you try other regions of this game?

**Comment by GodlyBDS** [comment]
the us version of the game works just fine which is odd and i unfortunately cant change the language to german which is why i would love to use eu version instead because i dont like the english names and i prefer to play games in my native language i will try around more

**Comment by GodlyBDS** [comment]
okay i finally got it to work apparently it was a cheat issue idk why a cheat was active but it works now for anyone else having this problem try disabling your cheats xD
