### ISSUE TITLE
Digimon World Championship boot error

### ISSUE THREAD

**Issue by SparkLux** [DS-Homebrew/nds-bootstrap#1409]
**Your console: New 3DS XL**

**Launch Method: Boostrap 0.57.1 via Twilight Menu 24.8.0 with flashcart access**

**Version used: Release 0.57.1**

**Game tested/used/applicable: Digimon World Championship (USA).nds**

**Expected Behavior: Game boots normally**

**Actual Behavior: after first 2 boot logos, top screen turns red and game freezes**

### Steps to reproduce
1. Boot game
2. 
3. 

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
USE_ROM_REGION = 1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 1
HOTKEY = 284
NDS_PATH = fat:/Games/Digimon World Championship.nds
SAV_PATH = fat:/Games/saves/Digimon World Championship.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/8802618/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
Likely caused by the save data not being read correctly, so commit 6a16b563 should fix it.
This issue does not occur on my side.

**Comment by RocketRobz** [comment]
nvm, was testing in B4DS mode. The issue still occurs outside of B4DS mode.

**Comment by NightScript370** [comment]
Do we know if this is a data-loading error or an AP problem?

**Comment by RocketRobz** [comment]
It's a data loading error. The issue does not occur in B4DS mode or the console's SD card.

**Comment by RocketRobz** [comment]
Pretty sure this has been fixed some versions ago.
