### ISSUE TITLE
Nintendogs shuts down when saving

### ISSUE THREAD

**Issue by ChipsLabs** [DS-Homebrew/nds-bootstrap#1413]
**Your console: DSi XL

**Launch Method: Twilight with unlaunch (not Hiya)

**Version used: [v24.9]

**Game tested/used/applicable: 0466 - Nintendogs - Dalmatian & Friends (E)(Legacy)

**Expected Behavior: Saving

**Actual Behavior: When Saving the DS crash and shut down

### Steps to reproduce
1. 
2. 
3. 

### nds-bootstrap.ini
[nds-bootstrap v0.58.0]

**Comment by RocketRobz** [comment]
Does this happen with other games?
Also, please upload `nds-bootstrap.ini` from `sd:/_nds/`, instead of placing the version there.

**Comment by RocketRobz** [comment]
Closing due to no response, and no one else reporting the same issue.
