### ISSUE TITLE
Petz Nursery 2 - Touch input does not work and bottom-left button is missing

### ISSUE THREAD

**Issue by vengestone-dragoon** [DS-Homebrew/nds-bootstrap#1415]
Rom compatibility

**Comment by RocketRobz** [comment]
Please fill out the issue template.

**Comment by vengestone-dragoon** [comment]
The game "Petz Nursery 2" appears to run fine but it's gui is completely missing when the 3d renderer switches to the bottom screen

**Comment by RocketRobz** [comment]
1. Are you using a DS, DSi, or 3DS?
2. Are you using a flashcard, TWLMenu++ (no flashcard), or a forwarder (no flashcard)?
3. Does this issue still occur in nds-bootstrap v0.63.1?

**Comment by RocketRobz** [comment]
Just tried on my side, and I'm also encountering the issue.
Seems to be another case of a broken AP-fix, as enabling the AP-fix cheat fixes the issue.
