### ISSUE TITLE
Add support for external font files (if possible)

### ISSUE THREAD

**Issue by Tailx501** [DS-Homebrew/nds-bootstrap#1416]
**Is your feature request related to a problem? Please describe.**
The USA, EUR, and JPN version of Pyoro and Paper Plane works completely fine with no errors.
But when I try to load the Chinese (iQue) and the Korean version of Pyoro and Paper Plane, the game freeze to a black screen. It's probably do to a missing font file which I sure the CHN and KOR version requires to function properly.

**Describe the solution you'd like**
Add a support for `TWLFontTable.dat` file for both CHN and KOR. Maybe it can work like this.
`SD\_nds\TWLFontTable\Rename and put CHNFontTable.dat for Chinese ROMs Games if required.file`
`SD\_nds\TWLFontTable\Rename and put KORFontTable.dat for Korean ROMs Games if required.file`
And make it optional too (if they don't have the required file)

**Describe alternatives you've considered**
None

**Additional context**
I just want to open this issue up since I want to share what happened and gotten real close to get these two versions working.
And you should update the compatibility list for Pyoro and Paper Plane too.
Here's the list at the bottom.

Bird & Beans (USA) - ✅
Pyoro (EUR) - ✅
Tori to Mame (鳥とマメ) (JPN) - ✅
Saekong Alkong (새콩알콩) (KOR) - ❌
Niǎo hé Dòu (鸟和豆) (CN) - ❌

Paper Airplane Chase (USA) - ✅
Paper Plane (EUR) - ✅
Kami Hikouki (紙ヒコーキ) (JPN) -✅
Jongi Bihaenggi (종이비행기) (KOR) - ❌
Zhǐ Fēijī Tiǎozhàn (纸飞机挑战) (CN) - ❌

**Comment by RocketRobz** [comment]
Why was this closed?

**Comment by RocketRobz** [comment]
Implemented in 1810ee949e198a64f697665bbf5cc38299be4890

**Comment by Tailx501** [comment]
> Why was this closed?
Oh? I not sure why I decided to closed this. Probably because I lost interest.
