### ISSUE TITLE
Download Play Not working for games without cloneboot

### ISSUE THREAD

**Issue by Combatcarl2911** [DS-Homebrew/nds-bootstrap#1417]
Nintendo Dsi (hosting with twighlight)
Phat DS (download Playing)

Via SD

TWiLight Menu++: v24.10.1
nds-bootstrap: Release v0.59.1

Tetris DS 

Should show up in download play list

Download play isnt showing up at all 

### Steps to reproduce
1. Dsi on latest firmware with twighlight and another ds
2. launch tetris on twighlight and host a game
3. try to join on second ds (wont show up in download play)

**Comment by RocketRobz** [comment]
Try turning off card read DMA in the per-game settings menu.

**Comment by Combatcarl2911** [comment]
How do I get to that menu?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Combatcarl2911** [comment]
> Try turning off card read DMA in the per-game settings menu.

Probably a dumb question but how do i get to that menu

**Comment by RocketRobz** [comment]
In TWLMenu++, press Y to open the per-game settings menu, and scroll down to the option.

**Comment by Combatcarl2911** [comment]
No fix on that tried with it both off and on and got no result

**Comment by RocketRobz** [comment]
Make sure WiFi is turned on in TWLMenu++ Settings then.

**Comment by Combatcarl2911** [comment]
still no result it was working before i updated twlmenu, unsure what version i was on before though

**Comment by RocketRobz** [comment]
If you've already made sure to save the setting(s) by pressing B to exit TWLMenu++ settings, try downgrading to each version until it starts working again.

**Comment by RocketRobz** [comment]
Have you found out which version had Download Play working?

**Comment by Radriant** [comment]
This seems to be working as inteded, tested with a n2dsxl (host) and ds lite (DLP) and was able to find, download and play the game.
Tested on the latest nds-bootstrap commit (55c9a77) and the latest TWiLight Menu++ release (v25.2.1)
