### ISSUE TITLE
Doom 64 DS not work

### ISSUE THREAD

**Issue by JhulkerCraft** [DS-Homebrew/nds-bootstrap#1418]
I've been playing it on v24.8.0 and it was working fine, but after that version I get a guru meditation error when I select the difficulty, I'm playing on a Nintendo DSi with the latest version 1.4.5U and hiyaCFW installed TWiLight Menu++ v24.10.1
nds-bootstrap Release v0.59.1

**Comment by RocketRobz** [comment]
I don't see how v0.58.0 of nds-bootstrap can cause this issue.
Try deleting the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/`.]
If the issue persists, then switch to a theme in TWLMenu++ that isn't DSi, 3DS, Saturn, or HBL.

**Comment by RocketRobz** [comment]
Also, did you try TWLMenu++ versions v24.9.0 and v24.9.1?

**Comment by theone390** [comment]
I can't get past the difficulty select screen

**Comment by JhulkerCraft** [comment]
It already works correctly in the last update so far I was able to pass the difficulty selection

**Comment by JhulkerCraft** [comment]
The same thing happens with the port of duke nukem 3d and the neo geo emulator, in the old versions it worked and in the new ones it didn't.

**Comment by JhulkerCraft** [comment]
> No veo cómo una versión anterior a la v0.58.0 de nds-bootstrap puede causar este problema. Prueba a borrar la `patchOffsetCache`carpeta en `sd:/_nds/nds-bootstrap/`. Si el problema persiste, cambie a un tema en TWLMenu++ que no sea DSi, 3DS, Saturn o HBL.

**Comment by merntl** [comment]
Sooooo, does anyone have the doom 64 ds port. I've tried decompiling it. No luck tho.
