### ISSUE TITLE
Rhythm Paradise (EUR) random choppy/glitched audio

### ISSUE THREAD

**Issue by nor2101** [DS-Homebrew/nds-bootstrap#1419]
New Nintendo 3DS XL Eur

**Launch Method:**
SD Card, scfg is locked. Launching through TwlMenu++ on 3ds, no flashcart.

**Version used:**
Stable(release v0.59.1)

**Game tested/used/applicable:**
Rhythm Paradise (Europe) (En,Es,It) Decrypted rom
md5(ae9ba509d170bd63a00b38f4573e4e2b)
Sha-1(4f00036db66f409b695d3c4b98f5f77e24d8d48c)

**Expected Behavior:**
No audio glitches or choppiness

**Actual Behavior:**
Audio sometimes randomly starts to glitch up and skip.

### Steps to reproduce
1. Get the aformentioned dump
2. Play it for a while, trying different minigames
3. At some point, the audio should exhibit the aformentioned behaviour

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 384
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Super Mario 64 DS.nds
SAV_PATH = sd:/roms/nds/saves/Super Mario 64 DS.sav
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = it
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Other notes
This now closed issue reported a similar problem:
https://github.com/DS-Homebrew/nds-bootstrap/issues/131

**Comment by RocketRobz** [comment]
Please check if the issue still occurs in v0.63.1.
If it still occurs, then try turning off `Card Read DMA` in the per-game settings menu (opened by pressing Y in TWLMenu++).

**Comment by nor2101** [comment]
> Please check if the issue still occurs in v0.63.1. If it still occurs, then try turning off `Card Read DMA` in the per-game settings menu (opened by pressing Y in TWLMenu++).

I retested the game with the latest v0.63.2 (launched through the latest TWiLight Menu ++ release) and now everything seems to be fine. I did not need to set the `Card Read DMA` option to off, it just worked!

I'd close the issue if it's ok with you.

**Comment by RocketRobz** [comment]
Sure! Thanks for the report.
