### ISSUE TITLE
ACWW DS-to-DS connection crashes after connection is established

### ISSUE THREAD

**Issue by Aceina** [DS-Homebrew/nds-bootstrap#1420]
**Your console:**
New 3DS XL
and
3DS XL
Both using the latest Luma installs

**Launch Method:**
Launched via SD card & microSD card (90MB/s read, 20MB/s write on both 3DSs) using TwilightMenu++ v24.10.1

**Version used:**
Release version (v0.59.1)

**Game tested/used/applicable:**
Animal Crossing Wild World (Rev 1)
MD5: a5793ed9dde3a1918a2b91637d9baede
SHA1: 77fde3e30e1e6068395d1f96ea63be569b61c351

**Expected Behavior:**
Games should connect using ds to ds wifi (no internet connection needed) and allow you to play until you leave

**Actual Behavior:**
The games connect and send 1 player to the other's world but the connection crashes as soon as you gain control of your character (sometimes slightly sooner). A few times the game froze entirely and had to be hard reset; In most cases, it goes to the Resetti screen saying the connection failed.

### Steps to reproduce
1. Load both games and open Player 1's gate to ds-to-ds connections
2. Have Player 2 connect via their own ds-to-ds connection
3. Connection crashes soon after being transported

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/Animal Crossing - Wild World (USA) (Rev 1).nds
SAV_PATH = sd:/roms/nds/saves/Animal Crossing - Wild World (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
REGION = 1
AP_FIX_PATH = 
USE_ROM_REGION = 1
B4DS_MODE = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9023534/NDSBTSRP.LOG)
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9023538/NDSBTSRP.LOG)

### Other notes
Changing Arm Clock speed didn't help
Wifi is set to on
The connection does work in Bootstrap versions: v0.32.1, v0.33.0, and v0.34.0 but ceases to work in v0.35.0 and onward
(connections do occasionally fail after a minute or 5 in the working bootstraps, but fail every time repeatedly in the newer versions)

This issue was previously [reported here](https://github.com/DS-Homebrew/nds-bootstrap/issues/985) by others but closed before it was tested and confirmed fixed

**Comment by RocketRobz** [comment]
It got re-opened, lol

**Comment by RocketRobz** [comment]
Duplicate of #985

**Comment by Aceina** [comment]
Awkward, that's what I get for not double-checking I guess
Hopefully the new logs and data are helpful at least
