### ISSUE TITLE
SDK5 DS mode games not booting

### ISSUE THREAD

**Issue by SimPiko** [DS-Homebrew/nds-bootstrap#1424]
**Your console:** DSi XL, 1.4.5E

**Launch Method:** TWiLight Menu++ v24.12.0

**Version used:** v0.61.0 

**Game tested/used/applicable:** Puzzler World 2013 (Europe) MD5:d3cc5f2a2d3f6a1eda722a99b09fb8cb

**Expected Behavior:** After ~4ish seconds of "Loading", game should launch fine, without any errors

**Actual Behavior:** After much shorter "loading" screen (~1s), "CANT OPEN FILE" message shows up

### Steps to reproduce
1. Launch game
2. Let it load
3. Observe

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
ROMREAD_LED = 1
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 0
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/Puzzler World 2013 (Europe).nds
SAV_PATH = sd:/roms/nds/saves/Puzzler World 2013 (Europe).sav
PRV_PATH = sd:/ROMS/DSIWARE/_NET/!GG/SAVES/
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 1
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 1
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 1
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
AP_FIX_PATH =
HOMEBREW_ARG =
MACRO_MODE = 0
CARD_READ_DMA = 1
REGION = -1
GUI_LANGUAGE = en
HOTKEY = 284
APP_PATH = sd:/ROMS/DSIWARE/_NET/!GG/GG4671~1.NDS
SDNAND = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 0
USE_ROM_REGION = 1
B4DS_MODE = 0
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9073499/NDSBTSRP.LOG)

### Other notes
Game runs fine on previous bootstrap version (v0.60.0)

**Comment by RocketRobz** [comment]
Nothing DSiWare-related was changed, so it boots fine on my side.
Something looks wrong in `nds-bootstrap.ini`, so try deleting it, and re-launch the game.
If the issue persists, which theme are you using in TWLMenu++?

**Comment by SimPiko** [comment]
oh, right, forgot, i'm on R4 theme ('Park' skin, if that matters at all)
replacing bootstrap to previous release (v0.60.0) 'fixes' the game, but it looks like something broke the game in-between the two releases.
