### ISSUE TITLE
Rytmik Retrobits freezes

### ISSUE THREAD

**Issue by FoxBlocks** [DS-Homebrew/nds-bootstrap#1425]
**Your console:**
New 3DS XL, with Luma3DS and Boot9Strap, on version 11.15.0-47U.

**Launch Method:**
Via SD card on TWiLight Menu++. I don't think the SCFG question applies to me, because I'm not using a flashcard, but the SCFG access in Slot-1 setting is off.

**Version used:**
I tried both, and they both exhibit the same problem. The release version is v0.61.1, and the nightly hashes are:
SHA1: D505698833B9B803A05C18C23148FABF0DD212F2
MD5: 5B59AD48C08CB28687452C3E210A1E96

**Game tested/used/applicable:**
SHA1: A0A9D3245262D77CC25D084528C457ED78AAB154
MD5: 4E09CE4890E25511DB908DB65A5EE969
TID: TWL-KYRE-USA

**Expected Behavior:** Pressing Play in the song or clip editors should start playback.

**Actual Behavior:** The app freezes. The nds-bootstrap menu cannot be accessed while the app is frozen, and the app can only be exited via the home button or the power button.

### Steps to reproduce
1. Start Rytmik Retrobits
2. Wait until the song editor appears
3. Press the L button, or the on-screen Play button
4. The app will freeze

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/ROMs/DS/Rytmik Retrobits.nds
SAV_PATH = sd:/ROMS/DS/SAVES/RYTMIK~1.PUB
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 2
HOTKEY = 284
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = -1
USE_ROM_REGION = 1
DSI_MODE = 1
BOOST_VRAM = 1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
APP_PATH = sd:/ROMS/DS/RYTMIK~2.NDS
PRV_PATH = sd:/ROMS/DS/SAVES/  
GAME_SOFT_RESET = 1
DONORTWLONLY_NDS_PATH = sd:/ROMs/DS/Rytmik Retrobits.nds
```

### Logs
Release
```
findModuleParamsOffset:
Module params offset restored: 02004FF4
sdk_version: 05057531

arm9 is not compressed
hi heap end: 020221E4

old hi heap value: E3A007BE

new hi heap value: E3A007BD

Hi Heap Shrink Sucessfull

cardIrqEnable location : 02020AE0

SCFG_EXT location : 0238021C

cardIrqEnable location : 02384918

hookNdsRetailArm7
hookLocation arm7: 023A5538

ERR_NONE
hookLocation arm9: 02FE0020

Device list address: 03800F40
```
Nightly
```
findModuleParamsOffset:
Module params offset restored: 02004FF4
sdk_version: 05057531

arm9 is not compressed
hi heap end: 020221E4

old hi heap value: E3A007BE

new hi heap value: E3A007BD

Hi Heap Shrink Sucessfull

cardIrqEnable location : 02020AE0

SCFG_EXT location : 0238021C

cardIrqEnable location : 02384918

hookNdsRetailArm7
hookLocation arm7: 023A5538

ERR_NONE
hookLocation arm9: 02FE0020

Device list address: 03800F40
```

### Other notes
Just a question. Why was DSiWare Booter removed from the 3DS version of TWiLight Menu++?

**Comment by RocketRobz** [comment]
`DSiWare Booter` was removed from 3DS consoles because Unlaunch never worked on 3DS consoles, and was left in as a bug.
nds-bootstrap has always been the only way to boot DSiWare from the SD card.
