### ISSUE TITLE
No No Kuni (Translated) Freezes after casting heal

### ISSUE THREAD

**Issue by MarioKartFan** [DS-Homebrew/nds-bootstrap#1432]
This is a highly specific and strange issue that is easily replicated. Ni No Kuni (English patched) will freeze if you use the magic spell Heal outside of battle on any of the “main” characters. 

If relevant, this version of the patch is the ARM7 version for Flashcards. The other version does not work with Bootstrap (just white screens on launch).

**Comment by Kaisaan** [comment]
Does this issue happen on the latest version of TWiLight Menu++ and nds-bootstrap? If so, does this issue also happen on an original (unpatched/untranslated) ROM?

**Comment by lifehackerhansol** [comment]
Closing due to invalid issue template (and no response from OP).

Feel free to reopen with issue templates filled out if this is still an issue.
