### ISSUE TITLE
Pokemon Black/White has red (AP) screen in DSi mode 

### ISSUE THREAD

**Issue by Pandawan** [DS-Homebrew/nds-bootstrap#1433]
**Your console:** Nintendo 3DS XL

**Launch Method:** SD Card with TWiLightMenu++

**Version used:** release, TWiLightMenu++ v25.2.0 and nds-bootstrap v0.63.1

**Game tested/used/applicable:** 5584: Pokemon - White Version (USA, Europe), NDSi Enhanced (md5: 77c34ba77f8fa44e7caf04f695db0560)

**Expected Behavior:** nds-bootstrap should AP patch the game when running, the game should work properly in DSi Mode.

**Actual Behavior:** When forcing DSi mode in TWiLightMenu++, starting the game (after "continuing" in the main screen) will have a red screen with a few white dots in the top right corner, which I believe is the anti piracy filter.

If starting from a clean save, must go through the prof tutorial (and get to the overworld) before red screen appears.

Note: I've also tried with and without the AP fix cheat but get the same result. However, disabling DSi mode fixes the issue. Still, it'd be nice if it worked in DSi mode.

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
ROMREAD_LED = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/Pokemon - White Version (USA, Europe) (NDSi Enhanced).nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - White Version (USA, Europe) (NDSi Enhanced).sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
USE_ROM_REGION = 1
B4DS_MODE = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
```

### Logs
```
findModuleParamsOffset:
Module params offset restored: 02004FCC
sdk_version: 0503757C
arm9 is compressed
findLtdModuleParamsOffset:
Ltd module params offset restored: 02004F8C
arm9i is compressed

AP-fix found
hi heap end: 020865E0

old hi heap value: 13A007BE

new hi heap value: 13A007BD

Hi Heap Shrink Sucessfull

patchCardNds

[SDK 5]

cardIrqEnable location : 02084980

startOffset : 02004000

cardRead location : 02076E64
02F78800

swi12 location : 0200451A

dsiModeCheck location : 02004EB4

dsiModeCheck2 location : 02085D54

cardRomInit location : 02077354

cardHashInit location : 0242EA78

cardPullOut location : 02077428

cardId location : 02076CE8


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02077020


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020770B0

Mpu change: 02086554

Mpu init end TWL: 02086584

reset location : 02087BE4

ERR_NONE

SCFG_EXT location : 02380258

Sleep location : 0238D250

cardIrqEnable location : 023848C4

Relocation src: 02380644

Arm7 (patch v5)
JumpTableFunc: 0238FB14
card id:	0238FAFC
card read:	0238FB0C
Eeprom read:	0238FB20
Eeprom page write:	0238FB38
Eeprom page prog:	0238FB50
Eeprom verify:	0238FB68
Eeprom page erase:	0238FB7C
swi12 location : 02383BA4

swiGetPitchTable location : 02383BB8

sdCardReset location : 02EB3824

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02391918

ERR_NONE
hookLocation arm9: 02FE0020

AP-fix applied
chipID: C001FFC2
```

**Comment by RocketRobz** [comment]
Red screen != AP

The issue is caused by card read DMA not working properly, so it needs to be turned off in the per-game settings menu.

**Comment by Pandawan** [comment]
Hmm, turning that setting off didn’t fix it. Do you know what else I could try?

**Comment by Squall-Leonhart** [comment]
redump the game with dsi data intact.

**Comment by RocketRobz** [comment]
Both TWLMenu++ and nds-bootstrap need to be updated as well.

**Comment by Pandawan** [comment]
I don’t think there was any issue dumping since the md5 hash matches that of no-intro entries.

Also I noticed that you pushed an update for nds-bootstrap and TWiLightMenu++ but that didn’t seem to have any effect.

I tried both with and without the “Card Read DMA” option for the per-game setting, still getting a red screen. 

Lmk if I should send another log with the new update

**Comment by RocketRobz** [comment]
I'm able to start the save in DSi mode fine.
Make sure all cheats are disabled by pressing L while in the cheat menu, and then saving.

**Comment by Squall-Leonhart** [comment]
no-intro has seperate entries for the initial dumps (without dsi block) and the later dumps that do have it intact.

Incomplete
f45fd94bb761721e30bd3a0a4fde124a 

Complete
37bff1431eda9b3a525737c7f59a432d

**Comment by Pandawan** [comment]
Looks like disabling cheats did the trick. Is there a reason cheats don’t work in this mode? 

Also it looks like the game correctly loads with Card Read DMA now, so should I leave it on or off?

And yeah, if you see the initial post my md5 matches the complete one.

**Comment by Squall-Leonhart** [comment]
DSI mode shifts the address stack, some cheats do work, anything needing button input doesn't,  The top most enablement cheat isn't needed on hardware and might break dsi mode boot.

**Comment by Pandawan** [comment]
Ig I’ll have to do some trial and error with those. 

I’m assuming that the cheats simply need some kind of offset to work again?

**Comment by Squall-Leonhart** [comment]
Correct, no work has started on updating the cheats file for dsi enhanced mode is underway to my knowledge.

https://github.com/DS-Homebrew/nds-bootstrap/issues/1144

**Comment by Pandawan** [comment]
Alright, well thanks a lot for the help! I don’t really need the cheats anyway (just to move faster) but I’ll see if maybe I can figure out the offset.
