### ISSUE TITLE
Animal Crossing Wild World RTC Not Working and Sky Glitching 

### ISSUE THREAD

**Issue by Planterarium** [DS-Homebrew/nds-bootstrap#1434]
**Your console:** DSi

**Launch Method:** SD using TWiLightmenu version 25.2.1, launched with Unlaunch 2.0 and Nds-bootstrap is on version 0.63.2. System firmware is 1.4.5E.

**Version used:** Release (0.63.2)

**Game tested/used/applicable:** Animal Crossing Wild World (Europe)

**Expected Behavior:** Game progresses with real time clock. Town tune chimes once on the hour.

**Actual Behavior:** Town tune chimes multiple times in an hour. Clouds on top screen move erratically and jump between positions randomly. This only seems to occur on the DSi and not on the 3DS.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b50/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 1
NDS_PATH = sd:/ANIMAL CROSS_ADMP01_00.nds
SAV_PATH = sd:/saves/ANIMAL CROSS_ADMP01_00.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B64
sdk_version: 030028A0
arm9 is compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 020E82A8

startOffset : 02000000

cardRead location : 02127620
03700000

swi12 location : 02000470

cardPullOut location : 02127D80

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02127954

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 021278BC

Mpu start: 02000A88

Mpu data: 02000B1C

Mpu init: 0211DE68

Mpu data alt: 0211DD04

Mpu start 2: 02000A90

Mpu data 2: 02000B20

Mpu init 2: 0211DE70

reset location : 0211E78C

ERR_NONE

Sleep location : 0238ADF8

cardIrqEnable location : 02380B18

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238028C
Relocation dst: 037F8000

Arm7 (patch v2)
cardReadEndAddr: 02388D68
cardstructAddr: 038090C0
readCacheEnd: 02388EA4
JumpTableFunc: 02388EA8
returned_A0_with_MKDS: 02388F48
addrOfSomething_85C0: 0238884C
anotherLocinA7WRAM: 038096E4
amal_8CBC: 02388F48
aFinalLocation: FE388F2C
Eeprom protect:	02388F88
Card id:	02388F90
Card read:	02388FB0
Eeprom read:	02388FC8
Eeprom page write:	02388FE0
Eeprom page prog:	02388FF8
Eeprom verify:	02389010
Eeprom page erase:	02389020
swi12 location : 0238948C

swiGetPitchTable location : 02384448

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F7C0

ERR_NONE
hookLocation arm9: 027E0000

chipID: 00003FC2

**Comment by RocketRobz** [comment]
Are you sure the chime occurs multiple times in an hour? Because that bug has been long since fixed.
As for the clouds issue, that's also been fixed in v0.63.2.

Try checking your SD card for errors using h2testw, because it sounds like it's reading data slowly, which isn't normal.
If no errors are found, then try re-installing TWiLight Menu++ and nds-bootstrap:
1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
2. https://wiki.ds-homebrew.com/twilightmenu/installing-dsi
If the issues persist, then try a new SD card.

**Comment by Planterarium** [comment]
Thank you for the reply. I have just reinstalled TWiLight Menu++ and nds-bootstrap and it seems to have fixed all of the above issues as far as I can tell. I used the helper tool on dsi.cfw.guide to install everything the first time around and I guess something messed up in the process. 

Have a good one!
