### ISSUE TITLE
Pokemon White Version 2 doesn't start

### ISSUE THREAD

**Issue by RzoregDe96** [DS-Homebrew/nds-bootstrap#1435]
**Your console:** Nintendo DSi LL

**Launch Method:** SD card/TWLMenu++ ver. 25.2.1 (nds-bootstrap v0.63.2)

**Version used:** Release

**Game tested/used/applicable:** TWL-IRDO-USA (White Version 2), TWL-IREO-USA (Black Version 2)

**Expected Behavior:** The game should've run properly

**Actual Behavior:** It stays on white screen after I hit start/A button, and no logo of nds-bootstrap is shown

### Steps to reproduce
1. It should be working on both DS-mode and DSi (TWL) mode.
2. 
3. 

### Logs
[nds-bootstrap_log.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/9335412/nds-bootstrap_log.zip)
I didn't find the "NDSBTSTRP.log" file on my SD, even I set the logging option to 1.

**Comment by RocketRobz** [comment]
Sounds like an issue with your SD card.
Try reformatting by following this guide: https://dsi.cfw.guide/sd-card-setup.html

The game works fine for other users.

**Comment by RzoregDe96** [comment]
My SD card works fine, and I can run other games from it. I just can't open White 2.

**Comment by RocketRobz** [comment]
You never know. Please try to reformat it anyways.
