### ISSUE TITLE
ROMs not booting on flashcard with SCFG access + SD access

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/nds-bootstrap#1443]
**Your console:** Nintendo DSi

**Launch Method:** DSTT/Ace3DS+ with SCFG unlocked + SD access

**Version used:** bf4bdcb56c05ca264ff580cf18fe402e3daa71fd

**Game tested/used/applicable:** Super Mario 64 DS USA Rev 1, Pokemon Black 2 USA

**Expected Behavior:** Game boots

**Actual Behavior:** Game does not boot

### Steps to reproduce
1. Turn on SCFG access in Slot-1 + SD access in Slot-1
1. Boot flashcard from TWiLight
1. Boot game

### nds-bootstrap.ini
```ini
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = fat:/0056 - Super Mario 64 DS (USA, Australia) (Rev 1).nds
SAV_PATH = fat:/saves/0056 - Super Mario 64 DS (USA, Australia) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 1
DEBUG = 1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
AP_FIX_PATH =
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9389977/NDSBTSRP.LOG)

**Comment by lifehackerhansol** [comment]
Whatever happened between the mentioned commit and v0.64.1, now it freezes on nds-bootstrap loading screen.

Can anyone with a DSTT (or a DSTT clone) reproduce this?

**Comment by RocketRobz** [comment]
Using an R4i SDHC 3DS card (which is a DSTT), I cannot reproduce this.

**Comment by lifehackerhansol** [comment]
For some reason, it works on my N3DS, but not on my DSi...

**Comment by RocketRobz** [comment]
Works fine on my DSi XL with Unlaunch and no hiyaCFW. Are you using hiyaCFW?

**Comment by lifehackerhansol** [comment]
I'm directly booting via Unlaunch.

**Comment by lifehackerhansol** [comment]
Tracked the issue down to the SD card.

Which is weird, a format didn't fix it either. Had to switch to another SD card I had lying around. I'll run a hardware test and see what comes out of it.

*sigh* that was my last full-size SD card...
