### ISSUE TITLE
pokemon white 2 menu lag. most recent nds-bootloader version.l

### ISSUE THREAD

**Issue by mrpejoflan** [DS-Homebrew/nds-bootstrap#1445]
https://www.reddit.com/r/NDSHacks/comments/wvd3lg/how_can_i_fix_this_the_bag_menu_is_so_slow_im/?utm_medium=android_app&utm_source=share

i have a dsi xl and have a dsi enhanced pokemon white 2.

i have tried:
-reformating the sd card correctly
-updating nds-bootloader
-difrerent roms
-ds mode (worked fine but i need the wpa support from dsi mode)

**Comment by RocketRobz** [comment]
Unfortunately, this cannot be fixed without breaking DSi mode compatibility in other games, so the only solution is toeither play it on 3DS, or just launch the original cartridge.

**Comment by mrpejoflan** [comment]
hey i just updated to the newest version of twmenu and bootloader and now the menus in bw are hell. they are so slow that you have to press multiple times the buttons for it to register and now somehow the pokedex menu is now affected (it wasnt before) the game is now unplayable in dsi mode and now i have no way to play online.
something needs to be reworked in some way or something. its affecting all dsi supported pokemon games.
