### ISSUE TITLE
Partially strange Japanese display in in-game menu

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1452]
Japanese display of bootstrap after V0.64.00 (maybe from 6553be7?) is partially strange.

Also, although it has not been confirmed when, some iWARE
is not working properly.

example
"Most of the G.G. series"…The game does not start (whiteout)
"Solitaire DSi": Does not start when started newly (whiteout).
If you use the save data created by installing with TMFH, you can start normally. (However, icon animation does not work)

If I have a little more time, I can examine it in more detail...

**Comment by RocketRobz** [comment]
Which titles of the G.G. Series are booting, and which ones aren't booting?
I tried All Breaker, Assault Buster, and Black X Block, and they boot for me (all USA region).

**Comment by RocketRobz** [comment]
Also, which "Solitaire DSi" are you referring to?
I tried Touch Solitaire, and it boots on my side with the save created by TWLMenu++.

**Comment by RocketRobz** [comment]
Opened an issue for it: https://github.com/DS-Homebrew/TWiLightMenu/issues/2031

**Comment by KururinX** [comment]
ALL BLAKER
ASSAULT BUSTER
CHOU HERO AUGA
CHOU HERO AUGA 2
Energy Chain
Score Attacker
Shinobi Karakuri Den
Shinobi Karakuri Den 2
Vertex
Wonder Land
Z.ONE
Z.ONE2
  I confirm with these

Solitaire is the one whose icon is a black cat.

**Comment by RocketRobz** [comment]
I assume those are all Japanese versions then.
Do you have access to the USA versions? If so, and they boot, try renaming the save data of them to the Japanese versions, and see if they fix them not booting.

**Comment by KururinX** [comment]
For now, you can only access the Japanese version.

**Comment by Epicpkmn11** [comment]
Is this about glitched text (ex. ゲ上ムを自動) in the in-game menu or games not working? these seems to be two different issues here.

Glitched text is fixed by #1453, however that doesn't fix the games not starting.

**Comment by KururinX** [comment]
Re:Epicpkmn11

I didn't know which problem caused the phenomenon, so I listed them all together.
