### ISSUE TITLE
C-Gear slows down card read speed

### ISSUE THREAD

**Issue by mrpejoflan** [DS-Homebrew/nds-bootstrap#1454]
hey i just updated to the newest version of twmenu and bootloader and now the menus in bw are hell. they are so slow that you have to press multiple times the buttons for it to register and now somehow the pokedex menu is now affected (it wasnt before) the game is now unplayable in dsi mode and now i have no way to play online.
something needs to be reworked in some way or something. its affecting all dsi supported pokemon games.

**Comment by RocketRobz** [comment]
If you turned off card read DMA, then please turn it back on, and update to the latest nds-bootstrap nightly.
https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z

After adding the nightly (and replacing the existing one), open the per-game settings, and set `Bootstrap` to `Nightly`.

**Comment by RocketRobz** [comment]
I'm not experiencing the slowness issue on my side, so hopefully the nightly fixes it on your side.

**Comment by mrpejoflan** [comment]
after doing everything you said, nothing has changed. im using a dsi xl and the latest version of both, dma is enabled, as well as bootstrap nightly. 

the slow bag menu hasn't gone away or got better to an extent as it was before. the bag icons are still very unresponsive and laggy

**Comment by RocketRobz** [comment]
Does downgrading nds-bootstrap fix the issue?

**Comment by RocketRobz** [comment]
Wait, I think I see what's wrong.
Is C-Gear turned on? If so, then it needs to be turned off. Using wireless makes card read speeds slow in order to avoid communication errors.

**Comment by mrpejoflan** [comment]
Yes!!! it works to some extent, there is now very minimal lag. that seems to be the fix. thanks!
