### ISSUE TITLE
Jam With The Band boots to a red screen

### ISSUE THREAD

**Issue by JohnSmith2007** [DS-Homebrew/nds-bootstrap#1455]
Old 3DS XL
**Your console:**

 SD Card
**Launch Method:**

 Release
**Version used:**

 No clue of what any of that is
**Game tested/used/applicable:**

 Game should have booted normally
**Expected Behavior:**

 screen turned red, and stays there indefinitely
**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3. 

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/4950 Jam with the Band (EU)(M5).nds
SAV_PATH = sd:/roms/nds/saves/4950 Jam with the Band (EU)(M5).sav1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
HOMEBREW_ARG =
DONOR_NDS_PATH = sd:/roms/nds/5514 Rock Band 3 (US)(M5).nds
GAME_SOFT_RESET = 1
USE_ROM_REGION = 1
GUI_LANGUAGE = en
REGION = 2
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
B4DS_MODE = 0
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
```

### nds-bootstrap.ini

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9592890/NDSBTSRP.LOG)

### Logs

 
![20220917_195631](https://user-images.githubusercontent.com/45465767/190881881-7f15df5e-af6e-4bf7-82fc-a3924b0b6dab.jpg)

**Comment by RocketRobz** [comment]
Which version of nds-bootstrap did you use?

**Comment by RocketRobz** [comment]
I'm not encountering this on latest nightly. If you're encountering this issue on v0.64.1, then try updating to latest nightly.
https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z

After adding the nightly (and replacing the existing one), open the per-game settings, and set `Bootstrap` to `Nightly`.

If the issue persists, then your ROM is corrupted, and needs to be replaced.

**Comment by JohnSmith2007** [comment]
> 

Tried 3 different ROMS from 3 different websites. None of them work on my 3DS, but function just fin in an emulator like Desmume. This is such a croc of shit.
