### ISSUE TITLE
WarioWare: Snapped! (debug build) does not boot

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1462]
**Your console:** DSi

**Launch Method:** Unlaunch/SD card

**Version used:** 84d547a

**Game tested/used/applicable:** WarioWare: Snapped! debug build
```
from_Nintendo.rar
KUWV01D.srl
CRC32: F98D5937
SHA1: 45481fb0d897fd03efe818822a2e5a93855d8a86
Build date according to the debug menu: 2009/03/25 14:13:15
SVN date according to the debug menu: 2009/03/25 14:08:20
```
Feel free to edit out any of the above if it's too much information for this sort of thing.

**Expected Behavior:** The game would boot.

**Actual Behavior:** White screens are displayed instead. I waited several minutes with no change. The in-game menu is not accessible, either.

### Steps to reproduce
1. Run the specified game with nds-bootstrap

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/KUWV01D.srl
SAV_PATH = sd:/ROMS/NDS/SAVES/  
DONOR_SDK_VER = 5
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 3
BOOST_CPU = 1
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
LANGUAGE = -1
DSI_MODE = 1
BOOST_VRAM = 1
SOUND_FIX = 1
GAME_SOFT_RESET = 1
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 1
SOUND_FREQ = 1
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = -1
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
APP_PATH = sd:/ROMS/NDS/KUWV01D.SRL
PRV_PATH = sd:/ROMS/NDS/SAVES/  
SWI_HALT_HOOK = 0
HOMEBREW_ARG =
B4DS_MODE = 1
USE_ROM_REGION = 1
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
AP_FIX_PATH =
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9652117/NDSBTSRP.LOG)

### Other notes
The ROM boots just fine when booted with Unlaunch.

**Comment by RocketRobz** [comment]
With the exception screen being added, please check if the white screen issue persists, or if the exception screen now appears.
If you're not on latest nightly, press L+Down+Select to allow the in-game menu to be controlled.

**Comment by spellboundtriangle** [comment]
The white screens persist on aec60c1.
