### ISSUE TITLE
Pokemon Ranger - Batonnage (JPN): cannot boot (Bottom screen turns red)

### ISSUE THREAD

**Issue by Wokann** [DS-Homebrew/nds-bootstrap#1463]
**Your console:** N3DSLL

**Launch Method:** SD card, SCFG locked

**Version used:** nds-bootstrap release v0.64.1

**Game tested/used/applicable:** SHA1(66766207dcc23023688efbbfc5bc6f6e4229e597), NTR-YP2J-JPN

**Expected Behavior:** running game normally

**Actual Behavior:** top screen turns white, bottom screen turns red with some white dots.

### Steps to reproduce
1. just boot the rom through nds-bootstrap in twilightmenu++

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 0
GUI_LANGUAGE = zh-CN
LANGUAGE = 6
DSI_MODE = 1
NDS_PATH = sd:/roms/nds/POKE_RANGER2_YP2J01_00.nds
HOMEBREW_ARG =
BOOST_CPU = 0
BOOST_VRAM = 0
SAV_PATH = sd:/roms/nds/saves/POKE_RANGER2_YP2J01_00.sav
RAM_DRIVE_PATH = sd:/null.img
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs
```
findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04017531
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 020649F4

startOffset : 02000000

cardRead location : 0206FA3C
03700000

swi12 location : 02000296

cardPullOut location : 0206FF98

cardId location : 0206FB2C


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0206F78C


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0206F828

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020664F8

Mpu data alt: 02066260

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 02066500

reset location : 02067410

waitCpuCycles location : 02067334

ERR_NONE

Sleep location : 0238A238

cardIrqEnable location : 02380BF0

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023802A4
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 023886C8
Eeprom read:	023886D4
Eeprom page write:	023886EC
Eeprom page prog:	02388704
Eeprom verify:	0238871C
Eeprom page erase:	02388730
swi12 location : 02388AA0

swiGetPitchTable location : 02384138

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238ECF8

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80003FC2
```

### Other notes
no

**Comment by RocketRobz** [comment]
Please check if the bug is fixed in v0.66.0.

**Comment by Wokann** [comment]
> Please check if the bug is fixed in v0.66.0.

Still red screen. Now with an in-game menu showing "Error : Data Abort"

**Comment by Wokann** [comment]
@RocketRobz Sorry, but this bug hasn't been fixed up to now. Pokemon Ranger - Batonnage (JPN) still can't be played in nds-bootstrap not only 0.66.0, but also the lastest version(0.69.0). So it's still too early to close this issue.

**Comment by RocketRobz** [comment]
> @RocketRobz Sorry, but this bug hasn't been fixed up to now. Pokemon Ranger - Batonnage (JPN) still can't be played in nds-bootstrap not only 0.66.0, but also the lastest version(0.69.0). So it's still too early to close this issue.

It's fixed for me though? Maybe your ROM is corrupted.

**Comment by Wokann** [comment]
> > @RocketRobz Sorry, but this bug hasn't been fixed up to now. Pokemon Ranger - Batonnage (JPN) still can't be played in nds-bootstrap not only 0.66.0, but also the lastest version(0.69.0). So it's still too early to close this issue.
> 
> It's fixed for me though? Maybe your ROM is corrupted.

Sorry it's my fault. I cleaned my sd card and reinstall twllightmenu++ and nds-bootstrap, then it worked fine on ranger2 jap. Thanks for your guys' working!
