### ISSUE TITLE
Donor ROM issue 

### ISSUE THREAD

**Issue by Lolbg83** [DS-Homebrew/nds-bootstrap#1467]
**Your console:ds lite**

**Launch Method:f lashcart**

**Version used: release v0.64.1**

**Game tested/used/applicable:cave story/weir donor ROM games**

**Expected Behavior: game boots, i play, everything is ok**

**Actual Behavior: a weir donor ROM error popped up, i read somewhere that I had to set the donor ROM to sdk3/5 thing? Anyway i checked all of my games, most of them where in that range, but no"set as donor ROM option ever showed up**

### Steps to reproduce
1. Get cave story (dsi ware, not the other one)'ROM 
2. Move it to the r4
3. Try to play it

### nds-bootstrap.ini
Qjsjdowkbdjd

### Logs
Donuts are round

**Comment by RocketRobz** [comment]
In TWiLight Menu++, it tells you to set a DSi-Enhanced ROM as a donor ROM.
Do you know what a DSi-Enhanced ROM is?

**Comment by Lolbg83** [comment]
> 

I am so sorry, I fixed it, i should have just done my research before complaining, i am so sorry for making you waste your time

**Comment by NightScript370** [comment]
Not a waste of anyone's time. We're just glad you figured it out! :)
Closing... (feel free to open a new one any time you believe you found a bug, although best to join our Discord Server instead).
