### ISSUE TITLE
Rhythm Paradise (EUR) crashes (red-screen) at "blue birds 2" minigame

### ISSUE THREAD

**Issue by Janni9009** [DS-Homebrew/nds-bootstrap#1470]
**Your console:**
DSi XL

**Launch Method:**
SD Card, firmware 1.4.5, Unlaunch, SysNAND, SCFG unlocked

**Version used:**
nds-bootstrap release v0.65.1
TwilightMenu++ release v25.4.0

**Game tested/used/applicable:**
Rhythm Paradise (EUR)
TitleID: NTR-YLZP-EUR
SHA1: b041870c381ece882cda21e3fc3a522b60c4841f
MD5: 20ecda50b5202804106fa776e4af3020

**Expected Behavior:**
The game should load into the intro screen, then the minigame.

**Actual Behavior:**
The game crashes immediately after fading-to-black/before loading the intro with a red bottom-screen and several white dots along the left side, as well as a black top-screen.

### Steps to reproduce
1. Play the game through until unlocking the "blue birds 2" minigame (38/50 total)
2. Tap the OK button to launch the minigame, resulting in a crash.

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b50/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/games/RHYTHMPARADI_YLZP01_00.nds
SAV_PATH = sd:/games/saves/RHYTHMPARADI_YLZP01_00.sav
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
APP_PATH = sd:/ROMS/DSI/CLUBHO~3.NDS
PRV_PATH = sd:/ROMS/DSI/SAVES/
GAME_SOFT_RESET = 1
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9789444/NDSBTSRP.LOG)

### Other notes
Game dumped using GM9i on-console.

**Comment by RocketRobz** [comment]
Please check TWLMenu++ Settings if it shows nds-bootstrap v0.65.1. If it shows v0.65.0 or an older version, then please update nds-bootstrap.

**Comment by Janni9009** [comment]
Well then, didn't even notice the version number on the top screen at first and sure enough, looks like I messed up updating my DSi. I was indeed still on v0.65.0.
Closing the issue, works fine with now properly installed v0.65.1.
