### ISSUE TITLE
Super Mario 256 0.1.4 cannot pass file select + inconsistent crashes while loading in B4DS

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1479]
**Your console:** DSi XL

**Launch Method:** R4 3DS UPGRADE SDHC Revolution for 3DS DSI XL/LL DSL DS GOLD Pro Real Time Save r4isdhc.com 2021, SCFG locked, autobooting TWLM++

**Version used:** 75aea63

**Game tested/used/applicable:** [Super Mario 256 (0.1.4)](http://kuribo64.net/get.php?id=Wx1BNA6YvghU40As)

**Expected Behavior:** After the loading and intro screens and selecting a file, the game would be played normally.

**Actual Behavior:** The game freezes after the file selection. It also often freezes before, during, or after the loading screen.

### Steps to reproduce
1. Load SM256 0.1.4 demo
2. Attempt to begin a file, if you get to file select in the first place

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = fat:/roms/nds/Super_Mario_256_v14.nds
SAV_PATH = fat:/roms/nds/saves/Super_Mario_256_v14.sav1
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 1
DSI_MODE = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
LOGGING = 1
DEBUG = 1
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
```

### Logs
[Taken on a launch where the loading screen did not appear]
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9847151/NDSBTSRP.LOG)

### Other notes
N/A

**Comment by RocketRobz** [comment]
Does this issue still occur in later versions?

**Comment by spellboundtriangle** [comment]
Ah, forgot about this issue. As said in #1481 
> Super Mario 256 appears to be working as well
