### ISSUE TITLE
the Dsi Soulsilver Pokémon Silver Edition Game Gives Error: Data Abort When Entering Game

### ISSUE THREAD

**Issue by ATRUZ9** [DS-Homebrew/nds-bootstrap#1483]
**Your console:**
Dsi

**Launch Method:**
SD card

**Version used:**
25.5.0

**Game tested/used/applicable:**
Pokémon Edition silver Soulsilver 

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by RocketRobz** [comment]
Please fill out the above issue template.

**Comment by RocketRobz** [comment]
Also, if this is a ROM hack, try manually AP-patching the ROM using DS-Scene ROM Tool, then apply the ROM hack patch to the AP-patched ROM.

**Comment by ATRUZ9** [comment]
No es un truco de rom

**Comment by ATRUZ9** [comment]
La herramienta de ROM de DS-Scene cómo hago eso

**Comment by RocketRobz** [comment]
If you can read English, then please post in English as well.

**Comment by ATRUZ9** [comment]
Sorry

**Comment by ATRUZ9** [comment]
It's not a rom hack

**Comment by ATRUZ9** [comment]
DS-Scene ROM Tool, how do I do that?

**Comment by ATRUZ9** [comment]
It's not a rom hack

**Comment by ATRUZ9** [comment]
DS-Scene ROM Tool, how do I do that?

**Comment by PokeMatt22** [comment]
Hey @RocketRobz, having a similar issue. when I play my Pokemon HG, it'll play for a minute or two, before saying in basically all red: ERROR: DATA ABORT. Not sure what the issue could be. I am using the latest firmware. Thanks.

**Comment by RocketRobz** [comment]
> Hey @RocketRobz, having a similar issue. when I play my Pokemon HG, it'll play for a minute or two, before saying in basically all red: ERROR: DATA ABORT. Not sure what the issue could be. I am using the latest firmware. Thanks.

Is the ROM modified in any way?

**Comment by PokeMatt22** [comment]
To my knowledge, no. It is a normal ROM downloaded online. I dont have a randomizer or anything of the such.

**Comment by RocketRobz** [comment]
> To my knowledge, no. It is a normal ROM downloaded online. I dont have a randomizer or anything of the such.

Is the game being run from a flashcard or the console's SD card?

**Comment by PokeMatt22** [comment]
The console's SD Card, it's an 8GB SD card, so thats my best assumption. Here's a picture. got this from a friend so. 

![IMG_8276](https://user-images.githubusercontent.com/122332119/211452948-15cb600d-a123-4151-ae8f-18a1ea05de43.jpg)

If that doesn't work, it's an SDHC Card 8GB SanDisk.

**Comment by RocketRobz** [comment]
> The console's SD Card, it's an 8GB SD card, so thats my best assumption. Here's a picture. got the DSi from a friend so.
> 
> ![IMG_8276](https://user-images.githubusercontent.com/122332119/211452948-15cb600d-a123-4151-ae8f-18a1ea05de43.jpg)
> 
> If that doesn't work, it's an SDHC Card 8GB SanDisk.

Are you using cheats?

**Comment by PokeMatt22** [comment]
Nope, fully clean game since i started playing. Not sure what it could be.

**Comment by RocketRobz** [comment]
> Nope, fully clean game since i started playing. Not sure what it could be.

Are you sure the ROM is clean? Since you got it from online, there's a chance it may actually be corrupted.
I recommend dumping the ROM from your own cartridge instead: https://dsi.cfw.guide/dumping-game-cards.html

**Comment by PokeMatt22** [comment]
Yeah, so I reinstalled a new ROM, and for now atleast, its working fine. Ill remessage the thread if anything changes. Thanks man, I appreciate the fast response.

**Comment by Yeethawed64dot7z** [comment]
I'm having the same issue no matter what i do on one of my sd cards it will never work on that sd card giving the data abort error but it works perfectly on my other one

**Comment by Bee684** [comment]
I have the same issue, it seems a solution hasn't been found. Any updates? @RocketRobz I am using a randomized file, randomized with PokeRandoZX. Even though these other people weren't, we're getting the same issues. I just installed TWiLight Menu++ a few days ago. Is there no way to play a randomized Pokemon game on it? 

Honestly, it's playable. When the error occurs I just have to go back to the last time I saved. It just pops up often, is a bit tedious and annoying, and might happen in the middle of important battles, so I'd prefer not to power through the issue and find a solution, if it is possible.

**Comment by RocketRobz** [comment]
> I have the same issue, it seems a solution hasn't been found. Any updates? @RocketRobz I am using a randomized file, randomized with PokeRandoZX. Even though these other people weren't, we're getting the same issues. I just installed TWiLight Menu++ a few days ago. Is there no way to play a randomized Pokemon game on it?
> 
> Honestly, it's playable. When the error occurs I just have to go back to the last time I saved. It just pops up often, is a bit tedious and annoying, and might happen in the middle of important battles, so I'd prefer not to power through the issue and find a solution, if it is possible.

What you could try doing is applying the .ips file from this TWLMenu++ repo (somewhere in the `resources` folder) to the clean ROM, and then randomize the ROM with the .ips patch applied.

**Comment by SenjuSlh** [comment]
Hello may i ask where is the ".ips file from this TWLMenu++ repo (somewhere in the resources folder)" where can i download it

**Comment by SenjuSlh** [comment]
I found the ressources but there are a lot of  ips folder how can i know which one is my pkmn game

**Comment by RocketRobz** [comment]
Seems to have been caused by lack of SD card space, as checks have been implemented as of recent versions.
