### ISSUE TITLE
Touchscreen not working in certain DS roms

### ISSUE THREAD

**Issue by PovertysFinest** [DS-Homebrew/nds-bootstrap#1485]
Old 3DS LL

SD card, boot9strap 1.4+Luma3DS v11.0

release TWiLight Menu++ v25.5.0 & nds-bootstrap v0.66.0

Games tested on: Pokemon White 2, Fossil Fighters, Kingdom Hearts Re:Coded, Radiant Historia, Avalon Code.

Game should detect when touching or using touchscreen.

Not all games detecting use of touchscreen, whether at all or only in bottom left corner, and center-right portion of screen. Works completely fine in Pokemon White 2. Only works during conversations in Radiant Historia

### Steps to reproduce
1. Open up any ROMS mentioned above (except White 2).
2. Attempt to use touchscreen, whether on start screen or in-game.
3. Check if entire screen is not detected, or if certain sections are.

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Radiant Historia (USA).nds
SAV_PATH = sd:/roms/nds/saves/Radiant Historia (USA).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
SLEEP_MODE = 1
```

**Comment by RocketRobz** [comment]
Have you checked if this is the same case when playing from the cartridges or an emulator?

**Comment by PovertysFinest** [comment]
Tested it on an emulator and the problem does not occur, however, when tested on my Kingdom Hearts 358/2 Days cartridge, the problem persists.

**Comment by PovertysFinest** [comment]
Reinstalling Twilight menu or downgrading to v24.9.1 (the version used on another 3ds that does not have this problem) does not solve this issue. Have attempted trying to run the ROMS in both DS and DSi mode but problem persists.

**Comment by RocketRobz** [comment]
Sounds like the touch hardware is bugged then.

**Comment by RocketRobz** [comment]
Closing, as this is not an nds-bootstrap issue.
