### ISSUE TITLE
Game crashes with Error Data Abort! Whenever I perform a certain action in my game

### ISSUE THREAD

**Issue by Graciexoxo** [DS-Homebrew/nds-bootstrap#1491]
**Your console:**
3DS XL

**Launch Method:**
SD Card

**Version used:**

**Game tested/used/applicable:**

**Save file:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3. 

### Other notes
Playing sims 2, whenever i open my bag it crashes to this.

### Will you be available for future issues and/or replies?

![315520317_899758998059501_4261417544267194690_n](https://user-images.githubusercontent.com/118656400/202892245-d0dbf398-1789-4af9-ab0b-84b16b98fb43.jpg)

**Comment by RocketRobz** [comment]
Does this still occur in the latest version?
If so, try re-dumping the ROM.

**Comment by RocketRobz** [comment]
Closing due to no response, as well as the issue not being reported as of later versions.

**Comment by ayanami3** [comment]
I can confirm this issue is still happening with the latest version of Twilight Menu. Opening the bag produces the same crash on New 2DS XL.

**Comment by RocketRobz** [comment]
Try turning off card read DMA in the per-game settings menu (opened in TWLMenu++ by pressing Y button).

**Comment by ayanami3** [comment]
Fixed it. It's a known bug with the game related to the Alien Autopsy minigame, the "Pockets Anti-Corruption v2" AR cheat fixes the issue. It's on the main cheat database.
