### ISSUE TITLE
Freeze when attempting to take a screenshot in a DS game running in DSi mode

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/nds-bootstrap#1497]
**Your console:** DSi, N3DS XL

**Launch Method:** SD card

**Version used:** f8fad63

**Game tested/used/applicable:** Any DS game, _probably_. This effect didn't happen in the DSi-Enhanced title or DSiWare that I tried.

**Save file:** N/A

**Expected Behavior:** I would be able to take screenshots while running a DS game in DSi mode.

**Actual Behavior:** The system freezes, kind of. No crash screen is produced, but sleep mode can still be used.

### Steps to reproduce
1. Start a DS game in DSi mode
2. Open the in-game menu
3. Try to take a screenshot

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/gm9/out/MP_HUNTERS_AMHE01_00.nds
SAV_PATH = sd:/gm9/out/saves/MP_HUNTERS_AMHE01_00.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 2
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
HOTKEY = 284
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/10138657/NDSBTSRP.LOG)

### Other notes
None

### Will you be available for future issues and/or replies?
Yes

**Comment by spellboundtriangle** [comment]
Okay, I was able to get the log. Windows (or me) just wasn't seeing it, I guess.

**Comment by RocketRobz** [comment]
Does this issue still occur in later versions?

**Comment by AKA10195** [comment]
I have this freeze when I was playing Pokémon black on my o3ds nds bootstrap 1.0.3 and I lost my save data ;(

**Comment by AKA10195** [comment]
Well since the 1.1.0 fixed it this shall be closed
