### ISSUE TITLE
In-game menu crash in Diddy Kong Racing

### ISSUE THREAD

**Issue by iGom** [DS-Homebrew/nds-bootstrap#1498]
Diddy Kong Racing is crashing when trying to enter in-game menu, there is no any crash info, just black screen and then booting into TWLMenu++.

N3DSXL
TWLMenu++ v25.6.1
ndsbootsrap v0.67.0

https://user-images.githubusercontent.com/4786772/205524302-0d8cac0b-39b1-4e19-abd7-022f9e5791d5.MOV

**Comment by iGom** [comment]
Others games are fine https://user-images.githubusercontent.com/4786772/205524418-8256c927-dd00-4cbe-be53-b5e0177b0861.MOV

**Comment by RocketRobz** [comment]
This is because arm9 IRQ isn't hooked, which is required for the in-game menu to open.
A few other games also have this issue, such as *Golden Sun: Dark Dawn* (demo version only works, but the full version will likely have the same issue when it works as well).

**Comment by Peter0x44** [comment]
Another game with this issue is Tom Clancy's Splinter Cell - Chaos Theory

**Comment by RocketRobz** [comment]
The game no longer crashes, and will instead simply not open the in-game menu.
