### ISSUE TITLE
Ghost Trick freeze with a black screen when launching

### ISSUE THREAD

**Issue by ApolloRodriguez** [DS-Homebrew/nds-bootstrap#1500]
-> **Old 3ds** 
system version: 11.16.0

-> **TWLMenu++** v25.6.1
-> **ndsbootstrap** v0.67.0

-> **Launched via SD card** 

  **NDSbootstrap nightly or release?**
 -> I don't know, i use the default one preset in the original download.

  **Game:**
->Ghost Trick: Phantom Detective (USA, Europe. Then, later, AP Patched these roms).

 **What should have happened?**
Launch and open ghost trick without any problems.

 **What actually happened?** 
Can't open the game, it crashes // freezes with a black screen when i try to launch it from the menu.

 **Steps to reproduce**
1.  Open TwilightMenu++ from the 3DS menu.
2.  Wait until it opens to the folders, then go to the nds folder.
3.  Search from your list of games: Ghost Trick.
4.  Then, try to launch Ghost Trick.
5.  Wait for it...
6.  Game still doesn't show up.
7.  It's a Black Screen, and it frozen it up.

 **Anything else that may be relevant to the issue?**
Other games fuction normally, except for 999 Hours, this games appears crashing at launch with two red screens with some weird code text(?)
i'm totally newbie with code stuff (zero knowledge), so if this issue envolves some coding, please be pacient with me so i can understand every step ya make! 

  **Will you be available for future issues and/or replies?**
 Yes!

**Comment by RocketRobz** [comment]
TWiLight Menu++ uses release bootstrap by default.
Use Universal-Updater to get the nds-bootstrap nightly build, then use TWiLight Menu++ to switch the `Bootstrap` setting to `Nightly` in either TWLMenu++ Settings or the per-game settings menu.

If the issue persists, use clean non-patched ROMs of both 999 and Ghost Trick.

**Comment by ApolloRodriguez** [comment]
Sorry if i kept you waiting. I share the 3ds with my boyfriend and I'm very busy
I installed the nightly version with Universal-Uptader, so...
I'm quite confused, how do i see the nightly version?

**Comment by RocketRobz** [comment]
Open TWLMenu++ Settings, then switch to the nds-bootstrap settings page, and change the `Bootstrap` setting from `Release` to `Nightly`.

**Comment by ApolloRodriguez** [comment]
I put the nightly version, but didn't work well
(PS: i did use the non ap patched roms, and nothing happened beside the same error :c )
![20221211_213356](https://user-images.githubusercontent.com/119901785/206938861-ed799324-624e-45b1-9971-281c5e37b594.jpg)
![20221211_213411](https://user-images.githubusercontent.com/119901785/206938873-b9121e2d-dfa3-4b60-83ad-5682a7747ca7.jpg)
![20221211_213450](https://user-images.githubusercontent.com/119901785/206938884-15c4e73b-b046-4992-94b6-d4bb509d48bc.jpg)
![20221211_213537](https://user-images.githubusercontent.com/119901785/206938893-e4e4d397-a117-4032-a09e-833b6eedfda5.jpg)

**Comment by RocketRobz** [comment]
Try re-dumping your ROM(s) from the original cartridge(s) then.

**Comment by ApolloRodriguez** [comment]
So, uh...
i don't have any cartridges 
(sorry for kept you waiting for an answer :c )
what do i do in this case?

**Comment by RocketRobz** [comment]
Try updating both TWiLight Menu++ and nds-bootstrap to their latest versions using either Universal-Updater or the manual method.
If the issue persists, then buy the original game cartridge, which you can then get the ROM from.

**Comment by RocketRobz** [comment]
Closing, due to no response, as well as no recent reports of the issue from other users.
