### ISSUE TITLE
dsi games not working with a white screen

### ISSUE THREAD

**Issue by kevincrans** [DS-Homebrew/nds-bootstrap#1508]
**Your console:**
N2dsXL (eur)

**Launch Method:**
ds internet settings

**Version used:**
Twilight V25.6.1

**Game tested/used/applicable:**
own copy of european pokemon white

**Save file:**
[POKEMON_W_IRAO01_00.csv](https://github.com/DS-Homebrew/nds-bootstrap/files/10268161/POKEMON_W_IRAO01_00.csv)
**rename to .sav**

**Expected Behavior:**
The game loading after a cluster message

**Actual Behavior:**
after the cluster message. loading and sav file created, white screen

### Steps to reproduce
1. dump eur dsi game to sd
2. open twilight menu and select a random dsiware title with y
3. go back to the the dsi cart u want to play and press a

### nds-bootstrap.ini

<details><pre>

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = c
USE_ROM_REGION = 1
NDS_PATH = sd:/POKEMON_W_IRAO01_00.nds
SAV_PATH = sd:/saves/POKEMON_W_IRAO01_00.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
HOMEBREW_ARG =
APP_PATH = sd:/TITLES/000300~1/768/00000001.APP
PRV_PATH = sd:/TITLES/000300~1/768/SAVES/00000001.PRV
GAME_SOFT_RESET = 1
DONORTWLONLY_NDS_PATH = sd:/titles/00030004484e4750/768/00000001.app

</pre></details>

### Logs

<details><pre>
findModuleParamsOffset:
Module params offset restored: 02004FCC
sdk_version: 0503757C
arm9 is compressed
findLtdModuleParamsOffset:
Ltd module params offset restored: 02004F8C
arm9i is compressed

hi heap end: 020865E0

old hi heap value: 13A007BE

new hi heap value: 13A007BB

Hi Heap Shrink Sucessfull

patchCardNds

[SDK 5]

cardIrqEnable location : 02084980

startOffset : 02004000

cardRead location : 02076E64
02EF4000

swi12 location : 0200451A

dsiModeCheck location : 02004EB4

dsiModeCheck2 location : 02085D54

cardRomInit location : 02077354

cardHashInit location : 0242EA78

cardPullOut location : 02077428

cardId location : 02076CE8

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 02077020

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020770B0

reset location : 02087BE4

ERR_NONE

a7_findScfgExtOffset:
SCFG_EXT found

SCFG_EXT location : 02380210

findSleepPatchOffset:
Sleep patch not found

Trying thumb...
findSleepPatchOffsetThumb:
Thumb sleep patch thumb not found
Thumb sleep patch thumb alt found: 0238A94C

findCardIrqEnableOffset:
irq enable not found
irq enable alt not found
irq enable thumb found

cardIrqEnable location : 02383D44

findCardCheckPullOutOffset:
Card check pull out not found

Relocation src: 023805A8

Arm7 (patch v5)
JumpTableFunc: 0238CA4A
Eeprom read branch:	0238CA52
Eeprom read:	0238C5BC
Eeprom page write branch:	0238CA60
Eeprom page write:	0238C684
Eeprom page prog branch:	0238CA6E
Eeprom page prog:	0238C600
Eeprom verify branch:	0238CA7C
Eeprom verify:	0238C708
Eeprom page erase branch:	0238CA88
Eeprom page erase:	0238C764
findSwi12Offset:
swi 0x12 call found

findSwiGetPitchTableOffset:
swiGetPitchTable call SDK 5 found

swi12 location : 02382FD8

swiGetPitchTable location : 02382FEC

findSdCardResetOffset:
SD Card reset found

sdCardReset location : 02EAF49C

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0239DEC8

ERR_NONE
hookLocation arm9: 02FE0020

AP-fix found
AP-fix applied
</pre></details>

### Other notes
it also happens for my other dsi dumps, my sd is 32gb

### Will you be available for future issues and/or replies?
?
I'm occasionally always available and not a practical expert.

**Comment by RocketRobz** [comment]
Try reformatting your SD card by following this guide: https://dsi.cfw.guide/sd-card-setup.html

**Comment by kevincrans** [comment]
Thanks, I will cause it's idd running slow, luckily the titles I dumped confirmed to be working on melonds, phew.

**Comment by NightScript370** [comment]
> ds internet settings

Wait, why not just install a CIA to launch TWiLight directly rather than launch it through the DS Internet Settings menu?

**Comment by kevincrans** [comment]
Because I don’t use cfw (sometimes I use ntrboot for gm9, openagbfirm, region free and layeredfs)

**Comment by RocketRobz** [comment]
Did reformatting the SD card (and updating nds-bootstrap) fix the issue?

**Comment by RocketRobz** [comment]
Closing, due to no response.
