### ISSUE TITLE
Pokemon Black USA Slowdown After Some Time When Launched in Default DSi Mode Settings

### ISSUE THREAD

**Issue by slahapman** [DS-Homebrew/nds-bootstrap#1518]
**Your console:** DSi XL

**Launch Method:** SD card

**Version used:** TWiLightMenu v25.7.0 (nds-bootstrap v0.68.0)
TWiLightMenu v25.8.0 (nds-bootstrap v0.69.0)

**Game tested/used/applicable:** Pokemon Black (USA ROM Dump, no-intro verified)
SHA1SUM: 26ad0b9967aa279c4a266ee69f52b9b2332399a5

**Expected Behavior:** When running the game in the default DSi mode, the game should run without issues.

**Actual Behavior:** When set to the default DSi mode, after a while, the game will start to slow down at some point. The point in question isn't guaranteed as it seems to happen randomly after some while of play, but it becomes like the game has trouble loading in any new sprites or animations. (i.e. if somebody sends out their pokemon, the game will freeze up/slowdown along with the music, and then it will load at some point).

### Steps to reproduce
1. Play game in DSi mode.
2. After some time, the issue should occur.
3. Doesn't seem dependent directly on player actions or location. Could happen after 30 minutes, could happen after three hours, doesn't always happen in the same spot, but it does eventually always seem to happen.

### nds-bootstrap.ini
```[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/POKEMON B_IRBO01_00.nds
SAV_PATH = sd:/roms/nds/saves/POKEMON B_IRBO01_00.sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Other notes
Original Reddit threads about the issue here: https://www.reddit.com/r/NDSHacks/comments/10dfjzu/pokemon_black_slowdown_on_twl_v0680/
https://www.reddit.com/r/nds/comments/10e13pa/pokemon_black_slowdown_on_twl_v0680/

Tried with a brand new 32GB SanDisk Extreme U3/Class 10/V30 SD card along with a brand new 64GB Samsung ProPlus U3/V30 SD card, both of which were formatted and verified per https://dsi.cfw.guide/sd-card-setup.html and both of which are legitimate cards purchased directly from SanDisk and Samsung.

Also dumped my own original cartridge with GodMode9i twice, both times resulted in ROMs that matched no-intro's database.

Unfortunately, issue seems intermittent in cause. I was able to play for a few hours one time, and then another get issue right away. In some cases an area where the issue would occur would go away on console reboot, but the slowing down/loading issues would start up again a little ways on in somewhere else different. The game never outright crashed, but I usually saved and restarted once it started as it would start affecting everything and going slower.

This only seems to affect the game if ran in DSi mode (which it's set to by default). Forcing DS mode does cause the game to run without this slowdown, at least from what I've noticed. Settings above are from last DS mode test. Mainly reporting the issue for DSi mode. Willing to test with other settings in DSi mode.

### Will you be available for future issues and/or replies?
Yes.

EDIT: Of course, as soon as I write all this after work, I notice there's a new TWiLightMenu and nds-bootstrap release. I'll try it out again on that one and see.

EDIT: Can confirm it also happens on latest. Added version number above. Closing DSi lid for sleep mode seemed to help.

**Comment by RocketRobz** [comment]
Sounds like the slowdown is being caused by the C-Gear being turned on.
Is this the case on your side?

**Comment by slahapman** [comment]
No, I normally play with C-Gear off since I have wifi turned off on my console most of the time anyway. I also don't turn it back on during gameplay.

**Comment by RocketRobz** [comment]
Seems to have been fixed some versions ago.
