### ISSUE TITLE
Red screen trying to lauch games on DSi

### ISSUE THREAD

**Issue by Akire00** [DS-Homebrew/nds-bootstrap#1521]
**Your console:** Dsi

**Launch Method:** SD card

**Version used:** Release, 25.8.0

**Game tested/used/applicable:** Mario and Sonic 2010 olimpic games us, soulsilver us

**Save file:** there's no save file i can't launch the game

**Expected Behavior:** Launch a game 

**Actual Behavior:** 
![20230205_213945](https://user-images.githubusercontent.com/124542082/216866079-b3b5c0b5-3755-4c49-9960-3b1af030d3bc.jpg)

### Steps to reproduce 
I just try to launch the game

### nds-bootstrap.ini
I dont understand this

### Logs
This neither

### Other notes
Yes I already tried to turn off recently played list and it didn't work

**Comment by RocketRobz** [comment]
Try re-dumping your ROMs using GodMode9**i**.

**Comment by Akire00** [comment]
> Try re-dumping your ROMs using GodMode9**i**.

Wdym by redump?

**Comment by RocketRobz** [comment]
> Wdym by redump?

Use GodMode9**i** to dump the ROM again from your own cartridge.

**Comment by Akire00** [comment]
> > Wdym by redump?
> 
> Use GodMode9**i** to dump the ROM again from your own cartridge.

This is a rom downloaded from the internet, not from a cartridge

**Comment by RocketRobz** [comment]
> This is a rom downloaded from the internet, not from a cartridge

Probably the issue then. ROMs from the internet tend to be bad/corrupted.
We recommend dumping from your cartridge to ensure you have a good dump.

However, if you've tested that the ROMs work fine on emulators, then try re-installing TWiLight Menu++ using these guides:
https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

**Comment by Akire00** [comment]
Thanks I will try to get new roms to see if that works

**Comment by spellboundtriangle** [comment]
> Thanks I will try to get new roms to see if that works

Did it work?

**Comment by RocketRobz** [comment]
Closing, due to no response.
