### ISSUE TITLE
Pokémon Sacred Gold translation spanish white screen

### ISSUE THREAD

**Issue by Wiki5100** [DS-Homebrew/nds-bootstrap#1525]
Hello, I am using the latest version of Van Valentin's twiligth menu with the latest boostnds but the Pokémon Sacred Gold and the screen goes white after loading the boostnds,

**Comment by RocketRobz** [comment]
Please fill out the issue template.

**Comment by Wiki5100** [comment]
@RocketRobz please Rocket Sana :'3

**Comment by RocketRobz** [comment]
Try changing the `Run in` setting to `DSi mode` in the per-game settings menu (opened by pressing Y in TWLMenu++).

**Comment by lifehackerhansol** [comment]
Closing due to invalid issue template (and no response from OP)
