### ISSUE TITLE
Error 1 when booting game through menu

### ISSUE THREAD

**Issue by Ruqix** [DS-Homebrew/nds-bootstrap#1526]
**Your console:** Old 3ds

**Launch Method:** SD card, and firmware is on the latest version.

**Version used:** Release #11

**Game tested/used/applicable:** Pokemon Soul silver and Pokemon White 2

**Save file:**

**Expected Behavior:**
Was expecting to boot up

**Actual Behavior:**
Gave me an error when trying to boot for the first time
![IMG_4548](https://user-images.githubusercontent.com/125772266/219903261-ad55694d-3379-4b30-9d03-dec3b8617892.JPG)

### Steps to reproduce
1. 
2. 
3. 

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/nds/cf_ds.nds
SAV_PATH = sd:/nds/cf_ds.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
You need to install the SD forwarder pack using Universal-Updater for forwarders to work.
