### ISSUE TITLE
Pokémon Black and Black 2 ROM hacked converted CIA files won't work

### ISSUE THREAD

**Issue by Hardback247** [DS-Homebrew/nds-bootstrap#1529]
**Your console:**
New 3DS XL

**Launch Method:**
SD card

**Version used:**
TwiLightMenu++ v25.8.1 and nds-bootstrap v0.70.0

**Game tested/used/applicable:**
Pokémon Black and Black 2

**Save file:**

**Expected Behavior:**
I download ROMs for Pokemon Black and Black 2, and after using DS-Scene Rom Tool, I added the "Complete Unova Pokedex Edition" rom hack for the former, and "Black 2 Unova Dex" rom hack for the latter. While these two nds files do, in fact, work on TwiLightMenu, I would much rather have them be cia files, so that I could directly access them from the 3DS Home Menu.

**Actual Behavior:**
When I used Forwarder3-DS to turn the nds files to cia files, I instead get these weird brown icons on it. When I pressed the blue button on the bottom left, a cia was only made for Black 1, and not for Black 2. I decided to add the Black 1 cia file to my 3DS XL, but when I used FBI to bring it to the Home Menu, it turns out to be a blank icon with no words on it. What should I do to fix all of this?
![unnamed](https://user-images.githubusercontent.com/125831518/220204366-48311799-ffd2-41f7-9c83-cde0f96ee2e3.jpg)
![unnamed-1](https://user-images.githubusercontent.com/125831518/220204372-cca703fe-d92e-4626-af08-961bc0aae425.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/125831518/220204378-8c74d208-9c60-49aa-9189-21cbcca9fbd1.jpg)

### Steps to reproduce
1. 
2. 
3. 

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
This is not an nds-bootstrap issue.
Please move this to this Discord server: https://discord.gg/yD3spjv
