### ISSUE TITLE
Call of Duty: Black Ops don't doesn't work anymore

### ISSUE THREAD

**Issue by GuttoBarros09** [DS-Homebrew/nds-bootstrap#1531]
**Your console:** Nintendo 3DS

**Launch Method:** Via the SD Card. The SCFG is locked. 

**Version used:** I used the release version, most especific v0.70.0.

**Game tested/used/applicable:** Call of Duty: Black Ops. NTR-BDYE-USA

**Save file:** 
[Call of Duty - Black Ops (USA).zip](https://github.com/DS-Homebrew/nds-bootstrap/files/10832609/Call.of.Duty.-.Black.Ops.USA.zip)

**Expected Behavior:** The game should open, show the ESRB screen, and then go to the title screen.

**Actual Behavior:** The game opens, shows the ESRB screen, and instead of going to the title screen, the screen just goes black and the game doesn't progress. It stays with the black screen, and only comes back if you exit Twilight (special key command doesn't work).

### Steps to reproduce
1. Open the folder where the .nds rom is located
2. Select the game with Y button
3. Set the following settings: DSi Mode to Run and VRAM too
4. Press B, then A to iniciate game
5. Wait the ESRB mensage and then the black screen

### nds-bootstrap.ini 
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/10832628/nds-bootstrap.zip)

``` 
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Call of Duty - Black Ops (USA).nds
SAV_PATH = sd:/roms/nds/saves/Call of Duty - Black Ops (USA).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 1
DSI_MODE = 2
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
CONSOLE_MODEL = 2
LANGUAGE = -1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
REGION = -1
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 0
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 1
HOTKEY = 780
GUI_LANGUAGE = pt-BR
ASYNC_CARD_READ = 1
HOMEBREW_ARG =
SWI_HALT_HOOK = 0
B4DS_MODE = 0
USE_ROM_REGION = 1
SLEEP_MODE = 1
```

**Comment by RocketRobz** [comment]
The game works with default settings on my side.
Both DSi mode and DSi VRAM mode are settings which can break certain games, and the results may not be consistent across versions.
Please revert the settings back to their default ones.

**Comment by GuttoBarros09** [comment]
So, i just needed delete the folder named nds-bootstrap inside the _nds and restart game to back all normal, with the same configuration that i mentioned in the first issue report.

In more, thanks  @RocketRobz. The TWL++ is the best to use and fun! S2
