### ISSUE TITLE
Pokemon Soulsilver giving "Error: Data Abort" screen

### ISSUE THREAD

**Issue by MatthewSRR** [DS-Homebrew/nds-bootstrap#1533]
**Your console:** New 3DS XL

**Launch Method:** SD Card

**Version used:** nds-bootstrap v0.70.0. TWL v25.8.1

**Game tested/used/applicable:** Pokemon Soulsilver.

**Save file:** [Pokemon - SoulSilver Version (USA).zip](https://github.com/DS-Homebrew/nds-bootstrap/files/10914516/Pokemon.-.SoulSilver.Version.USA.zip) though I doubt there is much to find.

**Expected Behavior:** Game behaves like any other nds rom, launches and is playable.

**Actual Behavior:** Game crashes, does not even get to the game's title screen.
![nnnn](https://user-images.githubusercontent.com/127070982/223570040-7019f8f6-f981-4f09-988f-d140c0a21f7f.png)

### Steps to reproduce
1. Launch the game from the Twilight Menu
2. Red screen appears

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Pokemon - SoulSilver Version (USA).nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - SoulSilver Version (USA).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
USE_ROM_REGION = 1
DSI_MODE = 1
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs
N/A

### Other notes
I have tried at least seven different ROMs that I could find online, and I also tested multiple Heartgold ROMs. These two games are the only games that do not work for me, and both have the same problems. I looked into similar issues other people had, but they seem to be able to launch the game for a small amount of time, whereas I can't launch it at all. I tried installing other nds ROMs to see if they work, and they do. My SD card is 32gb, formatted correctly, however it is almost at full capacity, so I don't know if that's an issue.

### Will you be available for future issues and/or replies?
Yes.

**Comment by RocketRobz** [comment]
Please join our Discord server for assistance: https://discord.gg/yD3spjv

Closing, since this game is known to work fine for most users.
