### ISSUE TITLE
Super Mario 64 DS crashes

### ISSUE THREAD

**Issue by Leonardo5681** [DS-Homebrew/nds-bootstrap#1538]
Hello, today I was going to play Super Mario 64 DS, but when I opened it it crashed, and it only does it with super mario 64 ds. So I tried with an older version of nds-bootstrap, 0.54.1 and it worked perfectly. Please fix this bug

**Comment by RocketRobz** [comment]
The game works fine for me on DSi & 3DS with the latest nds-bootstrap version.

1. Which console are you using?
2. If you're using a flashcard, then which one?
3. Did you change any settings?

**Comment by Leonardo5681** [comment]
1. Nintendo DSi
2. I don't use flashcard
3. No
4. Bootstrap version. 0.70.0

**Comment by Leonardo5681** [comment]
the thing that doesn't fit me and that with the bootstrap version 0.54.1 it goes perfectly, updating it to 0.70.0 instead gives me an error and it only does it with mario 64 ds

**Comment by Leonardo5681** [comment]
![image00001](https://user-images.githubusercontent.com/92219720/227791955-25c991cc-16a5-4b8f-b9ef-e5426ffd256e.jpeg)

**Comment by Leonardo5681** [comment]
[ramdump (open it).zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11072381/ramdump.open.it.zip)
Here is the ram dump

**Comment by RocketRobz** [comment]
> ![image00001](https://user-images.githubusercontent.com/92219720/227791955-25c991cc-16a5-4b8f-b9ef-e5426ffd256e.jpeg)

Judging by the info from the image, it seems the nds-bootstrap installation went wrong.
Try re-installing using these guides:
https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

**Comment by Leonardo5681** [comment]
It doesn't work, same problem. But I don't like the fact that with an older version of bootstrap (0.54.1) it works great, but with 0.70.0 it doesn't. So it's bound to be a bug

**Comment by RocketRobz** [comment]
> It doesn't work, same problem. But I don't like the fact that with an older version of bootstrap (0.54.1) it works great, but with 0.70.0 it doesn't. So it's bound to be a bug

You seem to be the only one reporting it though.
What region is the ROM?

**Comment by Leonardo5681** [comment]
My rom is not corrupted, and anyway it doesn't go the same, I tried many non-European roms and in any case it didn't work, so there is something wrong with bootstrap, because with melonds it goes perfectly. It's give me the same error, the SAME FUCKING ERROR

**Comment by Leonardo5681** [comment]
Ok

**Comment by Leonardo5681** [comment]
I also formatted the SD, now I think it's my microSD because it's so many years old so, since I'm buying the SanDisk Extreme 32GB soon, I'll wait. Thank you all the same

**Comment by christopher3242** [comment]
> ![image00001](https://user-images.githubusercontent.com/92219720/227791955-25c991cc-16a5-4b8f-b9ef-e5426ffd256e.jpeg)

I remmber Red nds xl Of cousre.
