### ISSUE TITLE
Red screen crash when launching Ace Attorney Investigations 2 (Gyakutenkenji2) (Chinese translation)

### ISSUE THREAD

**Issue by AkihaDesu** [DS-Homebrew/nds-bootstrap#1539]
**Your console:**
NDSi

**Launch Method:**
SD Card

**Version used:**
0.70.0 release

**Game tested/used/applicable:**
Ace Attorney Investigations 2 (JP version, Chinese translated)

**Save file:**
[GK2.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11071245/GK2.zip)

**Expected Behavior:**
Game launches

**Actual Behavior:**
Red screen crash, but this rom works well in emulator

### Steps to reproduce
1. Launch the game via TWMenu++

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/GK2.nds
SAV_PATH = sd:/roms/saves/GK2.nds
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = ja
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Fixed by opening and saving the ROM in TinkeDSi.
Might be difficult to fix within nds-bootstrap.
