### ISSUE TITLE
[Pokemon Pearl version FR] crash at Wifi Connection screen

### ISSUE THREAD

**Issue by SeleDreams** [DS-Homebrew/nds-bootstrap#154]
Hi, i'm posting this bug report since this is a pretty annoying bug, i want to play online to pokemon pearl version (french version) i've patched the rom for Altwfc and the ds wifi setup menu works perfectly and detects the connection, however when i go to gts or anywhere else that uses the cwf nintendo, the game either crashes or is stuck in a soft lock (the game is still searching for a connection for hours without showing any error code)
so i'm wondering if it could be fixed

**Comment by Robz8** [comment]
It can be fixed, but I dunno what broke it.

**Comment by BtheDestroyer** [comment]
DS Wi-Fi Setup works because it's built into the 3ds and not homebrew. Search for any issue with playing games online and you'll find the problem currently being met with large games like Pokemon: the whole ROM cant be loaded into RAM so it can't communicate with Wi-Fi  correctly

**Comment by Robz8** [comment]
> the whole ROM cant be loaded into RAM so it can't communicate with Wi-Fi correctly
wat?

**Comment by pikachuk** [comment]
the pokemon pearl rom is around 40 mb, the 3ds has 128mb of ram, the 3ds system uses so much ram ?

**Comment by BtheDestroyer** [comment]
Other than https://gbatemp.net/threads/3ds-ram-for-ds-homebrew.346752/

**Comment by BtheDestroyer** [comment]
Unless my info is wrong. I'm on mobile so IDK how to edit that last post, but please correct me if I'm wrong.

**Comment by Robz8** [comment]
DSi mode on 3DS has access to 32MB, which is the amount dev/panda DSi units have.

**Comment by pikachuk** [comment]
"DS flash carts run in DS-mode, which means they run as if they were in an original 2004 model DS.
Use of the additional RAM would require 3DS-mode to be hacked, which it's not. "
but the 3ds mode is now hacked, so i don't know if nds bootstrap is able to use all the 3ds ram

**Comment by Robz8** [comment]
He meant that it would require reverse-engineering TWL_FIRM.

**Comment by pikachuk** [comment]
oh i see
i wonder if it would be hard to do, since "theorically" it's just a variable to change

**Comment by pikachuk** [comment]
it depends on how it's implemented

**Comment by pikachuk** [comment]
I've a basic level of C++ i don't know if i could help in anything
is there some basic things that require help ?

**Comment by ahezard** [comment]
Is this still true?

**Comment by RocketRobz** [comment]
Closing, due to no response.
