### ISSUE TITLE
Final Fantasy: The 4 Heroes of Light - nds-bootstrap save loading issue

### ISSUE THREAD

**Issue by RyuuSlayer** [DS-Homebrew/nds-bootstrap#1540]
**DSi XL**

**Launch Method: Flashcard (R4iSDHC.com labled "2015")**
-> using the autoboot included from release page. And YSMenu for when i don't use nds-bootstrap.

**Version used:**
I used both release and nightly from the latest release here from github releases. + i tried the newest Build Bot nightly which i included in the following zip.
[Used bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11073301/Used.bootstrap.zip)

**Game tested/used/applicable: https://datomatic.nointro.org/index.php?page=show_record&s=28&n=5259 -> used a clean dump & checked it against DAT using RomVault.**

**Save file:**
[Saves.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11073285/Saves.zip)
Included is both a save created by nds-bootstrap which won't load. And a save created with the cards fw by TWMenu using ysmenu, the one from firm loads without problems, which means this is a nds-bootstrap issue.

**Expected Behavior: Ingame created save should be loadable.**

**Actual Behavior: It isn't :/**

### Steps to reproduce
1. Launch the game using nds-bootstrap, be it release or nightly.
2. Start the game, name the four characters, leave the house and walk left to the guy with a brown hat and a dog to save the game. Choose that you don't wanna continue playing. Now back in the menu try to load the newly created save.
3. Voila, nothing.

### nds-bootstrap.ini
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11073296/nds-bootstrap.zip)

### Will you be available for future replies?
No, sorry. Just wanted to mention it here so future folks don't have to run into it.

**Comment by RyuuSlayer** [comment]
Update: Upon looking at the AP Patches list there is only "Final Fantasy: The 4 Heroes of Light (Europe) (BFXP)" while the rom i am using is also English only but the European cardridge -> NTR-BFXP-EUR. This version of the game is also entirely missing from the compatibility list. The listed BFXP states that AP is required.

Not sure if adding the AP patch will fix the saving issue but i think it might be related.

**Comment by RocketRobz** [comment]
> Update: Upon looking at the AP Patches list there is only "Final Fantasy: The 4 Heroes of Light (Europe) (BFXE)" while the rom i am using is also English only but the European cardridge -> NTR-BFXP-EUR. This version of the game is also entirely missing from the compatibility list. The listed BFXE states that AP is required.
> 
> Not sure if adding the AP patch will fix the saving issue but i think it might be related.

Yes, you'll need to AP-patch the ROM, if you don't have a DS (lite) with a Memory Expansion Pak.

**Comment by rkocour** [comment]
I can't even get 4 heroes of light to boot after bootstrap creates save file when launching via twilight menu on my n3ds. I've tried both usa and europe version, both pre patched with ap fix and using ap fix cheat. Everytime it goes to red screen
Error: Undefined Instruction!

**Comment by RocketRobz** [comment]
> I can't even get 4 heroes of light to boot after bootstrap creates save file when launching via twilight menu on my n3ds. I've tried both usa and europe version, both pre patched with ap fix and using ap fix cheat. Everytime it goes to red screen Error: Undefined Instruction!

Please try with just a clean ROM with no AP-fixes enabled.
AP-fixes are applied automatically.

**Comment by rkocour** [comment]
same thing with unpatched and no ap cheat

**Comment by RocketRobz** [comment]
> same thing with unpatched and no ap cheat, also deleted the save file and let it get remade

Sounds like your SD card is having issues and/or your ROM is corrupted.
Try reformatting the SD card here: https://dsi.cfw.guide/sd-card-setup.html

**Comment by rkocour** [comment]
Probably wasn't the sd card, transferred all my data to a new micro sd same issue. What finally resolved was deleting my _nds folder and starting the install of twilight menu from scratch manually.

**Comment by lifehackerhansol** [comment]
OP fixed issue
