### ISSUE TITLE
Loz ph issue 

### ISSUE THREAD

**Issue by Braedyn1943848** [DS-Homebrew/nds-bootstrap#1550]
Every time I reach a certain point in tloz ph for ds, it brings up an error message saying error: data abort! I have the latest release of everything and don't use the nightly versions of anything. I have tried 3 different roms of the same game, one being a d-pad patch and at the same point the same error message. That's why idk if it's my console or what, everything else works just fine. This is bugging me though cause I've spent a good 5+ hours on this and I'm wanting to finish it and move ok to the rest of the games in the series. If anyone could help it'll be greatly appreciated

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue. Turning on TWL clock speed is known to fix this.

**Comment by Braedyn1943848** [comment]
Do you by chance know how to do this? I am really new to all this and don't really know what I'm doing😅

**Comment by MmeCromatique** [comment]
Press Y on the Game in TW++, You will a launch option, you can use the DSi Mode or alternatively the option just under just put the Clock at 133 TWL

**Comment by RocketRobz** [comment]
Closing, as the other issue (#1570) contains more information.
