### ISSUE TITLE
WarioWare DIY Showcase 

### ISSUE THREAD

**Issue by Demodude2023** [DS-Homebrew/nds-bootstrap#1552]
**Your console:**

**Launch Method:**

**Version used:**

**Game tested/used/applicable:**

**Save file:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3. 

### Will you be available for future issues and/or replies?
I'm on 2DSxl
I'm using the latest version as I updated yesterday
I'm able to connect to the Wii version and send games/sounds to it but when I try to receive games from Wii to DS it crashes. Sorry if this has been reported in the past. 
My son loves the game that's all.

**Comment by PW5190** [comment]
I've having a similar issue myself. After it crashed, I haven't started WWDIY in nds-bootstrap again since. I want to give the game a second chance, but I'll have to wait until further notice.

**Comment by TCAtrevor** [comment]
I'm having this issue, too (nds-bootstrap 1.0.3 on a Nintendo 3DS XL). Downloading from NinSoft (Wiimmfi) also freezes the game. I haven't tested downloading from online friends, but I presume that would also freeze based on the nature of this. When connected to Wii, the connection does not get interrupted until the game is shut down completely. The nds-bootstrap menu cannot be opened after the game has frozen.

**Comment by RocketRobz** [comment]
Is this fixed as of v1.6.2?

**Comment by artyye** [comment]
Fixed on 1.6.2.

**Comment by RocketRobz** [comment]
> Fixed on 1.6.2.

Great! Thanks for letting us know!
