### ISSUE TITLE
super mario 3D land black screen

### ISSUE THREAD

**Issue by lxg1202** [DS-Homebrew/nds-bootstrap#1553]
when i try TWM April Fool ,3ds GAME(super mario 3D land) black screen for a long time ,and DSI speaker has little noise.thank!

**Comment by RocketRobz** [comment]
You're a little late for the April Fools joke.
3DS games has never worked on DSi, and never will, due to hardware differences.

**Comment by lxg1202** [comment]
> You're a little late for the April Fools joke. 3DS games has never worked on DSi, and never will, due to hardware differences.

what a joke!Thanks!
