### ISSUE TITLE
What is error -2

### ISSUE THREAD

**Issue by blasterboyorange** [DS-Homebrew/nds-bootstrap#1556]
**Your console:** New 2DS XL

**Launch Method:** SD card. I don't know what SCFG means.

**Version used:** release, whatever is latest as of 4/11/23 i can't include version number because I don't know how.

**Game tested/used/applicable:** n/a

**Expected Behavior:** booted nds file

**Actual Behavior:** Load failed, error -2

### Steps to reproduce
I know for a fact that rearranging files on an SD card using a phone file browser corrupts data because it's happened before but this is the first time it's happened to an nds thing
What exactly is error -2 and is it fixable?

**Comment by RocketRobz** [comment]
Error -2 means that it failed to open the specified `.nds` file.
The error should already be fixed by later TWiLight Menu++ versions.
