### ISSUE TITLE
hi im wondering if anyone can help, i recently modded my 2ds xl and it was working just fine but now whenever im on the main menu  almost every input is unresponsive and the ones that work are very delayed

### ISSUE THREAD

**Issue by deathgrips2** [DS-Homebrew/nds-bootstrap#1560]
new 2ds xl
**Your console:**

sd luma
**Launch Method:**

**Version used:** nds-bootstrap: Release v0.71.0

**Game tested/used/applicable:** i opened terraria and quake inputs worked fined,and touch screen was a little bugy

**Save file:**

**Expected Behavior:** all inputs would work in the main menu

**Actual Behavior:**  whenever im on the main menu  almost every input is unresponsive and the ones that work are very delayed

### Steps to reproduce
1. 
2. 
3. 

### Other notes

i put ear buds in aux right before the issue started 

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
There is no fix for 3DS/2DS, unfortunately.
For touch input to work, you'll need to play the homebrew on a DS, DS Lite, DSi, or DSi XL.
