### ISSUE TITLE
Tropix doesn't boot

### ISSUE THREAD

**Issue by illteteka** [DS-Homebrew/nds-bootstrap#1563]
**Your console:** DSi

**Launch Method:** Unlaunch

**Version used:** v0.71.1

**Game tested/used/applicable:** Tropix!

**Save file:**

**Expected Behavior:** Game should boot

**Actual Behavior:** White screen / freeze

### Steps to reproduce
1. Launch TWiLightMenu
2. Run Tropix
3. White screen

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Tropix has worked fine in prior versions.
Please test each prior version of nds-bootstrap, and let me know which one boots Tropix.

**Comment by illteteka** [comment]
Sure, I'll try some older versions

**Comment by illteteka** [comment]
Ok I tested a bunch of old versions and confirmed that Tropix stopped working in v0.64.0 and the last working version is v0.63.2
