### ISSUE TITLE
[Feature] BootStream

### ISSUE THREAD

**Issue by EpicDoodleboy2** [DS-Homebrew/nds-bootstrap#1564]
Not a nds bootstrap issue

3DS and DSI

SD Card

OK this would stream the game footage via a application like snicker stream from the IP address from that systems DS Mode. 
So people don't have to pay a lot of money to get their console a capture card.

**Comment by Janni9009** [comment]
Not possible. The new3DS family can barely stream to a comprehensible degree with all it's overhead.

**Comment by EpicDoodleboy2** [comment]
Huh, I thought with more power of the new 3ds and TWL Patch to access the true power of the 3ds I thought it would run at a decent frame rate.

Even though I made the 3ds games run a at a good fps 30 top around 25 for the bottom. (Don't comment about this sentance plz)
