### ISSUE TITLE
Pokemon Black/White freezes randomly when saving

### ISSUE THREAD

**Issue by JunkerWilli** [DS-Homebrew/nds-bootstrap#1567]
**Your console: Nintendo DSi XL**

**Launch Method: SD card using Unlauch 2.0**

**Version used: TWiLight Menu++ v25.9.4 - release version with nds-bootstrap v0.71.1. ~~Also tried it with v25.8.1 with nds-bootstrap v0.70.0~~**

**Game tested/used/applicable: Pokemon Black, Pokemon White, Pokemon Schwarze Edition, Pokemon Weisse Edition**

**Expected Behavior: Game should not freeze while saving**

**Actual Behavior: Game freezes randomly while saving in Route 1 before reaching first city. The music however keeps playing**

### Steps to reproduce
1. Play the game until you fight against your 2 rivals
2. Go to route 1 and encounter a wild Pokemon
3. try to save multiple times until it freezes

### nds-bootstrap.ini
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Pokemon - Schwarze Edition.nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - Schwarze Edition.sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
LANGUAGE = -1
REGION = 2
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

I don't know if the freeze also happens in other stages of the game, because I only have started that game today. I also found a post on reddit covering that topic which is only 2 weeks old: https://www.reddit.com/r/3dspiracy/comments/12rffr1 

I tried using the English version with the same outcome and also White instead of Black. What is more, I tried activating DS-Mode instead of DSi-Mode. However, also the same freeze occurs. Then I tried two other SD cards. Unfortunately, that also didn't fix the problem. 
~~Then I went on and tried a older version of TWiLight Menu++ (v25.8.1). The freeze also happend in that version.~~ 
Acctually v25.8.1 seems to be fine. I just downloaded the latest version again when I thought I downloaded v25.8.1 :(. In v25.9.0 however the freeze occurred. 

-> Therefore, with nds-bootstrap v0.70.0 no freeze but with nds-bootstrap v0.71.0 the freeze happens

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Because this issue hasn't been reported until some time ago, please try each prior version of nds-bootstrap until you see that the bug is fixed.
Please let me know which version fixes the issue.

**Comment by JunkerWilli** [comment]
I have to correct myself. When I thought I was downloading v25.8.1, I was downloading the latest version of TWiLight Menu++ as I didn't expand the "Assets" in github but let myself forward to the homebrew page :/. 
So v25.8.1 with nds-bootstrap v0.70.0 actually did not freeze after 15 min of constant saving. Then I went on to install v25.9.0 with nds-bootstrap v0.71.0 and just after 2 minutes of repetitive saving the freeze occurred again. I tried then again v0.70.0 for 10 more minutes, but it was fine as before. 
So I think it is safe to say, the bug came into life in v0.71.0.

I will be playing more on v0.70.0 the next few days/weeks as I want to play through Black. If I notice a freeze on save, I will be informing you immediatelly.

**Comment by RocketRobz** [comment]
Please try this nightly build, and see if it fixes the issue: https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z
Place `nds-bootstrap-nightly.nds` and the `nightly-bootstrap.ver` files into `sd:/_nds/`, overwriting existing files.
Then in TWLMenu++ Settings, change the `Bootstrap` setting to `Nightly`.

**Comment by JunkerWilli** [comment]
Yes, it most certainly seems that it fixed the issue. Atleast with that nightly version also after 15 minutes of saving no freeze occurred.

**Comment by RocketRobz** [comment]
Nice! Thank you for testing!

**Comment by rsfez** [comment]
Hi,
I was wondering if the fix was reverted in the latest nightlies?
I'm facing similar issues as OP with a similar setup.

Thank you!

**Comment by RocketRobz** [comment]
> Hi, I was wondering if the fix was reverted in the latest nightlies? I'm facing similar issues as OP with a similar setup.
> 
> Thank you!

The fix has not been reverted, as it's been proven to work by reports from other users.

**Comment by rsfez** [comment]
Thanks.
Yes it seems the nightly I put in the `_nds` folder either got replaced after launching the game by an older version, or more probably I just messed the transfer up.

I've been re-trying again since I noticed after I posted the previous message and everything looks fine so far 👍 Sorry about the noise.

**Comment by sddsiv** [comment]
> Please try this nightly build, and see if it fixes the issue: https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z Place `nds-bootstrap-nightly.nds` and the `nightly-bootstrap.ver` files into `sd:/_nds/`, overwriting existing files. Then in TWLMenu++ Settings, change the `Bootstrap` setting to `Nightly`.

This solution does not eliminate the freezing, just attempted to save on pkmn black and it froze right after I hit yes to save.

**Comment by Souljaboiii** [comment]
Yesterday i had no issue with Saving.. but today i had some freezing in a few minutes… any help?

**Comment by RocketRobz** [comment]
> This solution does not eliminate the freezing, just attempted to save on pkmn black and it froze right after I hit yes to save.

Revert the `Bootstrap` setting, then try updating the non-nightly nds-bootstrap version to v0.72.0.
If the issue persists, then downgrade it to v0.71.2.

Please let me know what you have tried, so that in the case of the issue still persisting, I'll know what to do for the next version.

**Comment by RocketRobz** [comment]
> Yesterday i had no issue with Saving.. but today i had some freezing in a few minutes… any help?

Did you update nds-bootstrap today?

**Comment by Souljaboiii** [comment]
> 

I don’t think, maybe it updated it by himself?
I’m using the nightly build you mentioned, or at least i think so..

**Comment by RocketRobz** [comment]
> I don’t think, maybe it updated it by himself?

nds-bootstrap does not auto-update.

> I’m using the nightly build you mentioned, or at least i think so..

What's the nightly build number shown in TWLMenu++ Settings?

**Comment by Souljaboiii** [comment]
Where do i check?

**Comment by RocketRobz** [comment]
> Where do i check?

Top-left of the top screen of TWLMenu++ Settings.

**Comment by Souljaboiii** [comment]
It’s the v0.72.0

**Comment by RocketRobz** [comment]
> It’s the v0.72.0

That's a release version number, not a nightly version number.

Seeing as you're on the latest version though, try downgrading to v0.71.2.
https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.71.2

**Comment by Souljaboiii** [comment]
I’ll try! Thanks a lot, in case something happen I’ll ask for more help!

**Comment by JunkerWilli** [comment]
Yesterday I started to play Black 2 and I encountered the same freeze as in Black 1 today after the 4th total ingame save. So I was kinda suprised as I updated to v0.72.0 beforehand to make sure to have the fixed release version without using the nightly version you gave me a few weeks ago.
So I guess I will stick with v0.71.2 for the while being.

**Comment by Souljaboiii** [comment]
> Yesterday I started to play Black 2 and I encountered the same freeze as in Black 1 today after the 4th total ingame save. So I was kinda suprised as I updated to v0.72.0 beforehand to make sure to have the fixed release version without using the nightly version you gave me a few weeks ago.
> So I guess I will stick with v0.71.2 for the while being.

Yeah, i had no more save issues using the v0.71.2
So stick with it!

**Comment by JunkerWilli** [comment]
Indeed, after 11h of gameplay I can confirm v0.71.2 is working without save freezes.

**Comment by MrPbhorseman** [comment]
I have an issue in Pokemon Platinum 8 hours of playtime. This fix fixed it Now I'm on my 80 hours of playthrough and I have not encountered any crashes or freezes since then.

> Please try this nightly build, and see if it fixes the issue: https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z Place `nds-bootstrap-nightly.nds` and the `nightly-bootstrap.ver` files into `sd:/_nds/`, overwriting existing files. Then in TWLMenu++ Settings, change the `Bootstrap` setting to `Nightly`.
