### ISSUE TITLE
Pokemon moon black 2 glitch when booting up i get a white screen

### ISSUE THREAD

**Issue by ShtxSergio** [DS-Homebrew/nds-bootstrap#1571]
**Your console:**

**Launch Method:**

**Version used:**

**Game tested/used/applicable:**

**Save file:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by RocketRobz** [comment]
Try changing the `Run in` setting in the per-game settings menu to `DS mode`.

**Comment by RocketRobz** [comment]
Closing, due to no response.
