### ISSUE TITLE
Cheats not working anymore on DS One Flashcard starting v0.68.0

### ISSUE THREAD

**Issue by TonyLinkMario** [DS-Homebrew/nds-bootstrap#1574]
### Discussed in https://github.com/DS-Homebrew/TWiLightMenu/discussions/2221

<div type='discussions-op-text'>

<sup>Originally posted by **TonyLinkMario** May 27, 2023</sup>
It has been almost a year since I last update TWiLightMenu Flashcard edition on DS One Flashcard used on a DS Lite and DSi edition on a DSi because the update process need to be done manually. 3DS edition can easily keep up to date thanks to Universal Updater. After updating, I found that if I use TWiLightMenu on DS One and launch game with Bootstrap, no cheat would work at all. I can set the cheats I want in the menu that pop out by pressing Y button on game icon, but after entering the game, I found no cheats is actually taking effect. However, on DSi everything works fine. Cheats also work if I don't launch TWiLightMenu but use DS One Kernel to launch game. I used the same cheat database everywhere, and I have tested several games, but everything is the same. Only when I launch game with TWiLightMenu on DS One that cheats don't work. By the way, I once tried to launch TWiLightMenu on DS One but choose Kernel instead of Bootstrap as Game Loader, hoping it would solve the problem. But it failed to launch, and what's worse, I found the game save data was deleted or reset when I launch with Bootstrap again. Luckily I happened to have a backup of the save file, so nothing was lost. </div>

**Comment by lifehackerhansol** [comment]
Is this the DSONE SDHC or DSONE?

they are two very different carts

**Comment by lifehackerhansol** [comment]
I suppose it doesn't matter either way. Both DSONE and DSONE SDHC, TWLM++ 25.10.0, Mario Kart DS with constant Bullet Bill cheat appears to work.

It is also uncertain which types of cheats are not working for OP, so I assume all cheats were broken.

Closing, as it appears to work now.

**Comment by RocketRobz** [comment]
> It is also uncertain which types of cheats are not working for OP, so I assume all cheats were broken.

That is indeed the case, as the cheat engine wasn't being loaded at all.

**Comment by TonyLinkMario** [comment]
I have tried the latest 25.10.0 version, and tested the same Bullet Bill cheat, still doesn't work, but works fine in flashcard kernel.

**Comment by RocketRobz** [comment]
> I have tried the latest 25.10.0 version, and tested the same Bullet Bill cheat, still doesn't work, but works fine in flashcard kernel.

Did you add the autoboot file(s) from that version? If not, please do so, in order to fix the cheat issue.

**Comment by TonyLinkMario** [comment]
After replacing the SCFW.SC file and adding the TTMenu.dat file at the root of SD card to let TWiLightMenu Autoboot, cheats start working now. Thanks for the advice! But is this really necessary? I am used to autoboot the dsone kernel, then I can either select to boot game just with kernel so that I can use features like real time save or run BOOT.NDS file to manually enter TWiLightMenu and boot game with bootstrap so that there won't have issues like abnormally long loading time between scenes in games like Super Princess Peach, and chance that rumble pack won't work. In fact, this is the first time that I configured Autoboot for TWiLightMenu. In 25.6.1 and earlier versions, cheats can work without Autoboot.

**Comment by TonyLinkMario** [comment]
![IMG_0123](https://github.com/DS-Homebrew/nds-bootstrap/assets/81405607/1ce65c7c-9c0f-4a50-bdfb-a25a68d1fec0)

**Comment by TonyLinkMario** [comment]
Here is what my flashcard looks like. I assume it is DSONE SDHC?

**Comment by RocketRobz** [comment]
> After replacing the SCFW.SC file and adding the TTMenu.dat file at the root of SD card to let TWiLightMenu Autoboot, cheats start working now. Thanks for the advice! But is this really necessary? I am used to autoboot the dsone kernel, then I can either select to boot game just with kernel so that I can use features like real time save or run BOOT.NDS file to manually enter TWiLightMenu and boot game with bootstrap so that there won't have issues like abnormally long loading time between scenes in games like Super Princess Peach, and chance that rumble pack won't work. In fact, this is the first time that I configured Autoboot for TWiLightMenu. In 25.6.1 and earlier versions, cheats can work without Autoboot.

In that case, you could make a copy of the `SCFW.SC` file and rename to `boot_sc.nds`.
If that doesn't fix the no-autoboot cheat issue, then you'll need an application (which I can't find) that prevents the .nds file from being DLDI-patched by the flashcard kernel.

> Here is what my flashcard looks like. I assume it is DSONE SDHC?

Yes, it is.

**Comment by TonyLinkMario** [comment]
Yes, it really works this way! Thank you very much!

Detailed steps:
1. Make a copy of the SCFW.SC file from the TWiLightMenu release, path: TWiLightMenu-Flashcard/Autoboot/SuperCard DSONE SDHC & SuperCard DSONEi/SCFW.SC 
2. Rename the copied SCFW.SC file to boot_sc.nds
3. Copy the renamed boot_sc.nds file to the root of SD card in DSONE SDHC flashcard
4. Launch boot_sc.nds instead of BOOT.NDS in DSONE menu to enter TWiLightMenu

By the way, is it necessary to update the SCFW.SC file for every new version release, just like _nds folder and BOOT.NDS file? And in this case BOOT.NDS file seems isn't used because it is the renamed boot_sc.nds file that is launched instead, so is it still necessary to update the BOOT.NDS file for every new version release?

**Comment by RocketRobz** [comment]
> By the way, is it necessary to update the SCFW.SC file for every new version release, just like _nds folder and BOOT.NDS file? And in this case BOOT.NDS file seems isn't used because it is the renamed boot_sc.nds file that is launched instead, so is it still necessary to update the BOOT.NDS file for every new version release?

Yes, it is necessary.
Also, `boot.nds` is used when exiting DS homebrew, so it needs to be updated as well.

**Comment by TonyLinkMario** [comment]
OK, got it. Thanks!
Just curious, is this no-autoboot cheat issue just for DSONE SDHC flashcard? And if this is not considered a bug and won't be fixed in the future, maybe some notes should be added in case someone meets the same problem in the future? After all, Autoboot is an optional step in the installing guide, not necessary.

**Comment by RocketRobz** [comment]
> OK, got it. Thanks! Just curious, is this no-autoboot cheat issue just for DSONE SDHC flashcard? And if this is not considered a bug and won't be fixed in the future, maybe some notes should be added in case someone meets the same problem in the future? After all, Autoboot is an optional step in the installing guide, not necessary.

It likely won't be fixed, because of the DLDI drivers being a bit bugged in the first place.
It may possibly be an issue for DSTT-based flashcards as well.
