### ISSUE TITLE
Guitar Hero On Tour can't use cheat since ndsbootstrap/b4ds v0.68.0

### ISSUE THREAD

**Issue by heydootdoot** [DS-Homebrew/nds-bootstrap#1577]
**Your console:**
DS Lite

**Launch Method:**
- Launched with WiFi R4I-SDHC 3DS RTS flashcart (www.r4i-sdhc.com), autobooted to TWiLight Menu++
- There's no SCFG settings on DS Lite TWiLight Menu++, so I can't check

**Version used:**
I'm using TWiLight Menu v25.10.0 with nds-bootstrap/b4ds v0.72.0 (release)

**Game tested/used/applicable:**
- Guitar Hero: On Tour (NTR-YGHE-USA)

**Expected Behavior:**
Would play normally without guitar grip with mapped ABXY button and doesn't show error message when guitar grip is loose or detached

**Actual Behavior:**
Can run without guitar grip with cheat activated

### Steps to reproduce
1. Select no guitar grip cheat on TWiLight Menu and save
2. Launch the game
3. "You can't rock without a Guitar Hero Guitar Grip!" error message appears

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 6
NDS_PATH = fat:/DS ROMs/DS Games/Guitar Hero - On Tour (USA) (En,Fr).nds
SAV_PATH = fat:/DS ROMs/DS Games/saves/Guitar Hero - On Tour (USA) (En,Fr).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DONORTWL_NDS_PATH = fat:/DSiWare ROMs/Pop Island - Paperfield (USA).nds
APP_PATH = fat:/DSROMS~1/DSIWARES/SHANTA~1.NDS
PRV_PATH = fat:/DSROMS~1/DSIWARES/SAVES/SHANTA~1.SAV
BOOST_CPU = 1
BOOST_VRAM = 1
GAME_SOFT_RESET = 1
AP_FIX_PATH =
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONORTWL0_NDS_PATH = fat:/DS ROMs/DSiWares/Dr. Mario Express (USA) (Rev 2).nds
```

### Logs
[NDSBTSRP.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11713885/NDSBTSRP.zip)

### Other notes
I've found which version that doesn't give an error message when no guitar grip cheat activated and that is v.0.67.0; afterwards it's just doesn't want to play without actual guitar grip which actually run by ndsbootstrap because i could still open in-game menu. The weird thing is, i can't open in-game menu when the error screen pops up.
Also, there are other games that somehow doesn't run properly or becomes more and more unplayable by each new updates (always crashed with red screen); e.g. Plant vs. Zombies (USA)

### Will you be available for future issues and/or replies?
Yes, but I can't answer right away because of other things; will reply asap when I see a new reply

**Comment by RocketRobz** [comment]
Did you add the flashcard autoboot files from TWLMenu++ v25.10.0?
Because that is supposed to fix cheat support.

**Comment by heydootdoot** [comment]
> Did you add the flashcard autoboot files from TWLMenu++ v25.10.0? Because that is supposed to fix cheat support.

huh i haven't done that, will try that right now and i'll tell you right away when it does works

**Comment by heydootdoot** [comment]
also, i want to ask something. should i made a new issue regarding Plants vs Zombies doesn't play properly because i could never went into the stage even though previous ndsbootstrap (or is it when b4ds hasn't been merged to ndsbootstrap?) could still play it just fine, i forgot which version because so far previous build that i have tried from 2022 builds still doesn't play it right

**Comment by lifehackerhansol** [comment]
Issues should only be created for games that are affected on the latest version.

PvZ as far as I see has not ever seen an issue created for it, so if you can verify something is wrong on the latest version, please do make a new issue.

Closing, as OP has resolved the issue.
