### ISSUE TITLE
AmorousDS Won't Launch Black Screen

### ISSUE THREAD

**Issue by TrueNTG** [DS-Homebrew/nds-bootstrap#1579]
**Your console:** DSi

**Launch Method:** SD Card, TwilightMenu, idk 😐

**Version used:** release (0.72) & Nightly (idk)

**Game tested/used/applicable:** https://bit.ly/42D9ftf

**Save file:** Not Needed

**Expected Behavior:** Game running right

**Actual Behavior:** Black Screen

### Steps to reproduce
1.  Run game
2. 
3. 

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/AmorousDS - NIGHTLY v06132023.nds
SAV_PATH = sd:/saves/AmorousDS - NIGHTLY v06132023.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
AP_FIX_PATH =

### Logs

arguments passed

Running fat:/AmorousDS NIGHTLY v06132023.nds
Running fat:/AmorousDS NIGHTLY v06132023.nds with 1 parameters
arguments passed

Running fat:/AmorousDS NIGHTLY v06132023.nds
Running fat:/AmorousDS NIGHTLY v06132023.nds with 1 parameters

### Other note;
 Well this started outta nowhere when I was making the game.

**Comment by RocketRobz** [comment]
Are you using DS Game Maker to make the game?

**Comment by TrueNTG** [comment]
Yes I am

**Comment by TrueNTG** [comment]
`

> Are you using DS Game Maker to make the game?

Why you ask???

**Comment by RocketRobz** [comment]
> Why you ask???

Because games made by DS Game Maker are not compatible.
It is recommended to use the latest tools available, and program in C/C++ instead.

**Comment by TrueNTG** [comment]
Well Poop :/ I really don't want to restart.

**Comment by TrueNTG** [comment]
Go ahead and add this to unsupported games. Thank you,

**Comment by spellboundtriangle** [comment]
It may work if you boot it via Unlaunch

**Comment by TrueNTG** [comment]
It launches perfectly in Unlaunch but really want to launch it directly from Twilight Menu++

**Comment by spellboundtriangle** [comment]
There's [TWiLightMenu #2028](https://github.com/DS-Homebrew/TWiLightMenu/issues/2028) for that

**Comment by TrueNTG** [comment]
Is that A feature?????


> There's [TWiLightMenu #2028](https://github.com/DS-Homebrew/TWiLightMenu/issues/2028) for that

**Comment by spellboundtriangle** [comment]
Not atm, it's a request for the feature to be implemented. I'm just showing that it already has an open issue for it

**Comment by TrueNTG** [comment]
Ahhhhh Well they def need to get started on that lol

**Comment by TrueNTG** [comment]
https://github.com/DS-Homebrew/TWiLightMenu/issues/2028 (Closed) now we wait.. 🙏
