### ISSUE TITLE
My Healthy Cooking Coach Guru Meditation Crash

### ISSUE THREAD

**Issue by Sukotto-1999** [DS-Homebrew/nds-bootstrap#1582]
**Your console:** New 3DS XL

**Launch Method:** SD Card

**Version used:** v0.72.0

**Game tested/used/applicable:** My Healthy Cooking Coach

**Expected Behavior:** The game should boot normally without any issue.

**Actual Behavior:** The game crashes with Guru Meditate error in both DS and DSi modes

### Steps to reproduce
1. Launch My Healthy Cooking Coach
2. Error occurs

### Other notes
None.

### Will you be available for future issues and/or replies?
Yes.

**Comment by RocketRobz** [comment]
Sounds like your ROM is corrupted. Try re-dumping it.

**Comment by Sukotto-1999** [comment]
The rom is still valid, i calculated the crc, the rom is good dump.

**Comment by RocketRobz** [comment]
I've gotten the same issue, and turning off card read DMA fixes it on my side.
Please test it by pressing Y in TWLMenu++, then turning off said setting.

**Comment by Sukotto-1999** [comment]
Okay, i turned off Card DMA Read and, the game worked. It also works in DSi mode too!
