### ISSUE TITLE
jeopardy ds does not work crashes to red screen

### ISSUE THREAD

**Issue by wbkid** [DS-Homebrew/nds-bootstrap#1583]
**Your console:**

**Launch Method:**

**Version used:**

**Game tested/used/applicable:**

**Save file:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by RocketRobz** [comment]
Please fill out the issue template.

**Comment by lifehackerhansol** [comment]
Closing due to no response from author. Feel free to re-open this issue after filling out the issue template.
