### ISSUE TITLE
Soft reset causes DSi to crash

### ISSUE THREAD

**Issue by GunnarFoss** [DS-Homebrew/nds-bootstrap#1584]
**Your console: DSi**

**Launch Method:Unlaunch+SD**

**Version used:release**

**Game tested/used/applicable:TWiLight Menu++**

**Expected Behavior:Soft reset and boot back to Twilight**

**Actual Behavior:Soft reset causes it to crash**

### Steps to reproduce
1. Fix the soft reset issue where DSi crashes upon soft resetting

### Will you be available for future issues and/or replies?
Not really.

**Comment by RocketRobz** [comment]
wdym "crashes"?

**Comment by GunnarFoss** [comment]
When I press the power button while on the TWiLight Menu (plus its emulators/mpeg4 menu stuff), The top screen goes black and the audio loops (crash) when I try to soft reset the console by pressing the power button.

This doesn't affect it while on a DS/DSi game, only affects when you are on the TWiLight Menu (or its emulators built in).

**Comment by RocketRobz** [comment]
This sounds like it's caused by `boot.nds` missing from the SD card root.
If it's already exists on the SD root, then the crash might be caused by the ROM or video's filename being too long or smth.

**Comment by RocketRobz** [comment]
> I added the boot.nds file into the SD Card, now it's fixed!

Nice! This will be closed now.
