### ISSUE TITLE
Inazuma Eleven 2 Feuersturm (Germany) not working

### ISSUE THREAD

**Issue by KingdomSora24** [DS-Homebrew/nds-bootstrap#1585]
**Your console:** Nintendo 2DS XL

**Launch Method:** SD card Samsung Evo 128Gb

**Version used:** v0.72.1

**Game tested/used/applicable:** tested, used and applicable

**Save file:** no save file

**Expected Behavior:** After I pressed New Game and entered a name and skipped or watched the cutscene afterwards a textbox should come up.

**Actual Behavior:** After I pressed New Game and entered a name and skipped or watched the cutscene afterwards a textbox should come up instead a red screen comes up with error data abort.

### Steps to reproduce
1. Inazuma Eleven 2 Germany Rom
2. nds Bootstrap v0.72.1 and Twilight Menu
3. SD Card

### Other notes

 Yes

**Comment by RocketRobz** [comment]
Is it a ROM hack?

**Comment by KingdomSora24** [comment]
No rom hack it is the normal game

**Comment by RocketRobz** [comment]
Bug seems to be due to a broken AP-patch, as the data abort occurs at `PC` offset 02000540.

**Comment by Itzjaylo343** [comment]
Can Somebody Tell me what is the wrong with the Red Screen i cant play

**Comment by RocketRobz** [comment]
> Can Somebody Tell me what is the wrong with the Red Screen i cant play

Make sure nds-bootstrap (and TWLMenu++) is up to date.

**Comment by Itzjaylo343** [comment]
> > Can Somebody Tell me what is the wrong with the Red Screen i cant play
> 
> Make sure nds-bootstrap (and TWLMenu++) is up to date.

Can you Link this for me i dont know how 2 do this

**Comment by RocketRobz** [comment]
> Can you Link this for me i dont know how 2 do this

https://wiki.ds-homebrew.com/twilightmenu/updating
