### ISSUE TITLE
Houkago Shounen freezes after saving

### ISSUE THREAD

**Issue by S41Nya** [DS-Homebrew/nds-bootstrap#1587]
**Your console:**
DSI

**Launch Method:**
SD card

**Version used:**
Release v0.72.1

**Game tested/used/applicable:**
Houkago Shounen (Japan) (YHGJ)
MD5: 63dd7eb2a55496b7bad6b6f076403016

**Expected Behavior:**
Continue after saving

**Actual Behavior:**
Freezes after saving

### Steps to reproduce
1. Start the game until you can save
2. Press start to save
3. Game freezes (successfully saved, but needs to reboot to continue the game)

### nds-bootstrap.ini
```ini
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/Houkago Shounen (Japan).nds
SAV_PATH = sd:/roms/saves/Houkago Shounen (Japan).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = ja
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
APP_PATH = sd:/ROMS/GENIUS~2.NDS
PRV_PATH = sd:/ROMS/SAVES/  saves/
GAME_SOFT_RESET = 1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
```

### Will you be available for future issues and/or replies?
No

**Comment by RocketRobz** [comment]
It might be caused by an old issue where Pokemon Gen 5 would also freeze during saving.
It is also not a commonly reported issue, so it's safe to assume this is fixed. If the issue still occurs, this may be re-opened.
