### ISSUE TITLE
Rune Factory crashes when trying to start a new game.

### ISSUE THREAD

**Issue by elecrom94** [DS-Homebrew/nds-bootstrap#1588]
**New 3DS:**

**SD Card, Twilight Menu++:**

**release 0.72.1:**

**Rune Factory - A Fantasy Harvest Moon (Europe) (En,Fr,De,Es,It).nds
CRC:	5FF5CCBA
MD5:	DB989E8D92FC5C234BDC56AFEA343E36
SHA-1:	1E9E97D18FD1F2DDC9AF9BDF6C541D838698129A
Date:	2022-01-07:**

**[Rune Factory - A Fantasy Harvest Moon (Europe) (En,Fr,De,Es,It).zip](https://github.com/DS-Homebrew/nds-bootstrap/files/11951083/Rune.Factory.-.A.Fantasy.Harvest.Moon.Europe.En.Fr.De.Es.It.zip):**

**Gameplay starts after picking a savefile for a new game:**

**Game crashes with Data Abort Error:**

### Steps to reproduce
1. Launch Twilight Menu++
2. Locate Game Rom and launch it
3. The game launches and the Intro Cutscene plays, after that the Title screen appears
4. Select to begin a new game
5. Select either of the two possible save slots

### nds-bootstrap.ini
```ini
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Rune Factory 2 - A Fantasy Harvest Moon (Europe) (En,De).nds
SAV_PATH = sd:/roms/nds/saves/Rune Factory 2 - A Fantasy Harvest Moon (Europe) (En,De).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Other notes 
![RuneFactoryRedScreen](https://github.com/DS-Homebrew/nds-bootstrap/assets/138608100/50accb7a-1bcd-4041-a51c-f6e43570d524)

**Comment by Sukotto-1999** [comment]
Hey, do not post links to full games! Remove them immediately @elecrom94

**Comment by Masamune3210** [comment]
While I can see why you thought what you did, it might be prudent to check before yelling next time lol

**Comment by RocketRobz** [comment]
Crash does not occur on my side. Either it has been fixed later on, or your ROM is corrupted.
