### ISSUE TITLE
Snemulds sram saves and save states get deleted when i open the game from twilight menu

### ISSUE THREAD

**Issue by ExGuestCJ** [DS-Homebrew/nds-bootstrap#1590]
(also it doesnt work in unlaunch unlike nesds)

**Comment by RocketRobz** [comment]
Saving doesn't work because the game is loaded into a RAM disk created by nds-bootstrap.
To work around this, open `sd:/_nds/TWiLightMenu/settings.ini`, and set `NEW_SNES_EMU_VER` to `1`, though it'll break compatibility with some games.

**Comment by ExGuestCJ** [comment]
thanks

**Comment by ExGuestCJ** [comment]
wait i cant find it, probably bc the twilight menu version i have is slightly outdated

**Comment by RocketRobz** [comment]
> wait i cant find it, probably bc the twilight menu version i have is slightly outdated

That may not be why it's missing, but if you're are on an outdated TWLMenu++ version, then please update.
`NEW_SNES_EMU_VER = 1` should be added in the .ini file, under `[SRLOADER].`

**Comment by ExGuestCJ** [comment]
also (i dont wanna annoy you but) the same happens with jenesisds

**Comment by RocketRobz** [comment]
> also (i dont wanna annoy you but) the same happens with jenesisds

You can switch to PicoDriveTWL then.
Also, if you have further issues or questions, please join our Discord server.

**Comment by ExGuestCJ** [comment]
but i dont have (or rather, I am not allowed to use) discord

**Comment by ExGuestCJ** [comment]
> > wait i cant find it, probably bc the twilight menu version i have is slightly outdated
> 
> That may not be why it's missing, but if you're are on an outdated TWLMenu++ version, then please update. `NEW_SNES_EMU_VER = 1` should be added in the .ini file, under `[SRLOADER]`.

what the heck, i updated it and it still doesnt appear

**Comment by RocketRobz** [comment]
> what the heck, i updated it and it still doesnt appear

I meant to say that you should add it manually to the .ini file.

**Comment by ExGuestCJ** [comment]
> > what the heck, i updated it and it still doesnt appear
> 
> I meant to say that you should add it manually to the .ini file.

oh sorry

**Comment by ExGuestCJ** [comment]
it worked!
