### ISSUE TITLE
Error: Data Abort when trying to load my save file on Pokemon HeartGold 

### ISSUE THREAD

**Issue by DarkluckSS** [DS-Homebrew/nds-bootstrap#1591]
**New 3DS XL**

**Through SD card, forwarded the NDS file to homescreen**

**Version used: v0.72.1**

**Pokemon HeartGold (US) **

**Save file: [Save.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12016946/Save.zip)
**

**Expected Behavior: Press Continue in the menu and game should start normally on the last save point.**

**Actual Behavior: Press Continue in the menu, crash happens and Error: Data abort is shown**

### Steps to reproduce
1. Boot the game up through the home screen in 3ds
2. Let the game load all the way to the menu
3. Press Continue 

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/nds games/Pokemon HeartGold Version.nds
SAV_PATH = sd:/nds games/saves/Pokemon HeartGold Version.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 1
CACHE_FAT_TABLE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
CONSOLE_MODEL = 2
LANGUAGE = -1
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
USE_ROM_REGION = 0
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
REGION = 1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 1

**Comment by DarkluckSS** [comment]
Forgot to mention that I grabbed the save file from the spanish rom, modified it to english, renamed it after the US Copy name and tried to boot it up

**Comment by RocketRobz** [comment]
If there are AP-fix files in `sd:/_nds/ntr-forwarder/`, try deleting them.

**Comment by DarkluckSS** [comment]
ok, will try it rn

**Comment by DarkluckSS** [comment]
Yea I dont have any AP-fix files in sd:/_nds/ntr-forwarder/

**Comment by RocketRobz** [comment]
Sounds like it's an AP issue, but if works fine in TWiLight Menu++, then idk.

**Comment by RocketRobz** [comment]
> Yea I dont have any AP-fix files in sd:/_nds/ntr-forwarder/. Only header.bin and sdcard.nds

Make sure the forwarder pack is up to date by updating it using Universal-Updater.

**Comment by DarkluckSS** [comment]
Ok, will update this comment in a few mins while I check that and quick question: do the AP files appear automatically?

**Comment by RocketRobz** [comment]
> Ok, will update this comment in a few mins while I check that and quick question: do the AP files appear automatically?

No. If TWiLight Menu++ is installed, it'll read the AP-fix patches from there.

**Comment by DarkluckSS** [comment]
Alright it works just fine now! Thank you so much for the help!
