### ISSUE TITLE
Meteos - Disney Magic Touch not Working

### ISSUE THREAD

**Issue by levosw** [DS-Homebrew/nds-bootstrap#1593]
**Your console:** New Nintendo 3DS XL

**Launch Method:** SD, SCFG Unlocked
**System Version:** Sys 11.16.0-42K, Luma3ds v12.0.1

**Version used:** Nightly v25.11.0-878d79d

**Game tested/used/applicable:** NTR-ADZE-USA

**Save file:** [0863 - Meteos - Disney Magic (USA) Save File.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12091992/0863.-.Meteos.-.Disney.Magic.USA.Save.File.zip)

**Expected Behavior:** Touch should be worked where I touched.

**Actual Behavior:** When I touch the screen, cursor automatically moves to lower left corner. And it doesn't respond to any touches but just bouncing on that corner.

### Steps to reproduce
1. Turn on 3DS.
2. Open the TWiLight Menu++.
3. Open the game I mentioned earlier.
4. Touch on the main menu. (Touchscreen should work on title screen)

### nds-bootstrap.ini
```ini
[NDS-BOOTSTRAP]
NDS_PATH = sd:/nds/0863 - Meteos - Disney Magic (USA).nds
SAV_PATH = sd:/nds/saves/0863 - Meteos - Disney Magic (USA).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 0
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -1
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = ko
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/12092026/NDSBTSRP.LOG)

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Using a DSi XL (which shouldn't matter in this case), and cannot reproduce on my side.
