### ISSUE TITLE
Randomized Pokemon black2/white2 crashing

### ISSUE THREAD

**Issue by Spas120** [DS-Homebrew/nds-bootstrap#1597]
I'm using the latest version of twilight menu and when ever i play a pokemon black2/white2 whenever i go to the catching tutorial it crashes and a red screen appears showing bunch of numbers and letters saying error: data abort usually i would be able to continue onto the game but it does this all the time and im playing a pokemon randomizer and it use to work fine before until now.

**Comment by Spas120** [comment]
> > im pretty sure it was either v25.9.6 or v25.10.0
> 
> Try re-installing TWiLight Menu++ by deleting `TWiLightMenu` folder in `sd:/_nds/`, then install TWiLight Menu++ again. If the issue persists, then wait for a fix.

was the update suppose to fix this problem?

**Comment by RocketRobz** [comment]
> was the update suppose to fix this problem?

This was not a known issue until you reported it.

**Comment by Spas120** [comment]
> > was the update suppose to fix this problem?
> 
> This was not a known issue until you reported it.

so does that mean it didnt fix it i guess that makes sense cause the problem is still there

**Comment by RocketRobz** [comment]
> so does that mean it didnt fix it i guess that makes sense cause the problem is still there

You could try a nightly version of nds-bootstrap to check if it fixes the issue.
Which console are you using?

**Comment by Spas120** [comment]
> > so does that mean it didnt fix it i guess that makes sense cause the problem is still there
> 
> You could try a nightly version of nds-bootstrap to check if it fixes the issue. Which console are you using?

I'm using a 2ds and i could try the nightly version

**Comment by RocketRobz** [comment]
> I'm using a 2ds and i could try the nightly version

Alright, then you can use Univerrsal-Updater to get the nightly.
After getting the nds-bootstrap nightly, launch TWLMenu++, open the per-game settings by pressing the Y button, then set the `Bootstrap` setting to `Nightly`.

**Comment by Spas120** [comment]
> > I'm using a 2ds and i could try the nightly version
> 
> Alright, then you can use Univerrsal-Updater to get the nightly. After getting the nds-bootstrap nightly, launch TWLMenu++, open the per-game settings by pressing the Y button, then set the `Bootstrap` setting to `Nightly`.

well it still crashes the same way every time and just so you know i used the universal pokemon randomizer zx

**Comment by RocketRobz** [comment]
> well it still crashes the same way every time and just so you know i used the universal pokemon randomizer zx

Then revert the setting back to `Default`, and downgrade to each prior nds-bootstrap version, until you find the one which doesn't crash the game.

**Comment by Spas120** [comment]
> > well it still crashes the same way every time and just so you know i used the universal pokemon randomizer zx
> 
> Then revert the setting back to `Default`, and downgrade to each prior nds-bootstrap version, until the game stops crashing.

well no matter which version i try it still crashes the same way

**Comment by RocketRobz** [comment]
> well no matter which version i try it still crashes the same way

If you've already tried the nds-bootstrap versions of which the prior TWLMenu++ versions you've used have already included, then the randomizer is likely the culprit.
Can you check if it crashes in an emulator such as melonDS?

**Comment by Spas120** [comment]
> > well no matter which version i try it still crashes the same way
> 
> If you've already tried the nds-bootstrap versions of which the prior TWLMenu++ versions you've used have already included, then the randomizer is likely the culprit. Can you check if it crashes in an emulator such as melonDS?

It also crashes on melonDS but instead of the red screen it just freezes

**Comment by RocketRobz** [comment]
> It also crashes on melonDS but instead of the red screen it just freezes

That confirms the randomizer is indeed the issue, so you'll need to open a new issue at that repo, if it hasn't been opened yet.

Closing, as this is not an nds-bootstrap issue.
