### ISSUE TITLE
Pokemon diamond times out when connecting to my pokemon ranch

### ISSUE THREAD

**Issue by Noahkirby** [DS-Homebrew/nds-bootstrap#1598]
**Nintendo Wii:**

**SD Card:**

**Nightly:**

**Save file:**

**It connects and you can send the pokemon:**

**it times out then trys to power off the 3ds:**

### Steps to reproduce
1. Load pokemon diamond
2. Press the button on my pokemon ranch for connecting a ds
3.  Wait and it will time out then try to power off the 3ds

**Comment by RocketRobz** [comment]
Duplicate of #415
