### ISSUE TITLE
Error Data Abort

### ISSUE THREAD

**Issue by rickymbeats** [DS-Homebrew/nds-bootstrap#1599]
![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/141270010/d7009849-e22b-4c0d-8e49-be51a6407f8e)

I'm currently playing Pokémon Platinum which i homebrewed onto my 3ds and it plays for a bit until i do a random action and then comes up with this? I don't know how to fix it can anyone help?

**Comment by RocketRobz** [comment]
Is the ROM modified?

**Comment by rickymbeats** [comment]
> Is the ROM modified?

Not really, it's been happening since i started it but in between that i've put a widescreen thing on, i tried changing the cpu speed but it didn't change what eventually happens. I've been told to use TWLFix.

**Comment by RocketRobz** [comment]
TWLFix wouldn't work, since DS(i) mode is already working properly.

Are you using cheats? They'd be activated by opening the TWLMenu++ in-game menu by pressing Y, and then pressing X to view the cheat list to see which cheat you want to use.

**Comment by rickymbeats** [comment]
> TWLFix wouldn't work, since DS(i) mode is already working properly.
> 
> 
> 
> Are you using cheats? They'd be activated by opening the TWLMenu++ in-game menu by pressing Y, and then pressing X to view the cheat list to see which cheat you want to use.

It says no cheats found so i'm pretty sure i'm not.

**Comment by RocketRobz** [comment]
Try turning off widescreen then.
If the issue persists, then your ROM might be corrupted.

**Comment by rickymbeats** [comment]
> Try turning off widescreen then.
> 
> If the issue persists, then your ROM might be corrupted.

If i was to delete it and re-download a new one would i still be able to keep the same save data?

**Comment by RocketRobz** [comment]
> If i was to delete it and re-download a new one would i still be able to keep the same save data?

Yes, you can. Make sure both the ROM and save data are named the same (aside from file extension).

**Comment by rickymbeats** [comment]
> > Try turning off widescreen then.
> > 
> > If the issue persists, then your ROM might be corrupted.
> 
> If i was to delete it and re-download a new one would i still be able to keep the same save data?

Yeh i've just tried without the widescreen and it still happened.

**Comment by rickymbeats** [comment]
> > If i was to delete it and re-download a new one would i still be able to keep the same save data?
> 
> 
> 
> Yes, you can. Make sure both the ROM and save data are named the same (aside from file extension).

What does this mean?

**Comment by RocketRobz** [comment]
> What does this mean?

It means to make sure both the `.nds` and `.sav` files contain the same name.

**Comment by rickymbeats** [comment]
> > What does this mean?
> 
> 
> 
> It means to make sure both the `.nds` and `.sav` files (latter being in the `saves` folder) contain the same name.

THANK YOU hahahah i think it works thank you for your time :)
