### ISSUE TITLE
Mario & Luigi Partners in Time Video Glitch right before battles

### ISSUE THREAD

**Issue by Goserz** [DS-Homebrew/nds-bootstrap#1602]
**Your console:** Old 3DS XL

**Launch Method:** SD Card 

**Version used:** Release [v25.11.0] "latest"

**Save file:** [Mario & Luigi - Partners in Time Save File NTSC.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12294193/Mario.Luigi.-.Partners.in.Time.Save.File.NTSC.zip)

**Expected Behavior:** The 3D ball animation that leads into battle happens without graphical glitches.

**Actual Behavior:** There's a flickering or sometimes tearing for a split second during the transition from 2D to the 3D ball animation.

### Steps to reproduce
1. Load the attached save file and pick save file 2.
2. Go up the platform where you will fight the shroob alien boss.

### Other notes 
1. The game are Mario & Luigi Partners in Time PAL and NTSC.
2. I already tried enabling the "Nightly" option in the settings and it still happening.
3. This bug was already been reported on older version and has been fixed but it seems the bug on the latest version is recurring
( The issue i'm talking about #854 )

**Comment by Goserz** [comment]
I already have the latest nds bootstrap installed on 3ds

**Comment by RocketRobz** [comment]
Does this still occur on later versions?

**Comment by RocketRobz** [comment]
Closing due to lack of response. I also don't recall this issue happening on my side.
