### ISSUE TITLE
can't play pokemon heart gold vietnamese game 

### ISSUE THREAD

**Issue by Pig0983** [DS-Homebrew/nds-bootstrap#1604]
My 3ds run twilight menu++ latest version but i can't run pokemon heart gold vietnamese game,please fix it bro.

**Comment by RocketRobz** [comment]
Works fine for me. Are you using this?: https://www.deviantart.com/elfcoach/art/VIET-HG-SS-COMPLETION-850166092
If so, did you apply the patch to a Japanese ROM?
