### ISSUE TITLE
Inazuma Eleven crashes when I start a match

### ISSUE THREAD

**Issue by SonHugo** [DS-Homebrew/nds-bootstrap#1605]
When I enter the Twilight menu++ and start playing the Inazuma eleven 1, 2 and the hack rom origins through nds bootstrap latest version, when I start a game the screen turns red and says in white letters 'Error: Data Abort!' I don't know how to solve it or how to play those nds games please help

**Comment by RocketRobz** [comment]
Are they ROM hacks?

**Comment by SonHugo** [comment]
Can I play that rom hack on Twilight menu++?

**Comment by RocketRobz** [comment]
> Can I play that rom hack on Twilight menu++?

Generally, to play ROM hacks, the clean ROM needs to first be AP-patched using DS-Scene ROM Tool, before applying the ROM hack patch.

**Comment by SonHugo** [comment]
The game is Inazuma eleven 1 (Spain)

**Comment by RocketRobz** [comment]
Should be fixed as of this year's halloween release.

**Comment by RocketRobz** [comment]
> Italian, I'm too far in the story to restart the game in english, i really hope i can repair the italian rom

Where is the game being run from? Flashcard or DSi/3DS SD card?

**Comment by RocketRobz** [comment]
> From the sd card into the rom folder, using twl and ndsboostrap, I even put an ap patch, i took it from gba temp, and it was still crashing, maybe the file in the megathread is corrupted ?
> 
> ![Image](https://github.com/user-attachments/assets/5aeb93ea-44f6-4d50-b541-b7f21ebdc9a6)

Try the clean ROM instead of the AP-patched ROM, as nds-bootstrap automatically AP-patches your ROM on-the-fly.

**Comment by jinyo329** [comment]
> > From the sd card into the rom folder, using twl and ndsboostrap, I even put an ap patch, i took it from gba temp, and it was still crashing, maybe the file in the megathread is corrupted ?
> > ![Image](https://github.com/user-attachments/assets/5aeb93ea-44f6-4d50-b541-b7f21ebdc9a6)
> 
> Try the clean ROM instead of the AP-patched ROM, as nds-bootstrap automatically AP-patches your ROM on-the-fly.

I used the clean rom for two days and then the ap-patched, it's the same thing
