### ISSUE TITLE
Download Play Not working in Metroid Prime Hunters

### ISSUE THREAD

**Issue by Non0611** [DS-Homebrew/nds-bootstrap#1609]
I'm using the latest version of TWiLight Menu++ and nds-bootstrap, but the metroid prime hunters clone boot that worked before doesn't work.

**Comment by RocketRobz** [comment]
Is the other console crashing on the Nintendo logo? If so, try re-dumping the ROM. If not, then what happens?

**Comment by Non0611** [comment]
The Nintendo logo doesn't crash, but disconnects from the host just before the match starts.

**Comment by RocketRobz** [comment]
> The Nintendo logo doesn't crash, but disconnects from the host just before the match starts.

Try turning off card read DMA then. You can do so by opening the per-game settings menu in TWLMenu++ by pressing the Y button, then scrolling down to the setting to turn it off.

**Comment by Non0611** [comment]
The result remains the same, it keeps disconnecting.

**Comment by RocketRobz** [comment]
Try adjusting the distance between each console then.

**Comment by RocketRobz** [comment]
Try setting ARM9 CPU Speed to TWL then. It is done in the same menu where you turned off card read DMA.
If the issue persists, then I'm out of ideas.

**Comment by RocketRobz** [comment]
Also, are you using a DSi or 3DS as the host console?

**Comment by Non0611** [comment]
I'm using a 3DS.

**Comment by RocketRobz** [comment]
> I'm using a 3DS.

Same here, and the connection works fine for me.
Are you sure it worked fine prior to this update? Because nothing related to wireless communications has changed.

**Comment by Non0611** [comment]
It still doesn't work. yes. It was working fine before.

**Comment by RocketRobz** [comment]
> It still doesn't work. yes. It was working fine before.

That's very strange then.
Are you using any cheats? If so, try turning them off.

If you don't have them turned on, or if turning them off doesn't fix the issue, then try reconnecting once the connection drops.
If the issue persists, then keep trying to connect.

**Comment by Non0611** [comment]
Downgrading the version still worked

**Comment by RocketRobz** [comment]
Which region is your ROM?

**Comment by Non0611** [comment]
JP

**Comment by RocketRobz** [comment]
> JP

I use the USA version. Also, I'm able to reproduce the issue now, so hopefully this is fixable.

**Comment by Non0611** [comment]
Thank you very much! I look forward to it.

**Comment by Non0611** [comment]
How is the progress?

**Comment by RocketRobz** [comment]
> How is the progress?

You could try the latest nds-bootstrap nightly build to check. Use Universal-Updater to download it, then set the `Bootstrap` setting to `Nightly` in either TWLMenu++ Settings or the per-game settings menu.

**Comment by Non0611** [comment]
Sorry for the late reply.
Has it been fixed?

**Comment by RocketRobz** [comment]
> Sorry for the late reply. Has it been fixed?

Have you tried doing what I said to install the nightly build?

**Comment by Non0611** [comment]
I checked with nds-bootstrap 1.0.0 release and it is working fine. 
Does that mean you were able to fix it?

**Comment by RocketRobz** [comment]
> I checked with nds-bootstrap 1.0.0 release and it is working fine. Does that mean you were able to fix it?

I think so. This change seems to have.

> Fixed certain SDK3-4 games not booting, due to the cluster cache of the save file being compressed.
