### ISSUE TITLE
Pokemon black 2 randomizer viewing pokemon crashes the game

### ISSUE THREAD

**Issue by Spas120** [DS-Homebrew/nds-bootstrap#1611]
Pokemon black 2 crashes when ever viewing the pokemon on a randomizer but it works on an emulator like melonDS so nds bootstrap seems to be the problem. I should be able to view the pokemon ut all it does is crash. all i did was get my starter and tried to view it but it ends up crashing instead. also I'm using nds bootstrap v0.73.1 on a 2ds and loading a game from the sd card and using twilight menu release v26.0.1

**Comment by RocketRobz** [comment]
It crashes because of an AP measure taking place.
AP is not (and will not be) patched out for randomized ROMs, so you'll need to manually AP-patch the clean ROM using DS-Scene ROM Tool before randomizing it.

**Comment by Spas120** [comment]
> It crashes because of an AP measure taking place. AP is not (and will not be) patched out for randomized ROMs, so you'll need to manually AP-patch the clean ROM using DS-Scene ROM Tool before randomizing it.

but wouldn't it do the same thing on melonDS if that was the case tho?

**Comment by RocketRobz** [comment]
> > It crashes because of an AP measure taking place. AP is not (and will not be) patched out for randomized ROMs, so you'll need to manually AP-patch the clean ROM using DS-Scene ROM Tool before randomizing it.
> 
> but wouldn't it do the same thing on melonDS if that was the case tho?

No, because melonDS properly emulates the game card slot in a way that bypasses AP measures like on the original game card.
The AP measure works by checking how the game card can be read. If it detects either a flashcard or no game card, then the AP measure takes effect (in this case, crashing when viewing the Pokemon summary).

**Comment by Spas120** [comment]
> > > It crashes because of an AP measure taking place. AP is not (and will not be) patched out for randomized ROMs, so you'll need to manually AP-patch the clean ROM using DS-Scene ROM Tool before randomizing it.
> > 
> > 
> > but wouldn't it do the same thing on melonDS if that was the case tho?
> 
> No, because melonDS properly emulates the game card slot in a way that bypasses AP measures like on the original game card. The AP measure works by checking how the game card can be read. If it detects either a flashcard or no game card (which is always the case on nds-bootstrap, as Slot-1 is disabled), then the AP measure takes effect (in this case, crashing when viewing the Pokemon summary).

Oh ok, thank you
