### ISSUE TITLE
Pokemon HeartGold Error: Data Abort on nds-bootstrap version higher than 0.64.1

### ISSUE THREAD

**Issue by KimJongAffe** [DS-Homebrew/nds-bootstrap#1612]
**Your console:** New 2DS XL

**Launch Method:** SD Card

**Version used:** TWL 26.0.1 and downgraded nds-bootstrap to 0.64.1. All version after 0.64.1 causes Error: Data Abort on start up.

**Game tested/used/applicable:** Multiple HG and SS roms from different countrys with and without AP-fix. Other games work just fine. Only HG and SS crashes.

**Save file:** No save file needed

**Expected Behavior:** Start the game

**Actual Behavior:** Crash.

### Steps to reproduce
1. Upgrade nds-bootstrap to a version higher than 0.64.1
2. 
3. 

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Pokemon - Goldene Edition HeartGold (Germany)_apfix.nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - Goldene Edition HeartGold (Germany)_apfix.sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 1
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -1
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
```

**Comment by RocketRobz** [comment]
This is a weird issue which doesn't occur on my side with the latest.
Are you using any cheats?

**Comment by KimJongAffe** [comment]
No. its a fresh savefile. No cheats activated.

**Comment by RocketRobz** [comment]
> No. its a fresh savefile. No cheats activated.

In that case, the version number should help with finding the cause of this issue, so thank you for that!

**Comment by KimJongAffe** [comment]
Which version number do you mean exactly?

**Comment by RocketRobz** [comment]
> Which version number do you mean exactly?

The one you reported, which is v0.64.1. Comparing that version and one one prior to it should help with finding the issue.

**Comment by KimJongAffe** [comment]
Ah okay. I thought you need more info about a version number or something.

**Comment by RocketRobz** [comment]
> No. its a fresh savefile. No cheats activated.

Even with no cheats activated, do you still have a `usrcheat.dat` file in `sd:/_nds/TWiLightMenu/extras/`?

**Comment by KimJongAffe** [comment]
No there is no `usrcheat.dat` file in this folder or anywhere else on the SD card.

**Comment by KimJongAffe** [comment]
I managed to fix the issue. After deleting everything related to TWL from the SD card, a completely fresh install and first time setup the ROM loads just fine. Perhaps some old files were preventing the game from loading?

**Comment by RocketRobz** [comment]
> I managed to fix the issue. After deleting everything related to TWL from the SD card, a completely fresh install and first time setup the ROM loads just fine. Perhaps some old files were preventing the game from loading?
> 
> Thanks for your time.

That makes no sense.
The only old file that (most likely) causes that issue is the patchOffsetCache file for that game, which in later nds-bootstrap versions, should've cleared it in order to prevent this very issue.

**Comment by KimJongAffe** [comment]
Hmm okay...strange.
Weird that it only happened with HG and SS. 

But at least it works now even with the newest version. For me personaly I wouldn't have had a problem to play with the old nds-bootstrap version but I wondered if this problem ever happened to someone else before.
