### ISSUE TITLE
Urusei Yatsura Endless Summer stuck on a white screen on most recent version

### ISSUE THREAD

**Issue by Kurotanooki** [DS-Homebrew/nds-bootstrap#1614]
**Your console:**New 2ds xl

**Launch Method:** SD card 
Twilight Menu  26.0.1//ndsbootstrap v0.73.1 (rom not loading// stuck in a whitescreen when launched)
                                               Twilight Menu 25.3.0// ndsbootstrap v0.64.0 (same rom// loading without issue)
                                                                                                                         

**Game tested/used/applicable:** Urusei Yatsura: Endless Summer

**Expected Behavior:** Game launching on most recent version

**Actual Behavior:** Stuck in whitescreen on most recent version

Cant say for sure how far back I had to go in versions to get it to start, Thought my best chances on getting it to start were on the version where this game is in the actual patchnotes.

**Comment by RocketRobz** [comment]
I have a feeling the fix for the Incredibles game has broken that game again. Please try nds-bootstrap v0.72.1, and see if it works there.
