### ISSUE TITLE
pokemon games not working

### ISSUE THREAD

**Issue by OmegaKINGpng** [DS-Homebrew/nds-bootstrap#1618]
the pokémon games that are installed do not work because of anti-piracy, I installed the latest version of TM on my DSi and it does not work at all

**Comment by RocketRobz** [comment]
How are they not working, exactly? If they don't boot at all, then it's not because of Anti-Piracy.

**Comment by OmegaKINGpng** [comment]
@RocketRobz so, when the game is going to make some transition, like going through a door, it has a black screen and the music continues, but the game does not continue

**Comment by RocketRobz** [comment]
> @RocketRobz so, when the game is going to make some transition, like going through a door, it has a black screen and the music continues, but the game does not continue

This issue only occurs on modified ROMs, such as ROM hacks and/or randomized ROMs. You must first manually AP-patch the clean/unmodified ROM using DS-Scene ROM Tool, and then applying either the ROM hack patch or randomizer.

**Comment by OmegaKINGpng** [comment]
@RocketRobz I tried to use unmodified ROMs and also from different sites, but they all have this problem

**Comment by RocketRobz** [comment]
Where are the games being run from? The DSi's SD card slot, or a flashcard?

**Comment by OmegaKINGpng** [comment]
@RocketRobz is running on a flash card, but it uses Twilight Menu

**Comment by RocketRobz** [comment]
> @RocketRobz is running on a flash card, but it uses Twilight Menu

Which Pokemon games then? Because HGSS and Gen 5 games are known to contain AP.

**Comment by OmegaKINGpng** [comment]
@RocketRobz pokemon black/white 2 work normally, but black/white and soul silver have this problem

**Comment by RocketRobz** [comment]
> @RocketRobz pokemon black/white 2 work normally, but black/white and soul silver have this problem

Doesn't sound like you're using the latest TWiLight Menu++ and/or nds-bootstrap version then.

Which versions are displayed in TWLMenu++ Settings?

**Comment by RocketRobz** [comment]
> @RocketRobz opening the settings says it's version 25.11.0 and the bootstrap release is v0.73.1

Ensure both are up to date by following this guide: https://wiki.ds-homebrew.com/twilightmenu/updating-flashcard

**Comment by OmegaKINGpng** [comment]
@RocketRobz they are

**Comment by RocketRobz** [comment]
> @RocketRobz they are

So TWiLight Menu++ is on v26.0.1 then?

**Comment by OmegaKINGpng** [comment]
@RocketRobz yup

**Comment by OmegaKINGpng** [comment]
@RocketRobz "this game has AP. PLease make sure you're using the lates version of TWiLight Menu++" and the game still doesn't work

**Comment by RocketRobz** [comment]
> @RocketRobz "this game has AP. PLease make sure you're using the lates version of TWiLight Menu++" and the game still doesn't work

Try re-dumping the ROMs then.

**Comment by OmegaKINGpng** [comment]
@RocketRobz sorry, but what is this ?

**Comment by RocketRobz** [comment]
> @RocketRobz sorry, but what is this ?

Dumping means getting the ROM from your physical cartridge.
You can do that on your DSi after following this guide: https://dsi.cfw.guide/

**Comment by RocketRobz** [comment]
Closing due to lack of response.
