### ISSUE TITLE
NTR Aging does not boot

### ISSUE THREAD

**Issue by IanSkinner1982** [DS-Homebrew/nds-bootstrap#1620]
**Your console:** DSi

**Launch Method:** DSi is v1.4.5U w/ unlaunch, booting via SD card.

**Version used:** Release build 0.73.1.

**Game tested/used/applicable:** 
- NTR Aging v1.0 (SHA1: `2a6da281da79d2f5606ea9a8b905ee114cf670e1`)
- NTR Aging v5.1 (SHA1: `a4f1ecaac2484769169f46585f76ba3dd7420bea`)
- NTR Aging v6.0 (SHA1: `e88ca2481cd22869ecdb423dc29296a7cb465d51`)
- NTR Aging v8.0 (SHA1: `1e41c99fcf677bfde103414a6f6a9214a768593a`)
- NTR Aging v9.0 (SHA1: `1ec5dd5d892f6ad86bbc13847a0d99948e3b9158`)
- NTR Aging v10.0 (SHA1: `91bb4935da06e9bad8c5b45dd9c2ca94b826b0f5`)
- NTR Aging v11.0 (SHA1: `30f3d6e8c573739e8bd6e87e3b28934fa63686e1`)
- NTR Aging v11.1 (SHA1: `51e57a9c9bebc92c181ebc9f84276401fdd7b0de`)

v1.0 has a TID of `AAAA`. All others are `NTRJ`.

**Save file:** [Nitro_EVA-saves.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12552993/Nitro_EVA-saves.zip) (saves for all versions included)

**Expected Behavior:** Programs should boot

**Actual Behavior:** nds-bootstrap gives "an error has occurred" when attempting to load the software.

### Steps to reproduce
1. Launch the software via TWiLight Menu++
2. nds-bootstrap will fail to load software

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/rmc-dsi/Nitro EVA/CTR/Nitro EVA (CTR) v11.1.nds
SAV_PATH = sd:/rmc-dsi/Nitro EVA/CTR/saves/Nitro EVA (CTR) v11.1.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 0
REGION = 0
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DEBUG = 1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 2
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 1
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
APP_PATH = sd:/RMC-DSI/DSSOUND/DSSOUN~1.SRL
PRV_PATH = sd:/RMC-DSI/DSSOUND/SAVES/DSSOUN~1.PRV
GAME_SOFT_RESET = 1
AP_FIX_PATH =
DONORTWLONLY_NDS_PATH = sd:/program.srl
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b4a/content/0000000141.app
HOMEBREW_ARG =
```

### Logs
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/12552994/NDSBTSRP.LOG)

### Other notes
From my limited testing this appears to happen with almost all dev/factory software. I can confirm these files boot via unlaunch and most emulators, so the issue is not with the software itself.

I have also re-installed TWiLight Menu++ and nds-bootstrap which produces the same results.

### Will you be available for future issues and/or replies?
Yes.

**Comment by IanSkinner1982** [comment]
The saves archive didn't compress properly the first time. Uploaded a good version now though. Sorry about that!

**Comment by IanSkinner1982** [comment]
I tried build [d18446e](https://github.com/DS-Homebrew/nds-bootstrap/commit/d18446edb84b1272287bceabf148e4b94d7bb14b) and `v1.0` to `v6.0` of NTR Aging work.

`v8.0` and above still crash however.
- [Nitro_EVA-saves_d18446e.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12554908/Nitro_EVA-saves_d18446e.zip)
- [NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/12554918/NDSBTSRP.LOG)
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/rmc-dsi/Nitro EVA/CTR/Nitro EVA (CTR) v11.1.nds
SAV_PATH = sd:/rmc-dsi/Nitro EVA/CTR/saves/Nitro EVA (CTR) v11.1.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 0
REGION = 0
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DEBUG = 1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 2
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 1
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
APP_PATH = sd:/RMC-DSI/DSSOUND/DSSOUN~1.SRL
PRV_PATH = sd:/RMC-DSI/DSSOUND/SAVES/DSSOUN~1.PRV
GAME_SOFT_RESET = 1
AP_FIX_PATH =
DONORTWLONLY_NDS_PATH = sd:/program.srl
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b4a/content/0000000141.app
HOMEBREW_ARG =
```

**Comment by RocketRobz** [comment]
Up to v11.1 works as of 51788da3

**Comment by IanSkinner1982** [comment]
Awesome, thanks @RocketRobz! That was really fast.
