### ISSUE TITLE
Portrait of Ruin Crash upon startup

### ISSUE THREAD

**Issue by RottedFish** [DS-Homebrew/nds-bootstrap#1621]
I’m attempting to play Portrait of Ruin with the “Portrait of Elegance” mod. However, no version of the game, modded or vanilla, will run. I’m using the nightly build of Twilight Menu ++ alongside the nightly build of NDS Bootstrap.
In theory, it should launch after making the initial save, but it crashes after exiting that screen and booting me back to the TWL Menu. 
I believe I experienced this issue in the past but can’t remember how I got around it. Any assistance would be very appreciated.

**Comment by RocketRobz** [comment]
Please downgrade nds-bootstrap to v0.72.1, and see if it fixes the game not working: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.72.1

**Comment by RocketRobz** [comment]
It may be fixed in the next version then.
