### ISSUE TITLE
Daigassou! Band-Brothers (Japan) - Double red screens on launch

### ISSUE THREAD

**Issue by Agusum** [DS-Homebrew/nds-bootstrap#1623]
**Your console:** New Nintendo 3DS XL

**Launch Method:** SD

**Version used:** Release v1.0.0

**Game tested/used/applicable:** Daigassou! Band-Brothers (Japan)

**Save file:** No save file possible

**Expected Behavior:** Game boots

**Actual Behavior:** Double red screens when launching the game

### Steps to reproduce
1. Launch the game
2. 
3. 

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/roms/nds/Daigassou! Band-Brothers (J).nds
SAV_PATH = sd:/roms/nds/saves/Daigassou! Band-Brothers (J).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
AP_FIX_PATH = 
USE_ROM_REGION = 1
B4DS_MODE = 0
```

### Will you be available for future issues and/or replies?
Yes

![IMG_3135](https://github.com/DS-Homebrew/nds-bootstrap/assets/4369698/ff45362a-7615-4356-aab6-076c49dd5ad1)

**Comment by RocketRobz** [comment]
Either it'll be fixed in the next version, or your ROM dump is bad.
Works fine for me on both DSi & 3DS.
