### ISSUE TITLE
ACWW rtc bug on DS lite --> potential sd corruption??

### ISSUE THREAD

**Issue by flanter21** [DS-Homebrew/nds-bootstrap#1625]
**Your console:** DS Lite

**Launch Method:** TWiLight Menu Flashcart (DSONE SDHC)

**Version used:** nds-bootstrap v1.0.0 and v0.72.1

**Game tested/used/applicable:** Animal Crossing Wild World (Europe) (ADMP)

**Save file:** N/A (sd card corrupted)

**Expected Behavior:** Bell chimes every hour.

**Actual Behavior:** Bell chimes every five minutes. Fuzzy audio when loading save. Occasional cuts to town hall announcements.

### Steps to reproduce
1. Play game as normal
2. Gameplay interrupted by sudden flashes on the screen followed by bells chiming (usually 10 o'clock but sometimes others like 12)

### nds-bootstrap.ini
```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = fat:/Games/Animal Crossing Wild World.nds
SAV_PATH = fat:/Games/saves/Animal Crossing Wild World.sav1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = fr
LANGUAGE = 2
REGION = 2
DSI_MODE = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs
```
Module params offset: 02000B64
sdk_version: 030028A0
arm9 is compressed
Secure area already decrypted
patchCardNds

cardIrqEnable location : 020E82A8

startOffset : 02000000

Mpu start 2: 02000A90

Mpu data 2: 02000B20

Mpu init 2: 0211DE70

cardRead location : 02127620
023FA800

cardPullOut location : 02127D80

cardReadDma location : 02127720

reset location : 0211E78C

ERR_NONE

WRAM end addr location : 023800D0

WRAM clear location : 0238064C

cardIrqEnable location : 02380B18

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238028C
Relocation dst: 037F8000

Arm7 (patch v2)
cardReadEndAddr: 02388D68
cardstructAddr: 038090C0
readCacheEnd: 02388EA4
JumpTableFunc: 02388EA8
returned_A0_with_MKDS: 02388F48
addrOfSomething_85C0: 0238884C
anotherLocinA7WRAM: 038096E4
amal_8CBC: 02388F48
aFinalLocation: FE388F2C
Eeprom protect:	02388F88
Card id:	02388F90
Card read:	02388FB0
Eeprom read:	02388FC8
Eeprom page write:	02388FE0
Eeprom page prog:	02388FF8
Eeprom verify:	02389010
Eeprom page erase:	02389020
swi12 location : 0238948C

swiGetPitchTable location : 02384448

ERR_NONE

hookLocation arm7: 0238F7C0

hookLocation arm9: 027E0000

chipID: 00003FC2
(+about 1000 empty lines)
```

### Other notes

- Seemed to cut to town hall announcements (especially La-Di-Day) much more frequently on v0.72.1
- Sounds very similar to issue #998 except this is on B4DS/DS Lite instead of DSi
- My save file was initially made in DSONE EOS but a new save file made in TWiLight Menu has the same issues.
- Several folders on my sd card vanished between me turning it off (by triggering in game menu) and putting it in the computer. (PLEASE KEEP IN MIND I AM NOT SURE IF NDS BOOTSTRAP WAS THE CAUSE)
- Sadly it seems only the saves folder was unrecoverable (via recuva). All other folders could be recovered via a deep scan.
- Upon checking the nds-bootstrap.ini still exists but is zero bytes.

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Sounds like the SD card is dying. Please try a new one.
As for the RTC bug, I'm surprised this hasn't been reported until now, as I've always thought the bug was caused by reading from the DSi/3DS SD card.
