### ISSUE TITLE
[3DS] The command to open the menu while playing (L + Down + Select by default) does not work in Pokémon Gen V games once I resume my game (it does work on the game title screen)

### ISSUE THREAD

**Issue by ElderjiLL** [DS-Homebrew/nds-bootstrap#1626]
**Your console:**
New 3DS XL

**Launch Method:**
SD card. Twilight Menu++ and nds-bootstrap latest

**Version used:**
Release

**Game tested/used/applicable:**
Pokémon White (EUR)
Pokémon Blaze Black 2 Redux (Black 2 hack ROM)

**Save file:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by ElderjiLL** [comment]
I don't have how to post the save file. I write from my mobile and I don't have a PC

**Comment by RocketRobz** [comment]
The button combo doesn't work, because C-Gear is turned on, which uses wireless communications.
It is done to prevent accidental wireless drops.

**Comment by ElderjiLL** [comment]
Thank you very much, I just tried and indeed it is as you say
