### ISSUE TITLE
L+R+↓+B does not work properly.

### ISSUE THREAD

**Issue by Non0611** [DS-Homebrew/nds-bootstrap#1627]
I'm using the latest version of TWiLight Menu++ and nds-bootstrap. L+R+↓+B doesn't work and returns me to the home menu. It worked fine before.

I am using New3ds.

**Comment by RocketRobz** [comment]
Does quitting the game work using the nds-bootstrap in-game menu?

**Comment by Non0611** [comment]
In that case, you can return to TWiLight Menu++ instead of the Home Menu.

**Comment by Non0611** [comment]
Sorry. I checked and it is working properly now. If I recall correctly, such a phenomenon may only occur after download play. That's how I feel.

**Comment by Non0611** [comment]
Sorry. I checked and it seems to be working properly now. From what I remember, this kind of phenomenon may only occur after download play. That's how I feel. Exiting from the in-game menu now successfully returns to TWiLight Menu++.

**Comment by RocketRobz** [comment]
Yeah, L+R+Down+B doesn't work sometimes.
