### ISSUE TITLE
I'm having problems with running DSiWare.

### ISSUE THREAD

**Issue by pmcc-notverysmartguy** [DS-Homebrew/nds-bootstrap#1628]
I'm using a DSi XL.

I'm new to this stuff. I don't know how to check the version, but I have Twilight Menu++ from dsi.cfw.guide as of 18/09/2023 on my SDHC card.

I don't know what version I use. I don't know if I use nightly. I don't know how to check these things.

I used a file of WarioWare Snapped. The file is called WarioWare - Snapped! (Europe, Australia) (En,Fr,De,Es,It).cia

[my sav.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/12644946/my.sav.zip)

I should've been able to see the DSiWare and play it.

I go into the folder I made for the DSiWare and nothing is inside.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
GUI_LANGUAGE = en
LANGUAGE = -1
DSI_MODE = 0
NDS_PATH = sd:/_nds/GBARunner2_arm7dldi_dsi.nds
HOMEBREW_ARG = sd:/gba/Donkey Kong Country (Europe) (En,Fr,De,Es,It).gba
BOOST_CPU = 1
BOOST_VRAM = 0

```

### Logs

Is DSiWare supposed to be a .cia file?

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
This issue occurs in TWiLight Menu++, which cannot display CIA files, and must end in .nds format.
For assistance, please join our Discord server here: https://discord.gg/yD3spjv

**Comment by pmcc-notverysmartguy** [comment]
How should I convert them to .nds?

**Comment by RocketRobz** [comment]
> How should I convert them to .nds?

Please join our Discord server, and we'll help you there. It'll be much faster than posting here.
