### ISSUE TITLE
Mario vs Donkey Kong Mini Land Mayhem Data Abort

### ISSUE THREAD

**Issue by Sukotto-1999** [DS-Homebrew/nds-bootstrap#1629]
**Your console: New Nintendo 3DS XL**

**Launch Method: SD Card**

**Version used: 1.0.0**

**Game tested/used/applicable: Mario vs Donkey Kong Mini Land Mayhem**

**Expected Behavior: The game should boot normally.**

**Actual Behavior: Game Hangs with a Data Abort**

### Steps to reproduce
1. Launch game.

### Will you be available for future issues and/or replies?

Yep.

**Comment by RocketRobz** [comment]
nvm, it has not fixed it.

**Comment by Sukotto-1999** [comment]
Should work when new NDS-bootstrap version releases.

**Comment by RocketRobz** [comment]
> Should work when new NDS-bootstrap version releases.

But I don't see why it's not working on v1.0.0 on your side, as it does work for me.
Please upload a photo of the error screen.

**Comment by Adanas2009** [comment]
I had the same issue:

![screenshot01](https://github.com/DS-Homebrew/nds-bootstrap/assets/106552987/b5539b11-b5b8-4425-801a-c3950a377fac)

**Comment by RocketRobz** [comment]
> > > Should work when new NDS-bootstrap version releases.
> > 
> > 
> > But I don't see why it's not working on v1.0.0 on your side, as it does work for me. Please upload a photo of the error screen.
> 
> ![IMG20241126190827](https://private-user-images.githubusercontent.com/36301121/389987191-9033be94-0140-4a16-8db7-b1f4e3ed29bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTYwMzksIm5iZiI6MTczMjY1NTczOSwicGF0aCI6Ii8zNjMwMTEyMS8zODk5ODcxOTEtOTAzM2JlOTQtMDE0MC00YTE2LThkYjctYjFmNGUzZWQyOWJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDIxMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmI2NTE3YWYxMjBmNWUwYTUzOGE0NjZmOTE3MTg0MTQ3Yjg5NTlhOGY1ZWI1NjBkOTRhMjZkMzRhNGQyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xwYFLoLaMeu_iD6tbZt4WyF8WOeZMHEYTX_ElpndI4s) Game doesn't run in DSi mode, but runs in DS mode. EU version on JP DSi with EU hiyaCFW.
> 
> UPD: Game runs on nightly bootstrap in DSi mode

Both USA and EUR versions work fine for me in DSi mode on a USA DSi console running nds-bootstrap v2.2.2.
Try re-installing TWLMenu++.
- https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
- https://wiki.ds-homebrew.com/twilightmenu/installing-dsi
