### ISSUE TITLE
Some games not working on nds bootstrap

### ISSUE THREAD

**Issue by Adanas2009** [DS-Homebrew/nds-bootstrap#1631]
Hey, some games like Mario vs Donkey Kong mini land mayhem and club penguin epf herbert's revenge don't work on ndsbootstrap. When I try to launch any of those games, it keeps giving me a data error when the game starts. Can anyone help me?

**Comment by RocketRobz** [comment]
- Which nds-bootstrap version are you using?
- Are you running from a flashcard or console's SD card?

**Comment by Adanas2009** [comment]
I am using v1.0.0: Rise of The Sun, as included with the twilight menu++. I am running on a 3ds with an sd card.

**Comment by RocketRobz** [comment]
Try re-installing using these guides:
1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds
2. https://wiki.ds-homebrew.com/twilightmenu/installing-3ds

**Comment by Adanas2009** [comment]
It didn't work... it showed the same data abort error when starting Mario vs donkey kong mini land mayhem. :(

I wonder, am I using the correct nds file for the game? Because there is different rev files for the game, which I downloaded from: https://romsfun.com/download/mario-vs-donkey-kong-mini-land-mayhem-25         but none of the USA versions don't work. Do I need the correct nds file? Which one do I need?

**Comment by RocketRobz** [comment]
> It didn't work... it showed the same data abort error when starting Mario vs donkey kong mini land mayhem. :(

Try deleting the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/` then.

> I wonder, am I using the correct nds file for the game? Because there is different rev files for the game, but none of the USA versions don't work. Do I need the correct nds file? Which one do I need?

I run Rev 2 of the USA version, which works on my side.
That said, hopefully the next version fixes it not booting.

**Comment by Adanas2009** [comment]
> Try deleting the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/` then.
> 
> I run Rev 2 of the USA version, which works on my side. That said, hopefully the next version fixes it not booting.

No, it didn't work again...
