### ISSUE TITLE
Final Fantasy the 4 heroes of light crashes after a few minutes of playing

### ISSUE THREAD

**Issue by ExGuestCJ** [DS-Homebrew/nds-bootstrap#1633]
**Your console:** Nintendo DSI xl

**Launch Method:** 1)sd card 2)dunno

**Version used:** 0.72.1

**Game tested/used/applicable:** Final Fantasy - The 4 Heroes of Light european version spanish patched

**Save file:** dont have

**Expected** Behavior:the game to play normally

**Actual Behavior:** theres a red screen a few minutes after starting the game

### Steps to reproduce
1. open the game
2. wait some minutes
3. and it crashes with a red screen

### Other notes
the creators of the patch dont wanna make an anti piracy fix for it and when booting the rom trough twilight menu it says it doesnt have an anti piracy fix or something like that

### Will you be available for future issues and/or replies?
Yes

**Comment by RocketRobz** [comment]
Try updating TWiLight Menu++ and nds-bootstrap first.
If the issue persists, then try AP-patching the clean ROM, before applying the translation patch to it.

**Comment by ExGuestCJ** [comment]
> Try updating TWiLight Menu++ and nds-bootstrap first. If the issue persists, then try AP-patching the clean ROM, before applying the translation patch to it.

ok when my dsi gets fixed bc my brother broke it

**Comment by RocketRobz** [comment]
As of later versions of TWLMenu++, the Spanish translation should already be AP-patched.
