### ISSUE TITLE
Apollo Justice: Ace Attorney crashing after displaying specific text box

### ISSUE THREAD

**Issue by Rocketman512** [DS-Homebrew/nds-bootstrap#1634]
**Your console:** Original 3DS 

**Launch Method:** SD Card. I believe I didn't touch SCFG at all.

**Version used:** Release Build: v1.0.0

**Game tested/used/applicable:** Apollo Justice: Ace Attorney PAL Germany (NTR-AGCX-EUR)

**Save file:** Sadly not available, but can be replicated by going to the part before recess in the first Trial.

**Expected Behavior:** The game should have continued displaying dialogue, playing music, and otherwise simply continuing as usual.

**Actual Behavior:** The game froze on a specific text box. ( "...Ergo! Ms. Olga Orly conspired to cheat, not with my client... ...but with the victim, Mr. Shadi Smith!" )

### Steps to reproduce
1. Get to the part before recess in the first trial.
2. If replicable, it should crash when Apollo says: "...Ergo! Ms. Olga Orly conspired to cheat, not with my client... ...but with the victim, Mr. Shadi Smith!"

### nds-bootstrap.ini
```
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
NDS_PATH = sd:/Apollo Justice - Ace Attorney.nds
SAV_PATH = sd:/saves/Apollo Justice - Ace Attorney.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = de
LANGUAGE = -1
REGION = 2
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
ASYNC_CARD_READ = 0
USE_ROM_REGION = 1
B4DS_MODE = 0
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
```

### Logs
```
Module params offset: 02000B84
sdk_version: 03027532
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 020AA014

startOffset : 02000000

Mpu start: 02000AA4

Mpu data: 02000B38

Mpu init: 020ABB6C

Mpu data alt: 020AB8A0

Mpu start 2: 02000AAC

Mpu data 2: 02000B3C

Mpu init 2: 020ABB74

waitCpuCycles location : 020AC4EC

cardRead location : 020B3A44
03700000

swi12 location : 02000082

cardPullOut location : 020B4284

cardId location : 020B39DC

cardReadDma location : 020B3B44

reset location : 020AC520

ERR_NONE

Sleep location : 0238E0C4

cardIrqEnable location : 02383EDC

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

Arm7 (patch vAll)

JumpTableFunc: 0238C200
Eeprom read:	0238C20C
Eeprom page write:	0238C224
Eeprom page prog:	0238C23C
Eeprom verify:	0238C254
Eeprom page erase:	0238C268
swi12 location : 0238C6F4

swiGetPitchTable location : 02387864

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02390440

ERR_NONE
hookLocation arm9: 027E0FE0

chipID: 00003FC2
```

### Other notes

Here is a YouTube video, which should give more insight into the issue. ( https://youtu.be/5DYSXHdl7_s )

### Will you be available for future issues and/or replies?

Yes!

**Comment by RocketRobz** [comment]
I think that's a known issue which can be worked around by setting `ARM9 CPU Speed` to `133mhz (TWL)` in the per-game settings menu (opened in TWLMenu++ by pressing Y button, or the forwarder by holding Y button before the game starts).

**Comment by Rocketman512** [comment]
It still crashed, exactly like in the video. I suspect that my dump of Apollo Justice is just damaged or of some sort. Ill try to see if I can find my other copy of Apollo Justice that I lost once to see if it works when dumped.

**Comment by Rocketman512** [comment]
Yeah... My Dump is damaged. When I tried the dump of my sister's copy, it worked flawlessly. My dump didn't even work in an emulator, even after dumping again, so I guess I'll just order another copy, it isn't that expensive anyway so It won't be as much of an inconvenience.
