### ISSUE TITLE
unstable multiplayer connection

### ISSUE THREAD

**Issue by zhoratxd** [DS-Homebrew/nds-bootstrap#1636]
The problem I am having is that I updated Twilight menu on my 3DS and Nintendo DSi console where I always played Mario Kart with my nephew and now in this new version it is unstable I create a group and when playing the first race the game disconnects only by losing the connection that was had and this started only when I updated to its latest version

**Comment by edo9300** [comment]
I can confirm having connection issues playing mkds multiplayer (one via r4 and the other twilight/bootstrap on the last version via memory pit). Didn't have time to test if with older releases things work properly tho

**Comment by RocketRobz** [comment]
Tried with both DSi & 3DS consoles running MKDS via TWLMenu++, and didn't have any connection issues on my side, though this is with latest nightly.
Tried both single-card and multi-card modes.
