### ISSUE TITLE
Super Mario 64 DS doesn't allow for touchscreen usage

### ISSUE THREAD

**Issue by Mine4114** [DS-Homebrew/nds-bootstrap#1637]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launched via microSD card, through TWiLightMenu++

### Version used

Release 1.0.1

### Game tested/used/applicable

Super Mario 64 DS(with circle pad patch applied)

### Expected Behavior

Game should allow for bottom screen to be tapped to pass the "Touch to Start" screen

### Actual Behavior

Touchscreen is unresponsive.

### Steps to reproduce

Boot game for the first time

### nds-bootstrap.ini

`[NDS-BOOTSTRAP]
NDS_PATH = sd:/Super Mario 64 DS (USA, Australia) (Rev 1)-patched.nds
SAV_PATH = sd:/saves/Super Mario 64 DS (USA, Australia) (Rev 1)-patched.sav
BOOST_CPU = 1
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 1
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
DSI_MODE = 2
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
GUI_LANGUAGE = en
HOMEBREW_ARG =
RAM_DRIVE_PATH = sd:/null.img
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0`

### Logs

Had to upload file, keyboard was acting up
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/12743397/NDSBTSRP.LOG)

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Does touch work without the Circle Pad patch?

**Comment by Mine4114** [comment]
I'll check, give me a few minutes

**Comment by Mine4114** [comment]
Yeah, I think it was a bad patch

**Comment by Searinox** [comment]
Having played the game myself on 1.0.0 and 1.0.1, I've never had issues with the touchscreen.

**Comment by NightScript370** [comment]
> Yeah, I think it was a bad patch
Seems like you solved it. Great
Closing...
