### ISSUE TITLE
Yoshi Touch & Go errors out then loading.

### ISSUE THREAD

**Issue by lbezos10** [DS-Homebrew/nds-bootstrap#1639]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [X] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card via TwilightMenu++ (v26.1.1) with CFW (Luma3DS) powered by Boot9Strap.
O2DS Firmware: 11.17.0-50E

### Version used

release v1.0.1

### Game tested/used/applicable

Game in question
Name: Yoshi Touch & Go
Title ID: NTR-AYIP-EUR
Region: Europe

Donor ROM:
Name: WarioWare: Touched!
Title ID: NTR-AZWP-EUR
Region: Europe

### Expected Behavior

It should run the game.

### Actual Behavior

Says: "An error has occurred" after the "Please wait..." message.

### Steps to reproduce

Set "WarioWare: Touched!" as Donor ROM.
Run "Yoshi Touch & Go"
Wait on the "Please wait..." screen.
See if the message "An error has occurred" appears.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Yoshi Touch & Go (Europe) (En,Fr,De,Es,It).nds
SAV_PATH = sd:/roms/nds/saves/Yoshi Touch & Go (Europe) (En,Fr,De,Es,It).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
SLEEP_MODE = 1
GAME_SOFT_RESET = 1
DONOR20_NDS_PATH = sd:/roms/nds/WarioWare - Touched! (Europe) (En,Fr,De,Es,It).nds

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/12781060/NDSBTSRP.LOG)

### Other notes

These games were trimmed by GodMode9 v2.1.1 so the hashes will be different.

### Will you be available for future issues and/or replies?

Yes

**Comment by JorgeRamirezDEV** [comment]
> @RocketRobz Thanks! I really appreciate the fix. :)

Hello! I would like to have some help on this, I'm not having a lot of experience in homebrew field.
I'm having exactly the same problem, how I could use this fix? Or should I wait until a new release?

**Comment by RocketRobz** [comment]
> Hello! I would like to have some help on this, I'm not having a lot of experience in homebrew field. I'm having exactly the same problem, how I could use this fix? Or should I wait until a new release?

Wait until a new release.
