### ISSUE TITLE
Pokémon sacred gold spanish white screen

### ISSUE THREAD

**Issue by zhoratxd** [DS-Homebrew/nds-bootstrap#1640]
I tried to play the Pokémon sacred gold version in Spanish and the game tries to load and stays on a white screen forever and I don't know how to solve it since it works in emulators and I play from my 3ds or DSi

**Comment by RocketRobz** [comment]
Which emulators did you try?

**Comment by zhoratxd** [comment]
> Which emulators did you try?

No$gba

**Comment by RocketRobz** [comment]
> No$gba

NO$GBA isn't a very accurate emulator, so please try with melonDS.

**Comment by zhoratxd** [comment]
> > No$gba
> 
> NO$GBA isn't a very accurate emulator, so please try with melonDS.

It works fine for me on no$gba the problem is on my consoles with Twilight menu since I don't want to play on an emulator

**Comment by RocketRobz** [comment]
> It works fine for me on no$gba the problem is on my consoles with Twilight menu since I don't want to play on an emulator

Please try it on melonDS, so that I'll know if it's issue with the ROM hack or not.
If the same issue occurs in melonDS, then it's an issue with the ROM hack.

If you don't want to try melonDS though, then try running it with the `Run in` setting set to `DSi mode` in TWLMenu++.

**Comment by Dartz150** [comment]
> > > No$gba
> > 
> > 
> > NO$GBA isn't a very accurate emulator, so please try with melonDS.
> 
> It works fine for me on no$gba the problem is on my consoles with Twilight menu since I don't want to play on an emulator

What Robz meant is that if it works in no$GBA, is because this emulator works differently than TwilightMenu++ in real hardware, so trying your romhack in MelonDS would give accurate results and tell you if the rom itself is the issue.

**Comment by zhoratxd** [comment]
> > It works fine for me on no$gba the problem is on my consoles with Twilight menu since I don't want to play on an emulator
> 
> Please try it on melonDS, so that I'll know if it's issue with the ROM hack or not. If the same issue occurs in melonDS, then it's an issue with the ROM hack.
> 
> If you _really_ don't want to try melonDS though, or if it works fine there, then try running it with the `Run in` setting set to `DSi mode` in TWLMenu++.

I already tried the DSi mode this morning and nothing worked and I'm sorry I don't have much time to try melonDS and it's not even an emulator that I like enough to go and download it

**Comment by RocketRobz** [comment]
Fixed by 8b5f70bf
