### ISSUE TITLE
The game will show the incorrect date/time.

### ISSUE THREAD

**Issue by eHerbaciarz** [DS-Homebrew/nds-bootstrap#1643]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [X] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launch form SD card

3DS software: 11.17.0-50E

### Version used

Check on v0.73.1 and 1.0.1

### Game tested/used/applicable

Zelda Spirit Tracks EU - but I think the problem also occurs in other games.

### Expected Behavior

The game will show the current date/time.

### Actual Behavior

When the link collects a stamp, the date of the given stamp is displayed in the book.

### Steps to reproduce

And when the game is launched, e.g. on 15/10 - the time is correct on the same day. However, if we close the console and open it after 3 days, when we collect the stamp, the date is still 15/10 instead of 18/10.

Turning the game off and on again fixes the problem.

### nds-bootstrap.ini

N/A

### Logs

N/A

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Are you sure the issue doesn't occur on the original cartridge(s)?

**Comment by eHerbaciarz** [comment]
> Are you sure the issue doesn't occur on the original cartridge(s)?

Yes, you are right - https://gamefaqs.gamespot.com/boards/959019-the-legend-of-zelda-spirit-tracks/52959506
