### ISSUE TITLE
doubt with Nintendo DS/DSi games

### ISSUE THREAD

**Issue by zhoratxd** [DS-Homebrew/nds-bootstrap#1644]
I have a very simple question. I have seen some videos where they reduce the weight of Nintendo DS/DSi games. They call it "tremear" but I would like to know if doing this by reducing the weight affects the Twilight menu and causes errors with the execution or finish a game

Program (NDSTokyoTrim)

**Comment by RocketRobz** [comment]
It should not cause any issues, but it may depend on the trimmer used.
