### ISSUE TITLE
Launching certain rom hacks gives "ERROR DATA ABORT" after boot screen

### ISSUE THREAD

**Issue by dldropper** [DS-Homebrew/nds-bootstrap#1645]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [X] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

launched through sd card on latest version crashed, don't know what scfg is.

### Version used

used release version, TWiLight Menu++ v26.1.1

### Game tested/used/applicable

- NSMBW v3.0.0
- Another Super Mario Bros. 2
- Newest Super Mario Bros. DS Deluxe Plus
- Newest Super Mario Doom (Remaster)

### Expected Behavior

the game/s should've opened the title screen and say "press start"

### Actual Behavior

it says:
https://drive.google.com/file/d/1mo9yCoD-G5Gr6aJxmX_tPr74zRnPydTg/view?usp=sharing

### Steps to reproduce

launch it/them in twilightmenu++

### nds-bootstrap.ini

https://drive.google.com/file/d/1csLAU0gSz2D--NHl3TGXk-y-URyfum4c/view?usp=sharing

### Logs

_None_

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
The ROM links have been removed. Please do not post links to ROMs.
Also, try downgrading nds-bootstrap to v1.0.0.

**Comment by dldropper** [comment]
sorry the hack maker wouldn't just post a hack file. how do i downgrade nds-bootstrap?

**Comment by RocketRobz** [comment]
> sorry the hack maker wouldn't just post a hack file. how do i downgrade nds-bootstrap?

Download it here, and follow the instructions: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v1.0.0

**Comment by dldropper** [comment]
Thanks!!! hope it's fixed in 1.0.2
