### ISSUE TITLE
Error Data aborted

### ISSUE THREAD

**Issue by FlazuelJr** [DS-Homebrew/nds-bootstrap#1647]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card
Is SCFG locked or Unlocked? Idk
Ver 1.4.5U

### Version used

TWiLight Menu++: v26.1.1
nds-bootstrap: Release v1.0.1

### Game tested/used/applicable

0434 - New Super Mario Bros. (U)(Psyfer) doesnt work 
0037 - Super Mario 64 DS (U)(Trashman) doesnt save

### Expected Behavior

They both should save and work

### Actual Behavior

0434 - New Super Mario Bros. (U)(Psyfer) doesnt work 
0037 - Super Mario 64 DS (U)(Trashman) doesnt save

### Steps to reproduce

Start the game
Play a level and try to save

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/0037 - Super Mario 64 DS (U)(Trashman).nds
SAV_PATH = sd:/roms/nds/saves/0037 - Super Mario 64 DS (U)(Trashman).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

I toggled it and played a level (nsmb ds) and tried launching super mario 64 but it did not create one

### Will you be available for future issues and/or replies?

Yes

**Comment by FlazuelJr** [comment]
![IMG_6399](https://github.com/DS-Homebrew/nds-bootstrap/assets/149436153/6946da9f-d0e6-4353-84ba-f49372140812)

**Comment by FlazuelJr** [comment]
wait I found the logs
findModuleParamsOffset:
Module params offset found
Module params offset: 02000B64
sdk_version: 03007532
arm9 is compressed

Switched to NTR mode BIOS
Cloneboot detected
patchCardNds

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 020434A8

startOffset : 02000000

findMpuStartOffset:
Mpu init found

Mpu start: 02000A88

findMpuDataOffset:
Mpu data found

Mpu data: 02000B1C

Mpu init: 0206EA30

findMpuDataOffsetAlt:
Mpu data found

Mpu data alt: 0206E8DC

findMpuStartOffset:
Mpu init found

Mpu start 2: 02000A90

findMpuDataOffset:
Mpu data found

Mpu data 2: 02000B20

Mpu init 2: 0206EA38

findWaitCpuCyclesOffset:
Wait CPU cycles found

waitCpuCycles location : 02045B00

findCardReadEndOffsetThumb:
ARM9 Card read end thumb not found

findCardReadEndOffsetType0:
ARM9 Card read end (type 0) elaborate not found
ARM9 Card read end (type 0) short found: 020774B4

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffsetType0:
ARM9 Card read start (type 0) found

cardRead location : 020773BC
03700000

findCardPullOutOffset:
Card pull out handler found

cardPullOut location : 02077BBC

findCardIdEndOffset:
Card ID end found: 020773B4

findCardIdStartOffset:
Card ID start found

cardId location : 02077358


patchCardSetDma
findCardSetDma
cardSetDmaSignatureValue1 found
02048CE8 : 04100010
cardSetDmaSignatureValue1 found
020773B8 : 04100010
cardSetDmaSignatureValue1 found
020774B4 : 04100010
cardSetDmaSignatureValue1 found
02077744 : 04100010
cardSetDmaSignatureValue2 found
0207774C : 040001A4
cardSetDmaEnd found
0207774C : 040001A4
cardSetDmaSignatureStart used: cardSetDma found


NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020776F8

findCardReadDmaEndOffset:
Card read DMA end found: 02077608

findCardEndReadDma

offsetDmaHandler found
02077614 : 0206EE38
Offset before relocation: 02077618
cardEndReadDma found


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 02077658

findResetOffset
Reset found: 0206EE88
Reset constant found: 0206EF04
Reset found

reset location : 0206EE88

ERR_NONE

findSleepPatchOffset:
Sleep patch found

Sleep location : 0238DE50

findCardIrqEnableOffset:
irq enable found

cardIrqEnable location : 02383DFC

findCardCheckPullOutOffset:
Card check pull out not found

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000
RAM mirror check location : 0238015C


Arm7 (patch v1)
[Error!] Card read addr not found

Arm7 (patch v2)
[Error!] Card read addr not found

Arm7 (patch vAll)

JumpTableFunc: 0238BFC8
Eeprom read:	0238BFD4
Eeprom page write:	0238BFEC
Eeprom page prog:	0238C004
Eeprom verify:	0238C01C
Eeprom page erase:	00000008
findSwi12Offset:
swi 0x12 call found

findSwiGetPitchTableOffset:
swiGetPitchTable SDK <= 2 call not found
swiGetPitchTable SDK <= 2 call alt 1 not found
swiGetPitchTable SDK <= 2 call alt 2 not found
swiGetPitchTable SDK <= 2 call alt 3 not found
swiGetPitchTable SDK <= 2 call alt 4 not found
swiGetPitchTable SDK <= 2 call alt 5 not found
swiGetPitchTable SDK <= 2 call alt 6 not found
swiGetPitchTable SDK <= 2 call alt 7 not found
swiGetPitchTable SDK <= 2 call alt 8 not found
swiGetPitchTable SDK <= 2 call alt 9 not found
swiGetPitchTable SDK <= 2 call alt 10 not found
swiGetPitchTable SDK <= 2 call alt 11 not found
swiGetPitchTable SDK <= 2 call alt 12 not found
swiGetPitchTable SDK <= 2 call alt 13 not found
swiGetPitchTable SDK <= 2 call alt 14 not found
swiGetPitchTable SDK <= 2 call alt 15 not found
swiGetPitchTable SDK 3 call not found
swiGetPitchTable SDK 3 call alt 1 not found
swiGetPitchTable SDK 3 call alt 2 not found
swiGetPitchTable SDK 3 call alt 3 not found
swiGetPitchTable SDK 3 call alt 4 not found
swiGetPitchTable SDK 3 call alt 5 found

swi12 location : 0238C4A0

swiGetPitchTable location : 02387750

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D4

ERR_NONE
handlerStartSig
02048964
handlerEndSig
020489A4
tableAddr
027E0000
returnAddr
01FFD63C
hookLocation arm9: 027E0000

chipID: 00001FC2

**Comment by RocketRobz** [comment]
Try reformatting the SD card here: https://dsi.cfw.guide/sd-card-setup.html
If the issue with SM64DS persists, then your ROM might be corrupted.

**Comment by RocketRobz** [comment]
Closing due to lack of response.
