### ISSUE TITLE
Style Lab Jewelry Design does not boot up

### ISSUE THREAD

**Issue by captured-nostalgia** [DS-Homebrew/nds-bootstrap#1649]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [X] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

rom on 64gb microSD card, launched via twilight menu

### Version used

Twilight menu v26.2.0, nds-bootstrap v1.0.2

### Game tested/used/applicable

Style Lab: Jewelry Design (twl-vjwe-usa),  tested original and rev 1

### Expected Behavior

Game should have loaded and started up

### Actual Behavior

Selected game in twilight menu, gets stuck on white screen and won't start at all

### Steps to reproduce

try to boot game on twilight menu ver26.2.0

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Style Lab - Jewelry Design (USA) (En,Fr,Es) (NDSi Enhanced).nds
SAV_PATH = sd:/roms/nds/saves/Style Lab - Jewelry Design (USA) (En,Fr,Es) (NDSi Enhanced).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

eader CRC is valid!
Module params offset: 02004FCC
Ltd module params offset: 02004F7C
sdk_version: 05017537
arm9 is not compressed
arm9i is not compressed

hi heap end: 02116CB0

patchCardNds

[SDK 5]

cardIrqEnable location : 021158C4

startOffset : 02004000

Mpu start 2: 02004AD4

Mpu data 2: 02004B90

Mpu init 2: 02004B20

Mpu change: 02116C50

Mpu init end TWL: 02116C70

waitSysCycles location : 02117AD0

cardRead location : 02108AB8
02FD6C00

swi12 location : 0200477A

dsiModeCheck location : 02004EB4

dsiModeCheck2 location : 0211663C

cardRomInit location : 02108E68

cardHashInit location : 0242C2F0

cardPullOut location : 02108F30

cardId location : 02108990

patchCardSetDma
cardReadDma location : 02108C6C

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 02108C58

reset location : 02117BA8

ERR_NONE

SCFG_EXT location : 02380258

Sleep location : 0238D8D4

RAM clear I location : 02E9739C

RAM clear I 2 location : 02E972C0

cardIrqEnable location : 02384AD8

Relocation src: 02380644

Arm7 (patch v5)
JumpTableFunc: 02390258
card id:	02390234
card read:	02390244
Eeprom read:	02390264
Eeprom page write:	0239027C
Eeprom page prog:	02390294
Eeprom verify:	023902AC
Eeprom page erase:	023902C0
swi12 location : 02383D80

swiGetPitchTable location : 02383D94

sdCardReset location : 02EB4BE4

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023921D8

ERR_NONE
hookLocation arm9: 02FE017C

chipID: C0001FC2

### Other notes

I've tried deleting and redownloading rom and still nothing, I've let the 3ds sit and see if it'll eventually load and still nothing.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Please turn on logging in the nds-bootstrap page, re-launch the game, wait for the issue to occur again, and upload `NDSBTSRP.LOG` from the SD root.

**Comment by captured-nostalgia** [comment]
> Please turn on logging in the nds-bootstrap page, re-launch the game, wait for the issue to occur again, and upload `NDSBTSRP.LOG` from the SD root.

I have updated the post with the log
