### ISSUE TITLE
Ds apps (Ds download, Ds games, Twilight menu, etc.) won't work on a new nintendo 3ds xl with Cfw

### ISSUE THREAD

**Issue by Willy342** [DS-Homebrew/nds-bootstrap#1650]
When i try to open any ds apps it displays a white screen for a second and then shuts down the console.
I asked for help also in the discord channel of nintendo hombrew and i tried different solutions (ctrcheck, hardware test, manual twlfix, etc.) but nothing worked can anyone help?

**Comment by SleepyLark** [comment]
This issue doesn't seemed to be caused by nds-bootstrap/TWiLightMenu and shouldn't be posted here.

As for the problem you're having, personally I have no idea how to fix it if neither twlfix nor CTRtransfer worked
