### ISSUE TITLE
Tetris DS Data Abort upon disconnecting from WFC and upon entering Records in menu

### ISSUE THREAD

**Issue by bartekmil** [DS-Homebrew/nds-bootstrap#1652]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launched via SD card with latest version of NDS bootstrap (1.0.2) and TWLmenu, tried launching the game with both DS and DSi mode (no difference)

### Version used

Release version 1.0.2 of NDSbootstrap with the latest halloween release twilight menu

### Game tested/used/applicable

Tetris DS (Europe) (En,Fr,De,Es,It) and upon crash I also tried in Tetris DS (USA, Australia) with no change in behavior

### Expected Behavior

Game should just display Records and High scores

### Actual Behavior

Upon exiting WFC or WFC settings the game freezes with black screen for some seconds, there is sometimes a message "corrupt save data, deleting". After that once you enter Records the game displays a red screen with Data Abort
When completing Marathon, no prior black screen appeared and the crash manifested only upon entering Records
![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/19625430/674be132-8bcc-4f28-b7c2-ad3531aa0f2b)
![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/19625430/28e04806-0936-441d-a87f-e4148bcdae2d)
![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/19625430/1d9aa572-6e97-4912-8af3-6be3e79362fd)
![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/19625430/0d00d5b7-4076-4c66-bb10-0b9936cde4fc)

### Steps to reproduce

[savestetrisds.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/13337614/savestetrisds.zip)
To trigger the crash either:
1.Enter Wi-fi connection settings and then the Records in menu
2.connect to WFC, disconnect, and then go to Records
3.Complete Marathon mode and then enter Records
Any of these steps lead to the red screen

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
USE_ROM_REGION = 1
PRECISE_VOLUME_CONTROL = 1
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
GUI_LANGUAGE = en
LANGUAGE = 1
DSI_MODE = 1
NDS_PATH = sd:/roms/nds/fav/Tetris DS (Europe) (En,Fr,De,Es,It).nds
HOMEBREW_ARG =
BOOST_CPU = 0
BOOST_VRAM = 1
SAV_PATH = sd:/roms/nds/fav/saves/Tetris DS (Europe) (En,Fr,De,Es,It).sav2
RAM_DRIVE_PATH = sd:/null.img
REGION = 2
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
APP_PATH = sd:/ROMS/DSI/BOMBER~1.NDS
PRV_PATH = sd:/ROMS/DSI/SAVES/  Ŕ7
GAME_SOFT_RESET = 1
SLEEP_MODE = 1

```

### Logs

```
Header CRC is valid!
Module params offset: 02000B68
sdk_version: 03004F4D
arm9 is not compressed

Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 02004BBC

startOffset : 02000000

Mpu start: 02000A88

Mpu data: 02000B1C

Mpu init: 0200778C

Mpu data alt: 02007228

Mpu start 2: 02000A90

Mpu data 2: 02000B20

Mpu init 2: 02007794

waitCpuCycles location : 020080E4

cardRead location : 0200F7DC
03700000

swi12 location : 02000134

cardPullOut location : 0200FF88

cardId location : 0200F77C


patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0200FB00


NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0200FA6C

reset location : 02008128

ERR_NONE

Sleep location : 0238DE4C

cardIrqEnable location : 02383DF0

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000
RAM mirror check location : 0238015C


Arm7 (patch vAll)

JumpTableFunc: 0238BFC4
Eeprom read:	0238BFD0
Eeprom page write:	0238BFE8
Eeprom page prog:	0238C000
Eeprom verify:	0238C018
Eeprom page erase:	00000008
swi12 location : 0238C49C

swiGetPitchTable location : 0238774C

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D0

ERR_NONE
hookLocation arm9: 027C0008

chipID: 00000FC2
```

### Other notes

The bug didn't appear when I had the old version of Twilight menu (23.4.0) and nds-bootstrap (0.53.2) installed - back then I could connect and disconnect from WFC with no problem - I'm pretty sure the bug first appeared when playing the game for the first time after the update. I tried two different roms, tried unpacking them with 7zip, tried unpacking TWLmenu update with 7zip too.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
I cannot reproduce this issue, so it's likely difficult to fix.
Have you tried with nds-bootstrap v1.0.0?
