### ISSUE TITLE
when the game loads the save it crashes (gta chinatown wars)

### ISSUE THREAD

**Issue by axellevi200** [DS-Homebrew/nds-bootstrap#1655]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

via SD card
I don't know how to find out about the SCFG
luma 13.0.2 
11.17-50E

### Version used

I use the only version available

### Game tested/used/applicable

I don't know what it is

### Expected Behavior

1) (without saving) when I launch the game there is the launch cinematic it offers a new game I select my save and the game launches without problem
2) (with save) when I launch the game there is the launch cinematic and the game launches

### Actual Behavior

1) (without saving) when I launch the game there is the launch cinematic it offers a new game I select my save and the game crashes
2) (with save) when I launch the game there is the launch cinematic and the game crashes

### nds-bootstrap.ini

`[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/3517 - Grand Theft Auto - Chinatown Wars (USA) (En,Fr,De,Es,It).nds
SAV_PATH = sd:/roms/nds/saves/3517 - Grand Theft Auto - Chinatown Wars (USA) (En,Fr,De,Es,It).sav
BOOST_CPU = -1
DEBUG = 0
CACHE_FAT_TABLE = 0
AP_FIX_PATH = /_nds/nds-bootstrap/apFix.ips
BOOST_VRAM = 0
CARD_READ_DMA = -1
ASYNC_CARD_READ = -1
DSI_MODE = 1
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
USE_ROM_REGION = 1
`

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/13502369/NDSBTSRP.LOG)

### Other notes

I use ndsForvarder
[image.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/13502362/image.zip)

### Will you be available for future issues and/or replies?

No

**Comment by SleepyLark** [comment]
Please remove the link to the ROM

**Comment by axellevi200** [comment]
For what

**Comment by SleepyLark** [comment]
> I can't but what is that for?

The game is copyrighted so sharing links to it in any form is considered piracy. We don't need the ROM to debug the issue

**Comment by RocketRobz** [comment]
Please check if the issue occurs with TWiLight Menu++.

**Comment by axellevi200** [comment]
When I go to the nds folder it makes the same error

**Comment by RocketRobz** [comment]
> When I go to the nds folder it makes the same error

This doesn't make it clear if you used TWiLight Menu++.
If you have not used it to launch the game, please do so.

**Comment by axellevi200** [comment]
> > When I go to the nds folder it makes the same error
> 
> This doesn't make it clear if you used TWiLight Menu++.
> If you have not used it to launch the game, please do so.

I speak French and the translation of your sentence seems strange to me (I can no longer answer but tomorrow yes)

**Comment by axellevi200** [comment]
Yes I did this with a downloaded ROM (I couldn't answer you but tomorrow yes)

**Comment by axellevi200** [comment]
je ne peux pas mais je t'envoi le fichier NDSBTSRP.LOG quand je pourait

> > When I go to the nds folder it makes the same error
> 
> This doesn't make it clear if you used TWiLight Menu++. If you have not used it to launch the game, please do so.

I can't but I will send you the NDSBTSRP.LOG file when I can

**Comment by RocketRobz** [comment]
A new forwarder pack update has been released, which should fix your issue. Please get it here: https://github.com/RocketRobz/NTR_Forwarder/releases/tag/SD-13

If the issue persists, ensure you have the `apfix.pck` file in `sd:/_nds/ntr-forwarder/`.

**Comment by axellevi200** [comment]
Thank you for what you do I unfortunately don't have my 3ds with me at the moment when I have it I will update

**Comment by axellevi200** [comment]
It works thank you
