### ISSUE TITLE
Error Data Abort Screen on every game after opening a game

### ISSUE THREAD

**Issue by KazunariYamagishi** [DS-Homebrew/nds-bootstrap#1657]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

1.0.9

### Game tested/used/applicable

Castlevania DoS/PoR Mario E Luigi BiS

### Expected Behavior

Error on the cfw?

### Actual Behavior

I try to play any game, but when I start to play just a few minutes later the error show up and doesn't let me play, I read that probably is gonna be that my games are corrupted but I just put new roms on it and the screen still show up, I tried other things like update TW Menu, Format my sd card but nothing fix it, idk what can be

### Steps to reproduce

.

### nds-bootstrap.ini

.

### Logs

.

### Other notes

Sorry for my bad english, Im mexican xd

### Will you be available for future issues and/or replies?

idk

**Comment by RocketRobz** [comment]
Please join our Discord server for assistance: https://discord.gg/yD3spjv
