### ISSUE TITLE
Pokemon Refined Gold Overhaul - Freezing at first battle

### ISSUE THREAD

**Issue by fmojica30** [DS-Homebrew/nds-bootstrap#1658]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card

### Version used

Release v26.3.1 

### Game tested/used/applicable

Pokemon Refined Gold Overhaul v3.1
Pokemon - HeartGold Version (USA).nds  --> Base nds
RefGoldOverhaul_v3.1.0_Climax Of Avaritia.xdelta --> Patch file

### Expected Behavior

The game should have kept playing as normal.

### Actual Behavior

Game freezes on first battle with Silver after meeting with Mr.Pokemon with continuously spinning pokeball 

### Steps to reproduce

1) Play game
2) Save right before fight with silver
3) Battle with silver

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Pokemon - HeartGold Version (USA).nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - HeartGold Version (USA).sav
BOOST_CPU = 0
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
USE_ROM_REGION = 1
DSI_MODE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/13643782/NDSBTSRP.LOG)

### Other notes

I believe that the AP Patch for the Refined Gold overhaul is not working since it seems like the game is freezing as if it was not AP Patched.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
A new version of TWiLight Menu++ would need to be released to support v3.1 of that ROM hack.
