### ISSUE TITLE
Glory of Heracles [NTR-YEKE-USA] : Random "Data abort"

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/nds-bootstrap#1660]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [x] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

TWL Menu ++ v26.3.1

### Version used

release v1.0.3

### Game tested/used/applicable

0018bf6c799fcea931bb98818703bbbf  Glory of Heracles.nds
YEKE (NTR-YEKE-USA)

### Expected Behavior

No crash

### Actual Behavior

Random crash with "data abort"

### Steps to reproduce

Load provided save game, walk around and battle if necessary.

[Glory of Heracles.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/13753485/Glory.of.Heracles.zip)

### nds-bootstrap.ini

```
NDS_PATH = sd:/roms/nds/Glory of Heracles.nds
SAV_PATH = sd:/roms/nds/saves/Glory of Heracles.sav
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 0
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
LOADING_DARK_THEME = 0
LOADING_SWAP_LCDS = 0
LOADING_SCREEN_FOLDER = /_nds/TWiLightMenu/3dsmenu/loading/
LOADING_FRAMES = 8
LOADING_FPS = 10
LOADING_BAR_Y = 0
LANGUAGE = -1
BOOST_VRAM = 0
SOUND_FIX = 0
DSI_MODE = 1
GAME_SOFT_RESET = 0
FORCE_SLEEP_PATCH = 0
COLOR_MODE = 0
LOADING_BAR = 0
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 1
PRECISE_VOLUME_CONTROL = 0
HOMEBREW_ARG =
SOUND_FREQ = 0
AP_FIX_PATH =
DMA_ROMREAD_LED = -1
CACHE_FAT_TABLE = 0
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 1
MACRO_MODE = 0
CARD_READ_DMA = 1
REGION = -1
HOTKEY = 248
GUI_LANGUAGE = en
SDNAND = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
B4DS_MODE = 0
USE_ROM_REGION = 1
SLEEP_MODE = 1

```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/13753441/NDSBTSRP.LOG)

### Other notes

![screenshot01](https://github.com/DS-Homebrew/nds-bootstrap/assets/418685/2ac12233-9000-44b9-a743-a1f8521475bd)

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
Does this still happen on v1.4.0?

**Comment by eku** [comment]
Unfortunately, the crash also happens with version 1.4.2.

In your opinion, which commit should fix the crash?

**Comment by RocketRobz** [comment]
> Unfortunately, the crash also happens with version 1.4.2.
> 
> In your opinion, which commit should fix the crash?

Considering I have not tested the game, I have no idea.
Have you tried turning off card read DMA though?

**Comment by eku** [comment]
> Have you tried turning off card read DMA though?

This setting causes the game to crash much more quickly.

**Comment by RocketRobz** [comment]
As of v1.6.2, I have not gotten a crash. Tested on a DSi XL.
I walked around and went through 4 battles, grabbed the items from the two chests, and went through the item explanation.

Unless some further testing is needed, it's safe to say this is fixed.
