### ISSUE TITLE
Transfer save data and ROMs to 3DS?

### ISSUE THREAD

**Issue by pmcc-notverysmartguy** [DS-Homebrew/nds-bootstrap#1666]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [X] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

On the DSi, I launch TWilightMenu++ from an SD card. No idea what an SCFG is.

### Version used

nds-bootstrap ver. release v1.0.0

### Game tested/used/applicable

Planning to transfer most of my games, with their save files.

### Expected Behavior

I should've been able to find a tool to let me transfer my save files from DSi to 2DS.

### Actual Behavior

It doesn't exist.

### Steps to reproduce

I dunno. Own both a DSi and 2DS, and try to transfer?

### nds-bootstrap.ini

`[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
GUI_LANGUAGE = en
LANGUAGE = 1
DSI_MODE = 1
NDS_PATH = sd:/dsiware/AlphaBounce (Europe, Australia).nds
HOMEBREW_ARG =
BOOST_CPU = 1
BOOST_VRAM = 1
SAV_PATH = sd:/DSIWARE/SAVES/ALPHAB~1.PUB
RAM_DRIVE_PATH = sd:/null.img
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
APP_PATH = sd:/DSIWARE/ALPHAB~1.NDS
PRV_PATH = sd:/DSIWARE/SAVES/  ä 
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
TÖ
GAME_SOFT_RESET = 1`

### Logs

Can't. Sorry.

### Other notes

I also want to transfer DSiWare, GBA, Sega Genesis, SNES, NES.

### Will you be available for future issues and/or replies?

Yes

**Comment by SleepyLark** [comment]
There's no difference between how the DSi and 3DS version reads game and save files. All you need to do is copy and paste the `roms` folder, or wherever you have you games stored on your DSi, to your 3DS' SD card and open Twilight Menu and navigate to that folder. Save files are found in a folder labeled `saves` and need to be inside the same folder as where your games are in order to work.

**Comment by pmcc-notverysmartguy** [comment]
Oh. Okay. Thanks.
