### ISSUE TITLE
Pokemon HS\DP&Platinum error after saving

### ISSUE THREAD

**Issue by Retashe** [DS-Homebrew/nds-bootstrap#1669]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

sd card, twilight last update

### Version used

I tested both, both failed
release v1.1.0
nightly 2c47c9d

### Game tested/used/applicable

Pokemon heart gold & soul silver 
Pokemon Platinum, Dimond & Pearl
both us version

### Expected Behavior

After saving the game, reopen or restart it and continue the saved game

### Actual Behavior

The game starts normally, and I can play as usual, but after saving, every time I start the game again, I get a blue screen, and even if I follow what it says, the game doesn't come back, HS stays in a loop restarting and Platinum stays on a white screen

### Steps to reproduce

start the game, save the game, restart

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
GUI_LANGUAGE = pt-BR
LANGUAGE = -1
DSI_MODE = 2
NDS_PATH = sd:/roms/nds/Pokemon Platinum R.nds
HOMEBREW_ARG =
BOOST_CPU = 0
BOOST_VRAM = 0
RAM_DRIVE_PATH = sd:/null.img
SAV_PATH = sd:/roms/nds/saves/Pokemon Platinum R.sav1
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

sorry my inglish its not very good, I didn't understand how to do this

### Other notes

As I said before, my English and computer skills are not very good, I ask for understanding

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
The error occurs because the WiFi card isn't seated correctly. To fix the issue, open the console up, and reseat the WiFi card.
