### ISSUE TITLE
Using Web Browser whitout Terminate Game

### ISSUE THREAD

**Issue by giiutfff** [DS-Homebrew/nds-bootstrap#1670]
While playing a 3ds game, pressing the home button gives access to game note and Web browser etc, and the game is paused. This is super convenient for example: looking for some info about the game, or take notes.
I wonder if this is possible for ds/dsiware games. Since it takes toooooo long to return to home menu and relunch the game, even worse it's not possible to take a snapshot of the game state(real time save), nor it's paused in background like 3ds games.

**Comment by RocketRobz** [comment]
Closing, as that's something that'd need to be implemented into TWL_FIRM itself.
