### ISSUE TITLE
Pokemon Ranger: Guardian Signs launch crash

### ISSUE THREAD

**Issue by allisonpelton** [DS-Homebrew/nds-bootstrap#1673]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD via TWiLight Menu++ v26.5.1

### Version used

Nightly -f198ba1

### Game tested/used/applicable

A5CA6241

### Expected Behavior

The game should launch to the title screen.

### Actual Behavior

![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/24703308/2045301a-6f5f-4bee-8c6c-33f3e1570883)

This screen appears before the game even reaches the title screen. The save file creation screen appears, and once it finishes the crash occurs.

Note that this screenshot is a little bit stale, and I still experience the crash on the version listed above.

### Steps to reproduce

Not necessary. Game crashes with no save file present. I can provide additional files if desired.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
ROMREAD_LED = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
NDS_PATH = sd:/gm9/out/5253 - Pokemon_Ranger_Guardian_Signs_USA.nds
SAV_PATH = sd:/gm9/out/saves/5253 - Pokemon_Ranger_Guardian_Signs_USA.sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
GUI_LANGUAGE = en
REGION = 1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
SDNAND = 1
MACRO_MODE = 0
HOTKEY = 284
USE_ROM_REGION = 1
B4DS_MODE = 0
SLEEP_MODE = 1
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14054141/NDSBTSRP.LOG)

### Other notes

I copied data from the SD over from my N2DSXL. I had this same issue on that console as far back as early 2020. I no longer have the old console.

I have tried changing the per-game and nds-bootstrap settings to all sorts of configs. None of that affected when the crash occurred.

I have never experienced crashes with any other games while using nds-bootstrap.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Try re-dumping the ROM from your cartridge.

**Comment by allisonpelton** [comment]
Sure thing. I didn't bring the cartridge with me to college so it'll be a few weeks, but I'll get back to you. I don't think the ROM is the problem, though. It loads fine in DeSmuME and the CRC matches. I wonder if my config could be wrong.

**Comment by RocketRobz** [comment]
> Sure thing. I didn't bring the cartridge with me to college so it'll be a few weeks, but I'll get back to you. I don't think the ROM is the problem, though. It loads fine in DeSmuME and the CRC matches. I wonder if my config could be wrong.

Maybe, because the game worked fine for me, last time I tried.

**Comment by RocketRobz** [comment]
@allisonpelton Any update?
