### ISSUE TITLE
Pokémon Platinum and HeartGold get an error after saving

### ISSUE THREAD

**Issue by pkmnisc** [DS-Homebrew/nds-bootstrap#1674]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [X] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card

### Version used

Latest Twilight Menu+++ (v26.5.1)
Last Updated: 16/01/2024

### Game tested/used/applicable

Pokémon Platinum
Pokémon Heartgold

### Expected Behavior

I start the game, everything is good. I save the game, turn off the Nintendo 3DS XL, turn it on, open the game and it loads normally.

### Actual Behavior

I start the game, everything is good. I save the game, turn off the Nintendo 3DS XL, turn it on, open the game and after the main menu of the game (in this case, after Giratina appears in Pokémon Platinum) loads and I click "A", I get a blue screen error.

### Steps to reproduce

1. Turn on Nintendo 3DS XL
2. Open Twilight Menu
3. Go to the rom and click on Pokémon Platinum (or HeartGold)
4. Start the game for the first time and then save
5. Turn off the nintendo
6. Turn on the nintendo again and start the game
7. After Giratina appears in the main menu and I click "A" on my nintendo, the following error appears:

"A communication error has occured. If you were in the Union Room, you will be returned there. In all other cases, you will be returned to wherever you last saved. Please press A button"

https://github.com/DS-Homebrew/nds-bootstrap/assets/157741095/5a052a96-6f65-4c19-bb40-933f928bf804

![WhatsApp Image 2024-01-25 at 18 52 56](https://github.com/DS-Homebrew/nds-bootstrap/assets/157741095/2979d35d-9ed6-4653-a952-11a849790d42)

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Pokemon Platinum Version.nds
SAV_PATH = sd:/roms/nds/saves/Pokemon Platinum Version.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

Yes

### Other notes

Here is everything I've tried already:

1. Checking Internet connection
2. Turn it off and on
3. Checked if the game is running in DSi or DS (it's DS)
4. Redownloaded the lastest version of everything from scratch (I reset everything)
5. Tried Twilight Menu++ Nightly

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
This is not an nds-bootstrap issue. It's an issue with your WiFi card, which would need to be re-seated after taking apart the console's shell.
