### ISSUE TITLE
Meet Error: Data Abort when play Gyakuten Kenji 2

### ISSUE THREAD

**Issue by YuYue39** [DS-Homebrew/nds-bootstrap#1678]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launched from SD card and boot from TWiLight Menu++

### Version used

TWiLight Menu++ Version: v26.6.0
nds-bootstrap: Release v1.2.2

### Game tested/used/applicable

*Gyakuten Kenji 2: NTR-BXOJ-JPN

*This game is not the offical JPN version, but the modified version, which is translated into Simplified Chinese.
You can get this ROM from this link: https://drive.google.com/file/d/1W7asCaAgvByc1WRuV6tGW_aL8yH5PqrB/view?usp=sharing
The offical JPN version runs fine.

### Expected Behavior

When running this ROM, you should be able to play this game as same as the offical JPN version. Here is the screenshot from the DeSumME, which proved this ROM is not broken.

![image](https://github.com/DS-Homebrew/nds-bootstrap/assets/94784423/11236305-a145-40a7-ad6c-585987666cb1)

By the way, this ROM is also works on R4.

### Actual Behavior

When running this ROM on DSi, it occurred error. See the screenshot below:

![screenshot01](https://github.com/DS-Homebrew/nds-bootstrap/assets/94784423/9041c0ed-7667-4ed5-9e6e-4859311af32d)

### Steps to reproduce

1. Copy the ROM to SD card
2. Launch the ROM from TWiLight Menu++
3. Wait for a second and you will get the error screen

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = sd:/Games/NDS/逆转检事2.nds
SAV_PATH = sd:/Games/NDS/saves/逆转检事2.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = zh-CN
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
HOMEBREW_ARG =
AP_FIX_PATH =
APP_PATH = sd:/GAMES/NDS/������~3.NDS
PRV_PATH = sd:/GAMES/NDS/SAVES/
GAME_SOFT_RESET = 1
```

Notice: "逆转检事2.nds" means "Gyakuten Kenji 2.nds", it's the Chinese name of the game. Use Chinese name for file manage.

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14323374/NDSBTSRP.LOG)

### Other notes

Here is the memory dump from the red screen, hope it's useful: https://drive.google.com/file/d/1Op-Jh80kNZmfJNsT_dCt1bQ-ZO7e1He5/view?usp=sharing

I don't know if it is complete because when I was dumping the console freezed and no text showed the dump was completed.

This ROM is from an unoffical translation team and it was dissolved for many years. So I can't answer any details about the ROM. Since this ROM works fine on the DeSumME and R4, I don't think it's the ROM problem.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Next version of nds-bootstrap will fix this issue.
