### ISSUE TITLE
keep getting error code with booting pokemon games

### ISSUE THREAD

**Issue by BluPhoenix09** [DS-Homebrew/nds-bootstrap#1679]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [X] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

twilight menu and home menu

### Version used

newest version or latest release

### Game tested/used/applicable

pokemon heartgold, soulsilver, black, white, black 2, white, 2, platinum, pearl, and diamond.

### Expected Behavior

should boot and let me start game

### Actual Behavior

wont boot at all where i get the red error screen

### Steps to reproduce

just trying to boot the game to play the game causes the crash and ive gotten a new sd card to try to fix it

### nds-bootstrap.ini

my email is Langscor000@gmail.com. i dont know how to get the ini file. ill send the real file
[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/14336671/nds-bootstrap.zip)

### Logs

[nds-bootstrap.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/14336672/nds-bootstrap.zip)

### Other notes

wont load any pokemon game i try booting thru twilight menu or the home menu if i put the games on the homesceen. keeps giveing error code
![WIN_20240219_12_55_10_Pro](https://github.com/DS-Homebrew/nds-bootstrap/assets/160540361/543e33f0-df1d-4049-92b3-897c3a65888c)
![WIN_20240219_12_55_09_Pro](https://github.com/DS-Homebrew/nds-bootstrap/assets/160540361/028816a7-e93e-418d-8bac-91b99a6f822c)
![WIN_20240219_12_55_08_Pro](https://github.com/DS-Homebrew/nds-bootstrap/assets/160540361/529d0d81-3216-4bd1-a0d7-d48ee79068ab)

### Will you be available for future issues and/or replies?

yes

**Comment by takeshineale128** [comment]
mine don't crash when loading with the twilight menu app ans i don't use forwarders

**Comment by BluPhoenix09** [comment]
im not sure what the problem is and im glad yours is working. but mine isnt and im looking to fix this problem. because for the 3ds and 3ds XL i have had no problems whatsoever modding it. but when i tried my friends 2DS because he wanted to get his modded it wouldnt load anything. i even compared files to mine in the 3DS XL and it all looks the same. so im not too sure what is going on.

**Comment by BluPhoenix09** [comment]
Took 3 hours looking thru files trying to find problem but couldn’t find it so I reset DS and SD card fully and re modded and re installed everything and it works just fine now.
