### ISSUE TITLE
SoulSilver ROMs don't start, immediately red-screen/Error: Data Abort

### ISSUE THREAD

**Issue by MarkedInStone** [DS-Homebrew/nds-bootstrap#1680]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

The Twilight Menu++ is on v.26.6.0, and the nds-bootstrap is v1.3.1

### Game tested/used/applicable

The game is a clean ROM of Pokemon SoulSilver. I have tried multiple versions of SoulSilver, every other ROM I've tried (Pokemon Black, Pokemon Ranger: Shadows of Almia, and New Super Mario Bros.) works. 

### Expected Behavior

After selecting SoulSilver from the menu, the ROM should have loaded normally and booted up the game. 

### Actual Behavior

After creating the save file, a red screen appears saying ERROR: DATA ABORT. 

### Steps to reproduce

1. Place a SoulSilver ROM in the nds folder. 
2. Open Twilight Menu.
3. Load the SoulSilver ROM through Twilight Menu. 
4. Red screen.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
GUI_LANGUAGE = en
LANGUAGE = -1
DSI_MODE = 1
NDS_PATH = sd:/roms/nds/New Super Mario Bros. (USA, Australia).nds
HOMEBREW_ARG =
BOOST_CPU = 0
BOOST_VRAM = 0
SAV_PATH = sd:/roms/nds/saves/New Super Mario Bros. (USA, Australia).sav
RAM_DRIVE_PATH = sd:/null.img
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH = 

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02000BBC
sdk_version: 04027533
arm9 is compressed
Secure area already decrypted
Switched to NTR mode BIOS
AP-fix found
patchCardNds

cardIrqEnable location : 020D11D4

startOffset : 02000000

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020D3190

Mpu data alt: 020D2ABC

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 020D3198

waitCpuCycles location : 020D3AA8

cardRead location : 020DD570
027D8000

swi12 location : 02000358

cardPullOut location : 020DDAD0

cardId location : 020DD660

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020DD2C0

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020DD35C

reset location : 020D3B84

ERR_NONE

Sleep location : 0238A314

cardIrqEnable location : 02380B80

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238026C
Relocation dst: 037F8000
RAM mirror check location : 0238015C

Arm7 (patch vAll)

JumpTableFunc: 02388730
Eeprom read:	0238873C
Eeprom page write:	02388750
Eeprom page prog:	02388764
Eeprom verify:	02388778
Eeprom page erase:	02388788
swi12 location : 02388B70

swiGetPitchTable location : 02383FCC

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 0238ECF4

ERR_NONE
hookLocation arm9: 027E0000

AP-fix applied
Overlays cached to a file
chipID: E0017FC2

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Has it worked prior to nds-bootstrap v1.3.0?

**Comment by RocketRobz** [comment]
I tried HeartGold on my side, and it boots fine on my side.
How did you install or update TWiLight Menu++ and nds-bootstrap?

**Comment by MarkedInStone** [comment]
They were both updated with UniversalUpdater- the thing is I do specifically want SoulSilver. I have not used any versions prior to the most recent (1.3.1)

**Comment by RocketRobz** [comment]
> They were both updated with UniversalUpdater- the thing is I do specifically want SoulSilver. I have not used any versions prior to the most recent (1.3.1)

Try using the manual method instead of Universal-Updater then.
https://wiki.ds-homebrew.com/twilightmenu/installing-3ds?tab=manual

**Comment by MarkedInStone** [comment]
Thank you! It's working. I'll use this thread in case the screen pops up again, if that's okay.

**Comment by RocketRobz** [comment]
> Thank you! It's working. I'll use this thread in case the screen pops up again, if that's okay.

Yeah, it can be helpful for others as well.
