### ISSUE TITLE
Heartgold, Soulsilver and Sonic Colors crashes to red screen

### ISSUE THREAD

**Issue by possom2009** [DS-Homebrew/nds-bootstrap#1682]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card.

### Version used

v1.4.0

### Game tested/used/applicable

All regions available, plus AP patched versions.

### Expected Behavior

Boot to game.

### Actual Behavior

Crashes to red screen.

### Steps to reproduce

Load game.

### nds-bootstrap.ini

`[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
DONORTWLONLY_NDS_PATH = nand:/title/00030004/484e4745/content/00000001.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
GUI_LANGUAGE = en
LANGUAGE = -1
DSI_MODE = 1
NDS_PATH = sd:/roms/nds/Sonic Colours (Europe) (En,Ja,Fr,De,Es,It)_apfix.nds
HOMEBREW_ARG =
BOOST_CPU = 0
BOOST_VRAM = 0
SAV_PATH = sd:/roms/nds/saves/Sonic Colours (Europe) (En,Ja,Fr,De,Es,It)_apfix.sav
RAM_DRIVE_PATH = sd:/null.img
REGION = -1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
APP_PATH = sd:/ROMS/NDS/3HEROE~1.NDS
PRV_PATH = sd:/ROMS/NDS/SAVES/  ¶9
GAME_SOFT_RESET = 1
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
`

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14756818/NDSBTSRP.LOG)

### Other notes

I've tried all versions of those games, plus AP patched versions. All crash to a red screen when booting.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
According to the log, you have cheats enabled. Try turning them off.

**Comment by possom2009** [comment]
> According to the log, you have cheats enabled. Try turning them off.

Turned cheats off, the only one that was on was the AP bypass cheat. They still crash to the red screen.

Here's the logs for each game.

[SS NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766023/SS.NDSBTSRP.LOG)
[HG NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766024/HG.NDSBTSRP.LOG)
[Sonic Colors NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766025/Sonic.Colors.NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
> Turned cheats off, the only one that was on was the AP bypass cheat. They still crash to the red screen.

Revert back to the clean ROMs, if you haven't done so then.
If the issue persists, then delete `usrcheat.dat` in `sd:/_nds/TWiLightMenu/extras/`.

**Comment by possom2009** [comment]
> > Turned cheats off, the only one that was on was the AP bypass cheat. They still crash to the red screen.
> 
> Revert back to the clean ROMs, if you haven't done so then. If the issue persists, then delete `usrcheat.dat` in `sd:/_nds/TWiLightMenu/extras/`.

Deleted usrcheat.dat and downloaded the no intro time from Vimm's Lair, games sill crash.

Here's the log files for each game.

[HG NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766213/HG.NDSBTSRP.LOG)
[Sonic Colors NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766214/Sonic.Colors.NDSBTSRP.LOG)
[SS NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14766215/SS.NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
@possom2009 Please don't mention ROM sites.

Try re-installing TWiLight Menu++ then:
1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
2. https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

If the issue persists, then reformat the SD card: https://dsi.cfw.guide/sd-card-setup.html

**Comment by possom2009** [comment]
> @possom2009 Please don't mention ROM sites.
> 
> Try re-installing TWiLight Menu++ then:
> 
> 1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
> 2. https://wiki.ds-homebrew.com/twilightmenu/installing-dsi
> 
> If the issue persists, then reformat the SD card: https://dsi.cfw.guide/sd-card-setup.html

It looks like the files were corrupted when I updated TWiLight Menu++. Uninstalling and reinstalling worked. Thanks!

**Comment by RocketRobz** [comment]
> It looks like the files were corrupted when I updated TWiLight Menu++. Uninstalling and reinstalling worked. Thanks!

You're welcome!
