### ISSUE TITLE
Final Fantasy Tactics A2 freezes at random times

### ISSUE THREAD

**Issue by eatorres** [DS-Homebrew/nds-bootstrap#1683]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

Latest stable release 1.4.0

### Game tested/used/applicable

Final Fantasy Tactics A2 - Grimoire of the Rift: NTR-A6FE-USA

### Expected Behavior

The game does not freeze on animations

### Actual Behavior

The game freezes whenever certain animations are used. Particularly using Aero on multiple targets or using Fire Breath
Sometimes it simply freezes when opening the unit menu

### Steps to reproduce

- Load the second save file
- Sometimes it freezes right away after opening the unit menu
- Other times it is after entering combat an using some of the "flashier" animations. Particularly using Aero with the black mage or Fire Breath with the dragoon

[Save.zip](https://github.com/DS-Homebrew/nds-bootstrap/files/14814005/Save.zip)

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Final Fantasy Tactics A2 - Grimoire of the Rift (U)(Independent).nds
SAV_PATH = sd:/roms/nds/saves/Final Fantasy Tactics A2 - Grimoire of the Rift (U)(Independent).sav
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/14813990/NDSBTSRP.LOG)

### Other notes

I've tried both TWL and NTR clock speeds and the freezes keep happening.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Have you tried turning off card read DMA?

**Comment by RocketRobz** [comment]
Also, if TWiLight Menu++ is not installed, and you're using a forwarder, ensure `apFix.pck` exists in `sd:/_nds/ntr-forwarder/`.

**Comment by eatorres** [comment]
@RocketRobz I'm using TWiLight Menu++. I haven't tried turning off card read DMA. I'll try right now and play for a bit

**Comment by eatorres** [comment]
I haven't encountered any issues in the past couple of days. I'll close the issue for now 👌
