### ISSUE TITLE
hackroms for twilight menu

### ISSUE THREAD

**Issue by isadksgad** [DS-Homebrew/nds-bootstrap#1684]
I was just playing some hackroms for inazuma eleven (1,2 and 3) and in some points the games crashes with a red error message. I was just wondering if it was fixable or not. All games have an AP message at the start of the game and i already tried to patch them, but i can't. If i try to patch the base game i can't apply the hackrom patch, if i patch the hackrom it ends with an error. I can provide any information if needed.

**Comment by NightScript370** [comment]
This doesn't give us any information on what type of device you're using, what romhacks, or anything. Please fill out the issue template and then try again
