### ISSUE TITLE
I need help D:

### ISSUE THREAD

**Issue by PedroNiccola** [DS-Homebrew/nds-bootstrap#1687]
I Am trying to Do a HeartGold Chsllenge in which I can only use Shinies, I was trying to get shiny Cyndaquil, but I pressed L+R+Start+Select but it didn't work, can you solve this problem? 🥺

**Comment by RocketRobz** [comment]
Are you using a flashcard? If so, then which one?

**Comment by PedroNiccola** [comment]
The 208 in 1 cartridge

**Comment by RocketRobz** [comment]
Install the Ace3DS+ flashcard kernel by following the flashcard firmware steps here: https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard

**Comment by PedroNiccola** [comment]
Tell me the steps, and how to soft reset after installing TWILIGHT Menu

**Comment by RocketRobz** [comment]
> Tell me the steps

They're in the linked page above.

> and how to soft reset after installing TWILIGHT Menu

Do you mean going back to TWLMenu++ while running a game? If so, then press L+Down+Select to open the in-game menu, then select `Quit Game`. It will not work for your flashcard, considering resetting the game doesn't work either.

**Comment by PedroNiccola** [comment]
But can you help me install TWiLight Menu?

**Comment by RocketRobz** [comment]
> But can you help me install TWiLight Menu?

Please join our Discord server for faster assistance: https://discord.gg/yD3spjv

**Comment by PedroNiccola** [comment]
thanks for helping
