### ISSUE TITLE
Game crash when taking a screenshot in Pokémon B/W/B2/W2 during battles

### ISSUE THREAD

**Issue by Adnan12349** [DS-Homebrew/nds-bootstrap#1689]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launched via the SD card

### Version used

nds-bootstrap 1.4.3 Release version

### Game tested/used/applicable

Pokémon B/W/B2/W2

### Expected Behavior

Continue gameplay

### Actual Behavior

Game crash in B/W and red screen crash in B2/W2

### Steps to reproduce

L + Dpad Down + Select, then pressing screenshot

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/
SAV_PATH = sd:/roms/nds/saves/
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DSI_MODE = 1
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -1
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
GAME_SOFT_RESET = 1

### Logs

Couldn't get a log file for some reasons

### Other notes

This only happens during battle when the buttom screen is focused, it instantly crash after, when only the top screen is the main focus it keeps on going until the buttom screen makes action then crashes.

### Will you be available for future issues and/or replies?

Yes

**Comment by WisteriaSp** [comment]
This happens to me too, sometimes the entire console locks up when taking screenshots in the overworld too.

**Comment by Adnan12349** [comment]
Closing, this was fixed in the newest update.

**Comment by Adnan12349** [comment]
Closing, this was fixed in the newest update.
