### ISSUE TITLE
Saga 2  (english translation patched) crash during game play.

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/nds-bootstrap#1691]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

v27.0.0

### Game tested/used/applicable

Saga 2  (english translation patched)

### Expected Behavior

Run without crash

### Actual Behavior

Crash during game play. For saga 2, crash after starting story it crash after father of main protagonist jump out of window.  

### Steps to reproduce

Run game to the same point of crashing.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = 0
PRECISE_VOLUME_CONTROL = 1
SDNAND = 1
MACRO_MODE = 0
SOUND_FREQ = 1
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/NDS/SaGa 2 - Legend of the Relics - Goddess of Destiny (Japan) [T-En by Crimson Nocturnal v2.12] [n].nds
SAV_PATH = sd:/roms/NDS/saves/SaGa 2 - Legend of the Relics - Goddess of Destiny (Japan) [T-En by Crimson Nocturnal v2.12] [n].sav
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
APP_PATH = sd:/ROMS/DSIWARE/DRAGON~2.NDS
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/
GAME_SOFT_RESET = 1
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b4a/content/00000002.app
SLEEP_MODE = 1

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02000BB8
sdk_version: 04027539
arm9 is not compressed
Secure area already decrypted
Switched to NTR mode BIOS
AP-fix found
patchCardNds

cardIrqEnable location : 020C931C

startOffset : 02000000

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020CA434

Mpu data alt: 020CA23C

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 020CA43C

waitCpuCycles location : 020CA800

cardRead location : 020C47A4
03700000

swi12 location : 02000156

cardPullOut location : 020C4B84

cardId location : 020C4860

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020C4590

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020C45FA

reset location : 020CA8D4

ERR_NONE

Sleep location : 0238E748

cardIrqEnable location : 02383B40

forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000
RAM mirror check location : 0238018C

Arm7 (patch vAll)

JumpTableFunc: 0238BCC8
Eeprom read:	0238BCD4
Eeprom page write:	0238BCE8
Eeprom page prog:	0238BCFC
Eeprom verify:	0238BD10
Eeprom page erase:	0238BD20
swi12 location : 0238C11C

swiGetPitchTable location : 02387678

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 02390CAC

ERR_NONE
hookLocation arm9: 027E0000

AP-fix applied
chipID: 80007FC2

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Does the untranslated ROM have the same issue?

**Comment by tomudo** [comment]
The original untranslated ROM is not crash.

**Comment by tomudo** [comment]
Saga 2 translated V2.12  is crash but Saga 2 translated V2.11 is ok.

**Comment by Kenshokram** [comment]
> Saga 2 translated V2.12 is crash but Saga 2 translated V2.11 is ok. Thanks RocketRobz for looking into.

Hi! Sorry for another issue post, but I couldn't find a way to message this user. I haven't been able to find a working copy of english patched 2.11 Saga 2, and I fear that this game's english translation is gonna just become unplayable with the passage of time, do you have a working patch of that version uploaded somewhere?

If nothing else, is there any other way to make the modern available translation patch (2.12) work on bootstrap? (It still crashed due to AP after the dad jumps out the window)

**Comment by RocketRobz** [comment]
You need to use the specific xdelta patch from this page here: https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v27.10.0
If the issue persists, then you might be out of luck.

**Comment by Kenshokram** [comment]
> You need to use the specific xdelta patch from this page here: https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v27.10.0 If you are not using that specific TWLMenu++ version, please update.
> 
> If the issue persists, then you might be out of luck.

Omg it works!!!! You're a legend!!!!!!

You put this out yesterday???? Wtf What are the odds? lol

Thank you so much!

**Comment by Falkenmond79** [comment]
Weird. I just a few days ago found out that SaGa 2 is the old Final Fantasy Legends 2 I loved so much on my Gameboy. Got it for my DS. Wanted the english translation Rom for my 3DS. Found it. Was massively dissapointed to see it not working. What are the odds it was fixed the same week?

Got TinkeDSi, opened the ROM, saved it again, put it on the 3DS with updated TWM++ and voila, works like a charm. You´re the Bomb, Robz!
