### ISSUE TITLE
Cheat option does not appear when using the Kernel firmware option

### ISSUE THREAD

**Issue by tofugal** [DS-Homebrew/nds-bootstrap#1694]
As the title entails i cannot use cheats for the kernel firmware option 
in twilight menu, the flashcart i'm using is an acekard2i if that helps.

**Comment by RocketRobz** [comment]
Known issue, as it's already stated in the flashcard install page.

**Comment by real-F-00** [comment]
> As the title entails i cannot use cheats for the kernel firmware option in twilight menu, the flashcart i'm using is an acekard2i if that helps.

one thing you can do is going in the kernel's menu and enable cheat codes there, then launch through TWiLightMenu++
although it's very inconvenient that's one way to do it.

**Comment by RocketRobz** [comment]
Closing, as this is not an nds-bootstrap issue.
