### ISSUE TITLE
Pokemon HG and SS Error Data Abort

### ISSUE THREAD

**Issue by Veund** [DS-Homebrew/nds-bootstrap#1696]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [x ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Via SD Card

### Version used

release 0.65.0 through to 1.5.0

### Game tested/used/applicable

Gen 4 pokemon heart gold and soul silver, all other gen 4 and 5 pokemon games work fine 

### Expected Behavior

game launches to title screen

### Actual Behavior

game crashes as bootstrap loads 

### Steps to reproduce

launch clean dump of pokemon heart gold or soul silver from sd card 

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
BOOST_CPU = 0
NDS_PATH = sd:/roms/nds/Pokemon - SoulSilver Version (USA).nds
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
BOOTSTRAP_PATH = sd:/_nds/unofficial-bootstrap.nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - SoulSilver Version (USA).sav
LOCK_ARM9_SCFG_EXT = 0
DONOR_SDK_VER = 0
CHECK_COMPATIBILITY = 1
USE_ARM7_DONOR = 1
LOGGING = 0
ROMREAD_LED = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_VRAM = 1
GAME_SOFT_RESET = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
SWI_HALT_HOOK = 1
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = 3
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
B4DS_MODE = 0
USE_ROM_REGION = 1
SLEEP_MODE = 1

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02000BBC
sdk_version: 04027533
arm9 is compressed
Secure area already decrypted
Switched to NTR mode BIOS
AP-fix found
patchCardNds

cardIrqEnable location : 020D11D4

startOffset : 02000000

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020D3190

Mpu data alt: 020D2ABC

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 020D3198

waitCpuCycles location : 020D3AA8

cardRead location : 020DD570
027D8000

swi12 location : 02000358

cardPullOut location : 020DDAD0

cardId location : 020DD660

cardReadDma location : 020DD3E4

reset location : 020D3B84

ERR_NONE

Sleep location : 0238A314

cardIrqEnable location : 02380B80

forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 0238026C
Relocation dst: 037F8000
RAM mirror check location : 0238015C

Arm7 (patch vAll)

JumpTableFunc: 02388730
Eeprom read:	0238873C
Eeprom page write:	02388750
Eeprom page prog:	02388764
Eeprom verify:	02388778
Eeprom page erase:	02388788
swi12 location : 02388B70

swiGetPitchTable location : 02383FCC

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 0238ECF4

ERR_NONE
hookLocation arm9: 027E0000

AP-fix applied
Overlays cached to a file
chipID: E0017FC2

### Other notes

this is 100% clean rom dump from my physical cart i made using godmode9.

I actually reverted each version of nds bootstrap because I know this worked on a earlier version of twilight menu and found that it works in 0.64.1 but has the same issue in 0.65.0.

for anyone who is having the same issue what i did for a temp fix was download 0.64.1 and rename then to 

nds-bootstrap-hb-release.nds to nds-bootstrap-nightly.nds
nds-bootstrap-release.nds to nds-bootstrap-hb-nightly.nds
release-bootstrap.ver to nightly-bootstrap.ver

then pressed Y on soul silver and heart gold in twilight menu scrolled down to Bootstrap and selected nightly, this way everything runs in 1.5.0 except HG and SS that run on 0.64.1

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
Which method did you use to install TWiLight Menu++? Universal-Updater or Manual?

**Comment by Veund** [comment]
universal updater

**Comment by RocketRobz** [comment]
> universal updater originally
>
> now i have manually reinstalled it when i changed 0.64.1 to nightly

Have you followed these guides?
- https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds
- https://wiki.ds-homebrew.com/twilightmenu/installing-3ds?tab=manual

If so, then install/update to the latest nds-bootstrap version manually by following the steps in this page: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v1.5.0

**Comment by Veund** [comment]
I am following those instructions now

**Comment by Veund** [comment]
ok i did all that same issue but what i did notice on fbi i have various twilight menu titles 

twilight menu ++
twilight menu ++ last run rom
twloader twlnand side
twloader twlnande side part 2

**Comment by RocketRobz** [comment]
Ok, I was able to reproduce the issue. For the console which has the data abort error, what's the file size of `sd:/_nds/nds-bootstrap/apFixOverlays.bin`?

**Comment by Veund** [comment]
it is 0 bytes

**Comment by RocketRobz** [comment]
> it is 0 bytes

Ensure there's 8MB or more of free space on the SD card, then update nds-bootstrap to latest nightly.

**Comment by Veund** [comment]
ok did that and it works correctly
