### ISSUE TITLE
Mario & Luigi Partners in Time crashes with "RED screen" after creating a save slot

### ISSUE THREAD

**Issue by lesar8** [DS-Homebrew/nds-bootstrap#1698]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

1.5.0

### Game tested/used/applicable

Mario & Luigi Partners in Time "European" release, the Crc32 is 3184FBC4

### Expected Behavior

Game works without RED screen

### Actual Behavior

After creating a save state for the first time, the game fall into "red screen of death"

### Steps to reproduce

Launch clean dump of Mario & Luigi Partners in Time "European" release from sd card, create the save state for the first time to trigger the bug

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
BOOST_CPU = 0
NDS_PATH = sd:/roms/nds/Mario & Luigi Partners in Time (EU).nds
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
BOOTSTRAP_PATH = sd:/_nds/unofficial-bootstrap.nds
SAV_PATH = sd:/roms/nds/saves/Mario & Luigi Partners in Time (EU).sav
LOCK_ARM9_SCFG_EXT = 0
DONOR_SDK_VER = 0
CHECK_COMPATIBILITY = 1
USE_ARM7_DONOR = 1
LOGGING = 0
ROMREAD_LED = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = 1
DSI_MODE = 0
BOOST_VRAM = 1
GAME_SOFT_RESET = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
PRECISE_VOLUME_CONTROL = 1
COLOR_MODE = 0
SOUND_FREQ = 1
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
SWI_HALT_HOOK = 1
SDNAND = 0
MACRO_MODE = 0
HOTKEY = 284
GUI_LANGUAGE = en
REGION = 3
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
B4DS_MODE = 0
USE_ROM_REGION = 1
SLEEP_MODE = 1

### Logs

None

### Other notes

None

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Cannot reproduce this on my side. Your ROM might be corrupted.
