### ISSUE TITLE
Super Princess Peach doesn't start

### ISSUE THREAD

**Issue by massmagic85** [DS-Homebrew/nds-bootstrap#1699]
### Game Console(s) used

- [ ] Nintendo DS
- [X] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Flashcard R4iSDHC Gold

### Version used

release stable 1.5.1

### Game tested/used/applicable

DS Game - Super Princess Peach

### Expected Behavior

Start and play the game without any problem

### Actual Behavior

The game doesn't start.. when you try to start it for the first time it will hang to "NDS-BOOTSTRAP Please wait".. I waited more then 15 minutes.. still on the same screen

### Steps to reproduce

Just load the game using nds-bootstrap

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
NDS_PATH = fat:/Games/0444 - Super Princess Peach (Europe) (En,Fr,De,Es,It).nds
SAV_PATH = fat:/Games/saves/0444 - Super Princess Peach (Europe) (En,Fr,De,Es,It).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 2
DSI_MODE = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 1
DEBUG = 0
LOGGING = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
```

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/15241480/NDSBTSRP.LOG)

### Other notes

If I try to start the game using YSmenu, it works great.
I have tried the same game with an old version of nds-bootstrap (1.4.1) on a DS Lite.
The game is starting (it is very slow on loading) but it crashes after you try to play the first level of the game

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
Does the issue persist in v1.6.2? If so, there might be an issue with the microSD card.

**Comment by RocketRobz** [comment]
Boots fine for me.

**Comment by massmagic85** [comment]
Hi, sorry for late answer but I was in vacation..
I have tested it with nds-bootstrap 1.6.2, TWiLightMenuv27.7.0 and a different sdcard and I'm sorry it's not working.. 
the issue is the same.. still on the same screen "NDS-BOOTSTRAP please wait"
I forgot to tell you that the rom that has the "problem" is EU.. the US version is ok and it's loading without any issue.

Thank you

**Comment by massmagic85** [comment]
I have tried the same eu rom on a modded New 3DSXL with nds-bootstrap 1.6.2, TWiLightMenu v27.7.1 and It's working..
The issue is present on the flashcard version
