### ISSUE TITLE
Chibi-Robo! - Clean Sweep not loading with Circle Pad cheat enabled

### ISSUE THREAD

**Issue by Glacier214** [DS-Homebrew/nds-bootstrap#1704]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card

### Version used

Release v27.2.2

### Game tested/used/applicable

Chibi-Robo!- Clean Sweep(English patch)

### Expected Behavior

Expected games to run with circle pad support via cheats.

### Actual Behavior

The games do not load with the circle pad cheats enables, I get stuck on a white screen.

### Steps to reproduce

 Try running the games with the circle pad cheats. 

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Okaeri! Chibi-Robo! - Happy Rich Oosouji! (Japan)_apfix.nds
SAV_PATH = sd:/roms/nds/saves/Okaeri! Chibi-Robo! - Happy Rich Oosouji! (Japan)_apfix.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
AP_FIX_PATH =
```

### Logs

I Did this and logs are not appearing in the SD card

### Other notes

I cannot share the patched rom I used because 1. distributing it is illegal 2. file size is too big

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
You need to launch TWPatch and then press the START button for DS(i) mode to access 3DS controls.

**Comment by RocketRobz** [comment]
Closing due to lack of response, so I'll assume this is fixed.
