### ISSUE TITLE
BW2 Will not load save file nor will it create a new one.

### ISSUE THREAD

**Issue by kingreboot** [DS-Homebrew/nds-bootstrap#1705]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [X] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD

### Version used

 v1.5.2

### Game tested/used/applicable

Pokémon Black 2. Other Pokémon Titles fine. White 2 works fine.  

### Expected Behavior

The game should read my save file that is located in the correct folder as that is where my other save files are and I have moved them around with no issues in the past.

### Actual Behavior

Been using and playing the game for a while now. The recent change was Using PKSM to apply a Poke-transporter redirect script. I have undone this to the best that I know. I have Removed the rom and readded it (completely new rom file). I have removed the save file and I tried using a old save file and neither worked. 

### Steps to reproduce

Only thing I did differently was use the Poke-transporter redirect script from PKSM

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Pokemon - Black Version 2.nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - Black Version 2.sav
BOOST_CPU = 1
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 1
CARD_READ_DMA = -1
ASYNC_CARD_READ = -1
DSI_MODE = 1
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 2
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips

### Logs

I am lost on this one. When I open the nds-bootstrap.ini file I saw no logging line.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Have you tried saving within the new game?

**Comment by kingreboot** [comment]
I assume you mean start a new game and hit save. I have done this, I first removed the current save and backed it up. I booted the game up with no save files and tried to save. Once I did this I reloaded the game to see if it saved. It did not show a save file, but it did create a save file in the saves folder.

**Comment by RocketRobz** [comment]
There might be an issue with how the SD card is formatted. Otherwise, idk why this happens.
Try reformatting the SD card: https://dsi.cfw.guide/sd-card-setup.html

**Comment by kingreboot** [comment]
if its a formatting issue, then should other games have similar issues. also it was working fine just a new days ago.

**Comment by RocketRobz** [comment]
> if its a formatting issue, then should other games have similar issues? I White 2 (basically the same game) works fine. Black 2 was working fine until a few days ago.

Did you add, install, and/or change anything on the SD card during that time period?

**Comment by kingreboot** [comment]
I ran a script in PKSM that adds a title file in my Luma folder. But I reversed it by removing the file as the PKSM github page said that was the only new file added when added. Also PKSM usually requires me to save any changes I do to a save file before leaving, but as it does not prompt me to save, I made the assumption the rom nor the save was modified. I also tested it by removing the save and also reinstalling a new rom

**Comment by kingreboot** [comment]
is there a chance I might have a broken Rom?

**Comment by RocketRobz** [comment]
> is there a chance I might have a broken Rom?

Considering it was working fine a few days ago, I kinda doubt it's the ROM. You could try re-adding the ROM to see if it fixes the issue though.

> if its a formatting issue, then should other games have similar issues?

Formatting issues can cause some random issues, from one game not saving to many games not saving and/or not booting.

**Comment by kingreboot** [comment]
I get the formatting issue, but the format of the card has not changed in the last few days

**Comment by kingreboot** [comment]
ok, so it might have been a rom issue. I found a different one, I loaded it and it said it can't run it in dsi mode so it will run in ds mode, but it reading my save file

**Comment by kingreboot** [comment]
Funny, I actually found a forum where you mentioned the DSI binary issue for BW2

**Comment by kingreboot** [comment]
Ok, fixed my issue. I have a proper rom.
