### ISSUE TITLE
nsmbe gives me an error message

### ISSUE THREAD

**Issue by SonicfanDani2013** [DS-Homebrew/nds-bootstrap#1706]
### Game Console(s) used

- [ ] Nintendo DS
- [x] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [X] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [x] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

I launched it via an sd card(twilight menu ++).

### Version used

-

### Game tested/used/applicable

https://nsmbhd.net/download/

### Expected Behavior

-

### Actual Behavior

It gave me an error code guru meditation error data abort (i deleted settings.ini).

### Steps to reproduce

-

### nds-bootstrap.ini

-

### Logs

-

### Other notes

-

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
What you're trying to launch is a PC application?
