### ISSUE TITLE
start failed error 1 (using forwarder)

### ISSUE THREAD

**Issue by morcik12** [DS-Homebrew/nds-bootstrap#1710]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD

### Version used

latest

### Game tested/used/applicable

pokemon platinum

### Expected Behavior

the game should open normally i have the file downloaded (the file that the error says i am missing)

### Actual Behavior

The error 1 pops up on my screen, I am using forwarder on my dsi with hiya cfw

### Steps to reproduce

.

### nds-bootstrap.ini

.

### Logs

.

### Other notes

please quick response :(

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
This is an issue with the forwarder process, not nds-bootstrap.
Please join our Discord server for assistance: https://discord.gg/yD3spjv
