### ISSUE TITLE
Kingdom Hearts 358/2 Days Multiplayer Communication Error

### ISSUE THREAD

**Issue by Repcuh** [DS-Homebrew/nds-bootstrap#1712]
Hello and good day! My wife and I have been trying to play Kingdom Hearts 358/2 together on our 3DS. We are both using Twilight Menu  V27.5.0 with nds bootstrap V1.5.2 and we keep encountering Communication Errors. Every time we keep retrying, it happens a little later into the session. Ex: First time it happens right after we connect in a group together, Second time happens right before we load into a mission, third time happens somewhere in the middle of the mission and thats as far as it goes. We have tried setting card read DMA to off, starting in ds mode and setting speed to NTR but the issue still persists. Is there perhaps a fix i have missed? Thank you so much!

**Comment by RocketRobz** [comment]
Try setting speed to TWL instead.

**Comment by Repcuh** [comment]
Wow! Thanks for the speedy reply, hope you are having a good one! We tried setting the speed to TWL and tried a few times but still encountered the communication errors unfortunately.

**Comment by S3542U** [comment]
I have the same issue, but with FFCC: Rings of Fate.

We are able to play a little bit, but we get the communication error pretty randomly. Sometimes we can play for a few hours with no issue and sometimes we get the error after only 5 mins into the game.

Would using flashcards instead offer a more stable connection?

I'm going to try it and report later.

**Comment by RocketRobz** [comment]
With the recent fixes made to WiFi stability, it is safe to assume this is fixed.
