### ISSUE TITLE
Petit Computer crashes with data abort

### ISSUE THREAD

**Issue by joemck** [DS-Homebrew/nds-bootstrap#1715]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [x] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

System firmware 1.4.4U. SD card, loaded through Unlaunch 2.0 => TWiLightMenu++ 27.5.1 w/ r4menu theme => nds-bootstrap. SCFG unlocked.

### Version used

Release 1.5.3

### Game tested/used/applicable

Petit Computer DSiWare (KNAE), US release, MD5 of ROM: F0A86B004B2221DE0C320E722D867D09

### Expected Behavior

It should boot normally after a few seconds of white screen.

### Actual Behavior

Few seconds of white screens, then it crashes with a data abort error before displaying any logos. When I switch to nightly 6553be7, it works correctly. It was working with an old version from 2023 before I updated, but I don't remember what version number.

### Steps to reproduce

US console, US ROM, all default per-game settings (except switching nds-bootstrap between release and nightly) and default nds-bootstrap options. I had already created some programs in Petit Computer so I switched it to a new save slot and it still crashes the same way.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b45/content/00000002.app
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/dsiware/Petit Computer.nds
SAV_PATH = sd:/ROMS/DSIWARE/SAVES/PETITC~1.PU1
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = 1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 1
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 5
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
APP_PATH = sd:/ROMS/DSIWARE/PETITC~1.NDS
PRV_PATH = sd:/ROMS/DSIWARE/SAVES/  
GAME_SOFT_RESET = 1

```

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/16008260/NDSBTSRP.LOG)

### Other notes

It behaves the same whether I have nothing or a retail Pokemon Pearl cartridge in slot 1.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Try downgrading nds-bootstrap to v1.5.2.

**Comment by joemck** [comment]
I went back a few and then started skipping back and did a binary search once I found one that works.
1.5.2 crashes.
1.5.1 crashes.
1.5.0 crashes.
1.4.3 crashes.
1.3.2 crashes.
0.73.1 crashes.
**0.71.0 crashes.**
**0.70.0 works.**
0.68.0 works.

Unrelated: Why do all the zip downloads contain a copy of the 7z download?

**Comment by RocketRobz** [comment]
> Unrelated: Why do all the zip downloads contain a copy of the 7z download?

zip downloads of what?

**Comment by RocketRobz** [comment]
In the nds-bootstrap page of TWLMenu++ Settings, what is the SDNAND/Photo location setting set to?

**Comment by joemck** [comment]
Photo location is NAND.

I mean the zips on the releases page for nds-bootstrap. There is a 7z file which contains the 2 nds files and the ver file. Then there is a zip that contains those files plus a copy of the 7z file, which contains the same files too.

**Comment by RocketRobz** [comment]
> I mean the zips on the releases page for nds-bootstrap. There is a 7z file which contains the 2 nds files and the ver file. Then there is a zip that contains those files plus a copy of the 7z file, which contains the same files too.

Huh, I was not aware the zip file contained a copy of the 7z file.

**Comment by joemck** [comment]
BTW I have changed the photo location to the SD card and 1.5.3 still crashes and 6553be7 still works.

**Comment by RocketRobz** [comment]
I cannot reproduce this issue on my side. Which SD capacity size are you using? Mine is 32GB.

**Comment by joemck** [comment]
16 GB. It's an old Sandisk class 2 card.

**Comment by RocketRobz** [comment]
> 16 GB. It's an old Sandisk class 2 card.

Is it formatted as FAT(16) or FAT32?

**Comment by joemck** [comment]
It's FAT32.

Additional testing: I copied everything off the SD card, formatted it with SDFormatter, and copied freshly downloaded TWiLight Menu++ files and a fresh copy of "0221 - Petit Computer (USA).nds" downloaded from the Internet Archive. It still crashes.
