### ISSUE TITLE
Getting a data abort on Pokemon Black and White

### ISSUE THREAD

**Issue by trutown693** [DS-Homebrew/nds-bootstrap#1716]
Issue occurs when I try to use the auto run cheat code with both games. And when the cheat is not enabled the games are super slow and eventually freeze. 

Base Console: DSi XL

TWiLight Menu++ Version: 27.5.1
nds-bootstrap: Release v1.5.3
TWiLight Menu++ Theme: Nintendo DSi 
### Expected behavior

Game should start and play normally after pressing continue at the main menu.

### Actual behavior

When continue is pressed, the game suffers from an Error: Data Abort and shows this image:
![screenshot01](https://github.com/DS-Homebrew/TWiLightMenu/assets/174809121/52bc8e44-0f59-4dac-b0e9-5c29465d02f6)

### Steps to reproduce

1. Apply the Auto Run (or toggle B to run) action replay code
2. boot the game and get to the main menu with Continue, New Game, etc.
3. press continue
4. error appears.

This wasn't an issue until last week when I updated. And even without the cheat code active, the games suffer from a great deal of slowdown and eventually freeze after a few minutes. I found that the best way to get around this was to put a rom without the DSi binaries on my SD card. So maybe the DSi enhancemnts are the problem?

**Comment by RocketRobz** [comment]
The slowdown is due to C-Gear being turned on. Also, certain cheats do not work in DSi mode, so that's probably the cause of the error.

**Comment by trutown693** [comment]
The error occurs even when the C-gear is turned off. I got this error after telling the game not to turn on the C-Gear. And slowdown occurs regardless.

**Comment by RocketRobz** [comment]
> The error occurs even when the C-gear is turned off. I got this error after telling the game not to turn on the C-Gear. And slowdown occurs regardless.

Try re-installing TWiLight Menu++ then:
https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

If the slowdown persists, follow this SD setup guide: https://dsi.cfw.guide/sd-card-setup.html
