### ISSUE TITLE
Cooking mama sound nouse

### ISSUE THREAD

**Issue by bboygolem** [DS-Homebrew/nds-bootstrap#1722]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Twilight menu on SD card using memorypit

### Version used

TWiLight Menu++: v27.5.2
nds-bootstrap: Release v1.5.4

### Game tested/used/applicable

cooking mama 2 (eu / USA)

### Expected Behavior

game runs flawlessly as usinf r4

### Actual Behavior

as soon as you start the game you hear some static noise that impacts gameplay

### Steps to reproduce

start the game

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DONORTWLONLY0_NDS_PATH = nand:/title/00030005/484e4b50/content/00000002.app
USE_ROM_REGION = 1
NDS_PATH = sd:/Giochi/Cooking Mama 2 - Dinner with Friends (Europe) (En,Fr,De,Es,It).nds
SAV_PATH = sd:/Giochi/saves/Cooking Mama 2 - Dinner with Friends (Europe) (En,Fr,De,Es,It).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = it
LANGUAGE = -1
REGION = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
```

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02000BBC
sdk_version: 04017531
arm9 is not compressed
Secure area already decrypted
patchCardNds

cardIrqEnable location : 020442AC

startOffset : 02000000

Mpu start: 02000ADC

Mpu data: 02000B70

Mpu init: 020459F8

Mpu data alt: 02045760

Mpu start 2: 02000AE4

Mpu data 2: 02000B74

Mpu init 2: 02045A00

waitCpuCycles location : 02045DE4

cardRead location : 0204C8AC
027D8000

swi12 location : 020000D8

cardPullOut location : 0204CE08

cardId location : 0204C99C

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 0204C5FC

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 0204C698

ERR_NONE

Sleep location : 0238E524

cardIrqEnable location : 02383B0C

forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000
RAM mirror check location : 0238018C

Arm7 (patch vAll)

JumpTableFunc: 0238BBA8
Eeprom read:	0238BBB4
Eeprom page write:	0238BBCC
Eeprom page prog:	0238BBE4
Eeprom verify:	0238BBFC
Eeprom page erase:	0238BC10
swi12 location : 0238BF94

swiGetPitchTable location : 00000000

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 02390944

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80003FC2

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
Try turning off card read DMA in the per-game settings menu (opened by pressing Y button in TWLMenu++),

**Comment by bboygolem** [comment]
thanks but unfortunatly nothing changes, noise still present

Il giorno gio 25 lug 2024 alle ore 20:00 RocketRobz <
***@***.***> ha scritto:
