### ISSUE TITLE
Cut The rope (DSi) got a black screen

### ISSUE THREAD

**Issue by MrErik6000** [DS-Homebrew/nds-bootstrap#1726]
The Game works, but the problem is the black screen when the rom starts, it's just a black screen, but you can interact with the game, the sound works and the cinematic doesn't show any problem.

**Comment by RocketRobz** [comment]
You have not filled out the issue template. Please recreate your issue here: https://github.com/DS-Homebrew/nds-bootstrap/issues/new?assignees=&labels=&projects=&template=bug_report.yml
