### ISSUE TITLE
Dr.Mario Express Doesn't Boot

### ISSUE THREAD

**Issue by Luczin-a** [DS-Homebrew/nds-bootstrap#1731]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card Twilight Menu 20.4.1

### Version used

i used release

### Game tested/used/applicable

Dr.Mario Express

### Expected Behavior

The Game Boots

### Actual Behavior

White Screen

### Steps to reproduce

-Play The Game
-Sd Card
-Twilght Menu 20.4.1

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
NDS_PATH = sd:/Dr. Mario Express (USA) (Rev 1).nds
SAV_PATH = sd:/saves/Dr. Mario Express (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
APP_PATH = sd:/FLIPNO~2.NDS
PRV_PATH = sd:/
GAME_SOFT_RESET = 1

### Logs

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
NDS_PATH = sd:/Dr. Mario Express (USA) (Rev 1).nds
SAV_PATH = sd:/saves/Dr. Mario Express (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
APP_PATH = sd:/FLIPNO~2.NDS
PRV_PATH = sd:/
GAME_SOFT_RESET = 1

### Will you be available for future issues and/or replies?

yes

**Comment by Luczin-a** [comment]
The White Screen: https://drive.google.com/file/d/1bEvtqCtV0KalbLSpaapiwpxPRn2ovKRl/view?usp=drive_link

**Comment by RocketRobz** [comment]
The game boots fine for me. Please update TWiLight Menu++ & nds-bootstrap.

**Comment by Luczin-a** [comment]
> The game boots fine for me. Please update TWiLight Menu++ & nds-bootstrap.

How do I update?

**Comment by RocketRobz** [comment]
> How do I update?

See this page: https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

**Comment by Luczin-a** [comment]
still white screen

**Comment by RocketRobz** [comment]
> still white screen

Which region is your ROM and console then?

**Comment by Luczin-a** [comment]
my rom is rev1 and my console is usa region

**Comment by RocketRobz** [comment]
> my rom is rev1 and my console is usa region

I asked for the ROM region, not the revision.

**Comment by Luczin-a** [comment]
ah is usa

**Comment by RocketRobz** [comment]
> ah is usa

How long was the white screen shown for?

**Comment by Luczin-a** [comment]
It stays for an infinite amount of time, otherwise it crashes

**Comment by Luczin-a** [comment]
and not turn off

**Comment by RocketRobz** [comment]
> It stays for an infinite amount of time, otherwise it crashes

Does this mean it's been shown longer than 1 minute? If so, try reformatting the SD card here: https://dsi.cfw.guide/sd-card-setup.html

**Comment by Luczin-a** [comment]
still dont work there is anything wrong with my rom? check here: https://drive.google.com/file/d/1rS3ZNfG_7hU_JtTr3npwRlY8D4c0jtgv/view?usp=sharing

**Comment by RocketRobz** [comment]
> still dont work there is anything wrong with my rom?

Please don't post links to ROMs. Also, did you use both SDFormatter and h2testw from the SD setup guide?

**Comment by Luczin-a** [comment]
yes and ok i do not post

**Comment by RocketRobz** [comment]
> yes and ok i do not post

Please post a picture of the SD card you're using.

**Comment by Luczin-a** [comment]
![sduuu](https://github.com/user-attachments/assets/882b8c6d-b57f-45d8-bade-355477bbf6dc)

**Comment by RocketRobz** [comment]
Did h2testw report any errors on your SD card?

**Comment by Luczin-a** [comment]
no

**Comment by RocketRobz** [comment]
> no

Does the same white screen issue happen with other DSiWare ROMs?

**Comment by Luczin-a** [comment]
let me test

**Comment by Luczin-a** [comment]
no it works fine i tested 1001 blockbusters and shantae

**Comment by RocketRobz** [comment]
> no it works fine i tested 1001 blockbusters and shantae

Is Unlaunch installed?

**Comment by Luczin-a** [comment]
yes

**Comment by RocketRobz** [comment]
> yes

Hmm, then try setting the `DSiWare Booter` setting to `Unlaunch` in the per-game settings menu of TWLMenu++ (opened by pressing `Y` button).

**Comment by Luczin-a** [comment]
it opens for 1 second and then the white screen goes back

**Comment by RocketRobz** [comment]
> it opens for 1 second and then the white screen goes back

That would imply that the ROM is corrupted then. If you're sure the ROM isn't corrupted though, please revert the `DSiWare Booter` setting, and try a different SD card.

**Comment by Luczin-a** [comment]
Do you have a tip on where to find the ROM?

**Comment by RocketRobz** [comment]
> Do you have a tip on where to find the ROM?

Before trying a different ROM, please try re-adding the ROM onto the SD card.
If the issue persists, then try a different SD card.

**Comment by Luczin-a** [comment]
now it works! Thanks!
