### ISSUE TITLE
1.6.2 crashing and giving a data error

### ISSUE THREAD

**Issue by MintJuulPods** [DS-Homebrew/nds-bootstrap#1732]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launched via SD card through Twilight menu.

### Version used

1.6.2 release and nightly.

### Game tested/used/applicable

Dragon quest IX 

### Expected Behavior

Game usually boots without problems.

### Actual Behavior

Screen turned red and read a data error code.

### Steps to reproduce

Simply launch the game and it will happen. Tested on two different systems running different rooms of DQIX

### nds-bootstrap.ini

Not currently accessible because my laptop is not with me.

### Logs

Not accessible 

### Other notes

This problem was happening on the previous version, but only infrequently and completely random. With 1.6.2, it happens every time I start the game.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Are cheats turned on?

**Comment by MintJuulPods** [comment]
There was only one cheat turned on. The WFC Replay Bypass Code was causing the error. This is unfortunate because this cheat is essential for the enjoyment of the game.
