### ISSUE TITLE
How I Play WarioWare: Snapped! ?

### ISSUE THREAD

**Issue by Luczin-a** [DS-Homebrew/nds-bootstrap#1736]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [X] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD ANd Its The Latest Version 

### Version used

its realease

### Game tested/used/applicable

WarioWare: Snapped!

### Expected Behavior

play the game

### Actual Behavior

not .nds

### Steps to reproduce

-DS
-Rom

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
NDS_PATH = sd:/Dr. Mario Express (USA) (Rev 1).nds
SAV_PATH = sd:/saves/Dr. Mario Express (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
APP_PATH = sd:/FLIPNO~2.NDS
PRV_PATH = sd:/
GAME_SOFT_RESET = 1

### Logs

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
NDS_PATH = sd:/Dr. Mario Express (USA) (Rev 1).nds
SAV_PATH = sd:/saves/Dr. Mario Express (USA) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
APP_PATH = sd:/FLIPNO~2.NDS
PRV_PATH = sd:/
GAME_SOFT_RESET = 1

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
You just launch the game. If you do not have the `.nds` file for it, then dump it using GodMode9 or GodMode9**i**.

**Comment by Luczin-a** [comment]
and only i have is 
![image](https://github.com/user-attachments/assets/97adb6e6-c3b5-41ea-9980-5d33933c9a1c)

**Comment by RocketRobz** [comment]
Your dump is encrypted, which will not work. Dump the ROM from either a DSi or 3DS console which has the game using either GodMode9 or GodMode9**i**.
