### ISSUE TITLE
DS Lite Restart on Wii Connectivity

### ISSUE THREAD

**Issue by clayavery** [DS-Homebrew/nds-bootstrap#1737]
### Game Console(s) used

- [ ] Nintendo DS
- [X] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Twilight Menu ++ Flashcard

### Version used

Release

### Game tested/used/applicable

Pokemon Platinum & Diamond

### Expected Behavior

On my 3DS, testing the same process, Wii connectivity did not cause the system to power off. 

### Actual Behavior

On yhe DS Lite, It was powered off at each step of the Wii connectivity process. It did, however, make it to the screen where “Data could not be read” with PBR logo. It also responded to MPR. So the data issue persists on both systems, as well.

### Steps to reproduce

Load a DS Pokemon game from TwilightMenu ++ flashcard version on a DS Lite and proceed to connect your save game to PBR or MPR. The DS Lite will power off, you must power it back on, and it may do so once or twice more, but keeping turning it back on going back into the Twilight Menu and it will reload the Wii Connectivity immediately.

### nds-bootstrap.ini

N/A

### Logs

N/A

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
This happens because the patching code is not in memory while the game is running from flashcard (and there's no memory space to place the patching code), while on DSi/3DS, there is extra memory to place patching code, avoiding the need to reboot the console.

**Comment by clayavery** [comment]
Is there a way to remedy that?

**Comment by RocketRobz** [comment]
> Is there a way to remedy that? Thanks for the quick reply!

It may be possible for nds-bootstrap to reload the bootloader into VRAM. The bootloader is where the patching is done before the game boots.

**Comment by clayavery** [comment]
If I can be of any help, I’d be more than happy. I’d love to see the Wii Connectivity finally work!

**Comment by clayavery** [comment]
One of the recent updates has fixed the restarting issue on the DS Lite. Thanks! Hopefully we’ll see the connectivity go through and function!
