### ISSUE TITLE
Scooby Doo and the Spooky Swamp: I can't unlock the three remaining clothing items.

### ISSUE THREAD

**Issue by Jocathso10** [DS-Homebrew/nds-bootstrap#1740]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [X] New Nintendo 2DS XL/LL

### Launch Method

Sd card, SCFG Disabled, Twilight Menu v27.10.0 latest version.

### Version used

Nds-bootstrap Release version v2.0.2 latest version.

### Game tested/used/applicable

Scooby Doo and the Spooky Swamp (USA). NTR-BJ2E-USA.

### Expected Behavior

Normally in the other console versions, to unlock the three clothes I'm missing, I have to talk to a frog using different characters.

### Actual Behavior

In this version the frog doesn't appear, I don't know if the game developers removed it, replace it with other mechanics, or it's a bug, I even did everything to see how the suits were unlocked, but it was of no use. (I don´t know if nds-bootstrap has anything to do with this).

### Steps to reproduce

1. Enter the game.
2. Choose the first save file.
3. In The Swamp, select any characters and explore all the parts in the level, but the frog doesn't appear.
4. In The Muncho, select Shaggy and another character and explore all the parts in the level, but the frog doesn't appear.
5. In Howling Peaks, select Scooby and another character and explore all the parts in the level, but the frog doesn't appear.
[Scooby-Doo! and the Spooky Swamp (USA) (En,Fr,Es).zip](https://github.com/user-attachments/files/17285671/Scooby-Doo.and.the.Spooky.Swamp.USA.En.Fr.Es.zip)

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Scooby-Doo! and the Spooky Swamp (USA) (En,Fr,Es).nds
SAV_PATH = sd:/roms/nds/saves/Scooby-Doo! and the Spooky Swamp (USA) (En,Fr,Es).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = es
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[log.txt](https://github.com/user-attachments/files/17285687/log.txt)

### Other notes

The truth is that I have already finished the game, but as I said I still have to unlock the three clothing items and the frog doesn't appear, the truth is I don't know if it's a bug of this homebrew application or it also happens in the original physical cartridge, I hope you help me. Cheers. I'm using a translator, my native language is spanish.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Please test if the same bug happens on either the original cartridge, or an emulator such as melonDS, NO$GBA, or DeSmuME. If the same bug happens in the cartridge or those emulators, then it is not an nds-bootstrap issue.

**Comment by RocketRobz** [comment]
Closing due to lack of response.
