### ISSUE TITLE
Fatal Error on Wario Ware Touched in Toys on game Snore Rope

### ISSUE THREAD

**Issue by TRD2B** [DS-Homebrew/nds-bootstrap#1741]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [X] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Launch with Twilight Menu ++ v27.10.0 with nds-bootstrap v2.0.2 on SD Card (no linker)

![20241010_110951](https://github.com/user-attachments/assets/11700447-3014-40d3-bae6-ad370bee3069)
![20241010_111054](https://github.com/user-attachments/assets/0f004cab-db92-464f-86e3-7b25fcc4916c)
![20241010_111111](https://github.com/user-attachments/assets/0f55101a-45df-401b-847a-d4f3bc06a5fd)
![20241010_111136](https://github.com/user-attachments/assets/63ab3ffe-96be-4288-af59-e7671a7ae362)

### Version used

Twilight Menu ++ v27.10.0 with nds-bootstrap v2.0.2 release

### Game tested/used/applicable

MD5
0459c65aec45bb43d8e8b7c5372db4a8

SHA1
c021d77090ebbd882805bf519bbf4f7fd1934d41

ID
7197

Title ID
000480045A324154

### Expected Behavior

Launch Wario Ware Touched in "Toys" on game "Snore Rope" and play

### Actual Behavior

Fatal Error in Wario Ware Touched in "Toys" on game "Snore Rope", the rest of the game work well

### Steps to reproduce

Launch Wario Ware Touched, go to "Toys" and launch "Snope Rope"

![20241010_111111](https://github.com/user-attachments/assets/9e9ba2a8-78e8-4439-9707-7f8d32f638d4)
![20241010_111136](https://github.com/user-attachments/assets/f2f5a374-4378-4324-a9bd-4a5192f8ef83)

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 1
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 1
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/WarioWare - Touched! (E).nds
SAV_PATH = sd:/roms/nds/saves/WarioWare - Touched! (E).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = fr
LANGUAGE = 2
REGION = -1
DSI_MODE = 1
CARD_READ_DMA = 1
BOOST_CPU = 0
BOOST_VRAM = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

Loading the NDS file...
Header CRC is valid!
Module params offset: 02004B18
sdk_version: 02004EEB
arm9 is not compressed
Secure area already decrypted
Switched to NTR mode BIOS
patchCardNds

cardIrqEnable location : 0207AD10

startOffset : 02004000

Mpu start: 02004A40

Mpu data: 02004AD4
Mpu init: 0207C968

Mpu data alt: 0207C3D0

Mpu start 2: 02004A48

Mpu data 2: 02004AD8

waitCpuCycles location : 0207CEC0

cardRead location : 02084640
03700000

swi12 location : 02004652

cardPullOut location : 02084CF0

patchCardSetDma

NDMA CARD SET METHOD ACTIVE
cardSetDma location : 020848FC

NDMA CARD READ METHOD ACTIVE
cardEndReadDma location : 020848C8

reset location : 0207CEE0

ERR_NONE
Sleep location : 0238DA8C

Sleep input write location : 02386A94

cardIrqEnable location : 02383F8C
forwardedRelocStartAddr

02380154
vAddrOfRelocSrc
02380168
Relocation src: 02380168
Relocation dst: 037F8000
RAM mirror check location : 02380114

Arm7 (patch v1)
cardReadEndAddr: 0238B9D0
cardstructAddr: 0380A320
readCacheEnd: 0238BAF4
JumpTableFunc: 0238BAF8
Retry the search
JumpTableFunc: 0238BB9C
specificWramAddr: 03802E00
someAddr_799C: 0238B520
Eeprom page erase:	0238BBAC
Eeprom verify:	0238BBC8
Eeprom page write:	0238BBE4
Eeprom page prog:	0238BC00
Eeprom read:	0238BC1C
Card id:	0238BC48
Card read:	0238BC3C
Identify backup:			0238BC6C
swiHalt hooked
swiHalt location : 0238062C
swi12 location : 0238BFA4

swiGetPitchTable location : 023873E4

ERR_NONE

Card patch successful

hookNdsRetailArm7
hookLocation arm7: 0238FAA8

ERR_NONE
hookLocation arm9: 02113E04

Part of ROM pre-loaded into RAM
Nitro file info pre-loaded into RAM at 03708000

chipID: 00001FC2

### Other notes

I try with multiple rom USA and EUR and same error on this specific part

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Cannot reproduce this issue on my side with the USA ROM on New 3DS XL.
Do you have cheats enabled?

**Comment by TRD2B** [comment]
> Cannot reproduce this issue on my side with the USA ROM on New 3DS XL. Do you have cheats enabled?

No i haven't cheat enable and i tried with USA Rom, i don't understand, the game launch for you, i have a New DS (not xl), and for my parameters, do you apply something different ? The game crash in "Toy" section after select an launch the mini game "Snore Rope", what can i do ?
I test with the same rom and same save file with drastic and all work fine.

**Comment by RocketRobz** [comment]
> > Cannot reproduce this issue on my side with the USA ROM on New 3DS XL. Do you have cheats enabled?
> 
> No i haven't cheat enable and i tried with USA Rom, i don't understand, the game launch for you, i have a New DS (not xl), and for my parameters, do you apply something different ? The game crash in "Toy" section after select an launch the mini game "Snore Rope", what can i do ? I test with the same rom and same save file with drastic and all work fine.

I used default settings. It's possible your nds-bootstrap installation is corrupted.
Try re-installing TWiLight Menu++ & nds-bootstrap here:
1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds
2. https://wiki.ds-homebrew.com/twilightmenu/installing-3ds

If the issue persists, then something might be wrong with your SD card. Please post a picture of it.

**Comment by TRD2B** [comment]
> > > Cannot reproduce this issue on my side with the USA ROM on New 3DS XL. Do you have cheats enabled?
> > 
> > 
> > No i haven't cheat enable and i tried with USA Rom, i don't understand, the game launch for you, i have a New DS (not xl), and for my parameters, do you apply something different ? The game crash in "Toy" section after select an launch the mini game "Snore Rope", what can i do ? I test with the same rom and same save file with drastic and all work fine.
> 
> I used default settings. It's possible your nds-bootstrap installation is corrupted. Try re-installing TWiLight Menu++ & nds-bootstrap here:
> 
> 1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds
> 2. https://wiki.ds-homebrew.com/twilightmenu/installing-3ds
> 
> If the issue persists, then something might be wrong with your SD card. Please post a picture of it.

Ok, just to be sure, it's not a rom problem, can you tell me the size of your USA rom,
Thank's

**Comment by RocketRobz** [comment]
> Ok, just to be sure, it's not a rom problem, can you tell me the size of your USA rom, Thank's

It's 32MB.

**Comment by TRD2B** [comment]
> > Ok, just to be sure, it's not a rom problem, can you tell me the size of your USA rom, Thank's
> 
> It's 32MB.

So i follow your advice, i uninstall by FBI, reboot, delete all folder related _nds and _gba and boot.nds, reboot again, i reinstall twl++ by universal updater and boot the game in factory mode (all default), i tried another rom EUR, i downloaded a USA rom 32mb but same issue with this game, later i try to format my Micro SD and try again, i give you a feedback but for now, same weird issue.
