### ISSUE TITLE
Fatinitdefault Failed! Error

### ISSUE THREAD

**Issue by Pentonize** [DS-Homebrew/nds-bootstrap#1742]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [X] New Nintendo 2DS XL/LL

### Launch Method

Micro SD Card
Using NDS Forwarders as a path to launch.

### Version used

Release: 2.0.2

### Game tested/used/applicable

Pokemon Platinum.
Europe Version

### Expected Behavior

Should just boot through into the game.

### Actual Behavior

Randomly on boot it will crash instead of launching the game. Returning "Fatinitdefault Failed!" as an error.

### Steps to reproduce

Unable to constantly reproduce, it is seemingly random. 

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
NDS_PATH = sd:/roms/nds/Pokemon - Platinum Version (Europe).nds
SAV_PATH = sd:/roms/nds/saves/Pokemon - Platinum Version (Europe).sav
BOOST_CPU = 1
DEBUG = 0
CACHE_FAT_TABLE = 0
BOOST_VRAM = 0
CARD_READ_DMA = -1
ASYNC_CARD_READ = -1
DSI_MODE = 1
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
LANGUAGE = -1
REGION = -2
AP_FIX_PATH =
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
USE_ROM_REGION = 1
FORCE_SLEEP_PATCH = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
HOTKEY = 284
```

### Logs

[NDSBTSRP.log](https://github.com/user-attachments/files/17451202/NDSBTSRP.log)

### Other notes

The SD card works completly fine in 3ds mode, all games, apps and homebrew that are on the sd card boot completely fine. Only when booting an nds game off of the sd card do I get this error.

For example using FTPD works completely fine, 3dshell, any 3ds pokemon game works fine. 

Running the games through Twilight Menu seems to not cause the error to occur, This could mean it is an issue with NTR-Forwarder (https://github.com/RocketRobz/NTR_Forwarder/releases) when making game shortcuts. But I have tested the twilight menu as a launcher around 30 times and didn't get an error, only when using any forwarder. 

Further note, I have fully reformatted myt sd card and ran H2testw on it and found no errors.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Considering both use libfat, I have no idea as to why it works without any issues in TWLMenu++, but has issues in forwarders.
Please post a picture of the SD card you're using.

**Comment by Pentonize** [comment]
> Considering both use libfat, I have no idea as to why it works without any issues in TWLMenu++, but has issues in forwarders.

Yeah its confusing, had this issue for over a week now but thought I could figure it out. I could not hence I posted this.

Here are the images of my SD card
![PXL_20241020_211541103.jpg](https://github.com/user-attachments/assets/1c281368-a10d-4c6e-b8f9-a626c1742612)

![PXL_20241020_211556231.jpg](https://github.com/user-attachments/assets/d4e3c95c-8520-4c8a-ac39-91f5a4e00924)

**Comment by RocketRobz** [comment]
> Yeah its confusing, had this issue for over a week now but thought I could figure it out. I could not hence I posted this.

I'd try with a different microSD card. If the issue persists, then the microSD card slot is bugged.
