### ISSUE TITLE
New Super Mario Bros. undefined instruction when open minigame

### ISSUE THREAD

**Issue by dsguyiguess** [DS-Homebrew/nds-bootstrap#1744]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

I use Twilight Menu v27.0.0
with nds-bootstrap v2.0.2
with 16gb sd card

### Version used

release v2.0.2

### Game tested/used/applicable

New Super Mario Bros. NTR-A2DE-USA

### Expected Behavior

it should have opened a minigame in new super mario bros

### Actual Behavior

it says undefined instruction
pc: 020bfefa addr: 020bfefa

### Steps to reproduce

1. Open New Super Mario Bros.
2. Select "Minigames"
3. Select "1 player"
4. Click on any minigame
It throws a error

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 1
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 1
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/games/New Super Mario Bros. (USA, Australia).nds
SAV_PATH = sd:/games/saves/New Super Mario Bros. (USA, Australia).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
HOMEBREW_ARG =
APP_PATH = sd:/GAMES/DSIWARE/FLIPNO~1.NDS
PRV_PATH = sd:/GAMES/DSIWARE/SAVES/  !
GAME_SOFT_RESET = 1

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/17518094/NDSBTSRP.LOG)

### Will you be available for future issues and/or replies?

Yes

**Comment by gnesthenic** [comment]
I've personally experienced this with some cheats enabled for this game. Can you recreate this issue when all your cheats are disabled?

**Comment by dsguyiguess** [comment]
Thanks! That fixed the issue
