### ISSUE TITLE
"Quit game" option reboots the console

### ISSUE THREAD

**Issue by Contra-S** [DS-Homebrew/nds-bootstrap#1750]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [X] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

TWiLight Menu++ through SD card.

### Version used

Release v2.2.1

### Game tested/used/applicable

New Super Mario Bros. (USA) - MD5: `a2ddba012e5c3c2096d0be57cc273be5`
Mario Kart DS (USA) (En,Fr,De,Es,It) - MD5: `8cbf438d5a7c0d9acbe56a9b627ca6c5`
Pokemon SoulSilver (USA, Australia)_apfix - MD5: `ecb6351ff56a6879875ad600136e0f6b`
Kirby Super Star Ultra (USA) - MD5: `c0c84468ce0c9c7b3b97246ec443df1f`

### Expected Behavior

The console goes back to TWiLight Menu++ after exiting the game.

### Actual Behavior

The console reboots itself to the 3DS home menu.

### Steps to reproduce

Start any game through TWiLight Menu++ and then try exiting the game through the `L+Down+Select` menu in the "Quit game" option.

### nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 2
HOTKEY = 284
USE_ROM_REGION = 1
NDS_PATH = sd:/roms/nds/Kirby Super Star Ultra (USA).nds
SAV_PATH = sd:/roms/nds/saves/Kirby Super Star Ultra (USA).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
AP_FIX_PATH = sd:/_nds/nds-bootstrap/apFix.ips
```

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/17825459/NDSBTSRP.LOG)

### Other notes

"Reset game" does work.

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
You are not using v2.2.1, as it's has been fixed in that version. Please update TWiLight Menu++ and nds-bootstrap.

**Comment by RocketRobz** [comment]
Oh, I thought you we're using a flashcard.
In that case, this is a known issue that cannot be fixed on our side.
