### ISSUE TITLE
"Quit Game" shuts off the entire device. 

### ISSUE THREAD

**Issue by routomatic** [DS-Homebrew/nds-bootstrap#1751]
### Game Console(s) used

- [ ] Nintendo DS
- [X] Nintendo DS Lite
- [ ] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Flashcart R4 Smart Update

### Version used

2.2.0 release

Hotkeys not working on 2.2.1

### Game tested/used/applicable

All NDS roms

### Expected Behavior

Go back to twilightmenu++

### Actual Behavior

Shuts off the entire device.

### Steps to reproduce

Launch NDS rom. Press hotkey for bootstrap menu - quit game

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 383
NDS_PATH = fat:/nds/97. Draglade (USA).nds
SAV_PATH = fat:/nds/saves/97. Draglade (USA).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 1
DSI_MODE = 0
CARD_READ_DMA = 1
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/17835432/NDSBTSRP.LOG)

### Will you be available for future issues and/or replies?

Yes

**Comment by RocketRobz** [comment]
Please update nds-bootstrap, and then try running TWLMenu++ without the autoboot files.
Also, please do not open issues if later versions already fix them.

**Comment by routomatic** [comment]
> Please update nds-bootstrap, and then try running TWLMenu++ without the autoboot files. Also, please do not open issues if later versions already fix them.

I will do this. Sorry if I missed anything,
I'm fairly new to these stuff. I really appreciate your work. thank you!
