### ISSUE TITLE
Ndsbootstrap dont start pokemons games (DSI)

### ISSUE THREAD

**Issue by MegaGorgon** [DS-Homebrew/nds-bootstrap#1754]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD card

### Version used

[v27.12.2] TWiLightMenu
[nds-bootstrap v2.2.2]

### Game tested/used/applicable

Games Tested
Pokemon HeartGold
Pokemon SoulSilver
Pokemon Platinum
Pokemon black
Pokemon white
Pokemon black 2
Pokemon white 2
Fossil fighters
dinossaur king
Mario 64 ds

### Expected Behavior

Enter the game and run normally

### Actual Behavior

Dont boot the game and return to the twilight menu

(In Pokemon Black and White the game give me a black screen on top and a white screen on botton screen)

### Steps to reproduce

-install the room
-dump the room in the sd
-try to run in the twilight 
-dont run

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/Roms/NDS/Pokemon - Platinum Version (USA).nds
SAV_PATH = sd:/Roms/NDS/saves/Pokemon - Platinum Version (USA).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = pt-BR
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
CARD_READ_DMA = 1
BOOST_CPU = 0
BOOST_VRAM = 0
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

[NDSBTSRP.LOG](https://github.com/user-attachments/files/18054104/NDSBTSRP.LOG)

### Other notes

i retried reinstaling twilight inumerous times and stay the same way

### Will you be available for future issues and/or replies?

yes

**Comment by RocketRobz** [comment]
Do you have the cheat database installed?

**Comment by MegaGorgon** [comment]
where i can download the cheat database?

**Comment by RocketRobz** [comment]
> where i can download the cheat database?

I asked because it might be causing issues if you have it installed.
Try turning off `Update recently played list` in TWLMenu++ Settings then.

**Comment by MegaGorgon** [comment]
i will try

**Comment by MegaGorgon** [comment]
same problem

**Comment by RocketRobz** [comment]
Please record a video of the issue you're having then.

**Comment by MegaGorgon** [comment]
ok i gonna record it

**Comment by MegaGorgon** [comment]
https://drive.google.com/file/d/1nQlZI-orW3uXfzE4NkZUrf-TkLWtQHc9/view?usp=sharing

**Comment by RocketRobz** [comment]
Try reformatting the SD card, and then re-add the ROMs from your PC.
https://dsi.cfw.guide/sd-card-setup.html

**Comment by MegaGorgon** [comment]
ok, just a minute

**Comment by MegaGorgon** [comment]
now a red screen appeared (Error: Data Abort)

**Comment by MegaGorgon** [comment]
hey man, thanks for the support i did make it run :)
