### ISSUE TITLE
Screen brightness option

### ISSUE THREAD

**Issue by MidyGamy** [DS-Homebrew/nds-bootstrap#1758]
Would it be possible to add a brightness option in the in-game menu next to main screen and volume? I'm kinda tired to go back to the 3ds home menu just to change it...

**Comment by RocketRobz** [comment]
Press the HOME button, hold START or SELECT, and then press either Up or Down on the D-Pad to adjust brightness without having to exit to the HOME Menu.

**Comment by MidyGamy** [comment]
Oh I didn't knew about that thanks
