### ISSUE TITLE
Spider-Man Shattered Dimensions (Europe) random freezes/crash

### ISSUE THREAD

**Issue by krystalgamer** [DS-Homebrew/nds-bootstrap#1760]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

SD Card

### Version used

v2.3.0 - DSi

### Game tested/used/applicable

Spider-Man Shattered Dimensions (Europe)
MD5 - 64f6c3d017fc5f61eb3740ce2fd8a2a7
SHA1 - b09b7540e93292c8a7bdcc7e45a6b945470f34a3

### Expected Behavior

Play normally

### Actual Behavior

Game freezes, audio keeps plalying

### Steps to reproduce

Only starts happening after you reach spider-man 2099 level. At some key points in the game usually before a boss-fight or in a saving room, the game will freeze. It's random, since it happens in a save room usually it's possible to progress by restarting.

### nds-bootstrap.ini

[NDS-BOOTSTRAP]
USE_ROM_REGION = 1
DEBUG = 0
LOGGING = 0
B4DS_MODE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SLEEP_MODE = 1
SOUND_FREQ = 0
CONSOLE_MODEL = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/spidey_sd.nds
SAV_PATH = sd:/roms/nds/saves/spidey_sd.sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = 2
DSI_MODE = 1
CARD_READ_DMA = 1
BOOST_CPU = 0
BOOST_VRAM = 0
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

### Logs

Can upload later if needed.

### Other notes

I believe this might be AP related.

### Will you be available for future issues and/or replies?

Yes

**Comment by krystalgamer** [comment]
[NDSBTSRP.LOG](https://github.com/user-attachments/files/18255508/NDSBTSRP.LOG)

here's the log file

**Comment by RocketRobz** [comment]
Try downgrading nds-bootstrap to v2.2.2, and see if it fixes your issue: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v2.2.2

**Comment by krystalgamer** [comment]
2.3.2 works perfectly, thanks for the quick fix!
