### ISSUE TITLE
Screenshot saving to SD card

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/nds-bootstrap#187]

**Comment by theclashingfritz** [comment]
Would be great to have, I support this addition.

**Comment by piratesephiroth** [comment]
sure, AFTER savedata support for SDK3-4, lol

**Comment by mariomadproductions** [comment]
Piece of info that may help: the DS homebrew MoonShell can take screenshots of both screens in one go and store them as separate BMPs on the flashcard's SD Card. After holding select down for a second, a log displays on the top screen and the app freezes. Even if using this method means the game has to freeze, this would be a good feature. To check the accuracy of this feature I will take a screenshot of a many-colour image displayed in MoonShell and compare the screenshot with the displayed image on a PC. Though this won't be a very good test if MoonShell doesn't display images accurately.

**Comment by NightYoshi370** [comment]
> Also, can I ask why the other two screenshot issues were closed but not this one?
Because we want to have one issue per subject

**Comment by Plecra** [comment]
I'd quite like to have a go at this feature. I'd be learning a lot about the system as I went though - would you mind taking a PR even if it'll probably need some tuning up?

It'd be great if you could point me at a higher-level explanation of how this fits together with the rest of the 3DS (and CFW if it's relevant) so I can get my bearings 😊.

At this point this at least seems *doable*, though I'm not sure how best to approach it...

- Is MoonShell open source? It sounds like that could take out a chunk of the work involved in this feature
- Do you know how I should export the screenshots from NDS mode? I'm hoping I can reuse the mechanism used for saves.

**Comment by mariomadproductions** [comment]
> > Also, can I ask why the other two screenshot issues were closed but not this one?
> > Because we want to have one issue per subject

I meant #71, not #1019 or #1444
