### ISSUE TITLE
Golden Sun Dark Dawn black screen at launch

### ISSUE THREAD

**Issue by Stack3r** [DS-Homebrew/nds-bootstrap#252]
This game gets stuck at a black screen after loading from dsimenu++, even an AP patched rom has issues loading

**Comment by ahezard** [comment]
I do not think this is AP

**Comment by Stack3r** [comment]
Yeah i'm starting to think the same

**Comment by ahezard** [comment]
I have an issue in no$gba with this file jumped to empty wram, I am using a fat16 virtual sd card in no$gba so it may be the issue (the fat table cache is probably bigger than allowed)

**Comment by ahezard** [comment]
arm7 is not thumb and is properly patched

**Comment by ahezard** [comment]
arm9 is not thumb but I have some doubt on the card read patch here

**Comment by Kalanyr** [comment]
Testing: Haven't tested with an AP Patch, but this still black screens on launch on an unpatched ROM.

**Comment by ahezard** [comment]
Could be linked to #517

**Comment by ahezard** [comment]
The RomId of the card have a very specific behavior : 
Fomr user Jeod
"GS: Dark Dawn's card chip id is E080FF80
If I press a button to re-get card id, it changes to FF000000"

**Comment by ahezard** [comment]
Could be linked to #539

**Comment by RocketRobz** [comment]
The correct order of the ID is `80FF80E0`.

**Comment by ahezard** [comment]
[golden_sun_card_commmand_dma.txt](https://github.com/ahezard/nds-bootstrap/files/2920548/golden_sun_card_commmand_dma.txt)
Attached card command/dma log at startup (onlyfew seconds). The games sends a lot of card command (ap check?) and then the opening video start with dma card read command.

**Comment by ahezard** [comment]
This can be linked somehow to https://github.com/chishm/nitrohax/issues/3

**Comment by ahezard** [comment]
Wood contains a specific patch for this game
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_pr.cpp
Related to a MPU protection function at 4BA60 (US version)
Could be a good hint

**Comment by ahezard** [comment]
The cardId function is not properly matched :
findCardIdEndOffset:
Card ID end SDK 5 found: 0204994C

findCardIdStartOffset:
Card ID start SDK 5 not found
Card ID start SDK 5 alt 1 found: 02049850

**Comment by ahezard** [comment]
Card ID start should be : 02049904

**Comment by ahezard** [comment]
the game is looping on this code, blocking on irq forever :

02055DB4 EB000000      BL       0x02055DBC
02055DB8 EAFFFFFD      B        0x02055DB4
02055DBC E3A00000      MOV      R0, #0x0
02055DC0 EE070F90      MCR      P15, 0, R0, CR7, CR0, 4
02055DC4 E12FFF1E      BX       LR

**Comment by firelad97** [comment]
Hello, hoping it's ok for me to post on this issue. I am still new to nds-bootstrap.

In all honesty, I really love Golden Sun series, even Dark Dawn (idc about the flaws). So, as of writing the time now is 4:43 pm EST, on Oct 4th. Using the latest nightly version included in Twilight Menu++ Updater, Dark Dawn still starts on the black screen with AP patched.

Any updates? Anything I can do to help? I'd love to see this game running on my 3DS, haha. Thanks!

**Comment by KevinTheStarfish** [comment]
Yeah i have the same problem with the black screen is there a solution?

**Comment by dubbz82** [comment]
Currently no.  I know there was some work started on it, however at least as far as I'm aware, there's been no progress on this game yet.

**Comment by Kalanyr** [comment]
Yes, this still Black Screens on launch on the latest Stable as of this post (both with and without an AP-fixed ROM) 

Same with the nightly   (https://github.com/ahezard/nds-bootstrap/commit/4b1258bc7380a053cfb625ca44d4ab2a2d90cfd4 )

**Comment by JeodC** [comment]
This appears to be in part related to the absence of nds firmware. No$gba stalled at black screen without firmware.bin in same path, but booted the game without issue after firmware.bin was added to same path as no$gba exe.

**Comment by nickdesaulniers** [comment]
Perhaps interrupts were disabled, then never re-enabled?

**Comment by Squall-Leonhart** [comment]
ARM7 - IE
![image](https://user-images.githubusercontent.com/1098176/128583110-cc6369b3-b680-48e4-9c7a-e9f0bb7deb22.png)

ARM7 - IF
![image](https://user-images.githubusercontent.com/1098176/128583117-54412beb-757e-4699-a7e1-3e62068614ac.png)

ARM9 - IE
![image](https://user-images.githubusercontent.com/1098176/128583124-737769c7-3066-4af5-b753-fcc5100f4ee4.png)

ARM9 - IF
![image](https://user-images.githubusercontent.com/1098176/128583130-a3ac77ef-827d-4b3a-95ee-124e33de21bf.png)



> 
> 
> This appears to be in part related to the absence of nds firmware. No$gba stalled at black screen without firmware.bin in same path, but booted the game without issue after firmware.bin was added to same path as no$gba exe. Speculate nds firmware has an irq handler.

black screen in that case was caused by not being passed system language IIRC.



> 
> 
> the game is looping on this code, blocking on irq forever :
> 
> 02055DB4 EB000000 BL 0x02055DBC
> 02055DB8 EAFFFFFD B 0x02055DB4
> 02055DBC E3A00000 MOV R0, #0x0
> 02055DC0 EE070F90 MCR P15, 0, R0, CR7, CR0, 4
> 02055DC4 E12FFF1E BX LR

Be sure this is not the well known arm9 idle loop.

**Comment by Squall-Leonhart** [comment]
DMA1DAD and DMA1CNT hold a value of
![image](https://user-images.githubusercontent.com/1098176/128583723-ae1645af-b8ea-4278-a2f2-aed646af8334.png)

until the menu finally begins to appear, when the DMA2's recieve a value.
![image](https://user-images.githubusercontent.com/1098176/128583732-19437e6f-d22c-439e-adc1-cf975e354570.png)

**Comment by gh0sti** [comment]
@RocketRobz 
Is it possible we can get twilightmenu/nds-bootstrap to be updated that we can add our own NDS firmware.bin to see if that fixes the GSDD launch issue?

**Comment by RocketRobz** [comment]
The user settings aren't the issue, as they're loaded properly.
There is a separate issue that is causing the user settings check to fail.

**Comment by gh0sti** [comment]
It was just a theory since thats part of its AP that it needs to see a valid bios file check. I'm wondering if that would fix other compatibility issued games as well.

**Comment by RocketRobz** [comment]
It seems as of commit c34ee6ad, it no longer crashes on the user settings check.
It now loops in between RAM offsets 0x0204A30C-0x0204A31C. The actual cause may occur at 0x0205379C.

**Comment by Rose22** [comment]
> EDIT: Welp, it seems NO$GBA's breakpoint feature is causing issues, as without setting 0x021F7720 as breakpoint, it does branch to valid code, though it apparently branches to the code where it stops the game from running.

what happens if you test running golden sun using the nintendo DS bios? it might just solve the problem...

**Comment by NightScript370** [comment]
I wouldn't rely on that conclusion, to be frank. It could be a piece of code that got branched earlier because of the lack of firmware.bin and our issue would be solely because of something else.

Even if you still want to do it....how? You're loading the same thing already provided to you by the DS itself. After all, the firmware.bin originates from the same device we're hooking into directly.

**Comment by Rose22** [comment]
> I wouldn't rely on that conclusion, to be frank. It could be a piece of code that got branched earlier because of the lack of firmware.bin and our issue would be solely because of something else.
> 
> Even if you still want to do it....how? You're loading the same thing already provided to you by the DS itself. After all, the firmware.bin originates from the same device we're hooking into directly.

oh, i forgot twilight menu doesn't just run on 3DS but also on original DS's.. i figured it might be a subtle difference between the firmware.bin file and the DS firmware included with the 3ds.

perhaps you guys could do the firmware.bin thing that person described, and use breakpoints to see why it successfully runs?

**Comment by RocketRobz** [comment]
Unfortunately, even with breakpoints, it is unclear how it successfully runs.

**Comment by JeodC** [comment]
> > I wouldn't rely on that conclusion, to be frank. It could be a piece of code that got branched earlier because of the lack of firmware.bin and our issue would be solely because of something else.
> > Even if you still want to do it....how? You're loading the same thing already provided to you by the DS itself. After all, the firmware.bin originates from the same device we're hooking into directly.
> 
> oh, i forgot twilight menu doesn't just run on 3DS but also on original DS's.. i figured it might be a subtle difference between the firmware.bin file and the DS firmware included with the 3ds.
> 
> perhaps you guys could do the firmware.bin thing that person described, and use breakpoints to see why it successfully runs?

I used my firmware.bin ripped directly from my own 3ds. There is no difference.

**Comment by hubert-skowronek** [comment]
@RocketRobz what about forking desmume source code and use it as a debugger? Doing so helped me to create Bowsers Inside Story AP patch

**Comment by Ch3ck3rM0n** [comment]
> 
> I used my firmware.bin ripped directly from my own 3ds. There is no difference.

So this means, still no way or workaround to get my golden sun image working and I still have to use my hard copy?

**Comment by RocketRobz** [comment]
> So this means, still no way or workaround to get my golden sun image working and I still have to use my hard copy?

Right. This is something that other (possibly more experienced) nds-bootstrap or DS(i) homebrew developers would know what to do.

**Comment by gh0sti** [comment]
Would it be possible to try using a donor rom header?

**Comment by RocketRobz** [comment]
> Would it be possible to try using a donor rom header?

How, exactly?

**Comment by worstperson** [comment]
I found that MelonDS in DS mode is advanced enough to boot the flashcart version of TWL Menu and launch retail roms via nds-bootstrap. My idea is to add a bunch of logging to the interpreter (for example, every branch and it's destination) so I can directly compare code flow between a working state launched directly and broken launched through bootstrap. Just wanted to check with others if this approach has already been tried, or is even viable, since I have little arm reversing experience and basically no knowledge of the NDS platform.

**Comment by RocketRobz** [comment]
> I found that MelonDS in DS mode is advanced enough to boot the flashcart version of TWL Menu and launch retail roms via nds-bootstrap. My idea is to add a bunch of logging to the interpreter (for example, every branch and it's destination) so I can directly compare code flow between a working state launched directly and broken launched through bootstrap. Just wanted to check with others if this approach has already been tried, or is even viable, since I have little arm reversing experience and basically no knowledge of the NDS platform.

To my knowledge, this hasn't been tried yet.

**Comment by gh0sti** [comment]
> > Would it be possible to try using a donor rom header?
> 
> How, exactly?

Could we patch the rom with a good header to see if that would work? Tricking the emulator to boot up a good known header of a rom?

**Comment by chrisssj2** [comment]
Would love to see this finally updated to work

**Comment by RocketRobz** [comment]
Fully works as of cadf5535

**Comment by gh0sti** [comment]
What fixed it?

**Comment by RocketRobz** [comment]
> What fixed it?

Basically, the AP-fix included with TWLMenu++ was broken, so a new better AP-fix has been implemented into nds-bootstrap.
A writeup is coming soon.

**Comment by gh0sti** [comment]
> > What fixed it?
> 
> Basically, the AP-fix included with TWLMenu++ was broken, so a new better AP-fix has been implemented into nds-bootstrap. A writeup is coming soon.

Thank you for not giving up and the work is appreciated!

**Comment by RocketRobz** [comment]
New version with GSDD support is now available, along with the write-up: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v1.0.0

**Comment by Sukotto-1999** [comment]
All done!
