### ISSUE TITLE
DSi mode support for DSi-Enhanced/Exclusive games

### ISSUE THREAD

**Issue by cole36912** [DS-Homebrew/nds-bootstrap#300]
This is not an Issue. I was just wondering because I haven't seen much discussion on this. I know the features that use this are pretty rare in the nds library but I think it would make it more like using a real cartridge and it is something flashcarts can't provide(except for one). So is it possible? And are there plans for it?

**Comment by piratesephiroth** [comment]
yeah I thought the enhanced CPU clock was already DSi mode but nope, heh

**Comment by RinMaru** [comment]
That's what I thought lol

**Comment by piratesephiroth** [comment]
well nds-bootstrap already has access to the DSi clock speed and the SD card so the remaining features (camera and WPA wifi) are probably possible too.

**Comment by NightYoshi370** [comment]
Hasn't this already been implemented?

**Comment by RocketRobz** [comment]
DSi mode doesn't work with DSi-enhanced games yet.

**Comment by RocketRobz** [comment]
Currently WIP by @shutterbug2000

**Comment by ahezard** [comment]
Here is the debug output with IS-TWL, in dsi mode and nds-bootstrap v0.32.0 of 5325 - Mario vs. Donkey Kong - Mini-Land Mayhem! (USA) 

[[ Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x02004D88
   02004D88:  E4812004       STR        R2, [R1], #4

   CPSR:A000001F
     R0:02198698  R1:02FE4000  R2:49D84DCF  R3:02406C74
     R4:04000300  R5:023DA808  R6:04000200  R7:8307F100
     R8:FFFF820F  R9:00000000 R10:00000000 R11:00000051
    R12:02406C70  SP:02FE3760  LR:02004CC4  PC:02004D88

**Comment by ahezard** [comment]
Here is the debug output with IS-TWL, in dsi mode and nds-bootstrap v0.32.0 of 5585 - Pokemon - Black Version

It is crashing with the following error

[[ Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x02086E20
   02086E20:  05805000       STREQ      R5, [R0]

   CPSR:6000001F   
     R0:027FFD9C  R1:00000000  R2:7BF9DD5B  R3:FDDB597D
     R4:02FFFD9C  R5:02086E40  R6:04000200  R7:8307F100
     R8:FFFF820F  R9:00000000 R10:00000000 R11:00000051
    R12:02FE0000  SP:02FE3738  LR:02086E18  PC:02086E20

**Comment by ahezard** [comment]
The MPU end up badly configured when the dsi enhanced game runs via in nds boostrap : only 4MB is configured instead of 16MB. This the cause of the crashes above.

**Comment by ahezard** [comment]
configuration of the MPU in 5585 - Pokemon - Black Version

![image](https://user-images.githubusercontent.com/16766068/78411974-0c88c400-7612-11ea-84f1-291e011bdac8.png)

**Comment by ahezard** [comment]
As a reference here is the correct configuration of the MPU of 5585 - Pokemon - Black Version in no$gba in dsi mode

![image](https://user-images.githubusercontent.com/16766068/78412028-393cdb80-7612-11ea-8438-1e99a4df9abe.png)

**Comment by ahezard** [comment]
Some SCFG registers are wrong

![image](https://user-images.githubusercontent.com/16766068/78412477-c3d20a80-7613-11ea-8d22-f71aa5735e9c.png)

**Comment by ahezard** [comment]
for reference
![image](https://user-images.githubusercontent.com/16766068/78412495-dc422500-7613-11ea-858d-29028827d842.png)

**Comment by DraconicNEO** [comment]
What are the main issues With getting this feature working on 3DS?

**Comment by Tavisco** [comment]
Is this the cause of when I try to boot a DSi enhanced game via TWiLight Menu++ the upper screen turns black and the bottom white?

**Comment by hansoljin** [comment]
> Is this the cause of when I try to boot a DSi enhanced game via TWiLight Menu++ the upper screen turns black and the bottom white?

You would be correct. It is not fully implemented and thus not working in DSi mode.
You can change to DS-mode in either global settings or game-specific settings to mitigate this.

**Comment by RocketRobz** [comment]
Some progress has been made!

Most games will no longer crash with a top black screen and bottom white screen, and on DSi, it'll not show the nds-bootstrap error message. Depending on the ROM, it'll start with either white screens or black screens.
However, card reads are currently broken.
On DSi consoles, the card read code is stuck in a loop, with the card read LED staying on forever.

Some <=16MB ROMs will boot in DSi mode on NO$GBA though, but keep in mind that reading/writing save data will cause the game to crash. If the ROM is DSiWare, it'll show an error screen instead.

**Comment by Squall-Leonhart** [comment]
you've got pokemon black/white working with the current progress,i i can load a save and even see my 3ds connect to the wifi (and get a "this service has been discontinued" message on  xtransceiver.

not working is pokemon black 2/white 2,  it gets the menu and then black screens on loading save.

**Comment by RocketRobz** [comment]
As of later commits, most DSi-Enhanced games, all 5 DSi-Exclusives, and some DSiWare, all boot in DSi mode!
After nearly 3 years since this issue was open, this has finally been implemented.

**Comment by NightYoshi370** [comment]
Do cheats work in DSi Mode?

**Comment by RocketRobz** [comment]
> Do cheats work in DSi Mode?

Yes, they do.

**Comment by PixelateVision** [comment]
> you've got pokemon black/white working with the current progress,i i can load a save and even see my 3ds connect to the wifi (and get a "this service has been discontinued" message on xtransceiver.
> 
> not working is pokemon black 2/white 2, it gets the menu and then black screens on loading save.

I can confirm this as well. White 2 will now launch in DSi-mode, but when you try to launch a save from the main menu it goes to black screens and has to be force closed with L+Down+Select (quick pressing power doesn't quit).

**Comment by DraconicNEO** [comment]
> As of later commits, most DSi-Enhanced games, all 5 DSi-Exclusives, and some DSiWare, all boot in DSi mode!
> After nearly 3 years since this issue was open, this has finally been implemented.

Is this working on 3DS or is it DSi only?

**Comment by RocketRobz** [comment]
> > As of later commits, most DSi-Enhanced games, all 5 DSi-Exclusives, and some DSiWare, all boot in DSi mode!
> > After nearly 3 years since this issue was open, this has finally been implemented.
> 
> Is this working on 3DS or is it DSi only?

It works on both DSi and 3DS consoles.

**Comment by DraconicNEO** [comment]
> > > As of later commits, most DSi-Enhanced games, all 5 DSi-Exclusives, and some DSiWare, all boot in DSi mode!
> > > After nearly 3 years since this issue was open, this has finally been implemented.
> > 
> > Is this working on 3DS or is it DSi only?
> 
> It works on both DSi and 3DS consoles.
> 

Is there a Compatibility list for Working DSiware games?

**Comment by RocketRobz** [comment]
> Is there a Compatibility list for Working DSiware games?

See here: https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=524006717

It's still new, so you'll need to test some DSiWare yourself.
