### ISSUE TITLE
Kirby Super Star Ultra - Not recognizing any inputs after unlocking new games

### ISSUE THREAD

**Issue by 0klux** [DS-Homebrew/nds-bootstrap#314]
NDS-Bootstrap: 0.10.1

The game stop recognizing any inputs, buttons and touchscreen, after the "now you can play" message, it only really happens when we close the message.
The game still works fine after a reboot.

**Comment by legoj15** [comment]
I've noticed this too. Not detrimental since the game thankfully saves after unlocking new ones, but annoying.

**Comment by Okirihayato** [comment]
This must be an AP issue since this used to also happen on R4 cards.

**Comment by Stack3r** [comment]
Is this still an issue?

**Comment by dubbz82** [comment]
It looks like it's not explicitly an AP thing, but can be worked around with AR Codes (which should be able to be patched in with DSATM) information here: https://gbatemp.net/threads/kirby-super-star-ultra-freezes-sometimes.107230/#post-8177335

**Comment by legoj15** [comment]
Using DSATM to rebuild the ROM with that AR code injected fixed the issue.
Here are the settings that worked for me for those who also want to patch their ROM:
![image](https://user-images.githubusercontent.com/7399802/50748124-c58d0280-1205-11e9-845f-308c571c9d91.png)

**Comment by dubbz82** [comment]
This should probably be closed then...

**Comment by MasterGamingYT** [comment]
@dubbz82 If it's an AP problem, them why does the message about the game not being AP patched not show up?

**Comment by NightYoshi370** [comment]
> If it **is** an AP problem, then why does the message about the game not being AP patched not show up?

> It looks like it's **not** explicitly an AP thing

Plus, AP message is handled by TWiLightMenu++, not nds-bootstrap.

**Comment by dubbz82** [comment]
As this can in fact be patched out, this should probably be closed.
