### ISSUE TITLE
Mario's Holiday doesn't work

### ISSUE THREAD

**Issue by 3bdrzk** [DS-Homebrew/nds-bootstrap#402]
Mario's Holiday -An SM64DS Romhack- doesn't work, and shows a blue screen with white text.
![20180827_162135](https://user-images.githubusercontent.com/42783285/44744563-5851be00-aafd-11e8-9771-848ec2561005.jpg)

**Comment by Robz8** [comment]
What bootstrap version are you using?

**Comment by 3bdrzk** [comment]
the latest : v0.11.2

**Comment by Robz8** [comment]
Does this still occur in v0.12.0?

**Comment by NightYoshi370** [comment]
Hasn't this been fixed?

**Comment by 3bdrzk** [comment]
so i'm sorry for bein VERY late, but i updated to TWiLightMenu and everything is working fine.
thanks.

**Comment by RocketRobz** [comment]
It's not fixed on DSi though. It's due to the change of the cache chunk size.

**Comment by remysq** [comment]
I have a problem too with Mario's Holiday. I use Stargate 3DS to emule nds and 3ds games. Everything works except Mario's Holidays and don't know why
![image](https://user-images.githubusercontent.com/55348770/64920773-6bdccf00-d7bb-11e9-8eac-ec41a027d8c9.png)

**Comment by dubbz82** [comment]
Can anyone confirm if this is yet running on a DSi system?

**Comment by Kaisaan** [comment]
Issue still occurs on version 0.31.0, tested on my DSi XL.

**Comment by Kaisaan** [comment]
Testing this on version 0.32.1 on my DSi XL and both screens seem to show a whites creen instead of the top screen showing a blue crash/debug screen.

**Comment by theshinramen** [comment]
A solution has been found! A user in the [SM64DS modding Discord server](http://discord.gg/PhpA9Wt), **oreo** has found the solution. The fixed ROM is available [here](http://www.mediafire.com/file/wj2omaumsa7ajnl/file). I have tested it on my DSi on the latest version of TwilightMenu++.

**Comment by RocketRobz** [comment]
The ROM link has been removed for these reasons:
1. It contained copyrighted content from the original ROM.
2. It uses the same patch that is applied by nds-bootstrap.

**Comment by RocketRobz** [comment]
As of recent commits, this happens on 3DS as well.

**Comment by qamichele59** [comment]
Working on 3DS as well...

**Comment by ChainSwordCS** [comment]
> 
> 
> Working on 3DS as well...

Is the game *working* or is it still broken? I just tried running it on 3DS the other day and it was broken, but I'm not on the latest nightly. I also don't know if I need super specific special settings, but I tried messing with them.

**Comment by ChainSwordCS** [comment]
Yeah if I go all the way back to v0.19.5 aka 4cb2763 then it seems to work fine on 3DS

**Comment by ChainSwordCS** [comment]
I am on 3DS by the way.
It does work fine on v0.35.1 aka e6e8d4d
But it is broken on v0.36.0 aka 5bfeaa2
And the particular issue is the white bottom screen, blue top screen with debug information.

**Comment by Kaisaan** [comment]
This ROM Hack works. Using my N3DS XL on Luma3DS 10.2.1 with TWiLight Menu++ version 24.1.0, and nds-bootstrap 0.54.1. I'm using revision 11 of this hack that adds a "flashcard fix" according to the changelog. This revision was released sometime in October of 2021 (month after the previous comment). I think this should be good to close unless this still happens on DSi (which I cannot test currently). Should this be closed now?

**Comment by RocketRobz** [comment]
Revision 11 of *Mario's Holiday* boots on DSi as well!
