### ISSUE TITLE
Mario vs Donkey Kong Mini-Land Mayhem! Missing sprites in DS mode

### ISSUE THREAD

**Issue by hubert-skowronek** [DS-Homebrew/nds-bootstrap#467]
The patched rom works and the game proceeds after initial cutscene, saves and allows to complete levels but sprites are corrupted (big squares of pixels) - tested with the newest nds-bootstrap 0.12.3 rev01.

**Comment by Cee123** [comment]
I have to confirm. This game doesn't work for me either. Even with the AP patch, there are some pixellation issues.

**Comment by ahezard** [comment]
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by hubert-skowronek** [comment]
@ahezard where can I find the latest nightly or do I need to compile the latest commit myself?

**Comment by piratesephiroth** [comment]
https://github.com/TWLBot/Builds/releases

**Comment by hubert-skowronek** [comment]
@ahezard The issue still occurs

**Comment by RocketRobz** [comment]
RetroGameFan said this in a PM:
```
Here's some info in regards to Mario vs Donkey Kong Mini-Land Mayhem (V2GE etc), I can only speak in regards to flashcarts but all DSi games will either boot/load from E92D4038 E1A00C00 E1802421 or 0A0AB4F0 1C160600 but V2GE boots from 2 locations @ 02039848 (E59F3050 E5932000 E2120102 = load location) and @ 0204E734 (E92D4038 E1A00C00 E1802421). It also doesn't use 120F06EE to load.

If I was to only add the 0204E734 location and boot from that to my DSTT fixes, the game will suffer the no sprite/glitched sprite issue.

Hope this makes sense to you and helps you solve the corrupted/glitched sprite issue
```

**Comment by ahezard** [comment]
The retrogamefan input may significate that there is a duplication of the card read code in the game in 02039848 and 0204E734  and that we are patching only one. To be  checked

**Comment by nicastel** [comment]
So we only patch the 0204F374 location

**Comment by ahezard** [comment]
So we only patch the 0204F374 location. The first 02039848 location is missed.

**Comment by RocketRobz** [comment]
Actually, we're patching the card read at 0x0204E9C4.
The one at 0x0204E734 seems to be different from what we usually patch, and trying to patch it causes the game to not boot.

**Comment by RocketRobz** [comment]
Ok, so when patching the other function at 0x020398A8, the game boots at least, but upon loading a gameplay demo, it crashes on a black screen.

**Comment by ahezard** [comment]
There is several version of this rom

**Comment by Nintendo-png** [comment]
In Twilightmenu++, the sprites are invisible

**Comment by RocketRobz** [comment]
They're invisible, because there is no card in Slot-1.
To fix it would require patching the remaining card functions that read the sprites.

**Comment by Nintendo-png** [comment]
So, it trying to load data from slot-1

**Comment by RocketRobz** [comment]
Yes.

**Comment by Nintendo-png** [comment]
If I would put in the cart and load the ROM, it would load the sprites.

**Comment by Nintendo-png** [comment]
I put in Nsmb and loaded the ROM. I got pixels

**Comment by MasterGamingYT** [comment]
What happens when you put mayhem in and load the rom, is it normal?

**Comment by RocketRobz** [comment]
> What happens when you put mayhem in and load the rom, is it normal?

Before Slot-1 disabling was added, that would be the case.

**Comment by Kyrgr2114** [comment]
> > What happens when you put mayhem in and load the rom, is it normal?
> 
> Before Slot-1 disabling was added, that would be the case.

How would i disable slot-1 in TWiLightMenu’s settings? There’s options for SD access in Slot-1, SCFG access in Slot-1, Slot-1 launch method and Slot-1 SD save location, but no option to just disable Slot-1. Is this a feature that has yet to be added, or would it be in another location?

**Comment by RocketRobz** [comment]
> How would i disable slot-1 in TWiLightMenu’s settings? There’s options for SD access in Slot-1, SCFG access in Slot-1, Slot-1 launch method and Slot-1 SD save location, but no option to just disable Slot-1. Is this a feature that has yet to be added, or would it be in another location?

It's not a visible option, but it's added and enabled.

**Comment by Kyrgr2114** [comment]
> > How would i disable slot-1 in TWiLightMenu’s settings? There’s options for SD access in Slot-1, SCFG access in Slot-1, Slot-1 launch method and Slot-1 SD save location, but no option to just disable Slot-1. Is this a feature that has yet to be added, or would it be in another location?
> 
> It's not a visible option, but it's been added and enabled for a while.

It is enabled, okay. I wondered if that was the issue because I had the same problem whenever I would load up Mini-Land Mayhem: the sprites wouldn’t appear in the cutscenes or the gameplay.

**Comment by songokuemumania** [comment]
do we have a solution for this problem ?  i still have the same issue

**Comment by RocketRobz** [comment]
The location of the function to load the sprites is unknown, so nope.

**Comment by songokuemumania** [comment]
wow thanks Robz , we really appreciate all your work . we might not say it out loud but believe me when I say that we are really grateful . keep up the good work.

**Comment by RocketRobz** [comment]
Can confirm this is fixed by running the game in DSi mode!
(Tested with the Rev 2 ROM.)

**Comment by WALLE1Doctor1Who** [comment]
I'm getting a white screen if I try to boot the game in DSi mode. It does not happen when it's running under the default mode, but the sprites are still invisible. I am new to DSi moding, so I don't know if I just have something configured wrongly, or if it is just that I'm using a DSi in general. I am using the latest (as of typing this) version 0.43.2. I have included a link to a video displaying the settings for the game and demonstrating the issue in the hopes that it may be of some use. Video can be found here: [Video I hope is useful in debugging this issue](https://drive.google.com/file/d/19lSda_c1xc4p3pAxeAyJ-cUMnfHd-QUi/view?usp=sharing) Please let me know if I need to provide any more information to see this bug sorted out, as this is one of my favorite games on the DSi.

**Comment by RocketRobz** [comment]
That's a known issue. To run in DSi mode, you need a 3DS console for now.

**Comment by AbnormalPoof** [comment]
lets go 3ds gang

**Comment by josemiguex** [comment]
But I try to play it in a 3DS in DSi mode and I get a black screen too!

**Comment by RocketRobz** [comment]
Turn off asynch card read to fix the black screen crash.

Next nds-bootstrap version will allow the game to run in DSi mode on DSi consoles.

**Comment by josemiguex** [comment]
Yeah, I tried that and it worked! thanks!

**Comment by yellows111** [comment]
Trying out USAr2/V2GE and Europe/V2GV on a DSi with TWL enhancements enabled, Game works as normal until 1-DK, which seems to fail an AP check, as it forces the bottom four girder points to be disabled.

Wanting to know if this was still relevant, as it's the same game.

**Comment by mupp675** [comment]
I've a regular slim DS with a M3 real card. I just updated to the latest version and it made the REV2 version of this game boot. But as soon as I tap to select save file it crashes to a black screen. What can I do? I've tried to change the bootstrap but that doesn't work and the above solutions doesn't seem to exist on a DS, or maybe I'm blind.

**Comment by RocketRobz** [comment]
> I've a regular slim DS with a M3 real card. I just updated to the latest version and it made the REV2 version of this game boot. But as soon as I tap to select save file it crashes to a black screen. What can I do? I've tried to change the bootstrap but that doesn't work and the above solutions doesn't seem to exist on a DS, or maybe I'm blind.

Either insert a Memory Expansion Pak, or manually AP-patch the ROM using DS-Scene ROM Tool.

**Comment by mupp675** [comment]
Great, thanks.

**Comment by lifehackerhansol** [comment]
So the consensus here seems to be that DSi mode fixes sprite issues. However, the AP patch is completely broken in DSi mode, and requires manually AP-patching the ROM for it to work at all. The AP bypass cheat code from usrcheat.dat also does not work in DSi mode.

This should be a separate issue, but it is related anyway. Will mention https://github.com/DS-Homebrew/TWiLightMenu/issues/1422 just in case.
