### ISSUE TITLE
Bust-A-Move DS freezes when exiting to the title.

### ISSUE THREAD

**Issue by MintTears** [DS-Homebrew/nds-bootstrap#495]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.14.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Bust-A-Move DS (both EUR & USA versions)

### Expected behaviour

Choosing the "exit to title" option should return you to the title screen.

### Actual behaviour

When choosing the "exit to title" from the pause menu, the game freezes. 

### Steps to reproduce

1. Select "start" from the title screen, and then "single" in mode select.
2. Choose either "single," "endless," or "vs cpu," select a character, and choose whichever options you'd like, as the options do not prevent the glitch from happening.
3. When you get to where the gameplay is, pause the game.
4. Choose the "exit to title" option.

### Other notes

The rom must have it's arm7.bin replaced to be usable, otherwise it leads to a screen saying the save data could not be read.

**Comment by ahezard** [comment]
probably linked to #259

**Comment by Stack3r** [comment]
More than likely related to soft reset, needs testing

**Comment by RocketRobz** [comment]
Fixed in later nds-bootstrap versions.
