### ISSUE TITLE
Beyond Super Mario Bros. DS Crashes in 1-castle

### ISSUE THREAD

**Issue by YYoshi241** [DS-Homebrew/nds-bootstrap#499]
**Console:** Old 3DS/2DS XL
**CFW:** Luma3DS
**nds-bootstrap:** 0.14.1/0.15.0
**Game:** [Beyond Super Mario Bros DS](https://nsmbhd.net/thread/4320-beyond-super-mario-bros-ds-demo/)

**Steps to Reproduce:** 1-Castle, Second Room, walk to the right

It crashes, with this
![0113192215](https://user-images.githubusercontent.com/36418671/51095685-89691d00-1784-11e9-91ac-e0c90b7c4d63.jpg)

**Comment by Kaisaan** [comment]
Issue still occurs on version 0.31.0, tested on my N2DS XL. when I go right in the second room in the castle (as described in the original issue post), I get the first screen (linked) saying that the game has crashed. The second and third images I have linked below are the crash dump and RAM viewer respectively.
https://cdn.discordapp.com/attachments/283769550611152897/690724426416914503/image0.jpg
https://cdn.discordapp.com/attachments/283769550611152897/690724426974494840/image1.jpg
https://cdn.discordapp.com/attachments/283769550611152897/690724427570217031/image2.jpg

**Comment by Kaisaan** [comment]
Issue still occurs on version 0.32.1, as test on my N2DS XL. This might just be an issue of the hack itself, and not just nds-bootstrap. I'll test this on an emulator and see if it still happens there.

**Comment by Kaisaan** [comment]
Just tested this in DeSmuMe version 0.9.11 and the game doesn't seem to crash. Also test this on my DSi XL on version 0.32.1 and it does crash. So it does seem to be an issue from nds-bootstrap itself.

**Comment by Kaisaan** [comment]
Issue still occurs on 0.35.1, as tested on my DSi XL

**Comment by Kaisaan** [comment]
Testing this again and this issue seems to be fixed now. Setting the ROM hack to run in DSi Mode seems to fix this. Using my N3DS XL Luma3DS 10.2.1, TWiLight Menu++ version 24.1.0, and nds-bootstrap 0.54.1. Changing the Card Read DMA does not affect whether the crashing occurs or not. AFAIK this hack does not change the ROM to DSi-enhanced, so I'm not sure if this counts as the issue truly being "solved".

**Comment by lifehackerhansol** [comment]
Clock speed related? DSi Mode changes both VRAM mode and clock speed to its DSi equivalents.

**Comment by RocketRobz** [comment]
Possibly another issue related to incorrect ROM size in the header.

**Comment by Kaisaan** [comment]
Tested with more settings and setting it to DSi Mode is the only setting that does not cause the crash for me.

> Possibly another issue related to incorrect ROM size in the header.

How can that be fixed from the ROM's side?

**Comment by RocketRobz** [comment]
> How can that be fixed from the ROM's side?

I don't see how it could be fixed from the ROM's side, but maybe in nds-bootstrap's side.
It could be fixed by reading past the ROM size saved in the header, and checking if it's either data or padding.

**Comment by spellboundtriangle** [comment]
> Just tested this in DeSmuMe version 0.9.11 and the game doesn't seem to crash. Also test this on my DSi XL on version 0.32.1 and it does crash. So it does seem to be an issue from nds-bootstrap itself.

Where is this hack known to work, other than DeSmuME? It crashed in melonDS and my DSONE through EOS.

**Comment by lifehackerhansol** [comment]
If it only works on DeSmuME, then that is an issue with the ROM hack itself.

Closing.
