### ISSUE TITLE
SNEmulDS doesn't save with RAM disk

### ISSUE THREAD

**Issue by snes666** [DS-Homebrew/nds-bootstrap#520]
Settings & Game Saves in SNEmulDS aren't saved when using a RAM Disk.

**Comment by snes666** [comment]
It also wont save settings @ahezard

**Comment by snes666** [comment]
Can you help me  @RocketRobz

**Comment by RocketRobz** [comment]
Wait for the issue to be fixed.

**Comment by Heff87** [comment]
Just curious if any work has been done to try to get saving to work? Would it work using a flash card in slot 1 to boot from instead of booting from sd card? Or does that also use the same bootstrap? Still learning about how this stuff woks.

**Comment by RocketRobz** [comment]
Nothing homebrew-related has been worked on for a while.
Yes, you'll need a flashcard inserted with SNEmulDS on it.

**Comment by lifehackerhansol** [comment]
As of commit https://github.com/DS-Homebrew/TWiLightMenu/commit/667af6705880d64f1dcec1ee9ec61ec9207e8eb8 SNEmulDS TGDS has been added, which should completely eliminate the need for nds-bootstrap.

**Comment by lifehackerhansol** [comment]
RAM disk is no longer a requirement for SNEmulDS as native TWL support has been added in TWiLight Menu++.
