### ISSUE TITLE
Fix cloneboot (Download Play for most titles)

### ISSUE THREAD

**Issue by ahezard** [DS-Homebrew/nds-bootstrap#553]

**Comment by NightYoshi370** [comment]
Now that the old memcpy issue is closed, I'll repin this

**Comment by ahezard** [comment]
Wood code for dowload play patches is there :
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_dl.cpp

**Comment by RocketRobz** [comment]
That's already implemented though.

**Comment by ask-compu** [comment]
any progress on this?

**Comment by MasterGamingYT** [comment]
It's on their to-do list (If I'm not mistaken)

**Comment by Qwertymom** [comment]
yo, I can see the code has been posted but i'd like to know how I can apply it to my nintendo dsi with hiya cfw. The download play problem has been annoying me for a while now and it's quite an annoying feature to get around.

**Comment by krisdb2009** [comment]
@Qwertymom What commit is this patched in?

**Comment by SuperSaiyajinVoltZ** [comment]
It's not fixed yet iirc.

**Comment by Qwertymom** [comment]
@krisbd2009 ahezard literally posted some raw wood code but not sure if it's possible for me to apply it.

**Comment by Qwertymom** [comment]
would it be possible to in some way emulate an r4i card (because I KNOW this download play problem isn't there.) as a game within the cfw and execute the nds roms from there???

**Comment by Stack3r** [comment]
Just wait until it’s fully added and implemented by ahezard or another team member

**Comment by krisdb2009** [comment]
> @krisbd2009 ahezard literally posted some raw wood code but not sure if it's possible for me to apply it.

Gotcha, I thought you meant it was implemented in the nds-bootstrap project.

**Comment by Qwertymom** [comment]
> Just wait until it’s fully added and implemented by ahezard or another team member

but I don't think that's gonna happen for a while

**Comment by Barawer** [comment]
If its that important to you get a flashcard for the time being.

**Comment by MasterGamingYT** [comment]
Hate to be impatient, but any progress on this?

**Comment by RocketRobz** [comment]
@MasterGamingYT Nope. It hasn't been worked on.

**Comment by MasterGamingYT** [comment]
Oh, I see. (do hope it gets worked on since I want my two yoshis on sm64ds)

**Comment by Ninnovation** [comment]
Sorry for being impatient, but I want to play Clubhouse Games and Mario Party with my brother. When is this error expected to be fixed?

**Comment by MasterGamingYT** [comment]
> Sorry for being impatient, but I want to play Clubhouse Games and Mario Party with my brother. When is this error expected to be fixed?
It should be implemented in the 100th nds-bootstrap release if I'm not mistaken

**Comment by Ninnovation** [comment]
Sorry, I'm not familiar with the development and the terms of the software. Is there a date for when the release will happen?   

> > Sorry for being impatient, but I want to play Clubhouse Games and Mario Party with my brother. When is this error expected to be fixed?
> 
> It should be implemented in the 100th nds-bootstrap release if I'm not mistaken

**Comment by RocketRobz** [comment]
> Sorry, I'm not familiar with the development and the terms of the software. Is there a date for when the release will happen?

There is no ETA for when it'll be released.

**Comment by MasterGamingYT** [comment]
Also cloneboot seems to be in 1st party games iirc. So 3rd party games SHOULD work fine if it doesn't use cloneboot

**Comment by SleepyLark** [comment]
> Also cloneboot seems to be in 1st party games iirc. So 3rd party games SHOULD work fine if it doesn't use cloneboot

Actual I went ahead and tested every game known to have Download Play (in the USA region) a while back.  Out of the 315 games I found only 90 of them used cloneboot and out of that 90 only 21 of them were actually unplayable, meaning the rest can all still be played using multi-card.  So pretty much you have a 1/3 chance that the game uses cloneboot.  There's a section on the compatibility  sheet that has the full list of what games have cloneboot and what doesn't.

**Comment by idchahahaha** [comment]
is there any updates yet? and can someone please tell me where i can find the full list of games that do(nt) use cloneboot

**Comment by SleepyLark** [comment]
> 
> 
> is there any updates yet? and can someone please tell me where i can find the full list of games that do(nt) use cloneboot

It's on the [compatibility list](https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0), there's a separate sheet specifically for this purpose.

**Comment by idchahahaha** [comment]
okay thnks

**Comment by Haxorzz** [comment]
Bump cause I need this

**Comment by Ninkyo** [comment]
I've had several games that claim to work on the compatibility list not work, why is this??

**Comment by SleepyLark** [comment]
> 
> 
> I've had several games that claim to work on the compatibility list not work, why is this??

@Ninkyo Could you please be specific? What games are talking about and how are you running them?

**Comment by Ninkyo** [comment]
Running on a DSi through twilight menu both Monopoly/Boggle/Yahtzee/Battleship and Elite Beat Agents claim to work but don't and the only multiplayer game I've had success with is Countdown

**Comment by oxiver888** [comment]
whats the latest on this?

**Comment by RocketRobz** [comment]
> whats the latest on this?

No progress has been made, due to the devs not being around.

**Comment by oxiver888** [comment]
> 
> 
> > whats the latest on this?
> 
> No progress has been made, due to the devs not being around.

sad

**Comment by mooshimango** [comment]
The latest release of nds bootstrap says its fixed, but I tested it with a stock ds lite, and a CFW luma 2ds, and the ds lite still freezes on the Nintendo logo with games like MKDS and NSMB any ideas even though the patch notes say cloneboot is fixed?

**Comment by hansoljin** [comment]
> The latest release of nds bootstrap says its fixed, but I tested it with a stock ds lite, and a CFW luma 2ds, and the ds lite still freezes on the Nintendo logo with games like MKDS and NSMB any ideas even though the patch notes say cloneboot is fixed?

Nowhere on the patch notes say that it is fixed. The above half of the patch notes details what was _supposed_ to come, but were unable to be implemented at this time.

See under **What's new?** for the actual changelog.

**Comment by DraconicNEO** [comment]
Any updates on this in the Past Few months? Really hope this eventually gets fixed.

**Comment by DraconicNEO** [comment]
> > Also cloneboot seems to be in 1st party games iirc. So 3rd party games SHOULD work fine if it doesn't use cloneboot
> 
> Actual I went ahead and tested every game known to have Download Play (in the USA region) a while back.  Out of the 315 games I found only 90 of them used cloneboot and out of that 90 only 21 of them were actually unplayable, meaning the rest can all still be played using multi-card.  So pretty much you have a 1/3 chance that the game uses cloneboot.  There's a section on the compatibility  sheet that has the full list of what games have cloneboot and what doesn't.

This person is forgetting that most of those 21 games are most likely very popular first-party releases. That makes it more likely that people are going to run into those games because the ratio of people playing them is higher i.e. Mario Party DS.

**Comment by spellboundtriangle** [comment]
I think it's worth noting that Mario Party DS multiplayer can be used via multicard, you just need to use the [debug menu cheat code](https://tcrf.net/Mario_Party_DS#Debug_Menu) and a duplicate save in case of overwriting (see the linked page for more details)

**Comment by DraconicNEO** [comment]
> 
> 
> I think it's worth noting that Mario Party DS multiplayer can be used via multicard, you just need to use the [debug menu cheat code](https://tcrf.net/Mario_Party_DS#Debug_Menu) and a duplicate save in case of overwriting (see the linked page for more details)

Would be helpful if he included the list of which games worked and which didn't, because there isn't a list of cloneboot compatibility right now, especially for whether those titles are also incompatible with flashcarts.

@SleepyLark If it's not too much trouble do you think you could provide a list? if not it's okay.

**Comment by spellboundtriangle** [comment]
> Would be helpful if he included the list of which games worked and which didn't, because there isn't a list of cloneboot compatibility right now, especially for whether those titles are also incompatible with flashcarts.
> 
> @SleepyLark If it's not too much trouble do you think you could provide a list? if not it's okay.

There's a multiplayer table here https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc

**Comment by DraconicNEO** [comment]
> 
> 
> > Would be helpful if he included the list of which games worked and which didn't, because there isn't a list of cloneboot compatibility right now, especially for whether those titles are also incompatible with flashcarts.
> > @SleepyLark If it's not too much trouble do you think you could provide a list? if not it's okay.
> 
> There's a multiplayer table here https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc

Oh thanks, wait I have another question (sorry if this is annoying) do games in red not work on any flashcarts or do they not work with NDS-bootstrap on a Flashcart?

**Comment by RocketRobz** [comment]
Whether you're on an SD card or a flashcard, games marked in red will not work with cloneboot on nds-bootstrap.
This is not an issue with flashcard kernels.

**Comment by DraconicNEO** [comment]
> 
> 
> Whether you're on an SD card or a flashcard, games marked in red will not work with cloneboot on nds-bootstrap.
> This is not an issue with flashcard kernels.

Ah I see so it's just for nds-bootstrap. Good to know.

**Comment by AbnormalPoof** [comment]
The new implementation of cloneboot is partial and only works in some games. So this issue should stay open until full support is added

**Comment by RocketRobz** [comment]
Fully implemented in 24243ff4

**Comment by AbnormalPoof** [comment]
lmao THAT FAST?
Not a few days after partial implementation and it's already done
Great job guys! Development seems to be smooth sailing

**Comment by oxiver888** [comment]
wait, so its done? and is it available to use yet? or not? Im kinda confused tbh

**Comment by RocketRobz** [comment]
Yes, it's done and available to use.
The new version contains the complete fix: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.44.2

**Comment by oxiver888** [comment]
Nice!

**Comment by Haxorzz** [comment]
FINALLY! Amazing job devs!

**Comment by Farhan1379** [comment]
Could you guys tell me how to do that?

**Comment by spellboundtriangle** [comment]
@Farhan1379 how to do what?

**Comment by Farhan1379** [comment]
How to use that fix clone?

**Comment by RocketRobz** [comment]
> How to use that fix clone?

Just update both TWiLight Menu++ and nds-bootstrap.
https://wiki.ds-homebrew.com/twilightmenu/updating

**Comment by Farhan1379** [comment]
Yeah! It works completely and open clearly all of the game from DS Download Play.
But Sadly, only Diddy Kong Racing DS still has that problem.

**Comment by RocketRobz** [comment]
> Yeah! It works completely and open clearly all of the game from DS Download Play. But Sadly, only Diddy Kong Racing DS still has that problem.

If the other console is crashing on the Nintendo logo, what's the filesize of your ROM?

**Comment by Farhan1379** [comment]
you mean that diddy kong racing ds?
32 mb

**Comment by RocketRobz** [comment]
> you mean that diddy kong racing ds? 32 mb

Single-Card Multiplayer works on my side.
Try re-dumping the ROM from your cartridge, using GodMode9i.

**Comment by Farhan1379** [comment]
GodMode9? But i'm using it on my DSi.

**Comment by RocketRobz** [comment]
> GodMode9? But i'm using it on my DSi.

I said GodMode9**i** (or GM9**i**).

**Comment by Farhan1379** [comment]
But GodMode9 for 3DS, Not for DSi

**Comment by Epicpkmn11** [comment]
GodMode9i is a separate app for the DSi, https://github.com/DS-Homebrew/GodMode9i
