### ISSUE TITLE
potential icache issue after card read

### ISSUE THREAD

**Issue by ahezard** [DS-Homebrew/nds-bootstrap#558]
The icache may need to be invalidated even if the data is moved by CPU.
The code is manipulated as data by the CPU and not as instruction when moved from the rom to the memory so if the dst region is in the instruction cache already it creates an issue.
The dst region should be dflushed and then iinvalidated.

**Comment by ahezard** [comment]
Games using overlay may be particularly affected with black / white screen after scpecific action and freezes.

**Comment by ahezard** [comment]
remark : interrupt have to be disabled during icache invalidation

**Comment by NightYoshi370** [comment]
Does this still happen in the  latest release? This issue is a year old and a WALL-E issue references it, but that was fixed thanks to soft reset

**Comment by RocketRobz** [comment]
Most games are already working fine, so this doesn't seem to be too big of an issue, if at all.
