### ISSUE TITLE
lolSNES does not work on the RAM Disk Building method

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/nds-bootstrap#568]
Your console: 3DS XL
Custom Firmware: Luma3DS
nds-bootstrap version: latest nightly as the time of writing this (I have no idea what the commit hash is)

Homebrew: lolsnes ([Github Repository](https://github.com/Arisotura/lolSnes))
Issue: The game does not work with the RAM Disk building method that works on SNEmulDS

Steps to reproduce:

1. Replace SNEmulDS.nds in the TWiLightMenu++ emulators folder with the lolsnes.nds file
2. Boot a SNES game

**Comment by NightScript370** [comment]
At the time this issue existed, it didn't work fine without a ram disk. Maybe it changed since then?

**Comment by spellboundtriangle** [comment]
What issue did it have without a RAM disk did it have at the time? I assume it didn't work at all?
It works "fine" without one for me and I get similar results on my DSONE flashcard.

**Comment by NightScript370** [comment]
I guess I also used a RAM disk because I wanted to launch directly into the ROM back then.
