### ISSUE TITLE
Yu-Gi-Oh! 5D's World Championship 2009: Stardust Accelerator Racing Simulator freezes on start

### ISSUE THREAD

**Issue by ygo5d2009reporygo** [DS-Homebrew/nds-bootstrap#586]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Yu-Gi-Oh! 5D's World Championship 2009: Stardust Accelerator

### Expected behaviour

Interacting with the computer in any Motorcycle shop should load you to the track select without issue with the top screen showing the the outline of the track highlighted

### Actual behaviour

Interacting with the computer racing simulator causes the game to freeze
Music will still play and you may get to move for a second but freezes right after
Top screen doesn't show the track 
Story related races are unaffected
Happens 100% of the time
Happens in USA, EU, JAP roms
Tested on Wood R4 clone Flashcard for 3DS and works fine

### Steps to reproduce

1. Get through the story until the point you receive a motorcycle and finish your first race on the bridge
2. Go to the the motorcycle parts shop and interact with the computer at the top right
3. Replicate bug

### Other notes

Story related races are unaffected
Happens 100% of the time
Happens in USA, EU, JAP roms
Tested on Wood R4 clone Flashcard for 3DS and works fine

**Comment by RocketRobz** [comment]
Sounds like an AP issue.
Try AP-patching the ROM using DS-Scene ROM Tool.

**Comment by ygo5d2009reporygo** [comment]
Tried using the DS-scene Rom Tool but there aren't any for YGO WC 2009 only for 2010 and 2011
Also tried changing bootstrap to nightly but issue still persists

**Comment by dubbz82** [comment]
Possible that it may be undocumented AP?  this was released late enough that AP would be possible, but I'm also coming up empty with AP patches for it.

**Comment by hansoljin** [comment]
Freezing is still present in 0.37.0, in case anyone was wondering.

**Comment by RocketRobz** [comment]
Can you try the latest nightly?

**Comment by NightYoshi370** [comment]
What about the latest nightly?

**Comment by hansoljin** [comment]
Same freeze.

**Comment by lifehackerhansol** [comment]
This appears to be fixed in 0.52.0. Unfortunately I don't actually know which release has the fix.

**Comment by lifehackerhansol** [comment]
Actually, I reproduced this. TWL clock speed seems to trigger it. But NTR clock speed also slows the game down... (if anyone comes with that dilemma, disable SWI Halt Hook for this game.)

**Comment by lifehackerhansol** [comment]
As of commit https://github.com/DS-Homebrew/TWiLightMenu/commit/b08fb27a25cc8093a5a4375f28e642126b2fb8b0 SWI Halt Hook is off by default, and TWL clock speed for this game is blacklisted.
