### ISSUE TITLE
Certain games have out of sync audio/video (CGI intro, cutscenes,etc.)

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/nds-bootstrap#620]
### Your console

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

- [X] Release _[0.19.0]_
- [ ] Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

- Luminous Arc 2
- Pokemon Mystery Dungeon: Explorers of Sky
- Suikoden Tierkreis
- Tales of Innocence

### Expected behaviour

- CGI intro, etc. should be in sync in A/V

### Actual behaviour

- CGI intro, etc. are out of sync or freezing

### Other notes

I know the Tales of Innocence intro has a workaround but it has to be addressed either way.

**Comment by dubbz82** [comment]
I've spot checked this, and it still happens to some extent in Suikoden.....probably not as bad as it was when the issue was originally opened, however.  There's occasional pauses in the fmv after starting a new game.

**Comment by Stack3r** [comment]
Does this still happen?

**Comment by IrisHeartCPU** [comment]
Oh yes, it happens, i have the latest release (0.31.0), and Pokémon Mystery Dungeon Explorers of the Sky, and the A/V desync in the CGI is very hard, tested 1 minute ago.

**Comment by IrisHeartCPU** [comment]
I've noticed too that it takes too much time going through one scene and another of the CGI intro, and i think that's the cause of the desync. The music stops after the roar of Dialga, but the CGI intro has 20~30 seconds more of video (without music because of the desync)

**Comment by IrisHeartCPU** [comment]
Tested with 0.32.0, the desync in Pokemon Mystery Dungeon (Eur) is exactly the same as in 0.31.0

**Comment by IrisHeartCPU** [comment]
The A/V desync keeps happening in Pokemon Mystery Dungeon Explorers Of Sky Eur on nds-bootstrap 0.35.1

**Comment by IrisHeartCPU** [comment]
> Have you tried running it with the CPU speed set to NTR?

I tried all the options possible and nothing changed (CPU: NTR, TWL, RAM: Yes, No, Yes+512kb, Expanded ram: 16kb, 32kb, heap shrink, auto, off, on) i tried with all of them and none solved the desync

**Comment by haveanicedayyyy** [comment]
> Pokemon Mystery Dungeon: Explorers of Sky

I would like to mention that the intro in pokemon explorers of darkness (EU) is also out of sync.

my setup - new 2ds xl; twilight menu v15.1.1; nds bootstrap 0.35.1; luna 10.1.3

**Comment by FulguroBoy** [comment]
I had the same problem some time ago, and I remember fixing it by switching the CPU from NTR to TWL. However, this solution suddenly stopped working and the lag came back. I don't remember when it happened exactly, though.

My setup: O3DS, Luma3DS v10.1.2, TWiLight Menu++ v14.1.0, nds-bootstrap v0.33.0

**Comment by RocketRobz** [comment]
Various improvements have been made, and I haven't heard of such issues since then.
If the issue persists though, setting ARM9 CPU Speed to NTR may fix it (ex. in *Kirby Super Star Ultra*).
