### ISSUE TITLE
Support for DSi-Only Cart Games

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/nds-bootstrap#639]
This would add support for the following games.

Face Training (Europe Only)
Foto Showdown/Monster Finder (North America, Japan)
Hidden Photo/ Wimmelbild-Creator (Europe and Germany Only)
Ghostwire: Link to the Paranormal (North America Only, Unreleased, No rom seems to exist)
Picture Perfect: Hair Salon (North America, Europe, Australia)
System Flaw (North America Only)
Nintendo DSi Demo Video (Promo Video used in retail stores, North America)
Nintendo DSi Demo Video Volume 2 (Another Promo Video used in retail stores, North America)

**Comment by dubbz82** [comment]
I think correcting #300 may also correct this, though I guess I'm not positive if these games do anything special at boot that a standard DS cart doesn't.

**Comment by RocketRobz** [comment]
Currently WIP by @shutterbug2000

**Comment by Kaisaan** [comment]
With the release of nds-bootstrap version [v0.39.0](https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.39.0), launching DSi-exclusive games should work now. Just like #300 this can also be closed now.
