### ISSUE TITLE
Graphical glitches or screen tearing in certain games

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/nds-bootstrap#648]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Dragon Quest IV-VI
Knights in the Nightmare
Mario vs. Donkey Kong: Mini-Land Mayhem!

### Expected behaviour

Tell us what should happen

Dragon Quest IV-VI: works as intended
Knights in the Nightmare: works as intended
Mario vs. Donkey Kong: Mini-Land Mayhem!: works as intended

### Actual behaviour

Tell us what happens instead

Dragon Quest IV-VI: Screen tearing at the intro (V has the intro loop)
Knights in the Nightmare: Screen tearing at the intro
Mario vs. Donkey Kong: Mini-Land Mayhem!: the toy sprites are missing or corrupted

### Steps to reproduce

1.
2.
3.

### Other notes
V and VI are AP patched if anyone is asking

**Comment by Kaisaan** [comment]
The Mini-Land Mayhem issues are already known in #467. Issues with the other games have not been reported by others except the Dragon Quest V intro loop in #1354. If there are other issues, I think it would be better to create individual issue pages for each game. Closing.
