### ISSUE TITLE
hotel dusk language lock

### ISSUE THREAD

**Issue by Srzarco** [DS-Homebrew/nds-bootstrap#654]
### Your console

Tell us which console do you have:

- [x]  Old 3DS/2DS (XL)

hello guys and sorry to bother you, i been playing up with the 3ds and the bootstrap to play ds games in it(have an orginal one so would have been great to play them again without carrying them both)
all is working great except when i try to run hotel dusk, all work fine but the laguage stays always in english, no matter what i change, it always end playing it in english!
i dont know much about bootstrap so any help would be great!

**Comment by ahezard** [comment]
Are you using the us or european release?

**Comment by Srzarco** [comment]
I'm using the European version with Spanish language

**Comment by Srzarco** [comment]
And thanks for your time!

**Comment by piorrro33** [comment]
Hi, I can confirm the issue with another game; Etrian Odyssey.
The European version has support for other languages (probably MULTi5), but I cannot set the language to French.
I'm using Twilight Menu++. I hope my input this can help resolve this issue.

**Comment by Vendicatorealato** [comment]
The same issue happens in "Runaway 2: The Dream of the Turtle" EUR; that version is Multi5 but it always run in english.
Now I am on TWiLightMenu++ 14.2.0 and nds-bootstrap 0.34.0.

**Comment by kaosjr** [comment]
I can confirm that this issue still appears to be present with nds-bootstrap 0.35.1 on the EUR version of Hotel Dusk, alongside the other issues that the game has with TWL clockspeeds.

**Comment by twitifruity** [comment]
Same issue with european game called "SNK vs. Capcom - Card Fighters DS".
Rom number: 1842
Title ID: AVSP
Languages available in ROM: German, Spanish, English, Italian, French

Current problem: every boot in a different language from English set in Twilight Menu++ shows the following message: "SNK vs CAPCOM CARD FIGHTERS DS" does not include the chosen language. Game will go on in English.

Tested on current nds-bootstrap and Twilight Menu++ versions with different settings, but with no luck.

**Comment by Araujo143** [comment]
Reporting that the bug is still valid today.

(My example is etrian odyssey 1, which is multi and in the pc desmune it goes perfect to Spanish, but the nds-bootstrap only runs it in English).

Pd: I have both the twilight menu and the nds-bootstrap in their most current versions and the program and the console are fully configured in Spanish.

I hope they can solve it soon, Thank you

**Comment by Mnk3y** [comment]
I have located the address in DeSmuME which is responsible for the language change via the debug menu of the game. The address is `02100BBC`. The language values for the EU version are:

- FRN = 2
- GER = 3
- ITA = 4
- SPA = 5
- ENG = 6

A AR cheat code for spanish language would look like this: `02100BBC 00000005`
Maybe someone could test it if it works via the Twilight Menu++.

**Comment by RocketRobz** [comment]
Has been fixed for a while now.
