### ISSUE TITLE
Transfer repo over to DS-Homebrew group

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/nds-bootstrap#691]
This is so that we can block spammers from creating issues that do not contribute, and so that issues can transferred from this repo to TWLMenu++, and vice-versa.

**Comment by ahezard** [comment]
So I just did it!

**Comment by RocketRobz** [comment]
Thanks!

**Comment by ahezard** [comment]
I have not enough time to properly manage the repo and I have no contributed since a long time so it makes sense. I may contribute again in the future but I will still be able to do so anyway since I am part of the DS-Homebrew organisation.

**Comment by NightYoshi370** [comment]
Thank you so much ahezard.
We can now switch over to using GitHub Actions as opposed to Azure Pipelines. This allows forks to auto-compile nds-bootstrap for every new commit. Of course, actual commiting to TWLBot would only be done if its this repo, but for simple self-projects, this is great

**Comment by ahezard** [comment]
Is there other repo that would want me to transfer? like https://github.com/ahezard/NitroHax3DS for example?
