### ISSUE TITLE
Ermii Kart Legacy Edition won't allow for Local Multiplayer.

### ISSUE THREAD

**Issue by Jerdo32** [DS-Homebrew/nds-bootstrap#714]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v 0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Ermii Kart DS Legacy Edition (Mario Kart DS ROM Hack) (USA)

### Expected behaviour

When you select a race track on Local Multiplayer (Normal) and press ok, the race should start as normal.

### Actual behaviour

When you press ok, the 2DS of the player(s) that joined the group kind of crashes, showing a red screen with white text (two vertical columns).

### Steps to reproduce

1. Start Ermii Kart DS Legacy Edition.
2. Choose multiplayer, then create a group and select Normal, allowing only players with the game to join.
3.Keep setting up the game as normal, while choosing different characters, then, after the game is set and you select your race track, press on ok, then the ds of the player(s) who joined will show the crash.

### Other notes

     - If you choose the same character, the game will actually start and you can play with pals.
     - In the columns, you see things such as 2084B74  0000000 and much more codes.
     -  This only occurs with the consoles of the players who join (unless thet choose the same character as host.), the host only gets the "An error has occured, press A to go back" screen".

- This is a picture of one DS crashing because of one person who chose a different character than host.
![15642933259427224958708999184169](https://user-images.githubusercontent.com/53071715/62002866-ce2e2300-b0da-11e9-93f2-47fceac61ab9.jpg)

- This one shows two DS crashing because they all chose different characters.
![15642935222842536152458009883232](https://user-images.githubusercontent.com/53071715/62002897-44cb2080-b0db-11e9-8e91-152ffaa1866f.jpg)

- This one is when they all chose the same racer and thus it actually ran the game.
![15642936872845059488808435690685](https://user-images.githubusercontent.com/53071715/62002920-a3909a00-b0db-11e9-9cb7-ea2269339c89.jpg)

**Comment by RocketRobz** [comment]
Interesting.
I wonder if the same issue happens on flashcard firmwares...

**Comment by Jerdo32** [comment]
I wonder the same, as everyone used Nds bootstrap.

**Comment by Kaisaan** [comment]
Issue still happens on version 0.31.0. Tested with my DSi XL and N2DS XL.

**Comment by NixLon** [comment]
> Interesting.
> I wonder if the same issue happens on flashcard firmwares...

It does.

I tested two DS Lites playing Ermii Kart v1.
One uses ACE3DS+ Wood R4, while the other one uses RGF's YSmenu.
**I encountered the same issues what OP said about. Tell the mod author to fix this issue.**

Here is a photo. (Note: My other DS Lite has a broken top LCD panel so sorry for that.)
![user](https://user-images.githubusercontent.com/74946055/110790650-42b3d680-82ac-11eb-8233-69a153cb095b.jpg)
![host](https://user-images.githubusercontent.com/74946055/110790662-48a9b780-82ac-11eb-97f7-889cb0742d7b.jpg)
![both char](https://user-images.githubusercontent.com/74946055/110790673-4c3d3e80-82ac-11eb-9588-980956ce2d97.jpg)

**Comment by spellboundtriangle** [comment]
Considering that this is more so an issue with the game itself (as apparently evidenced above) shouldn't this be moved off of the 1.0 milestone, perhaps even closed as well?

**Comment by lifehackerhansol** [comment]
Appears not to be an nds-bootstrap issue after all. Closing.

**Comment by LandonBoi123** [comment]
This happens to me too.
