### ISSUE TITLE
Strange Issue regarding PPF

### ISSUE THREAD

**Issue by Kobun42** [DS-Homebrew/nds-bootstrap#749]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _0.24.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Puyo POP Fever 1 (US)

### Expected behaviour
During normal gameplay, random voices not attached to chains or anything should not play, and cutscenes should play out normally without crashing every few cutscenes.
### Actual behaviour

During normal gameplay, random voices not attached to chains or anything begin to play after a while, and cutscenes will play out normally at first glance, but then they will crash the game after a few cutscenes have played out.

### Steps to reproduce

1. Play the game normally on any course [Normal/Hard mode recommended]
2. Do not skip any cutscenes, let them play out normally
3. After you view a few cutscenes, the game will freeze.

**Comment by RocketRobz** [comment]
Is this still the case?
If so, try holding L after pressing A/START to launch the game.

btw, it doesn't seem to freeze in B4DS.

**Comment by Kobun42** [comment]
That seemed to do away with the freezing, but another problem's on our hands now.
Graphical issues with Raffine's first fight in the Harahara course have popped up.

**Comment by Kobun42** [comment]
For some reason, now. It appears that the game seems to be working a bit more ever since I've updated it recently (I've always had it up to date for context) but when testing it seemed to be working. I'll see if any of the bugs persist, but the Harahara course is working again and cutscenes seem to not crash the game.

**Comment by RocketRobz** [comment]
With the latest stealth nds-bootstrap, I haven't gotten any freezes in the RunRun Course, though there's brief flickers at points due to the streaming voice samples (which can be fixed by setting `Expand ROM space in RAM` to `Y+512KB` in TWLMenu++).
It's safe to say this is fixed.
