### ISSUE TITLE
Neighbours from Hell (EU) - freeze 

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/nds-bootstrap#786]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 2.0]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.26.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Neighbours from Hell (EU)  

### Expected behaviour

Game does not freeze

### Actual behaviour

Game freezes after start game and select mission.

### Steps to reproduce

1. Launch game from Twilight menu
2. in game menu start game -> standard mode -> select mission 
3. The game auto saving then black screen and freeze

### Other notes

Tried L button after launch game but does not work.

Launch game from Acekard 2i works.

**Comment by RocketRobz** [comment]
What SDK version does the game use, and how big is the ROM?

**Comment by tomudo** [comment]
SDK ver: 4
ROM size is 64MB

**Comment by RocketRobz** [comment]
Can you check if the bug persists in v0.26.1?

**Comment by tomudo** [comment]
V0.26.1 does not work.

**Comment by RocketRobz** [comment]
Still persists on v0.28.1.

**Comment by RocketRobz** [comment]
#830 mentions the fix.
