### ISSUE TITLE
Pokémon Ranger: Guardian Signs - Black screen after Celebi cutscene on slow SD cards

### ISSUE THREAD

**Issue by Someguy1519** [DS-Homebrew/nds-bootstrap#792]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[26.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Ranger Guardian Signs US Version AP Patched rom

### Expected behaviour
The Game plays a cutscene of Celebi taking the player back in time

### Actual behaviour

Black Screen after leaving old Mansion upon defeating Meganium when Celebi takes the player back in time

### Steps to reproduce

1. Load Game
2. Load the save file
3. From the point where I saved leave the Mansion by going south until you reach a hallway then go to the Eastern exit as shown on the top screen map then the southern exit after that the cutscene where I get a black screen will start.

### Other notes

https://drive.google.com/file/d/111dSZNUSHwcvLPmxNUTSSbYYed2KoRE_/view?usp=drivesdk

Link to save file

**Comment by RocketRobz** [comment]
Try a clean ROM instead of an AP-patched ROM.
Also, try the latest nds-bootstrap nightly.

**Comment by Someguy1519** [comment]
> Try a clean ROM instead of an AP-patched ROM.
> Also, try the latest nds-bootstrap nightly.

I tried both. Still get a black screen

**Comment by Someguy1519** [comment]
Tried the latest nightly and it works now. Thank you for your help.

**Comment by Spider-bomb** [comment]
I'm having the exact same problem, and neither of the fixes mentioned are working for me. The game does not load past file select on a rom that has not been AP-Patched, and the latest nightly as of February 1st, 2020. (I don't know where to find the commit hash, updated using Twilight Menu++ Updater)

**Comment by RocketRobz** [comment]
@Spider-bomb Do you get an AP message, when launching a non-AP-patched ROM?

**Comment by Spider-bomb** [comment]
@RocketRobz I do not.

**Comment by RocketRobz** [comment]
Is the original ROM modified in any way?

**Comment by Spider-bomb** [comment]
As far as I'm aware, it is not.

**Comment by YousufSSyed** [comment]
I'm having the same issue, I used TWILight Menu Update to update nds-boostrap to nightly and I had the exact same problem after leaving the mansion. I used what is to believed to be a clean ROM. Anyone have any other ideas or something?

**Comment by RocketRobz** [comment]
Welp, that fix lasted a short while. :P

**Comment by RocketRobz** [comment]
Hmm, so on a364d25, it seems the crashes are random.

**Comment by TheStylist2020** [comment]
I found a workaround for this issue: I put the ROM onto and imported the save file onto Desmume and went through the part after the mansion there, then saved after I got past the part, then moved the sav back onto my 3DS.

**Comment by RocketRobz** [comment]
Re-opened yet again, because this game doesn't work with heap shrink on, which for some reason, worked before.

**Comment by Bezerker7234** [comment]
I seem to have the same problem as spider bomb but it's not exactly clear what I'm supposed to do. can someone help me please

**Comment by RocketRobz** [comment]
Change `Cache block size` to `32KB` in TWLMenu++ Settings.

**Comment by Bezerker7234** [comment]
Can’t find cache block size in settings

**Comment by RocketRobz** [comment]
It's in the `Games/Apps settings` page.

**Comment by Bezerker7234** [comment]
Is it the VRAM boost?

**Comment by RocketRobz** [comment]
No, I said `Cache block size.`
What version of TWLMenu++ are you using?

**Comment by Bezerker7234** [comment]
8.0.0

**Comment by RocketRobz** [comment]
Please update by following this [page](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu).

**Comment by Bezerker7234** [comment]
Tried downloading most resent on but it wasn’t working with my computer  so I had to use another version

**Comment by Bezerker7234** [comment]
I’ll try

**Comment by Bezerker7234** [comment]
just updating it worked didn't know twilight updater app existed thanks

**Comment by Bezerker7234** [comment]
I'm trying to post an issue and it's not working (for Kung Fu Panda)

**Comment by RocketRobz** [comment]
Let's move this [here](https://discord.gg/yD3spjv).

**Comment by RocketRobz** [comment]
Re-opened, because this is still an issue on certain slow SD cards.

**Comment by RocketRobz** [comment]
Fixed as of recent versions.

**Comment by porotoman99** [comment]
I'm having this same issue on version 27.14.0 with an old 3DS and a 4mb/s SD card.

[Save file](https://github.com/user-attachments/files/20435223/Pokemon.Ranger.-.Guardian.Signs.zip)

**Comment by porotoman99** [comment]
Swapping out the SD card for one that is 130mb/s looks to have fixed the issue on my end, but that still leaves a problem with slower cards.
