### ISSUE TITLE
Multi-card for Mario Kart DS works occasionally

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/nds-bootstrap#794]
### Your console

Tell us which console you are using:

- [x]  DS Phat/Lite (Using the original cartridge, no TWL menu or B4DS)
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9 + 1.3.2]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.26.1]_
- [ ]  Nightly _[N/A]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario Kart DS (possibly other games too, but not yet determined) 

### Expected behaviour

Multi-card multiplayer should work on any copy of the game regardless if it's the physical cartridge or booted through nds-bootstrap

### Actual behaviour

The game will connect or it may fail.

### Steps to reproduce

1. Load Mario Kart's multiplayer screen and create a game
2. The second system connects to the host
3. Wait and see if it worked. 

### Other notes
Changing it to "DS mode" (i.e. clock speed to NTR) seems to have a better chance of working, but in other cases it will go to the race select screen but fail before the race is loaded.  There's also a higher chance of success if only two systems are used regardless if the host has a physical copy or not.  Oddly enough, when hosting through a flashcart (R4i Gold 3DS RTS), I was able to connect 5 systems (3 with nds-bootstrap, 1 physical, and the host) to a game with no problems and if I exit the game without resetting I was able to get any other system to host with no problem.  Could it be possible that there's a timing delay happening?

**Comment by SleepyLark** [comment]
Multi-card will eventually work if you keep retrying without turning the system off (I was able to get it to boot after three attempts), so it's not necessarily broken, it just doesn't work the first time.

**Comment by Jerdo32** [comment]
It sound like my problem, and I have to ask... Does a red screen appear when it doesn't work? Have you tried both using the same characters?

**Comment by SleepyLark** [comment]
No, I've never had a red screen appear.  All that happens is before the race starts or before the selection screen the screen goes black and "Communication Error, Press A" appears on the screen.  Using the same characters also doesn't change anything.

**Comment by popy2k14** [comment]
Same here, sometimes it works and sometimes before the race screen appears, it aborts.

Is there anything we can provide, debug logs...

To help solve the issue

**Comment by RocketRobz** [comment]
Card read improvements have been made since then, and seems to have fixed communication errors. Closing.
