### ISSUE TITLE
Kingdom Hearts 358/2 getting multiplayer error

### ISSUE THREAD

**Issue by Drakyem** [DS-Homebrew/nds-bootstrap#797]
I've been playing this for a while and I haven't got any errors, and a friend and I even played multi without any difficulties. But we uploaded nds-bootstrap and TWiLightMenu (release and nightly) and started getting connection errors. When any of us create a group and select a character, the menu shows up (to select misions, panels, etc) and then we get the "connection error". Why does this happen? I thought multicard games didn't have any problems :/

**Comment by SleepyLark** [comment]
May be related to #794, try changing it to "DS Mode" (clock speed to NTR) or using an older version.

**Comment by Drakyem** [comment]
Ok, so I "un-updated" TWiLightMenu (to v10.0.1) and nds-bootstrap (to v0.25.2) and it worked! Thank you very much

**Comment by RocketRobz** [comment]
Please re-update TWLMenu++ to the latest, but keep the current nds-bootstrap version.

**Comment by Drakyem** [comment]
> 
> 
> Please re-update TWLMenu++ to the latest, but keep the current nds-bootstrap version.
I just did it but it keeps giving me the same error :/ - I'm gonna use the other one then...

**Comment by SleepyLark** [comment]
Sorry, I should have specified that you only needed to downgrade the nds-bootstrap version, not necessarily the entire TWLMenu++

**Comment by Drakyem** [comment]
Don't worry, doing that fixed it!

**Comment by Jerdo32** [comment]
I think it's because it's not AP patched, that was my situation and then I could play multiplayer.

**Comment by RocketRobz** [comment]
The games are automatically AP-patched though.

**Comment by Jerdo32** [comment]
That's also true... But then what could be the cause? 
(Also, I tested with a physical game and another using nds bootstrap, maybe that has to do with it.)

**Comment by RocketRobz** [comment]
Haven't encountered any multiplayer errors on my side recently. Closing.

**Comment by dreamsyntax** [comment]
This has regressed - this issue exists in v0.61.3

**Comment by RocketRobz** [comment]
Nothing multiplayer-related was changed in v0.61.3, so maybe it has regressed before then.
Try turning off card read DMA in the per-game settings menu.

**Comment by dreamsyntax** [comment]
> Nothing multiplayer-related was changed in v0.61.3, so maybe it has regressed before then. Try turning off card read DMA in the per-game settings menu.

Confirmed no change.

We then both downgraded to v0.25.2, kept card read DMA off, and are able to connect successfully.

**Comment by RocketRobz** [comment]
I suggest finding out which version started causing this issue then.

**Comment by RocketRobz** [comment]
Since a multiplayer fix has been implemented some versions ago, I don't see why this issue would persist, so I'll close this.

**Comment by giovyg20** [comment]
still broken for me, tried with different 3ds with everything updated and still gets communication error

**Comment by RocketRobz** [comment]
> still broken for me, tried with different 3ds with everything updated and still get communication error

Wait for the next version to release then.

**Comment by giovyg20** [comment]
> > still broken for me, tried with different 3ds with everything updated and still get communication error
> 
> Wait for the next version to release then.

thank you (?)
sorry I didn't want to sound annoying or something
