### ISSUE TITLE
DSLinux white screen on DSI.

### ISSUE THREAD

**Issue by Remmy12** [DS-Homebrew/nds-bootstrap#808]
Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

Tell us which CFW do you have:

DSi:

- [X ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ X]  Nightly _[insert here commit hash]_

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
DSLinux

### Expected behaviour

Tell us what should happen

    TWiLightMenu starts
    I start DSLinux
    DSLinux Boot screen should appear

### Actual behaviour

Tell us what happens instead
 
    TWiLightMenu Boots
    I launch DSLinux
    A Wild White Screen has Appeared
 

### Steps to reproduce

    Install TWiLightMenu
    Install nds-bootstrap-nightly included with TWiLightMenu
   Start DSLinux

### Other notes
This only affects DSLinux.

**Comment by RocketRobz** [comment]
Try with a RAM disk.

**Comment by Remmy12** [comment]
It didn't work, please help me :(.

**Comment by OfficialNova** [comment]
Did you put the linux folder that came with the zip in the root of the sd card? (should be sdcard:/linux)

**Comment by spellboundtriangle** [comment]
This appears to be fixed in the latest release:
https://user-images.githubusercontent.com/79382000/148157924-ef90d00f-f199-44bd-9df7-c6fe4ca895c6.mp4
