### ISSUE TITLE
Possible DLDI issue with DSOrganise and other games

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/nds-bootstrap#820]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release v0.27.1
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

DSOrganize's text editor corrupts text files when run from nds-bootstrap

### Expected behaviour

Browsing files should be fast and writing to text files should save properly

### Actual behaviour

Browsing the system SD card using DLDI-enabled homebrew is painfully slow, and in DSOrganise, saving a text document by touching the Save button on the touchscreen freezes the system and corrupts the file. This does not occur when performing these actions using a flash cartridge.

### Steps to reproduce

1. Boot DSOrganise in DS mode 
2. Open the file browser
3. Navigate to an existing text document and push button Y to edit
4. Make some changes and tap Save using the stylus

### Other notes

DLDI is unusually slow and unreliable when using nds-bootstrap.

**Comment by RocketRobz** [comment]
Seems to be fixed as of ad180ab9
