### ISSUE TITLE
Graphic flickering in Mega Man games

### ISSUE THREAD

**Issue by ArbysSauce** [DS-Homebrew/nds-bootstrap#834]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch v2.0 +HiyaCFW 3.5

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release [v0.28.1]
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mega Man Zero Collection
Mega Man ZX Advent

### Expected behavior

Graphics should appear normal everywhere

### Actual behavior

The background of Heat Genblem's stage in Zero Collection (Zero 4) occasionally flickers in certain areas
Background flickering will appear in ZX Advent in Arctic Ice Floe, and some textboxes will occasionally flicker in and out

### Steps to reproduce

1. Launch either game through TWiLightMenu++
2. After completing either game's intro, go to Genblem's stage in Zero 4 or to Arctic Ice Floe in ZXA
3. Background graphics of these areas will begin to flash black in certain spots

**Comment by SleepyLark** [comment]
Tried changing the clock speed to NTR?  That usually fixes most flickering problems in other games

**Comment by ArbysSauce** [comment]
The settings are already configured to run everything in DS mode at NTR speeds.

**Comment by RocketRobz** [comment]
Since some recent speed improvements are implemented, I'll assume this is fixed.
