### ISSUE TITLE
Tropix! White screen crash

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/nds-bootstrap#835]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9+v1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it

Tropix!

### Expected behaviour

Game should launch

### Actual behaviour

Nds-bootstrap starts only to end up displaying "An error has occurred"

### Steps to reproduce

1. launch Tropix!
2. wait
3. An error message will appear 

### Other notes
As far as I'm aware, the game shouldn't be DSi-enhanced  (it's an SDK 4).  I've tried changing it to "DS mode",setting the clock speed to NTR, and turning heap shrink off to no effect.  There could be a slight chance that the ROM itself is a bad dump.

**Comment by RocketRobz** [comment]
Ah, nds-bootstrap didn't detect the card read code.

**Comment by RocketRobz** [comment]
Now patched in 66a9bbd, but white screens on boot. Turning heap shrink off doesn't fix it.

**Comment by RocketRobz** [comment]
The issue now, is that the card pull out handler code isn't found.
I can't seem to find the correct code though.
