### ISSUE TITLE
Mario & Luigi Partners in Time Video Glitch right before battles

### ISSUE THREAD

**Issue by zenseii** [DS-Homebrew/nds-bootstrap#854]
### Your console

Tell us which console you are using:

- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.28.1]_
- [X]  Nightly _[a33e2d8c]_

### Your device

Tell us which card you are using:

- [X]  SD Card
### If this issue only affects a certain game, which game is it?

Mario & Luigi Partners in Time PAL and NTSC

### Expected behaviour

The 3D ball animation that leads into battle happens without graphical glitches.

### Actual behaviour
There's a flickering or sometimes tearing for a split second during the transition from 2D to the 3D ball animation.

### Steps to reproduce

1. Load the attached save file and pick save file with Mario and co in the party.
2. Go up to the next screen and encounter any enemy. There is one in the upper area.

Alternatively if you cannot reproduce it with that save file load the other one:
You can also load the other save file with only Mario and go up and watch the cutscene before the battle against the alien.

### Other notes
Changing any of the settings (Heap shrink, vram boost, clock speeds, audio freq) does not change this behavior.

This happens in any battle but is easier to reproduce during the first battles. After playing for a while  (30mins~) it may sometimes not even happen.

.sav file for PAL attached under.
[Mario & Luigi - Partners in Time (Europe) save.zip](https://github.com/ahezard/nds-bootstrap/files/4124646/Mario.Luigi.-.Partners.in.Time.Europe.save.zip)

Video of glitch
[M&L PiT battle glitch.zip](https://github.com/ahezard/nds-bootstrap/files/4124662/M.L.PiT.battle.glitch.zip)

Picture

![MNLPIT](https://user-images.githubusercontent.com/12501091/73307153-f3ccee00-421d-11ea-9517-c4759ed9f67a.png)

**Comment by zenseii** [comment]
Latest Nightly, a33e2d8c, does this glitch as well.

**Comment by Kaisaan** [comment]
Issue still occurs on latest nightly, [9533d83](https://github.com/ahezard/nds-bootstrap/commit/9533d83e3794eec9c7d0381b92307c52357f269e)

**Comment by foxsouns** [comment]
Still happening on the latest TwilightMenu++ release, fb3DS/Luma on an o2DS, nds-bootstrap v0.36.0.

**Comment by RocketRobz** [comment]
Can you try with both the latest TWiLight Menu++ and nds-bootstrap nightlies?

**Comment by foxsouns** [comment]
> Can you try with both the latest TWiLight Menu++ and nds-bootstrap nightlies?

on it; let me download and see if it still happens!

**Comment by foxsouns** [comment]
@RocketRobz the graphical issue doesn't seem to be fixed. Also: the updater crashed around 5 times while trying to update, but I did end up getting both nds-bootstrap and twl-menu++ out of it in the end. Probably just my less than par internet, corrupting the installables lol

**Comment by foxsouns** [comment]
@RocketRobz Wait- I was stupid. I forgot to enable the "Nightly" option in the settings, and it seems to have been fixed now.

**Comment by foxsouns** [comment]
I think we can close this issue when nightly gets merged into the latest release?

**Comment by RocketRobz** [comment]
The fix is already implemented, so it's safe to close this.

**Comment by Goserz** [comment]
T

**Comment by Goserz** [comment]
T

**Comment by Goserz** [comment]
Y
