### ISSUE TITLE
Soft Reset events in SDK5.4/5.5 titles return the system to Home Menu instead of resetting the game

### ISSUE THREAD

**Issue by Dartz150** [DS-Homebrew/nds-bootstrap#876]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release 0.30.0

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Every game that tries to do a Soft Reset by any possible known way (ie. After saving and closing the game, finish a game, exit from an options menu, enter wifi settings, or simply manual reseting with the L+R+SEL+START Combo).

### Tell us what should happen

If the game tries to do a Soft Reset it should return to the title screen or any set area of the game.

### Tell us what happens instead

The system exits to 3DS Home Menu.

###  Steps to reproduce:

1. Open a game that supports Soft Reset.
2. Leave it running iddle more than 2~3 minutes, or simply take into account the time after a play session would surpass those marks (For details see Other Notes)
3. Try to manually soft reset the game/trigger a soft reset.

### Other notes:

It is unknown why it needs to be running some time to reproduce, as I noted that trying to soft-reset immediatly after the game boots works it as expected. This behaviour is simmilar and could be linked to the issue that happens when pressing the L+R+B+DOWN button combo to exit to TwilightMenu++, as it happened 4 of 10 times of my testings, but it has been less frequent than in pre-soft reset implementation versions.

**Comment by SleepyLark** [comment]
Are you on the latest version of TWiLight Menu?  I haven't tested the 3DS version yet but I know I was having a similar problem on the DSi unless they haven't added it `resetgame.srldr` to the 3DS version yet

**Comment by Dartz150** [comment]
Yes, I'm on v12.2.0

**Comment by Stack3r** [comment]
Does this still occur? I haven’t had this issue at all

**Comment by ErdbeerbaerLP** [comment]
It also does not happen for me anymore (old3ds). And this was indeed linked to the  L+R+B+DOWN button combo to exit to TwilightMenu++ bug. That one finally works for me too ;)

**Comment by SNBeast** [comment]
I can confirm this issue still exists. new 3DS, Luma, bootstrap 0.38.0, microSD. A place where I sometimes observe it is the Pokemon Link menu (one of the ones on the Continue/New Game menu): Sometimes it resets properly (but unexpectedly slow), and sometimes it kicks me to the Home Menu.

**Comment by RocketRobz** [comment]
Fast soft-resetting has been implement since then, which fixes the issue for most titles.
It may randomly (or for most O3DS consoles, consistently) still occur in SDK5.4/5.5 titles, when using NTR clock speed.

**Comment by RocketRobz** [comment]
Commit 782b7a9f has fixed this issue.
