### ISSUE TITLE
FAT Cache causes corruption on some 64+ GB (micro)SD cards 

### ISSUE THREAD

**Issue by Kalanyr** [DS-Homebrew/nds-bootstrap#882]
**Your console:**  N3DSXL Australian / N3DSXL US
**Launch Method:** SaltMode9 -> Luma 10.1 -> Twilight Menu 12.2.0 / Luma 10.1 -> Twilight Menu 12.2.0
**Version used:**  Release
**Game tested/used/applicable:** 
128GB Samsung Pro+ MicroSD U3 XC1, Formatted as FAT32 with a 32 KB Cluster Size
4 Heroes of Light
7th Dragon (English Patched)
A Witch's Tale
Atelier Annie
Avalon Code
Avatar - Into the Inferno
Avatar - The Burning Earth
Avatar - The Last Airbender
Black Sigil - Blade of the Exiled
Bleach - Blade of Fate

128GB Sandisk Extreme Pro  U3 A1 V30 XC1, Formatted as FAT32 with a 64KB Cluster Size
Pokemon Diamond
Pokemon Pearl
Pokemon Platinum
Pokemon Black
Pokemon Black 2
Pokemon Conquest
Pokemon White
Pokemon White 2
Pokemon Heart Gold
Pokemon Soul Silver

**Expected Behavior:** 
Should run with FAT Cache turned on without corrupting the SD Card

**Actual Behavior:** 
Do run with FAT Cache turned on without corrupting the SD Card (this is an attempt to gather info on this problem, not an issue effecting me)

### Steps to reproduce
1 Delete _nds\nds-bootstrap\fatTable
2 Start Twilight Menu
3 Enable FAT Cache in Twilight Menu
4 Run a Games  to create the cached FAT file 
5 Exit the Game
6 Run the game again to access the cached FAT Table
7 Repeat 4-6 with 9 other games 
8 Scan the card using a PC Tool (eg Properties -> Tools -> Error Check on Windows) to check if it's become corrupt 

Please report the Console (DS/DSi/3DS/N3DS) , SD Card type (microSD/SD), SD Card brand, SD Card Model,  SD Card Size and Cluster Size the card is formatted as (from a command line
type
wmic volume get driveletter,blocksize  on Windows, the cluster size will be given in Bytes)
And whether or not corruption occurred 

### Other notes
This is an attempt to 
a) Identify what exactly is causing the corruption with some games when FAT Cache is enabled and
b) identify SD Cards that do not have this issue, that can safely have FAT Cache enabled.

**Comment by RocketRobz** [comment]
Can you update the nightly nds-bootstrap, then switch to that in TWLMenu++ Settings?

**Comment by Kalanyr** [comment]
Yes, certainly, will retest with the latest nightly over the next couple of
days.

**Comment by Kalanyr** [comment]
Tested with Nightly 045f0928

128GB Samsung Pro+ MicroSD U3 XC1, Formatted as FAT32 with a 32 KB Cluster Size
4 Heroes of Light
7th Dragon (English Patched)
A Witch's Tale
Atelier Annie
Avalon Code
Avatar - Into the Inferno
Avatar - The Burning Earth
Avatar - The Last Airbender
Black Sigil - Blade of the Exiled
Bleach - Blade of Fate

No corruption. 

Tested with nightly e2ffcad
128GB Sandisk Extreme Pro U3 A1 V30 XC1, Formatted as FAT32 with a 64KB Cluster Size
Pokemon Diamond
Pokemon Pearl
Pokemon Platinum
Pokemon Black
Pokemon Black 2
Pokemon Conquest
Pokemon White
Pokemon White 2
Pokemon Heart Gold
Pokemon Soul Silver

No corruption

**Comment by Kaisaan** [comment]
Does this issue still happen? I don't have any extra SD cards to test this.

**Comment by Epicpkmn11** [comment]
I haven't heard of it happening since the initial 1 or 2 people, however it has been disabled by default since then so hard to tell.

Personally I've been using a 128 GB card on DSi and 64 GB card on 3DS (though I very rarely use TWiLight on 3DS) and had it on this whole time with no issues, but that's not a large sample size...

**Comment by RocketRobz** [comment]
FAT table cache is no longer written to the SD card since some versions ago, so there should be no corruption issues at this point.
