### ISSUE TITLE
Radiant Historia sound crackling after soft reset

### ISSUE THREAD

**Issue by hubert-skowronek** [DS-Homebrew/nds-bootstrap#889]
**Your console:**
new Nintendo 3DS XL
**Launch Method:**
Luma 10.0.1
**Version used:** 
0.30.1
**Game tested/used/applicable:**
Radiant Historia BRJE
**Expected Behavior:**
Sounds should never crackle
**Actual Behavior:**
Short time after soft reset sound starts to crackle, it's more like additional crackling than any slowdown or lag.
### Steps to reproduce
Soft reset the game and start playing. You will hear crackling soon.

nds-bootstrap.ini

```
[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/nds/Radiant Historia.nds
SAV_PATH = sd:/roms/nds/saves/Radiant Historia.sav
AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/BRJE-56A6.ips
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 5
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
HOMEBREW_ARG =
CACHE_FAT_TABLE = 0
```

### Logs

```
SFCG_ROM ARM9 1
SFCG_CLK ARM9 85
SFCG_CLK ARM7
SFCG_EXT ARM7
ARM7 data 187
ARM7 data FB06
...
saveSize: 80000
language: FF
dsiMode: 0
donorSdkVer: 5
patchMpuRegion: 0
patchMpuSize: 0
ceCached: true
consoleModel: 2
colorMode: 0
romRead_LED: 0
boostCpu: false
boostVram: false
soundFreq: false
forceSleepPatch: false
```

**Comment by RocketRobz** [comment]
Does this issue still occur in nds-bootstrap v0.35.1?

**Comment by hubert-skowronek** [comment]
@RocketRobz tested with 0.35.1 and it still crackles after soft reset

**Comment by haveanicedayyyy** [comment]
> Soft reset the game and start playing. You will hear crackling soon.

I would like to mention that the sound also starts to crackle after the ''in-game reset'' when all your party members die and the game goes back to opening intro.

my setup - new 2ds xl; twilight menu v15.1.1; nds bootstrap v0.35.1; luna v10.1.3

**Comment by RocketRobz** [comment]
Fixed in later TWLMenu++ versions.
