### ISSUE TITLE
Tony Hawk series has issues

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/nds-bootstrap#904]
**Your console:** New 3DS
**Launch Method:** Luma3DS v10.0.1 + B9S
**Version used:** 0.32.0
**Game tested/used/applicable:** 

- Tony Hawk's American Sk8land [TID: AH9E]
- Tony Hawk's Downhill Jam [TID: AWKE]
- Tony Hawk's Proving Ground [TID: YT9E]

**Expected Behavior:** 
Game should run at a somewhat playable state

**Actual Behavior:** 
All three games suffer from slowdowns or other problems that makes it hard to fully enjoy the game.
- American Sk8land: On version 0.30.0 the game would run really slow, however now it doesn't even boot to the main game and instead crashes when trying to make a new profile or continuing an existing profile (possibly a regression of #755 ).
- Downhill Jam: The game has graphical glitches and also runs slow especially during races.  Free Skate is somewhat "playable" but still slow.
- Proving Ground:  Perhaps the one with the least problems (at least during the 15 minutes I've spent playing it).  It's the most playable one out of the three but it still feels like it's too slow.

For all three games the audio still runs at a smooth rate and all three were made by the same developer
### Steps to reproduce
Start the game and pick any game mode (Story or Free Skate), you'll see the problems mentioned before.

### Logs
I can't upload them at the moment, but if it will help I can get the logs for all three games or just one specifically if needed

### Other notes
I've tried playing around with the settings (especially for American Sk8land) like turning off heapshrink and changing the CPU speed but doesn't seem completely fix the issue.  Using TWL speed does help it run a little bit faster, but not enough to notice a huge difference.

**Comment by SleepyLark** [comment]
I tried 0.32.1 and American Sk8land just whitescreens on boot now

**Comment by Meowlithius** [comment]
**Tony Hawk's Proving Ground**
SDK version : 4
Title ID : YT9E
Ran on : 3DS system on Luma 10.1.3 (in DS Mode)
NDSBootstrap : Nightly (cca60b3d)
Settings : DS "Stock" (heap shrink, vram boost, CPU boost, are all off. )
Issues: Slowdown when pedestrians are in view. (even without being in direct sight, such as behind a building) One single visual issue, a missing foot in certain pants styles. No apparent speed up with DSi clock speeds.

**Comment by RocketRobz** [comment]
As of recent commits, Sk8land now boots again, but freezes in the same areas.
Downhill Jam now white screens on boot.

**Comment by RocketRobz** [comment]
1. Sk8land no longer crashes.
2. The USA version of Downhill Jam white screens, but the EUR version boots and plays fine.
3. Proving Ground still boots fine.

**Comment by RocketRobz** [comment]
As of recent versions, there is no heavy slowdown.
