### ISSUE TITLE
Freeze in Zelda Phantom Hourglass

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/nds-bootstrap#911]
**Your console:** O3DS
**Launch Method:** TWL++ Menu
**Version used:** c7cd3b77
**Flashcart used:** none
**Game tested/used/applicable:** Zelda: Phantom Hourglass AZEP/SDK4 (clean no-intro dump, hash verified)

**Expected Behavior:** No freeze
**Actual Behavior:** After completing the Temple of Courage, Link returns to the ship where the Light Fairy of Courage is united. This is followed by a cut scene with Zelda calling for help from the ghost ship. The music continues to play, but the picture is still and the operation via stylus is impossible.

### Steps to reproduce

Configuration: DS mode, NTR speed, vram boost off, heap shrink off

### Logs

No logs at all.

### Other notes

The same ROM runs natively, i.e. without nds-bootstrap, with an M3 Simply card.

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by eku** [comment]
@RocketRobz please read again my configuration.

**Comment by RocketRobz** [comment]
@eku Sorry, I missed that somehow.
Try changing the cache block size.

**Comment by eku** [comment]
Yes, increasing the cache buffer to 32kB helped, which brings me to my next question. The setting in TWL++ menu applies to all programs, which is surely not always the best choice. Would it be possible for nds-bootstrap to determine the best value itself or at least use the white/blacklist to find the right value?

Or would at least one setting in TWL++ menu per program be possible? Should I open a corresponding FR?

**Comment by eku** [comment]
@RocketRobz It's a pity that from the point of view of the developers this is the end of the topic. From the user's point of view it would be, if the software would use the correct value by itself, as I suggested.

**Comment by eku** [comment]
After the final boss battle, the cut scene hangs again. Music continues with slight interruptions. The cache size is still configured to 32kB.

**Comment by RocketRobz** [comment]
I only closed it because you solved your issue, but since there's a new issue, it makes sense to re-open this.

**Comment by FlameKat53** [comment]
I don’t get any freezes or crashes in the final boss battle’s ending cutscenes.

**Comment by RocketRobz** [comment]
@eku Try switching the cache block size back to 16KB.

**Comment by eku** [comment]
@FlameKat53 Your contribution has no value for the developers or for me as a user. Would you like to provide some information about the version of nds-bootstrap you are using, the settings and your hardware to allow for a comparison with my environment? Maybe you have used a different version of nds-bootstrap and the developers have changed something since then that has had a negative impact.

@RocketRobz Changing the cache size did not have any effect. I'd like to note here that with an M3 flash card on a DS, it's perfectly possible to play through the game including cut scenes. Under nds-bootstrap the only option is to skip the cut scenes. But you have to get the right time to do this.

And one last note. After the credits have passed, the game apparently performs a soft reset, which with nds-bootstrap only leads to two white screens. I remembered that nds-bootstrap now supports soft-reset. Probably not for this game. Should I create a separate issue for it?

**Comment by FlameKat53** [comment]
I'm using this bootstrap version: https://github.com/ahezard/nds-bootstrap/commit/c0879bf233fce27daebe0599dbb520be0b912d11

And TWiLight Menu++ Nightly version: https://github.com/DS-Homebrew/TWiLightMenu/commit/fa065309fbc2f19bd3203602f18646a038668057

new Nintendo 3DS, 128GB Class 10 micro SD Card,

**Comment by eku** [comment]
@FlameKat53 what are your nds-bootstrap settings?

**Comment by FlameKat53** [comment]
```[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
SOUND_FREQ = 0
NDS_PATH = sd:/roms/srl/1456 - Legend of Zelda, The - Phantom Hourglass (USA) (En,Fr,Es).nds
SAV_PATH = sd:/roms/srl/saves/1456 - Legend of Zelda, The - Phantom Hourglass (USA) (En,Fr,Es).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 1
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0```

**Comment by eku** [comment]
@FlameKat53 thanks. We use different versions of the game and different consoles.

**Comment by Squall-Leonhart** [comment]
There are no apparent issues with the current release and the AZEP version of the game, issue is either already fixed, the users SD card or faulty AP patch.

**Comment by RocketRobz** [comment]
Closing, since there are no recent reports about the freeze.

**Comment by Zhounanitathai** [comment]
New freeze problem, with white screen, just after the first cave.
I'm playing on a New 3DS LL
Last release of TwilightMenu++ with standard settings
SD card 128 Gb Class 10

**Comment by RocketRobz** [comment]
Turn on the `Card read DMA` setting.
