### ISSUE TITLE
Mario & Luigi Bowser's inside story it freezes.

### ISSUE THREAD

**Issue by MrGoned** [DS-Homebrew/nds-bootstrap#915]
**Your console:** Dsi
**Launch Method:** Twilight Menu ++ V14.0.0, Dsi 1.4.5
**Version used:** nds-bootstrap v0.33.0
**Game tested/used/applicable:** Mario & Luigi Bowser's inside story
**Expected Behavior:** I hoped it wouldn't freeze.
**Actual Behavior:** The game freezes when I load the game.

**Comment by RocketRobz** [comment]
Do other games work?

**Comment by MrGoned** [comment]
> ¿Funcionan otros juegos?

I just tried Mario & Luigi Partners in Time and Pokémon Heart Gold and no problem, just happens with Bowser's inside story.

**Comment by MrGoned** [comment]
> Do other games work?

UPGRADE 19/04/20:

Change the rom and proceeded to test the game, this time save the game in the first save block we found in Peach's castle, I proceeded to save and restart the game, when I opened it everything worked fine but at the end of the combat with Bowser, when Peach proceed to remove it from the castle it freezes.

What do you think this is due to?

**Comment by RocketRobz** [comment]
Might be either bugged card reading code, or the cache block size is wrong.
Try changing it in TWLMenu++ Settings.

**Comment by MrGoned** [comment]
UPGRADE 01/05/20:

Try configuring in settings to run it in dsi mode (the one that turns on TW and Vram boost mode), resized cache block but it didn't work.

I opted to use the North American rom (since the European one didn't work), I was expecting the game to freeze when Peach took Bowser out of the castle, but to my surprise it didn't freeze, but upon awakening Bowser saved the game just before meeting us for the second Once with Fawful, I restarted the game and to my surprise when the game loads, the game works normally for a few seconds and then freezes.

To test to see if it was the rom use 2 options.

1st: Using an emulator, the game went perfectly.

The second: using an R4 clone, in this case I asked a friend to insert the game and, like the emulator, it went very well.

**Comment by MrGoned** [comment]
UPGRADE 09/05/20:

Sorry for being annoying, but I still don't get the game to work, and so far it's the only one not working as it should ...



> Might be either bugged card reading code, or the cache block size is wrong.
> Try changing it in TWLMenu++ Settings.

**Comment by Lucas7yoshi** [comment]
Am experiencing this aswell
NDS-Bootstrap v0.35.1
Twilight menu v15.0.1

Using US rom, crashes after loading saves. works fine on emulator for me aswell.

Hopefully this gets addressed, im in the same boat as you @MrGoned

**Comment by Lucas7yoshi** [comment]
Follow up: occurs on European rom aswell.

**Comment by Lucas7yoshi** [comment]
Follow up: Rob was right the entire time on discord
in order to load saves
- Launch Game
- Load save until it freezes
- tap the power button to soft reset
- Launch game again
- Load save

works consistently for me. Reflected it in the compatibility sheet

**Comment by SuperNessl** [comment]
It doesn't freeze for me but the save file I have doesn't load even if I soft reset. Any recommendations

**Comment by Galindaan** [comment]
the same happens on my dsi too

**Comment by jellees** [comment]
The game freezes for me too on the scene where Peach throws Bowser out. This is for both the EU and USA version. I use a DSi.

NDS-Bootstrap v0.36.0
Twilight menu v18.5.0

**Comment by RocketRobz** [comment]
Please check if this is fixed in the latest nds-bootstrap nightly.

**Comment by jellees** [comment]
I downloaded the lastest nds-bootstrap nightly and tested it on the USA version just now but it freezes on the same scene.

**Comment by jellees** [comment]
I tried the game on actual flashcards too, Acekard2i and dstt. On both flashcards the game also freezes on the exact same scene. The game seems to work for everyone else. At this point I am thinking my DS is cursed.

So this may not be an issue with nds bootstrap per sé.

**Comment by RocketRobz** [comment]
Do you have other consoles to test on?

**Comment by Lucas7yoshi** [comment]
I'm up to test it, not sure where to find a recent nightly though?

**Comment by RocketRobz** [comment]
> I'm up to test it, not sure where to find a recent nightly though?

https://github.com/TWLBot/Builds/commit/a75bb10e574b3f7359ded6f316057185218c63e1

**Comment by Lucas7yoshi** [comment]
Tested it on my old save - no luck
Tested on a fresh save from a new game in a new save slot - no luck
https://l7y.ca/files/sx/pxl8174.mp4.mp4

**Comment by foxsouns** [comment]
> Please check if this is fixed in the latest nds-bootstrap nightly.

I'm not sure if this is news or anything, but the latest nds-bootstrap release has this fixed. I believe it's safe to close this issue now.
