### ISSUE TITLE
Garbled/crackling audio in Call of Duty games in widescreen mode (error in cheat handler?)

### ISSUE THREAD

**Issue by wad11656** [DS-Homebrew/nds-bootstrap#918]
**Your console:** 
Old 3DS NTSC

**Launch Method:** 
Luma3DS v10.0.1 || TWiLight Menu++ v14.0.0/14.2.0

**Version used:** 
Release (v0.33.0/0.34.0)

**Game tested/used/applicable:** 
(Game ID: CALE) Call of Duty - World at War (NTSC-U)
(Game ID: C62E) Call of Duty - Modern Warfare - Mobilized (NTSC-U)

**Expected Behavior:** 
Game audio plays in 16:10 widescreen mode without ever garbling/crackling

**Actual Behavior:** 
Audio garbles/crackles in 16:10 widescreen mode sporadically (perhaps triggered by low-frequency/loud audio), but there are no audio issues in 4:3 fullscreen mode.

### Steps to reproduce

1. Install TWiLight Menu++ and install TWPatch for widescreen support
2. Use default TWiLight Menu++ settings, except change screen size from 4:3 to 16:10
3. Trigger the crackling/garbling audio: Wait on title screen music to activate garble or play game. (Should activate in 10-15 minutes).

nds-bootstrap.ini
```ini
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
CACHE_FAT_TABLE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 0
NDS_PATH = sd:/ROMs/nds/_Call of Duty - Modern Warfare - Mobilized.nds
SAV_PATH = sd:/ROMs/nds/saves/_Call of Duty - Modern Warfare - Mobilized.sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
AP_FIX_PATH =
```
### Logs

NDSBTSTRP.LOG
```
findModuleParamsOffset:
Module params offset restored: 02000BBC
sdk_version: 04027536
This rom is compressed

Switched to NTR mode BIOS
old heap pointer: 0222DCC0

new heap pointer: 0222F4C0

Heap Shrink Sucessfull

relocate_ce9
firstCardLocation 0222DCC0 : 02700000

armReadCardLocation 0222DDB4 : 02700000

thumbReadCardLocation 0222DDD0 : 02700000

armReadCardDmaLocation 0222DE00 : 02700000

armReadSlot2Location 0222DE24 : 02700000

armSetDmaCardLocation 0222DE58 : 02700000

thumbReadCardDmaLocation 0222DE90 : 02700000

thumbSetDmaCardLocation 0222DEB0 : 02700000

armReadNandLocation 0222DEDC : 02700000

thumbReadNandLocation 0222DF08 : 02700000

armWriteNandLocation 0222DF30 : 02700000

thumbWriteNandLocation 0222DF50 : 02700000

armIrqEnableLocation 0222DF80 : 02700000

thumbIrqEnableLocation 0222DFA0 : 02700000

pdashReadLocation 0222DFCC : 02700000

thumbReadSlot2Location 0222DFF0 : 02700000

ipcSyncHandlerLocation 0222E030 : 02700000

resetLocation 0222E05C : 02700000

globalCardLocation 0222F3A4 : 02700000

 ce9->patches 0222DCF8

patchCardNds

cardIrqEnable location : 020D09F4

startOffset : 02000000

cardRead location : 020C7004

cardPullOut location : 020C7560

cardId location : 020C70F4


patchCardSetDma
cardReadDma location : 020C6E78

patchMpuSize: 00000000

reset location : 020D2E60

ERR_NONE


Arm7 (patch vAll)
forwardedRelocStartAddr
023801D0
vAddrOfRelocSrc
023801E8
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F74C

ERR_NONE
hookLocation arm9: 027C0000

chipID: 80003FC2
                                                                                                 
[...]
                                                                                                              
debug: true
ndsPath: "sd:/ROMs/nds/_Call of Duty - Modern Warfare - Mobilized.nds"
savPath: "sd:/ROMs/nds/saves/_Call of Duty - Modern Warfare - Mobilized.sav"
donorPath: ""
gbaPath: ""
saveSize: 80000
language: FF
dsiMode: 0
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
ceCached: true
cacheBlockSize: 4000
extendedMemory: false
consoleModel: 2
colorMode: 0
romRead_LED: 0
dmaRomRead_LED: FFFFFFFF
boostCpu: false
boostVram: false
soundFreq: false
forceSleepPatch: false
logging: true
initDisc: false
gameOnFlashcard: false
saveOnFlashcard: false
backlightMode: 0
```

### Other notes
TEMPORARILY FIXED by:

1. Pessing HOME  during gameplay then B (Cancel)
2. Dying
3. Moving onto next stage

...but the gargling and crackling always comes back...always.

I already tried allocating more VRAM, increasing the audio quality, and whatever other potential improvements I could find in in TWiLight Menu++'s settings

-----

### Convo with Sono (TWPatch's (a.k.a. widescreen patch's) creator)

> wad11656 said: 
> Hi Sono, thanks so much for your amazing contributions :)
> Unfortunately TWiLight Menu++, I get Garbled/crackling audio in Call of Duty games, and the bad audio is almost too unbearable to play the game. In particular the issue arrives in these 2 games:
> 
> Call of Duty - World at War (USA/Europe/Korea/Chinese translation)
> Call of Duty - Modern Warfare - Mobilized (USA/Europe/France/Germany/Italy/Spain)
> 
> As soon as I turn resolution from 16:10 back to 4:3 in TWiLight Menu++'s settings, the garbled/crackling audio stops. Is there ANY way you could fix this?? Thank you :)

> Sono said: 
> That's weird, it's not supposed to influence the audio at all :wacko:
> 
> Hold Y to disable rtcom and re-patch. I think rtcom is interrupting the ARM7, causing weird problems with the audio.

> wad11656 said: 
> Thank you for the quick reply! Unfortunately, the audio is just as garbled and crackly as before when in 16:10 mode.

> Robz8 said:
> Sounds more like the cheat code handler is causing the sound issues.

https://gbatemp.net/threads/twpatcher-ds-i-mode-screen-filters-and-patches.542694/page-61#post-9022974

**Comment by RocketRobz** [comment]
Card read improvements have been made to cut down or remove sound issues since then, so it's safe to assume this is fixed.
