### ISSUE TITLE
The Wizard of Oz: Beyond the Yellow Brick Road/RIZ-ZOAWD not working

### ISSUE THREAD

**Issue by AdellThePhantom** [DS-Homebrew/nds-bootstrap#928]
Your console: 3DS XL
Launch Method: Luma 3DS via TwilightMenu++
Version used:v0.34.0
Flashcart used: SD Card
Game tested/used/applicable:
 3221 - Riz-Zoawd (J)
 4280 - The Wizard of Oz - Beyond the Yellow Brick Road (USA)

Expected Behavior: Game Lag 
Actual Behavior: Screen star to swan and the game is very slow and laggy
Steps to reproduce: Start the game until the menu screen

Boot up the game and try to complete the first tutorial sequence.

**Comment by RocketRobz** [comment]
Try changing cache block size to 32KB in TWLMenu++ Settings.

**Comment by AdellThePhantom** [comment]
> che block size to 32KB in TWLMenu++ Settings.

Setting the size to 32K let the speed be normal but the game still has the screen flickering and some lag only in the cutscene

**Comment by strelokcyka** [comment]
> 
> 
> > che block size to 32KB in TWLMenu++ Settings.
> 
> Setting the size to 32K let the speed be normal but the game still has the screen flickering and some lag only in the cutscene

Can corroborate these results, no luck with this game.

**Comment by RocketRobz** [comment]
Does this still happen in the latest nightly?

**Comment by RocketRobz** [comment]
Closing due to no response, and the issue is likely already fixed.
