### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/nds-bootstrap#930]
Since v0.35.0, B4DS now requires a Memory Expansion Pak for WiFi to work.
DSi or 3DS users with `SCFG access for Slot-1` enabled in TWLMenu++ on the SD card, will still be able to use WiFi.

**Comment by spellboundtriangle** [comment]
This appears to be fixed in the latest release:
https://user-images.githubusercontent.com/79382000/148156865-d4de6821-a032-439b-8a8a-ebbf8579b741.mp4

**Comment by RocketRobz** [comment]
Ah, I forgot that issue was a thing.
Yeah, it's been fixed for a while now.
