### ISSUE TITLE
Touch Screen Not Responding Exclusively Playing The Urbz: Sims In The City (U)

### ISSUE THREAD

**Issue by NateTheL0ser** [DS-Homebrew/nds-bootstrap#935]
**Your console:** N3DS XL
**Launch Method:** Luma3DS v10.1.3, nds-bootstrap launched via TWiLight Menu++ release 15.0.1
**Version used:** Release 0.35.1
**Game tested/used/applicable:** 0045 - The Urbz: Sims In The City, DS, USA

**Expected Behavior:** The touch screen should work to load a saved game
**Actual Behavior:** Touch is not responsive, making the game unplayable due to requiring a touch screen input. 

### Steps to reproduce

-Load The Urbz rom in TWiLight Menu++
-Select an option requiring touch screen input like Settings or Load An Urb 
-Attempt to select one of the touch screen buttons like the checkmark for Load An Urb

### Other notes

I could successfully play the Urbz last summer on TWiLight Menu++, so there was a point in time the game was indeed playable. Other games, such as Pokemon Black, Bokujou Monogatari: Corobockle Station For Girl, and Pokemon White 2 all have responsive touch screen input, as does the main menu for TWiLight Menu++

**Comment by LittleStinky123** [comment]
I could reproduce this on my DSi XL with TWiLightMenu 15.1.0 as well.
Changing DSi boot mode to DS or CPU speed didn't change the touch screen not working.

**Comment by Vivi20910** [comment]
same problem

**Comment by Labatryth** [comment]
Does anyone perhaps know when this will be fixed?

**Comment by RocketRobz** [comment]
The latest stealth nds-bootstrap build fixes this issue.

**Comment by qamichele5959** [comment]
The Urbz: Sims in the City USA changes following category color:
|Red: Game is unplayable.|
|---|

**Comment by qamichele5959** [comment]
Addes Other Notes: "Corrupted Game, was not. The Game has playable better tried it DeSmuME on my PC."

**Comment by qamichele5959** [comment]
The Urbz: Sims in the City USA changes following category compatibility rating color:

|Red: Game is unplayable.|
|---|
