### ISSUE TITLE
Army Men - Soldiers of Misfortune not work (black screen)

### ISSUE THREAD

**Issue by houmdiyoussef** [DS-Homebrew/nds-bootstrap#938]
**Your console:** DSI XL
**Launch Method:** HiyaCFW + TWiLight Menu++ release 15.0.1
**Version used:** 0.35.1
**Game tested/used/applicable:** Army Men - Soldiers of Misfortune (EUR & USA)
**Expected Behavior:** RUN GAME
**Actual Behavior:** BLACK SCREEN

### Logs
Log for USA version :
[logUSA.LOG](https://github.com/ahezard/nds-bootstrap/files/4625010/logUSA.LOG)

Log for EUR version :
[logEUR.LOG](https://github.com/ahezard/nds-bootstrap/files/4625022/logEUR.LOG)

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by houmdiyoussef** [comment]
Heap shrink off not worked for both versions

**Comment by RocketRobz** [comment]
Still happens as of recent commits.

**Comment by RocketRobz** [comment]
Fixed in later releases.
