### ISSUE TITLE
Pokéwalker only works when using hiyaCFW on DSi

### ISSUE THREAD

**Issue by Epicpkmn11** [DS-Homebrew/nds-bootstrap#939]
**Your console:** DSi (J), DSi (K), n3DS (U)
**Launch Method:** TWiLight Menu++ v0.35.1, hiyaCFW 1.3.3, Luma3DS v9.1, Memory Pit (DSi (1.4.5J))
**Version used:** v0.35.1
**Game tested/used/applicable:** IPKE (sha1: `4fcded0e2713dc03929845de631d0932ea2b5a37`)

**Expected Behavior:** Pokéwalker works regardless of whether you use hiyaCFW. 
**Actual Behavior:** When using hiyaCFW or on a 3DS the Pokéwalker works as expected, but when using any other launch method on DSi it is completely not detected.

### Steps to reproduce

1. Launch nds-bootstrap while having not used hiyaCFW that boot of your DSi
2. Launch Pokémon HeartGold or SoulSilver
3. Attempt to connect to the Pokéwalker
4. It doesn't see it

ini: [nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4625995/nds-bootstrap.zip)

### Logs

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4626029/NDSBTSRP.LOG)
(The log is identical when using hiyaCFW or not)

### Other notes
Both White (J) and HeartGold (U) carts with a HeartGold (U) rom worked

**Comment by NightScript370** [comment]
Is this still the case?

**Comment by Epicpkmn11** [comment]
I haven't tested... Very unlikely since Pokémon G5 IR works without hiya now, but maybe it could still be the case
