### ISSUE TITLE
5355	Nine Hours, Nine Persons, Nine Doors error

### ISSUE THREAD

**Issue by TheGaboefects** [DS-Homebrew/nds-bootstrap#942]
**Your console:** 3DS XL

**Actual Behavior:** Game always randomly crashes during the first point and click section of the game rendering it unplayable.

**Comment by SleepyLark** [comment]
What version are you running it on?  Have you tried turning heap shrink off or changing any of the per-game settings?

**Comment by SleepyLark** [comment]
So I was able to beat the first puzzle on my New 3DS just fine, was there a specific area or way to reproduce the crash?

**Comment by piratesephiroth** [comment]
this sounds like the anti-piracy protection

**Comment by SleepyLark** [comment]
> this sounds like the anti-piracy protection

Probably is, I remember I manually AP patched it a while back (before auto-patching was a thing)

**Comment by SleepyLark** [comment]
Did you ever try using an Anti-piracy patch?  I'm pretty sure that will fix it

**Comment by scj643** [comment]
I can confirm that this is an anti piracy issue as I have ran into this issue before on my 3DS.

**Comment by RocketRobz** [comment]
Does this still happen on the latest version?

**Comment by twisteroidambassador** [comment]
Since this bug is still open, I'm going to report my experiences here. I have a fan-translated Japanese ROM of this game (NTR-BSKJ-JPN). Launching this ROM from TWLmenu++ shows the AP patch notification screen, but the game still crashes in escape sections.

DSi LL 1.4J with Unlaunch v2.0, TWLmenu v21.4.0, nds-bootstrap v0.46.2

**Comment by Kaisaan** [comment]
Does this still happen on the latest version of TWiLight Menu++ and nds-bootstrap?

**Comment by RocketRobz** [comment]
Haven't encountered this issue lately, so I don't think so.

**Comment by MO35AB** [comment]
Still suffering from the same problem, gonna try with AP, I'll let you know.
