### ISSUE TITLE
A Probleme With Kingdom Hearts 528/2 Days Not Working

### ISSUE THREAD

**Issue by SirSoloPlayer** [DS-Homebrew/nds-bootstrap#947]
I Have A Probleme With Kingdom Hearts ... The Game Launches But When I Start A New Game The Screen Turna Black.. Pls Fix This And Thanks

**Comment by RocketRobz** [comment]
What version of TWiLight Menu++ and nds-bootstrap are you using?

**Comment by SirSoloPlayer** [comment]
Latest Version + The Game Is In US Version If Thats Important

**Comment by SirSoloPlayer** [comment]
Any Reponse Pls  ?!

**Comment by ariebe9115** [comment]
> Any Reponse Pls ?!

Does the game not boot or does it crash while playing?

**Comment by RocketRobz** [comment]
You could try patching the ROM using DS-Scene ROM Tool.

**Comment by SleepyLark** [comment]
Did patching the game work?

**Comment by RocketRobz** [comment]
Closing, due to no response.
