### ISSUE TITLE
Touch screen not working when playing Urbz Sims in the city [EUR]

### ISSUE THREAD

**Issue by Vivi20910** [DS-Homebrew/nds-bootstrap#949]
**Your console:** new 2DS XL
**Launch Method:** I have luma3ds, I launch nds-bootstrap v0.35.1 with TWiLight Menu++ v15.1.1
**Version used:** Release
**Flashcart used:** sd card
**Game tested/used/applicable:** 0130 Urbz - Sims ine the city EUR

**Expected Behavior:** play normally with  touchscreen for the menu
**Actual Behavior:** Stuck in language selection (because of first time booting) not being able to play because I can't use the touchscreen to select my language

### Steps to reproduce

Launch the game with nds-bootstrap v0.35.1 trought TWiLight Menu++ v15.1.1

### Other notes

My touchscreen works perfectly with other games (same launch method) like pokemon rangers or inazuma eleven.
Edit: I'm using the same .nds that i used back on a DS lite so it's def nds-bootstrap/twilight

**Comment by AlphaNERD-** [comment]
Okay, so i messed with my DS a bit and determined that the bug started occuring somewhere between 0.29.0 and 0.32.0 of nds-bootstrap.

**Comment by RocketRobz** [comment]
The latest stealth nds-bootstrap build fixes this issue.
