### ISSUE TITLE
blue screen when putting a pokemon in the pc

### ISSUE THREAD

**Issue by Rocky6354** [DS-Homebrew/nds-bootstrap#950]
**Your console:** New Nintendo 3ds Xl
**Launch Method:**  Luma 3ds
**Version used:** Twilight Menu 8.5.0

**Game tested/used/applicable:** Pokemon White 2 Only

**Expected Behavior:** put my pokemon in the pc
**Actual Behavior:** blue screen and an error had occured please turn of the power

**Comment by SuperSaiyajinStackie** [comment]
I'd suggest to update Twilight Menu and nds-bootstrap. Twilight Menu++ is pretty outdated on v8.5.0.

**Comment by Rocky6354** [comment]
SuperSaiyajinStackie   I Meant 15.1.1 Because Im Lazy To Search What Version The Birtday One Is

**Comment by RocketRobz** [comment]
Haven't heard anyone else having this issue, so I'll close this.
