### ISSUE TITLE
Pokemon platinum will give me and error msg everytime I try to get back on my save file."Communication Error.If you were in the union room, you'll be returned there, please press the A button" 

### ISSUE THREAD

**Issue by medaurfed** [DS-Homebrew/nds-bootstrap#951]
**Your console:** 
**Launch Method:** 
**Version used:** 
**Flashcart used:** 
**Game tested/used/applicable:** 

**Expected Behavior:** 
**Actual Behavior:**

**Comment by RocketRobz** [comment]
What version of nds-bootstrap are you using?
