### ISSUE TITLE
Pokemon Heartgold/Soulsilver: Framerate issues in specific areas when having five or more pokemons in party.

### ISSUE THREAD

**Issue by redholm** [DS-Homebrew/nds-bootstrap#959]
**Console** 
O3DS/2DS XL (Both tested)

**Launch Method** 
 Luma3ds, Twilightmenu++ v.15.1.1

**SD CARD (x) FLASHCART ( )** 
   SanDisk Ultra 32gb class 10. (Have also tried others with the same result.)

**Games tested** 
Pokemon Heartgold + Soulsilver

**Expected behavior**
 Normal gameplay

**Steps to reproduce**
Bike around in Goldenrod city + Cianwood city with one pokemon, then add five more to your party, notice decreased framerate.

Sorry, i didn't figure out how to fill in the form correctly. It's my first time using GitHub.

**Comment by RocketRobz** [comment]
SWI Halt Hook (previously known as Sound Fix) has possibly caused this. The feature has been removed later on.
