### ISSUE TITLE
Castlevania Order of Ecclesia Bug and Fix

### ISSUE THREAD

**Issue by helpingout** [DS-Homebrew/nds-bootstrap#963]
**Your console: DS Lite** 
**Launch Method: Twilightmenu 15.1.1, bootstrap 0.35.1** 
**Version used: 15.1.1 0.35.1** 
**Flashcart used: R4 Gold** 
**Game tested/used/applicable: Castlevania Order of Ecclesia** 

**Expected Behavior: It should boot the game** 

**Actual Behavior: Unless you revert back to an older version of Twilightmenu/bootstrap (sorry I don't know which one), the game will not boot (crashes after intro). To get it to boot on the older version you MUST enable 'Heap Shrink' option by pressing Y on the game. This option has been removed on newer versions, and pressing L does not fix the issue** 

I hope this is helpful for others and can be fixed! : )

**Comment by JosiasElias** [comment]
UP, Happens the same on a DSi with Hiya. I thought my save was corrupted, but the save works on an emulator and a clean start on the ds wont work, broke my fun :(

**Comment by lrrosa** [comment]
I confirm that the problem continues to happen with TWmenu 16.3 on my DSi. The game crashes right after the intro.

**Comment by RocketRobz** [comment]
If you're running on a flashcard, a DS Memory Expansion Pak is required, so that WiFi code runs correctly, otherwise switch to the flashcard kernel instead of B4DS, in TWLMenu++ Settings.

If it's not on a flashcard, make sure WiFi is turned on, in TWLMenu++ Settings.

**Comment by lrrosa** [comment]
> If it's not on a flashcard, make sure WiFi is turned on, in TWLMenu++ Settings.

Hi, thanks for the reply. The game really worked after enabling wifi. It would be nice if the game did not need this requirement.

**Comment by JosiasElias** [comment]
this problem returned... Vram boost allows the game to launch but it freezes when loading a save. Yes my WI-FI is active. Also why was heap shrink added and then removed?

**Comment by RocketRobz** [comment]
Heap shrink was added as a way for loading to be faster.
It was later removed, because we found a way for loading to be faster without it.

As for the issue itself, the card read DMA implementation is currently buggy, so try turning it off.
