### ISSUE TITLE
NDS TGM guru meditation

### ISSUE THREAD

**Issue by danyisill** [DS-Homebrew/nds-bootstrap#966]
**Your console:** DSi LL
**Launch Method:** TWiLightMenu++
**Version used:** release 0.35.1
**Game tested/used/applicable:** TetrisGrandMaster ds 20080815 https://www.gamebrew.org/wiki/Tetris:_The_Grand_Master_3_DS
**Expected Behavior:** works
**Actual Behavior:** 
![IMG_0442](https://user-images.githubusercontent.com/23189912/84838066-2303c080-b042-11ea-802d-e73ff3eb272b.JPG)

### Steps to reproduce

[nds-bootstrap.ini](https://pastebin.com/raw/cj5yJdTC)

### Logs

doesn't write a log file

**Comment by lifehackerhansol** [comment]
Closing in favour of https://github.com/DS-Homebrew/nds-bootstrap/issues/1284.
