### ISSUE TITLE
problem opening inazuma eleven 3 the ogre - freezes when started

### ISSUE THREAD

**Issue by Daezmon21** [DS-Homebrew/nds-bootstrap#971]
**Your console:**  DSi
**Launch Method:**  nds-bootstrap version 0.35.1
**Version used:**  release
**Device used:**  SD Card (SanDisk)
**Game tested/used/applicable:**  Inazuma eleven 3 - the ogre (J)

**Expected Behavior:**  start the game normally
**Actual Behavior:** the game freezes in the presentation video

**Comment by RocketRobz** [comment]
You can try skipping past the video, if you're referring to the one that appears before the title screen.
