### ISSUE TITLE
Game music's sounds with noise - SMT: Devil Survivor 2

### ISSUE THREAD

**Issue by abiliodasilva** [DS-Homebrew/nds-bootstrap#972]
**Your console:** Nintendo DSi XL
**Launch Method:** Unlaunch v1.9 + hiyaCFW -> Twilight Menu++ v15.1.1
**Version used:** Release v0.35.1
**Game tested/used/applicable:** Shin Megami Tensei: Devil Survivor 2 (USA Version)

**Expected Behavior:** Game's music sounds without any type of noise
**Actual Behavior:** Game's music sounds with a minor noise

### Steps to reproduce

1. Start the game from the last used ROM or Soft-Reset the console.
2. The noise begins a few seconds later the game has started, on the intro.
3. From then, every sound of the game have a little noise.

### Logs

```
findModuleParamsOffset:
Module params offset restored: 02000BA4
sdk_version: 05057534
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

swi12 location : 0200036C

cardIrqEnable location : 02005310

startOffset : 02000000

cardRead location : 02010864

cardPullOut location : 02010E0C

cardId location : 020106C4


patchCardSetDma
cardReadDma location : 02010ACC

reset location : 02007CFC

ERR_NONE


Arm7 (patch v5)
Relocation src: 023802E4
JumpTableFunc: 0238ECEC
card read:	0238ECD4
Eeprom read:	0238ECF8
Eeprom page write:	0238ED10
Eeprom page prog:	0238ED28
Eeprom verify:	0238ED40
Eeprom page erase:	0238ED54
swi12 location : 02383600

swiGetPitchTable location : 02383614

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238FED0

ERR_NONE
hookLocation arm9: 027E0000

AP-fix found and applied
chipID: 80007FC2
```

### Other notes

This behavior only occurs on the "TWiLight Menu++ Last-run ROM" or a soft-reset of the DSi XL. Starting the ROM normally (selecting it from TWiLight Menu++) do not generate this "music with noise" behavior.

**Comment by RocketRobz** [comment]
Has been fixed by an early TWLMenu++ version.
