### ISSUE TITLE
Loading an area is slow in Pokemon Mystery Dungeon: Explorers of Sky

### ISSUE THREAD

**Issue by usbadapter** [DS-Homebrew/nds-bootstrap#973]
**Your console:** New 3DS
**Launch Method:** Luma3DS, TWiLightMenu
**Version used:** v0.35.1
**Game tested/used/applicable:** Pokemon Mystery Dungeon: Explorers of Sky (U)

**Expected Behavior:** It should take around 1 second for an area in the overworld to load
**Actual Behavior:** It takes around 4 seconds for an area in the overworld to load

### Steps to reproduce

1. Load game
2. Enter an area on the overworld

**Comment by Whatnoww** [comment]
Seems to be an issue even outside of area loading. Even menuing can become incredibly slow when you have to wait so long for your map to show up on the top screen before moving. Wonder if there's any way to fix this.

**Comment by Whatnoww** [comment]
Seems to be slower even with the 32kb cache option, and this is compared to an old M3 flashcart.

**Comment by Nitrogen2Oxygen** [comment]
Most loading screens are long from what I've been able to gather. The title screen takes about 9 seconds after the intro to load (which I doubt is normal behavior). Kinda annoying, I hope its eventually fixed

**Comment by Kaisaan** [comment]
If I remember correctly, this issue first appeared in version [0.29.0](https://github.com/ahezard/nds-bootstrap/releases/tag/v0.29.0) of nds-bootstrap. A workaround would be to use a version of nds-bootstrap prior to that, such as [0.28.1](https://github.com/ahezard/nds-bootstrap/releases/tag/v0.28.1). I would suggest replacing your nightly version of nds-bootstrap with this older version.

**Comment by ChainSwordCS** [comment]
Was this resolved in #1037 ?

**Comment by Kaisaan** [comment]
Yes. Closing this now.
