### ISSUE TITLE
Touch is unresponsive in "The Urbz: Sims in the City"

### ISSUE THREAD

**Issue by Smirokek** [DS-Homebrew/nds-bootstrap#983]
**Your console:** Old 2DS, DSi XL
**Launch Method:** On o2DS, I tried to use both TwilightMenu and by creating a forwarder, on DSi XL I tried with TwilightMenu
**Version used:** Latest release, v0.35.1
( I noticed that on an old SD I have on the DSi, which has nds-bootstrap version 0.28.1, touch screen works properly on the game).
**Game tested/used/applicable:** The Urbz: Sims in the City (I tried both EU and USA versions)

**Expected Behavior:** Touch screen should work, it's needed in order to play
**Actual Behavior:** Touch screen doesn't work at all, is unresponsive making the game even unable to start because you need to select your language from touch screen as soon as you start.
### Steps to reproduce

1. Start the game
2. Try to use touch screen

**Comment by SleepyLark** [comment]
Already a known issue  (#949, #935),  however I'm curious about the DSi.  Can you update the nds-bootstrap on the DSi to the latest and see if the touchscreen still works?

**Comment by Smirokek** [comment]
As I said in the main comment, I said the SD where the older nds-bootstrap version is installed is indeed an old SD I used before upgrading to a bigger one which means, that if I upgrade, I won't be able to use the touchscreen. Indeed, in my new SD, with latest bootstrap version, it doesn't work. At the moment I'm playing the game on the old SD, on the DSi, which makes me think that the bug appeared in a version between 0.29 and the latest. Since I'd love to go on the 2DS, is this bug eventually considered to be fixed? It's such a pity for me to not play this game.

**Comment by SleepyLark** [comment]
The type of SD card shouldn't be a problem, the thing I'm curious about is whether this is a regression problem or if it's only affecting 3DS' as the previous two issues I linked were only tested on the 3DS and not the DSi and I know of some games that don't work on 3DS but works on DSi and vice versa.

**Comment by Smirokek** [comment]
You didn't probably understand me then, I said that even though I have latest version of nds-bootstrap on my DSi it won't work either.

**Comment by velloriaa** [comment]
I have this problem as well! Is there any way for me to go back to the bootstrap version that works?

**Comment by SleepyLark** [comment]
Can you please try testing the nightly build [linked here](https://github.com/ahezard/nds-bootstrap/issues/920#issuecomment-680115504)?

**Comment by SleepyLark** [comment]
I tried it using the nightly build included with the latest version of TWiLight Menu  (44267f3e) and the touchscreen appears to be working (at least on DSi).  The power button however doesn't reset.

**Comment by RocketRobz** [comment]
The latest nds-bootstrap nightly fixes the POWER button issue.

**Comment by RocketRobz** [comment]
The latest stealth nds-bootstrap build contains the fix.

**Comment by qamichelemassa5859** [comment]
Alright was not be presented on GBA version, now that it runs well on mGBA3DS version 0.9.3?
