### ISSUE TITLE
Not able to load a game

### ISSUE THREAD

**Issue by MyBoy90** [DS-Homebrew/nds-bootstrap#989]
**Your console:**  Old 3DS (XL)
**Launch Method:**  Luma3DS
**Version used:**  Release
**Game tested/used/applicable:**  Pokémon Platinum Spanish Version

**Expected Behavior:**  It should have loaded the game
**Actual Behavior:**  Unable to load the game. By less than a second, it appears ‘Creating save file... If this takes a while press HOME, and press B. Done!’ and the screen appears black while the touchable screen appears white

### Steps to reproduce

1. Launch a .nds game converted in .cia 
2. The error happens
### Other notes
I tried playing NDS games but this error keeps appearing in every game I play and it doesn’t load
![10C544A7-94BF-4247-8C79-270EA3CD699F](https://user-images.githubusercontent.com/68967412/88843499-22318300-d1d9-11ea-94ff-c75c1b63195f.jpeg)

**Comment by RocketRobz** [comment]
Try updating the forwarder template by following Part 1.1 in the forwarder thread.
