### ISSUE TITLE
Make the procedure to change a game to be compatible more accessible

### ISSUE THREAD

**Issue by juliankrieger** [DS-Homebrew/nds-bootstrap#995]
There really isn't any information on how to work on a game to make it compatible with nds-bootstrap. Is it possible to maybe showcase such a workflow?

**Comment by SleepyLark** [comment]
Probably could add a troubleshoot page to the wiki listed on GitHub, sounds like a good idea

**Comment by juliankrieger** [comment]
If you find the time. I want to try and make finished, popular ROM Hacks like Pokemon Gaia compatible with nds-bootstrap ( as far as possible, some ROM Hacks weigh above 32MB, I've read that this can be difficult to manage )

**Comment by edo9300** [comment]
Pokemon gaia is a gba ROM hack, the bootstrap is for ds and (hopefully in future) DSi, for GBA is gbarunner2 what's being used
